### PR TITLE
fix(desktop): prevent electron-builder from hoisting node_modules out of extraResources

### PR DESCRIPTION
**Pull request by kadones70-svg**
## Problem

electron-builder recognises node_modules directories inside extraResources and hoists them to resources/node_modules, leaving resources/native-deps/ without its staged JS vendor deps (simple-git and its dependency tree). This causes a hard crash on launch when git-review-ops.cjs cannot find simple-git.

Error: Uncaught Exception: Error: Cannot find module 'simple-git'

Introduced in e2b8018 (feat: add git worktree and review IPC).

## Root Cause

stage-native-deps.cjs stages vendor JS deps into build/native-deps/node_modules/. During packaging, electron-builder's extraResources processing hoists the inner node_modules/ directory to resources/node_modules/, while git-review-ops.cjs expects it at resources/native-deps/node_modules/.

### 1. git-review-ops.cjs - Multi-level fallback
- Dev mode (workspace-hoisted): require('simple-git')
- Packaged primary: resources/native-deps/npm/node_modules/simple-git
- Packaged fallback: resources/node_modules/simple-git (hoisted location)

### 2. stage-native-deps.cjs - Nest node_modules inside npm/
Changed staging path from build/native-deps/node_modules/ to build/native-deps/npm/node_modules/. The npm/ wrapper prevents electron-builder from recognizing the inner directory as a project node_modules, preserving the extraResources tree structure.

## Test Plan
- Existing test suite passes (16/16: git-review-ops + git-worktree-ops)
- Staging script idempotent across multiple runs
- Cross-package resolution verified
- git-review-ops.cjs loads in dev mode

### CODE REVIEW

**Review by tonydwb — APPROVED** [review]
## Code Review Summary

**Verdict: Approved**

### Looks Good
- Clean fix for electron-builder node_modules hoisting issue
- Prevents electron-builder from moving node_modules out of extraResources
- Well-scoped: 2 files, 234 additions/160 deletions
- Addresses a real desktop packaging bug
- Good error handling

---
*Reviewed by Hermes Agent*

**Comment by teknium1** [comment]
Closing — this is fixed on `main`.

The Windows desktop "Cannot find module 'simple-git'" crash (and the related `release\win-unpacked` EBUSY lock during rebuild) was resolved by commit df514654b "desktop: bundle main.cjs for electron". The Electron main process is now bundled — `simple-git` and its dependency tree are inlined into `main.cjs`, so there's no runtime module resolution to fail and no `node_modules` for electron-builder to hoist out of `extraResources` / win-unpacked.

Your approach (staging vendor JS deps into the package before electron-builder runs) targeted the now-obsolete failure mode and is superseded by the bundling fix. Thanks for the thorough diagnosis and root-cause writeup.

Fix for affected users: re-run the updater / installer once (you'll be a few commits behind) and the desktop build will succeed.
