### PR TITLE
fix(mcp): convert timeout values to timedelta for mcp >= 1.8.0

### LINKED ISSUE #49629: HTTP MCP timeout type mismatch: int passed where timedelta expected
## Description

After upgrading to v0.17.0, all `url:` type (HTTP) MCP connections fail with:

```
'float' object has no attribute 'seconds'
```

stdio type (`command:`) MCPs (e.g. tdx-mcp) are not affected.

## Root Cause

`StreamableHTTPTransport.__init__()` in the `mcp` library expects `timeout` and `sse_read_timeout` as `timedelta` objects. Hermes passes plain `int`/`float` values from `config.yaml` directly.

## Temporary Fix

Applied to `mcp/client/streamable_http.py`:

```python
if isinstance(timeout, (int, float)):
    timeout = timedelta(seconds=timeout)
if isinstance(sse_read_timeout, (int, float)):
    sse_read_timeout = timedelta(seconds=sse_read_timeout)
```

This is a third-party library patch and will be overwritten on pip upgrade.

## Proper Fix

Hermes should convert config values to `timedelta` before passing to `StreamableHTTPTransport`. The fix belongs in Hermes' MCP connection startup code.

## Environment
- Hermes Agent v0.17.0
- mcp library v1.8.0

### PR DESCRIPTION
**Pull request by tcconnally**
## Summary

Fixes HTTP/SSE MCP connections failing with `'float' object has no attribute 'seconds'` on mcp library >= 1.8.0.

The `mcp` library's `StreamableHTTPTransport.__init__()` now expects `timeout` and `sse_read_timeout` as `datetime.timedelta` objects, but Hermes was passing plain `int`/`float` values from `config.yaml`.

## What

- Adds `_to_timedelta()` helper that converts numeric timeout values to `timedelta`, passes through existing `timedelta` or `None` values unchanged
- Converts `timeout` and `sse_read_timeout` at both call sites:
  - SSE transport (`sse_client()`)
  - Deprecated HTTP transport (`streamablehttp_client()`)

The new HTTP path (`streamable_http_client` with explicit `httpx.AsyncClient`) was already correct — it uses `httpx.Timeout` which handles its own timeout.

## Testing

- [x] `_to_timedelta()` unit tested: int, float, timedelta passthrough, None passthrough, zero
- [x] No regression: all timeout values pass through identically for old mcp versions (timedelta is forwards-compatible)
- [x] Affected code paths: SSE transport and deprecated HTTP transport

Fixes #49629

### CODE REVIEW

**Comment by alt-glitch** [comment]
Duplicate of #49646 — both fix #49629 with the identical mechanism: a `_to_timedelta()`/`_timeout_delta()` helper that converts numeric `timeout`/`sse_read_timeout` values to `datetime.timedelta` at the legacy SSE/streamable-HTTP transport call sites in `tools/mcp_tool.py` (the new explicit-httpx path is untouched). #49646 was opened first, so it is the canonical version.

**Comment by tcconnally** [comment]
Closing as duplicate of #49646 — both fix #49629 with the identical approach. The other PR (#49646 by Tranquil-Flow) was filed first.
