### PR TITLE
fix(gateway): skip loop tick socket on Windows without warning traceback (#99895)

### LINKED ISSUE #99895: [Bug]: Windows: AttributeError: module 'asyncio' has no attribute 'start_unix_server' in shutdown_watchdog (v0.21.0)
### Bug Description

After upgrading to v0.21.0 (2026.8.31), Hermes Gateway fails to initialize the shutdown watchdog thread on native Windows. The application throws an AttributeError because asyncio.start_unix_server is used, which is not available on Windows Python.
The gateway still runs partially, but the liveness/heartbeat watchdog subsystem crashes repeatedly on startup.

### Steps to Reproduce

1.	Upgrade Hermes Agent to latest main branch (b20cc5f7)
2.	Run hermes gateway stop to clean old process
3.	Run hermes gateway
4.	Watch startup logs — watchdog thread crashes immediately

### Expected Behavior

he watchdog logic should gracefully fallback on Windows:
•	Skip unix socket initialization on Windows
•	Fallback to simple interval heartbeat without socket
•	No crash, no AttributeError

### Actual Behavior

The watchdog logic should gracefully fallback on Windows:
•	Skip unix socket initialization on Windows
•	Fallback to simple interval heartbeat without socket
•	No crash, no AttributeError

### Affected Component

Gateway (Telegram/Discord/Slack/WhatsApp)

### Messaging Platform (if gateway-related)

_No response_

### Debug Report

```shell
Full Error Log
python
2026-09-01 08:36:46,896 WARNING gateway.shutdown_watchdog: Loop tick socket unavailable — liveness probes will have no loop-scheduling witness and will not escalate on a stale heartbeat
Traceback (most recent call last):
  File "C:\Users\AdminUser\AppData\Local\hermes\hermes-agent\gateway\shutdown_watchdog.py", line 572, in loop_heartbeat_forever
    tick_server = await asyncio.start_unix_server(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'start_unix_server'
```

### Operating System

Windows 10 / Windows 11 (native PowerShell, no WSL)

### Python Version

3.11.15 (official Hermes managed venv)

### Hermes Version

v0.21.0 (2026.8.31) — current latest main branch

### Additional Logs / Traceback (optional)

```shell
All other warnings in the log are normal tool availability checks and unrelated to this crash.
This is a pure cross-platform compatibility bug, no local environment misconfiguration.
```

### Root Cause Analysis (optional)

Root Cause Analysis
asyncio.start_unix_server() is a Unix-domain socket API that only exists on Linux / macOS / WSL.
Windows native Python does NOT support unix sockets for asyncio, so calling this method directly causes a hard attribute crash.
The new shutdown_watchdog heartbeat logic added in v0.21.0 has no Windows platform guard clause.

### Proposed Fix (optional)

Add platform detection before calling start_unix_server in shutdown_watchdog.py line 572:
•	If sys.platform == "win32": skip unix server creation, use fallback loop tick
•	Isolate Unix-only socket logic from Windows runtime
•	Preserve full functionality for Linux/macOS

### Are you willing to submit a PR for this?

- [ ] I'd like to fix this myself and submit a PR

### PR DESCRIPTION
**Pull request by kyssta-exe**
Fixes #99895

**Problem:** On native Windows `asyncio.start_unix_server` does not exist. `loop_heartbeat_forever` already caught the `AttributeError` via `except Exception` and fell back to witness-disabled mode, but it logged a WARNING with `exc_info=True` — surfacing as a traceback that looks like a crash and repeats on every gateway startup.

**Fix:** Early-exit with `if not hasattr(asyncio, "start_unix_server"): logger.debug(...)` before attempting the bind. Same fail-safe semantics (`loop_tick_socket=False`, probes never escalate to WEDGED on Windows, graceful-drain backstop preserved), no warning noise.

**Tests:** `pytest tests/gateway/test_loop_liveness_watchdog.py` — 11 passed. Import and py_compile pass.

Closes #99895

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #96989. Both PRs gate the same POSIX-only asyncio.start_unix_server loop-tick witness on Windows.

**Comment by kyssta-exe** [comment]
Closing as duplicate — triage AI (alt-glitch) identified this as duplicate of #96989. Both PRs gate the same POSIX-only `asyncio.start_unix_server` loop-tick witness on Windows. Keeping the earlier PR to avoid duplicate changes.
