### ISSUE TITLE
migrate_config stamps _config_version to latest even when a migration step failed and was skipped, so the skipped step never re-runs

### ISSUE THREAD

**Issue by Treibs** [NousResearch/hermes-agent#119658]
## Bug Description

`migrate_config` writes `_config_version: <latest>` even when one of the migration steps raised and was skipped. The skipped step then never re-runs: `hermes doctor` reads the version as current, `hermes doctor --fix` has nothing to fix, and the update receipt records no skip. The only trace is one WARNING line.

**Version:** observed on two Linux git installs on 2026-09-22, both migrating inside `hermes update` to v0.21.4 (`94e8a255`), from v0.21.3 (`9326d9cd`) and from v0.21.0. Logic below checked against `94e8a255` and current `main`.

## What happened

During the update, migration 44→45 raised and was skipped — loudly, as designed:

```
2026-09-22 13:47:33,370 WARNING hermes_cli.config_migrations: config migration to v45 failed and was skipped: cannot import name '_configurable_keys' from 'hermes_cli.tools_config' (.../hermes_cli/tools_config.py)
```

(The import failure itself is the pre/post-pull module mix already covered by #111271 / #118154 and should stop happening once the source of an update carries the post-swap hand-off. This report is about what happens *after* any step is skipped, whatever raised.)

`config.yaml` was then stamped `_config_version: 45` on both boxes. Consequences:

- `hermes doctor` → config version current; `hermes doctor --fix` → nothing to do.
- The v45 step (`platform_toolsets` lists predating the connections toolset) is never applied.
- The update receipt has `skips: []` and no config step; `outcome` is unrelated to the skip.
- On a `--yes` run the console line scrolls past with the rest of the update output.

## Where

- `hermes_cli/config_migrations.py::run_migrations` — catches per step, appends to `results["warnings"]`, logs, continues. The comment on that branch already names the gap: *"Quiet callers (profile creation, unattended update) discard `results` and migrate_config still stamps the latest version, so without a log line the skipped step vanishes for good."*
- `hermes_cli/config.py::migrate_config` (≈L1443 on `94e8a255`): `if current_ver < latest_ver and not floor_refused: config["_config_version"] = latest_ver` — unconditional on whether every step succeeded.

## Repair used

On both boxes: set `_config_version` back to 44 by hand, run `hermes doctor --fix`. The step applied cleanly on the now-consistent tree.

## Suggestion

Stamp the highest *contiguous* successfully-applied version instead of `latest_ver`: if step N raised, write `N-1` and keep the warning. Then `hermes doctor` shows "Config version outdated (v(N-1) → vlatest)" and `--fix` re-runs exactly the skipped step, which is what the loud-not-silent intent of the per-step skip (#116593) seems to want. If a step is meant to stay non-blocking (a malformed nested value the user has to fix by hand), record it in the receipt's `skips` so it does not depend on someone reading `agent.log`.

Happy to test a patch on both boxes.

**Comment by Sahilvishnaliya** [comment]
Claiming this — working on a PR. @Sahilvishnaliya
