### ISSUE TITLE
Provider discovery imports *every* enabled plugin — including platform plugins — while `gateway.config` is still loading, which breaks pip-installed platform plugins with a circular import

### ISSUE THREAD

**Issue by srinathh** [NousResearch/hermes-agent#98438]
### What happens

I maintain a small **platform plugin** (a WhatsApp adapter for Twilio —
https://github.com/srinathh/twilio-whatsapp-platform-adapter) that is installed with
pip and registers itself through the `hermes_agent.plugins` entry-point group, exactly as the
plugin docs describe. It worked on v2026.8.3. After moving to v2026.8.27 the platform silently
disappears, and this warning shows up whenever something imports Hermes's `gateway` package
before anything else:

```
WARNING providers: Failed to load entry-point provider plugin 'twilio_whatsapp-platform':
cannot import name 'Platform' from partially initialized module 'gateway.config'
(most likely due to a circular import)
```

### Why it happens

Two pieces of Hermes both look at the same entry-point group, but they treat it differently.

1. **The plugin manager** (`hermes_cli/plugins.py`) is careful: it works out what *kind* of
   plugin each entry point is **without importing it** (`discover_entrypoint_manifests`,
   `_detect_kind_from_source`), and it loads platform plugins **lazily**, only when the
   gateway actually asks for that platform. Bundled platform plugins under
   `plugins/platforms/` rely on this — they all import `gateway.config` at the top of their
   adapter module, and that is fine because they are loaded late.

2. **The model-provider registry** (`providers/__init__.py`, added in #85504, first shipped in
   v2026.8.13) is not careful. Its `_discover_entry_point_providers()` was written so that
   pip-installed *model providers* get registered. But it calls `ep.load()` on **every**
   entry point listed in `plugins.enabled`, no matter what kind it is. There is no kind
   check before the import; the only guard (`_requires_arguments()`) runs *after* the module
   has already been imported and only applies to callables, not to bare-module entry points.

The timing makes this fatal. The registry's discovery runs from a hook that executes at
**import time** of `hermes_cli.config` (`_inject_profile_env_vars()` → `list_providers()`),
and `gateway/config.py` imports `hermes_cli.config` on its line 20 — long before it defines
the `Platform` enum (around line 325). So if the first Hermes package a process imports is
anything under `gateway.*`, the chain is:

```
import gateway.config
  └─ gateway/config.py:20      from hermes_cli.config import get_hermes_home
       └─ hermes_cli/config.py  (import-time hook) list_providers()
            └─ providers/__init__.py  _discover_entry_point_providers() → ep.load()
                 └─ my_platform_plugin/adapter.py   from gateway.config import Platform
                      → gateway.config is only half-initialised → ImportError
```

My plugin's entry module did what the documented example does — `from gateway.config import
Platform, PlatformConfig` at module top (`website/docs/developer-guide/adding-platform-adapters.md`,
around line 99) — and that is precisely what breaks. Nothing in the docs tells a plugin author
to avoid it.

### How to reproduce 

```bash
mkdir -p /tmp/stub/stubplug-0.0.1.dist-info /tmp/hh
printf 'from gateway.config import Platform\n' > /tmp/stub/stubplug.py
printf 'Metadata-Version: 2.1\nName: stubplug\nVersion: 0.0.1\n' \
    > /tmp/stub/stubplug-0.0.1.dist-info/METADATA
printf '[hermes_agent.plugins]\nstub-platform = stubplug\n' \
    > /tmp/stub/stubplug-0.0.1.dist-info/entry_points.txt
printf 'plugins:\n  enabled:\n    - stub-platform\n' > /tmp/hh/config.yaml

# Fails: gateway imported first
PYTHONPATH=/tmp/stub HERMES_HOME=/tmp/hh python -c 'import gateway.config'
#   WARNING ... Failed to load entry-point provider plugin 'stub-platform':
#   cannot import name 'Platform' from partially initialized module 'gateway.config'

# Works: hermes_cli.config imported first
PYTHONPATH=/tmp/stub HERMES_HOME=/tmp/hh python -c 'import hermes_cli.config; import stubplug'
```

Anything whose first Hermes import is under `gateway.*` hits it — test suites, tooling, and
documented commands such as `python -m gateway.platforms.feishu_comment_rules …`
(`website/docs/user-guide/messaging/feishu.md`). There is also a quieter failure mode: when the
*plugin package itself* is imported first, the registry finds the half-initialised module already
in `sys.modules` and silently registers that.

### What I would expect

Provider discovery should only import entry points that are model providers — it could reuse
the import-free classification the plugin manager already trusts, or the `<name>-platform`
naming convention the manager already relies on to derive platform ids — and/or it should not
run inside the `gateway.config` → `hermes_cli.config` import window.

### Related

- #85559 (open): "shared entry-point classification so PluginManager + provider registry agree
  on ownership" — would fix this by classifying before `ep.load()`, but it has drifted out of
  sync with `main`.
- #89199 (open): spurious `${env:VAR} not set` warnings — traced in the comments to the same
  import-time provider discovery on the config-import path. Same root, different symptom.
- The docs (`model-provider-plugin.md` "Distribute via pip", `plugins/index.md`) do not mention
  that an entry module must avoid `gateway.*` imports.

### Workaround for plugin authors

Keep the entry module free of `gateway.*` imports and import the adapter class inside
`register(ctx)`. That is what I shipped in https://github.com/srinathh/twilio-whatsapp-platform-adapter/releases/tag/v0.2.1 and it works on both v2026.8.3 and v2026.8.27.
