### PR TITLE
fix(mcp): pass legacy HTTP timeouts as timedeltas (#49629)

### LINKED ISSUE #49629: HTTP MCP timeout type mismatch: int passed where timedelta expected
## Description

After upgrading to v0.17.0, all `url:` type (HTTP) MCP connections fail with:

```
'float' object has no attribute 'seconds'
```

stdio type (`command:`) MCPs (e.g. tdx-mcp) are not affected.

## Root Cause

`StreamableHTTPTransport.__init__()` in the `mcp` library expects `timeout` and `sse_read_timeout` as `timedelta` objects. Hermes passes plain `int`/`float` values from `config.yaml` directly.

## Temporary Fix

Applied to `mcp/client/streamable_http.py`:

```python
if isinstance(timeout, (int, float)):
    timeout = timedelta(seconds=timeout)
if isinstance(sse_read_timeout, (int, float)):
    sse_read_timeout = timedelta(seconds=sse_read_timeout)
```

This is a third-party library patch and will be overwritten on pip upgrade.

## Proper Fix

Hermes should convert config values to `timedelta` before passing to `StreamableHTTPTransport`. The fix belongs in Hermes' MCP connection startup code.

## Environment
- Hermes Agent v0.17.0
- mcp library v1.8.0

### PR DESCRIPTION
**Pull request by Tranquil-Flow**
## Summary

Fixes #49629.

- Convert legacy Streamable HTTP MCP `timeout` to `datetime.timedelta` before calling the deprecated SDK-managed `streamablehttp_client` path.
- Pass companion `sse_read_timeout` as `datetime.timedelta` as well, matching the MCP SDK transport contract.
- Leaves stdio MCP servers and the newer explicit `httpx.AsyncClient` HTTP path unchanged.

## Verification

- Regression proof on upstream/main: `tests/tools/test_mcp_tool.py::TestHTTPConfig::test_legacy_streamable_http_timeouts_are_timedeltas` fails with `AttributeError: 'float' object has no attribute 'seconds'`.
- After the fix, ran:
  - `/Users/evinova-self/.hermes/hermes-agent/venv/bin/python3 -m pytest tests/tools/test_mcp_tool.py::TestHTTPConfig -v -o "addopts=" --tb=short`
  - Result: `7 passed in 0.70s`
- Verified branch is exactly one commit ahead of upstream/main: `0 1`.

## Duplicate / competitor check

Before publishing, checked open PRs by issue number, same-author branch pattern, and topic keywords (`HTTP MCP timeout timedelta`, `StreamableHTTPTransport timeout timedelta`). No focused open competing PR was found.

Auto-published by Moonsong via Path B automated pipeline.

### CODE REVIEW

**Comment by teknium1** [comment]
Thanks for the focused regression fix. The premise remains present on current main: the deprecated branch selected when `_MCP_NEW_HTTP` is false still passes `float(connect_timeout)` into `streamablehttp_client` at `tools/mcp_tool.py:2523-2532`. The added test explicitly forces that legacy branch, so it exercises the relevant behavior.

The MCP startup function has moved since the PR was opened, so salvage should transplant the coercion into the current legacy kwargs construction at `tools/mcp_tool.py:2525-2532`; the change remains small and targeted. No substantive defect was identified in the PR diff.

Automated hermes-sweeper review.
