### ISSUE TITLE
[Bug]: fix(gateway): QQAdapter.connect() does not accept is_reconnect parameter on reconnect

### ISSUE THREAD

**Issue by lixlongis** [NousResearch/hermes-agent#54679]
### Bug Description

After updating to v0.17.0, QQ Bot fails to reconnect after disconnection.
QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
In gateway/run.py, _connect_adapter_with_timeout() passes is_reconnect=True to adapter.connect(is_reconnect=is_reconnect), but the QQ Bot adapter's connect() method signature is async def connect(self): — it does not accept this parameter.

### Steps to Reproduce

Two options:
QQ Bot adapter: add **kwargs to the connect() signature
gateway/run.py: wrap the connect() call in try/except TypeError and fall back to connect() without arguments
Workaround
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):

### Expected Behavior

Two options:
QQ Bot adapter: add **kwargs to the connect() signature
gateway/run.py: wrap the connect() call in try/except TypeError and fall back to connect() without arguments
Workaround
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):

### Actual Behavior

Two options:
QQ Bot adapter: add **kwargs to the connect() signature
gateway/run.py: wrap the connect() call in try/except TypeError and fall back to connect() without arguments
Workaround
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):

### Affected Component

Gateway (Telegram/Discord/Slack/WhatsApp)

### Debug Report

```shell
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):
```

### Operating System

Windows 11

### Python Version

3.11.9

### Hermes Version

0.17.0

### Additional Logs / Traceback (optional)

```shell

```

### Are you willing to submit a PR for this?

- [ ] I'd like to fix this myself and submit a PR

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #52914 — same bug: `QQAdapter.connect()` is missing the keyword-only `is_reconnect` parameter that `gateway/run.py`'s reconnect watcher passes, so reconnects raise `TypeError` and QQBot never recovers. The fix is tracked by the open PR cluster anchored at #52922.

**Comment by rebecca554owen** [comment]
Marking as related: same root cause as #52914. Fix is in #55419 — accepts is_reconnect kwarg in QQAdapter.connect().

**Comment by teknium1** [comment]
Thanks for the clear root-cause report. This is now fixed on current `main`.

Automated hermes-sweeper review verified:
- `gateway/platforms/qqbot/adapter.py:281` now defines `QQAdapter.connect(self, *, is_reconnect: bool = False)`.
- The reconnect watcher still correctly calls the adapter with `is_reconnect=True` at `gateway/run.py:7910`.
- Commit `276542c729c10ff9d093760897f4c2d1256a79ce` added the QQBot fix and its targeted regression test.
- Merged PR #61767 added repository-wide adapter signature coverage in `tests/gateway/test_adapter_connect_is_reconnect_contract.py`, preventing this regression class from recurring.

The related #55419 proposed the same signature alignment but was closed; the implemented fix was shipped through #61767.
