### ISSUE TITLE
[Bug][Windows] hermes_state_lockguard.py 未处理 fcntl.F_RDLCK 缺失，导致后端启动失败

### ISSUE THREAD

**Issue by sbymkd** [NousResearch/hermes-agent#118026]
操作系统windows11
安装方式 | （桌面版）
Hermes 版本 | Hermes Agent v0.21.3 (2026.9.14)

在 Windows 上启动 Hermes 时，后端进程在宣告端口之前就崩溃退出，错误如下：
File "D:\Program Files\Hermes\hermes-agent\hermes_state_lockguard.py", line 49, in <module>
    _F_RDLCK, _F_UNLCK, _SEEK_SET = fcntl.F_RDLCK, fcntl.F_UNLCK, os.SEEK_SET
                                    ^^^^^^^^^^^^^
AttributeError: module 'fcntl' has no attribute 'F_RDLCK'
前端报错信息：
Error invoking remote method 'hermes:connection': Error: Hermes backend: exited before port announcement (1)
影响：Hermes 桌面端完全无法启动。任何导入 hermes_state 的路径都会触发此崩溃，包括 hermes doctor。

**Comment by teknium1** [comment]
**Triage (P0 confirmed, reproduced)**

**Root cause:** `hermes_state_lockguard.py` (introduced by 75e155ab0 / beb546b0f) treats "`import fcntl` succeeds" as "full POSIX `fcntl` present":

```python
try:
    import fcntl
    _F_OFD_SETLK = getattr(fcntl, "F_OFD_SETLK", ...)
    _F_RDLCK, _F_UNLCK, _SEEK_SET = fcntl.F_RDLCK, fcntl.F_UNLCK, os.SEEK_SET   # <- AttributeError
except ImportError:  # Windows
    ...
```

Only `ImportError` is handled. Stock CPython on Windows has no `fcntl` module at all, so CI's Windows lane takes the `except` branch and never sees this. On your machine some *other* module named `fcntl` is importable (a `flock`/`LOCK_*`-only stand-in — CPython for Windows ships none), so the import succeeds and the unguarded `fcntl.F_RDLCK` attribute read raises `AttributeError` at module import time.

**Blast radius:** `hermes_state.py` does `import hermes_state_lockguard as _lockguard` at module level, so every importer of `hermes_state` dies at startup — `hermes serve` (Desktop backend: "exited before port announcement (1)"), `hermes doctor`, the gateway, cron. Not caught by `supported()` because the crash is before that function exists.

**Reproduced** on origin/main by installing a stub `fcntl` module (`flock` + `LOCK_*`, no `F_RDLCK`) into `sys.modules` and importing `hermes_state_lockguard` → `AttributeError: module 'fcntl' has no attribute 'F_RDLCK'`. Same traceback as reported.

**Fix direction (a few lines, `hermes_state_lockguard.py` only):**
1. Gate on the platform first: `if os.name == "nt": fcntl = None; _F_OFD_SETLK = None` — the module docstring already promises "No-op on Windows"; a Windows `fcntl` lookalike must never enable it.
2. Make the POSIX branch tolerant of partial modules: `except (ImportError, AttributeError)` (or `getattr(fcntl, "F_RDLCK", None)` and disable the guard when any of `F_RDLCK`/`F_UNLCK`/`fcntl.fcntl` is missing) so `supported()` returns `False` instead of the process dying.
3. Invariant test: a stub `fcntl` without `F_RDLCK` → module imports, `supported() is False`, `hold()` returns `{}`.

Sibling sweep: the other `fcntl` users in the tree (`hermes_state_common.py`, `hermes_state_dbfile.py`, `cron/`, `hermes_cli/`, `tools/`) only touch `fcntl.flock` / `LOCK_*`, which a stand-in typically provides, so this module is the only import-time crash. Worth checking on your side which module that is, so we know what to expect on Windows installs:

```
"D:\Program Files\Hermes\hermes-agent\.venv\Scripts\python.exe" -c "import fcntl; print(fcntl.__file__)"
```

**Workaround until the fix lands:** remove/rename that `fcntl` module from the venv (Hermes does not need it on Windows; the Windows code paths use `msvcrt`).

**Comment by ehz0ah** [comment]
Carrier disposition at the current heads:

- #118040 (`9b028c7ba8`) correctly prevents any Windows `fcntl` lookalike from arming the POSIX lock guard. Its native Windows `SessionDB` regression covers absent, partial, and constant-bearing shims.
- #118269 (`f7cfbf78b3`) is the preferred carrier after correction because it also handles partial capability off Windows and has active hosted CI. It is not ready yet: constants alone are insufficient. Capability detection must also require a callable `fcntl.fcntl`; otherwise `supported()` returns true and `hold()` later raises `AttributeError`.

Please keep the early Windows gate, add the callable check, and add a native Windows regression through a real `SessionDB` cycle. After that exact head is reviewed, #118040 can close as the duplicate carrier. Keep this issue open until the corrected carrier merges.

**Comment by sbymkd** [comment]
> 操作系统windows11 安装方式 | （桌面版） Hermes 版本 | Hermes Agent v0.21.3 (2026.9.14)
> 
> 在 Windows 上启动 Hermes 时，后端进程在宣告端口之前就崩溃退出，错误如下： File "D:\Program Files\Hermes\hermes-agent\hermes_state_lockguard.py", line 49, in _F_RDLCK, _F_UNLCK, _SEEK_SET = fcntl.F_RDLCK, fcntl.F_UNLCK, os.SEEK_SET ^^^^^^^^^^^^^ AttributeError: module 'fcntl' has no attribute 'F_RDLCK' 前端报错信息： Error invoking remote method 'hermes:connection': Error: Hermes backend: exited before port announcement (1) 影响：Hermes 桌面端完全无法启动。任何导入 hermes_state 的路径都会触发此崩溃，包括 hermes doctor。



> **Triage (P0 confirmed, reproduced)**
> 
> **Root cause:** `hermes_state_lockguard.py` (introduced by [75e155a](https://github.com/NousResearch/hermes-agent/commit/75e155ab09b9e3fefd2856d199083b6dcbc270a9) / [beb546b](https://github.com/NousResearch/hermes-agent/commit/beb546b0f2125a595b8fd1420ca011d45f7f51c1)) treats "`import fcntl` succeeds" as "full POSIX `fcntl` present":
> 
> try:
>     import fcntl
>     _F_OFD_SETLK = getattr(fcntl, "F_OFD_SETLK", ...)
>     _F_RDLCK, _F_UNLCK, _SEEK_SET = fcntl.F_RDLCK, fcntl.F_UNLCK, os.SEEK_SET   # <- AttributeError
> except ImportError:  # Windows
>     ...
> Only `ImportError` is handled. Stock CPython on Windows has no `fcntl` module at all, so CI's Windows lane takes the `except` branch and never sees this. On your machine some _other_ module named `fcntl` is importable (a `flock`/`LOCK_*`-only stand-in — CPython for Windows ships none), so the import succeeds and the unguarded `fcntl.F_RDLCK` attribute read raises `AttributeError` at module import time.
> 
> **Blast radius:** `hermes_state.py` does `import hermes_state_lockguard as _lockguard` at module level, so every importer of `hermes_state` dies at startup — `hermes serve` (Desktop backend: "exited before port announcement (1)"), `hermes doctor`, the gateway, cron. Not caught by `supported()` because the crash is before that function exists.
> 
> **Reproduced** on origin/main by installing a stub `fcntl` module (`flock` + `LOCK_*`, no `F_RDLCK`) into `sys.modules` and importing `hermes_state_lockguard` → `AttributeError: module 'fcntl' has no attribute 'F_RDLCK'`. Same traceback as reported.
> 
> **Fix direction (a few lines, `hermes_state_lockguard.py` only):**
> 
> 1. Gate on the platform first: `if os.name == "nt": fcntl = None; _F_OFD_SETLK = None` — the module docstring already promises "No-op on Windows"; a Windows `fcntl` lookalike must never enable it.
> 2. Make the POSIX branch tolerant of partial modules: `except (ImportError, AttributeError)` (or `getattr(fcntl, "F_RDLCK", None)` and disable the guard when any of `F_RDLCK`/`F_UNLCK`/`fcntl.fcntl` is missing) so `supported()` returns `False` instead of the process dying.
> 3. Invariant test: a stub `fcntl` without `F_RDLCK` → module imports, `supported() is False`, `hold()` returns `{}`.
> 
> Sibling sweep: the other `fcntl` users in the tree (`hermes_state_common.py`, `hermes_state_dbfile.py`, `cron/`, `hermes_cli/`, `tools/`) only touch `fcntl.flock` / `LOCK_*`, which a stand-in typically provides, so this module is the only import-time crash. Worth checking on your side which module that is, so we know what to expect on Windows installs:
> 
> ```
> "D:\Program Files\Hermes\hermes-agent\.venv\Scripts\python.exe" -c "import fcntl; print(fcntl.__file__)"
> ```
> 
> **Workaround until the fix lands:** remove/rename that `fcntl` module from the venv (Hermes does not need it on Windows; the Windows code paths use `msvcrt`).

Verified. The fake fcntl is Hermes' own Windows shim
(venv/Lib/site-packages/fcntl.py, docstring: "minimal no-op flock for
render.py"), so it cannot be deleted — render.py needs fcntl.flock().

Applied the cfc15af direction locally (os.name == "nt" gate + hasattr
checks + except (ImportError, AttributeError)). Result:

  fcntl has flock: True, LOCK_EX: True, F_RDLCK: False
  lockguard.fcntl = None, supported() = False, hold() -> {}
  hermes serve / hermes doctor start fine.

Please get cfc15af into a release so Windows users don't need to patch
after every update.
