### PR TITLE
fix(config): model.provider survives config load as a string

### PR DESCRIPTION
**Pull request by strzhao**
# Read-path: `model.provider` reaches readers as a string, not an int

Addresses the read-path facet of #117345. The write-path facet (keeping
`hermes config set` from persisting the int) is covered by #117351 —
this PR is complementary to it, not a competing take: even with the
write side fixed, configs that already persisted `provider: 2` (or any
hand-written unquoted numeric) still load as int and kill the turn.

## Root cause

PyYAML loads the unquoted scalar `provider: 2` as `int`. Every downstream
reader treats the provider id as a string — `(provider or "").strip()`
appears 5 times in `agent/model_metadata.py` alone (39 across `agent/`)
— so on the messaging
gateway the turn dies before the agent runs, and the bot just never
replies. `get_model_context_length("deepseek-flash", provider=2)` on
current main reproduces it in one line:

    AttributeError: 'int' object has no attribute 'strip'

## Fix (two small hunks, one existing helper)

`_normalize_root_model_keys` is the single load/save chokepoint every
reader goes through, and it already canonicalizes the `model` section —
but its early-exit condition lets a plain `model: {provider: 2}` config
return untouched, and nothing stringified the routing key.

1. The early-exit condition now also enters work when `model.provider`
   is present and not a string.
2. After the section normalization, the key is coerced with the existing
   `coerce_provider_id` helper (introduced by #96505, which fixed the
   same int-coercion class for custom-provider names on the Desktop
   side). Guarded on presence, so provider-less configs gain no empty
   key and no config.yaml churn on the next save.

No new helpers, no new defaults. This is fail-open: the next save
rewrites the healed string back to config.yaml, so the persisted value
self-repairs.

## Tests

`tests/hermes_cli/test_config_provider_id_string.py` — 8 cases:

- int/str/nested-flatten/legacy-root-alias carriers normalize to str
- `load_config()` E2E through a real config.yaml (the gateway's entry):
  unquoted `2` -> `"2"`, falsy `0` preserved as `"0"`, `2.0` -> `"2.0"`
- negative: a provider-less model section gains no `provider` key

Verified RED-first on an unpatched base (5 failed / 2 passed), GREEN
after the fix (8 passed), and each hunk is mutation-pinned: reverting
the early-exit hunk alone turns the suite 4 failed, reverting the
coerce hunk alone turns it 5 failed. Neighbors
(`tests/hermes_cli/test_config.py` etc., 197 cases) pass, ruff clean.

## Relationship to other open work

- #117351 fixes the write path for the same issue and explicitly
  scopes the read side out ("gateway/model-metadata read-side
  normalization" in its non-goals) — together the two cover both
  facets the issue describes.
- #96505 already stringifies custom-provider *names* (dict keys and
  entry names); the routing key reference was the remaining gap, which
  is what this PR closes.

### CODE REVIEW

**Comment by tylerbrevard** [comment]
Duplicate/superseded by PR #117498. The salvage PR includes this read-path fix together with the write-path fix.

**Comment by strzhao** [comment]
Superseded by #117498, which carries the read-path commit cherry-picked with authorship preserved (verified on the commits list). Thanks @teknium1 for the salvage — closing.
