### PR TITLE
feat(desktop): expose update-all as a one-shot CLI action

### LINKED ISSUE #118098: [Feature]: expose Desktop's existing update-everything flow through a one-shot CLI action
## Problem or Use Case

I run Hermes on a Windows PC and a Linux VPS. I want one desktop shortcut to start updating both, without navigating through Desktop settings or maintaining a separate list of SSH hosts in a script.

Desktop already owns the registered connections and multi-target update flow. The missing piece is a supported external trigger, not another updater.

Proposed user command:

```sh
hermes desktop --update-all
```

This is a **launch/signal action for Desktop**, not a headless fleet-management command. Desktop would still display progress, authentication requests, safety blockers, and per-target results.

## Evidence baseline

Reviewed against [`080907e3b7ad4985cf4a7c73024a283a49381ba8`](https://github.com/NousResearch/hermes-agent/commit/080907e3b7ad4985cf4a7c73024a283a49381ba8), on 2026-09-21:

- [`hermes_cli/subcommands/gui.py`](https://github.com/NousResearch/hermes-agent/blob/080907e3b7ad4985cf4a7c73024a283a49381ba8/hermes_cli/subcommands/gui.py) registers `desktop` / `gui`, but has no update-all action.
- [`hermes_cli/main_desktop.py`](https://github.com/NousResearch/hermes-agent/blob/080907e3b7ad4985cf4a7c73024a283a49381ba8/hermes_cli/main_desktop.py) normally resolves/builds the packaged app and waits for it using `subprocess.run`.
- [`apps/desktop/src/store/updates.ts`](https://github.com/NousResearch/hermes-agent/blob/080907e3b7ad4985cf4a7c73024a283a49381ba8/apps/desktop/src/store/updates.ts) already provides `startActiveUpdate()` and the coalesced `applyEverythingUpdate()` flow: active remote backend, other eligible registered connections, then local client.
- [`apps/desktop/electron/main.ts`](https://github.com/NousResearch/hermes-agent/blob/080907e3b7ad4985cf4a7c73024a283a49381ba8/apps/desktop/electron/main.ts) already has single-instance delivery and queued main-to-renderer update requests. The new action should extend that boundary rather than introduce another connection manager.

Baseline reproduction: loading the real upstream `gui.py` parser in isolation on Linux/Python 3.13.5 rejects both `desktop --update-all` and `gui --update-all` with exit code 2, `unrecognized arguments: --update-all`. The source bytes were checked against Git blob `2a789694fbc667df05036cd324dbc1e91a421ffe`. This proves the parser gap; it is not a full CLI or Desktop end-to-end test.

## Proposed Solution

Add `--update-all` to `hermes desktop`, forwarding a narrowly typed local launch action into the existing Desktop update orchestration.

```text
shortcut / terminal
  -> hermes desktop --update-all
  -> existing primary Desktop instance, or launch it
  -> resolve Desktop routing and connection-registry readiness
  -> existing update-everything flow
```

Python must not read `connections.json`, decrypt credentials, or reimplement SSH, HTTP authentication, update eligibility, or fleet ordering.

### Required behavior

1. **Running and cold Desktop:** route to the primary instance, or queue the action during startup. Consume it once only after the listener AND the routing/registry state required by the update flow are ready. An unreachable remote must not cause an indefinite startup wait or a silent local-only update.
2. **No competing local build:** the action path should signal/launch an existing supported app, not run `npm install`, rebuild, or stop a running Desktop before handing off the request. If the required app is missing or cannot support the action, report an actionable failure rather than silently opening an ordinary window.
3. **No duplicate/replayed update:** repeated requests while pending or running coalesce. A relaunch performed by the updater must not replay the launch action. Normal later explicit invocations must still work.
4. **Preserve native safety:** reuse existing eligibility, update ordering, managed-SSH lifecycle, and refusal/confirmation behavior. No force flags, automatic credential entry, new network listener, or mutation-capable `hermes://` deep link.
5. **Launcher lifecycle:** the Python launcher must not remain an unnecessary venv holder during the Windows update. Distinguish successful launch/accepted dispatch from a completed fleet update; a launcher exit code must not be presented as proof that every machine updated.
6. **CLI compatibility:** normal `hermes desktop` / `hermes gui` behavior stays unchanged. Reject incompatible combinations such as `--build-only --update-all` before side effects.

## Acceptance and validation

- Parser and launch-argument propagation tests, including the `gui` alias and incompatible flags.
- Cold-start delivery with deliberately delayed registry/routing initialization.
- Delivery to an already-running primary instance without starting a competing backend.
- Repeated requests, renderer readiness/reload, and updater relaunch do not duplicate the operation.
- Single-target and multi-target cases use existing updater behavior; unreachable/skipped targets remain visible.
- Real Windows integration check that the launcher neither blocks the venv nor dies with the initiating `.cmd` window before handoff.
- Applicable Linux/macOS launch checks; report tested platforms and limitations honestly.
- Documentation states explicitly that this opens/signals Desktop, is not headless, and does not provide a synchronous fleet-success exit status.

## Alternatives Considered

- `hermes update --all-instances` that parses Desktop's private registry: duplicates Desktop-owned connection, credential, and lifecycle responsibilities.
- `hermes://update/all`: unnecessarily lets browser-delivered URLs request a mutating operation.
- A user-maintained local-plus-SSH script: works today, but keeps a second machine inventory outside Hermes.

## Related work and scope

- #90634: existing Desktop update-everything orchestration.
- #104604: Settings button alignment with the ordered flow. This request is an external trigger, not a competing ordering fix.
- #118029: broader managed-SSH rollout coordination. No canaries, pinned rollout plans, new journals, scheduling, or second fleet control plane are requested here.

The implementation should remain a focused adapter around existing seams. A fixed line-count target is less important than correct startup, ownership, and handoff behavior.

## Feature Type

CLI improvement / Desktop integration

## Contribution

- [x] I'd like to implement this myself and submit a PR.

No implementation or passing end-to-end tests are claimed by this issue.

### PR DESCRIPTION
**Pull request by sealca**
## What does this PR do?

Adds a shortcut-friendly entry point for Desktop's existing update-everything flow:

```sh
hermes desktop --update-all
# `hermes gui --update-all` also works.
```

The command launches/signals an **existing packaged Desktop build**, without rebuilding it first. Desktop continues to own the connection registry, credentials, managed SSH updates, ordering, progress and safety prompts. Python does not implement a second updater or read `connections.json`.

This is a **Desktop launch action, not a headless or synchronous fleet updater**. Exit code 0 reports an accepted/coalesced request, not successful updates on every machine.

## Related Issue

Closes #118098.

Builds on the orchestration introduced in #90634. Complements #104604 without changing the Settings button. Does not implement the rollout/canary scope of #118029.

## Type of Change

- [x] New feature (non-breaking change that adds functionality)
- [x] Bug fix: avoid skipping the local update during cold-start checks
- [x] Documentation and tests

## Changes Made

- `hermes_cli/subcommands/gui.py` / `main_desktop.py`: accept the action, reject incompatible build/runtime overrides before side effects, and use the existing packaged-app resolver. Normal Desktop launches are unchanged.
- `hermes_cli/desktop_update_request.py`: a short-lived local request/acknowledgement/commit handoff. Older apps that ignore the action time out without committing an update. The detached app waits for the Python launcher, and the Windows console shim when present, to exit before dispatching, rather than leaving the launcher holding the venv.
- `apps/desktop/electron/update-all-launch.ts` and native bridge wiring: validate the request, route cold and second-instance launches, coalesce repeated requests, wait for renderer readiness, and consume the argument before relaunch. A renderer interruption is reported rather than replayed. This is launch-intent bookkeeping, not another update lifecycle.
- `src/store/update-all-launch.ts`: obtain the local registry with a bounded wait, then call `applyEverythingUpdate()` directly. An unconnected remote primary cannot make the launch silently choose a local-only path.
- `src/store/updates.ts`: coalesce client checks and let a forced check wait for an in-flight passive check before refreshing. The real Electron test exposed the old race: remote dispatch completed while an unfinished startup check made the local client look current. The new regression fails against the previous implementation.
- Focused Python, native Electron, renderer and Electron integration tests; CLI reference and shortcut documentation.

No dependencies, credential formats, public URL actions, network listeners, force-update flags, or fleet inventory were added. Existing update refusals and confirmations remain in place.

## How to Test

From the repository root, using the project environment:

```sh
scripts/run_tests.sh tests/hermes_cli/test_desktop_update_request.py tests/hermes_cli/test_gui_command.py tests/hermes_cli/test_desktop_startup_cost.py tests/hermes_cli/test_desktop_local_flag.py tests/hermes_cli/test_subcommands_batch.py -q
```

From `apps/desktop`:

```sh
npx vitest run --maxWorkers=2 electron/update-all-launch.test.ts src/store/update-all-launch.test.ts src/store/updates.test.ts src/app/contrib/hooks/use-desktop-integrations.test.tsx
npm run typecheck
npm run build
xvfb-run -a --server-args='-screen 0 1280x1024x24' npx playwright test e2e/update-all-launch.spec.ts --workers=1 --retries=0 --repeat-each=3
```

The Electron integration test uses the real built app, local request files, process liveness, second-instance delivery, preload and renderer. **Only the final update effects are replaced**, so the test does not update its own checkout or a real VPS. It checks remote-before-local ordering, duplicate coalescing and no replay after a reload.

For a manual update smoke test, use disposable local/remote installations and a Desktop build containing this change. Run the command with Desktop closed and already open; inspect Desktop for the actual update results. The documented Windows `.cmd` example uses `call hermes desktop --update-all`.

### Executed validation

Current head: `58e9822445a468c155bc070e61aef170a0469071`, rebased onto upstream `fde4997f580c3480798fdf9c7e92c0079d6e03d6`.

[Original integration validation](https://github.com/sealca/hermes-agent/actions/runs/35595368611), [review-polish validation on Linux/Windows/macOS](https://github.com/sealca/hermes-agent/actions/runs/35738890724), and [rebased-tree validation](https://github.com/sealca/hermes-agent/actions/runs/35739695846):

| Check | Result |
| --- | --- |
| Focused Python suite on Linux | 63 passed, 13 platform-specific skips |
| Desktop unit/regression tests | 102 passed |
| Real Electron integration on Linux | 3 consecutive passes, retries disabled |
| New cold-start regression on pre-fix implementation | Fails as expected; passes with the fix |
| Renderer, Electron and E2E TypeScript projects | Passed |
| ESLint, Prettier, Ruff, Windows-footgun audit, diff check | Passed |
| Native Python launch/process tests on Windows and macOS | Both jobs passed on their actual operating systems |

The validation-only workflows and staging branches are **not part of this PR**. The rebased Desktop and Python focused suites plus TypeScript checks passed before publication; the final publish-only run reconstructed that exact reviewed tree and wrote it as a single feature commit. The failed status on the rebased-tree validation run is from GitHub refusing the final branch push because the fork was behind on upstream workflow commits, after all test steps had passed; the feature was then published through Git data without modifying workflows.

**Limits:** the full Python suite was not run. Packaged Electron UI/self-update was not exercised on Windows/macOS, and no real PC/VPS installation was updated. Native process tests there use a small app simulator; they are not a claim of full cross-platform fleet-update E2E coverage.

### Code

- [x] Read `CONTRIBUTING.md` and the applicable root, CLI and Desktop engineering guides.
- [x] Conventional Commits; focused feature branch rebased onto current upstream `fde4997f580c3480798fdf9c7e92c0079d6e03d6`.
- [x] Searched existing issues, open/closed PRs and source for duplicates.
- [x] No unrelated functional changes or validation infrastructure in the PR.
- [x] Added tests and ran the affected suites through the repository's test runner.
- [ ] Full `pytest tests/ -q` suite: not run.
- [x] Tested on Linux; native launch/process tests also ran on Windows and macOS, with the limits above.

### Documentation & Housekeeping

- [x] CLI reference and multi-connection/shortcut documentation updated.
- [x] Configuration example: N/A, no configuration keys added.
- [x] Architecture/engineering guides: existing authority boundaries retained.
- [x] Cross-platform process lifetime and file handling considered and tested.
- [x] Model tool descriptions/schemas: N/A.

## Screenshots / Logs

The linked validation runs include the fail-before regression, passing focused suites, cross-platform handoff checks, typecheck/build output, and the rebase verification.

### CODE REVIEW

**Review by sealca — COMMENTED** [review]
## Author-side review of `bf5e2308`

Reviewed the published diff, the launch/IPC/renderer path and the validation evidence. No blocking defect found within the tested boundaries. This is an author-side review, not independent maintainer approval.

### Boundaries checked

- The Python action takes its early return before the ordinary build path and rejects incompatible flags before effects. It neither reads Desktop's registry nor implements remote updates.
- Dispatch requires an acknowledged and committed local request. The native side waits for the launcher PIDs to exit; old apps cannot silently accept an unsupported operation. The private argument is consumed before relaunch and is not exposed through a public URL handler.
- Requests pending/in flight coalesce. Main-renderer readiness and completion are primary-window scoped. A renderer interruption is reported rather than turning an uncertain operation into an automatic replay.
- Registry loading is bounded and failures do not fall back to a local-only update. The adapter calls the existing `applyEverythingUpdate()` flow.
- The cold-start client-check race found during E2E validation is fixed. The new regression demonstrably fails on the pre-fix implementation; forced checks now wait for a passive check and then refresh, while concurrent forced checks share work.
- Managed SSH ownership, remote authentication and existing update confirmations/refusals remain with their existing implementations. No forced update or automatic credential entry was introduced.

### Evidence and scope

[Final fork validation](https://github.com/sealca/hermes-agent/actions/runs/35595368611): 102 Desktop tests; 63 Python tests on Linux; three consecutive real Electron integration passes with retries disabled; typecheck/lint/build/compatibility checks; native Python process tests on Windows and macOS. The integration test replaces the final update effects, not the launch/IPC/renderer path.

The 17 changed files reconstructed against the reviewed upstream baseline produce tree `65fd976771c65b423bdeb699157abae6cfbe3587`, matching the published commit. The helper workflow and staging payloads are absent from the PR. GitHub currently reports the PR mergeable; the intervening upstream changes do not overlap these files.

Remaining validation limits are explicit in the PR: no full Python suite, no packaged Electron UI/self-update run on Windows/macOS, and no real PC/VPS update. Those should not be inferred from the passing process/integration tests.

**Comment by kyssta-exe** [comment]
## Summary

Adds `hermes desktop --update-all` as a thin launch action that hands a one-shot request file to an existing packaged Desktop build, which continues to own the registry, ordering, progress, and safety prompts. Python implements no updater logic — exit 0 means accepted/coalesced, not updated. The design correctly avoids a second updater, duplicate credential handling, and headless fleet semantics.

## What changed

- `hermes_cli/desktop_update_request.py` (new) — staged atomic write of `request.json`, detached spawn, short-lived pending/accepted/committed handshake with id check.
- `hermes_cli/subcommands/gui.py`, `hermes_cli/main_desktop.py` — accept `--update-all`, reject incompatible build/runtime overrides before side effects.
- `apps/desktop/electron/update-all-launch.ts` + bridge — validate, coalesce repeats, wait for renderer readiness, consume argv before relaunch; renderer interruption reported, not replayed.
- `src/store/updates.ts` — forced check waits for in-flight passive check (fixes local-looking-current race); `update-all-launch.ts` store calls `applyEverythingUpdate()` with bounded registry wait.
- Tests at Python, Electron, renderer, and real-app integration levels plus CLI docs.

## Strengths

- Staged `.tmp` + atomic rename for the request file avoids torn reads by the polling loop.
- `id` mismatch guard and `coalesced`/`interrupted` states handle second-instance and crash-recovery paths explicitly.
- Launcher-PID wait (including the Windows console shim) shows real understanding of the venv-lock problem.

## Findings

- `hermes_cli/desktop_update_request.py` (`_launcher_pids`): `import psutil` runs unguarded on win32, but the surrounding `try` in `launch_desktop_update_all` only catches `(OSError, ValueError)` — a missing `psutil` raises `ImportError` and escapes as a traceback instead of the clean "Could not hand the update request" message. Wrap the import or add `ImportError`/`Exception` to the handler.
- `hermes_cli/desktop_update_request.py` (`launch_desktop_update_all`): the `subprocess.Popen` handle is never reaped or closed — CPython will emit a `ResourceWarning`. Assign and `popen.poll()`/detach explicitly, or close fds deliberately.
- Non-blocking: the 50ms poll loop re-reads and `json.loads` the file each tick; on a network tmpdir this is chattier than needed. Fine at 30s scale, but an exponential backoff (50ms → 250ms) would be kinder.

## Verdict

Needs minor polish (the `psutil` failure path is the one user-facing wart).

*Reviewed using Hermes-Agent*

**Comment by sealca** [comment]
Thanks for the review — addressed the polish points in the rebased head `58e98224`.

- **Polling:** changed the fixed 50 ms loop to a bounded backoff (50 → 100 → 200 → 250 ms).
- **Popen lifecycle:** the handle is now explicit, uses `close_fds=True`, and is opportunistically `poll()`ed when Desktop acknowledges. I also documented why we intentionally must not wait/reap synchronously: Desktop waits for the launcher PID(s) to disappear before touching the venv, so blocking on the Desktop process here would deadlock the handoff.
- **psutil:** I left this fail-fast intentionally. `psutil==7.2.2` is a core Hermes dependency in `pyproject.toml`, so an `ImportError` means the supported installation itself is broken. Adding a local defensive fallback here would mask that state and conflicts with the repo's guidance against defense-in-depth wrappers around required dependencies.

The focused handoff suite + Ruff passed on Linux, Windows and macOS: https://github.com/sealca/hermes-agent/actions/runs/35738890724

I also rebased the PR onto current upstream `main`, preserving upstream's newer Desktop changes. The focused Desktop + Python suites and TypeScript checks passed on that rebased tree before publication. GitHub now reports the PR mergeable again.
