### ISSUE TITLE
[Bug]: hermes update — transient ImportError (cannot import file_signature from utils) in gateway-restart phase and atexit cleanup

### ISSUE THREAD

**Issue by danindiana** [NousResearch/hermes-agent#112522]
## Bug Description

`hermes update` (upgrading from an earlier commit to v0.21.3, `main @ 30b22b54`) printed a
gateway-restart failure at the end of an otherwise-successful run, and the same `ImportError`
fired again, uncaught, in two atexit cleanup callbacks at process exit:

```
✓ Update complete! (v0.21.3) [main @ 30b22b54]
→ Refreshing cua-driver (Computer Use)...
✓     cua-driver upgraded: cua-driver 0.28.1 → cua-driver 0.28.2

⚠ Update incomplete — gateway auto-restart failed: cannot import name 'file_signature' from 'utils' (/home/<user>/.hermes/hermes-agent/utils.py)
  Any gateway still running is serving pre-update code
  (mixed sys.modules) against the updated checkout.
  Restart it manually, then verify:
    hermes gateway restart
    hermes gateway status

Exception ignored in atexit callback: <function _stop_browser_cleanup_thread at 0x...>
Traceback (most recent call last):
  File ".../tools/browser_tool_lifecycle.py", line 425, in _stop_browser_cleanup_thread
    _bt._cleanup_running = False
  File ".../tools/browser_tool_origin.py", line 84, in __setattr__
    setattr(origin_module(3), name, value)
  File ".../tools/browser_tool_origin.py", line 70, in origin_module
    import tools.browser_tool as mod
  File ".../tools/browser_tool.py", line 25, in <module>
    from hermes_cli.config import DEFAULT_CONFIG, cfg_get
  File ".../hermes_cli/config.py", line 33, in <module>
    from utils import atomic_replace, atomic_yaml_write, fast_safe_load, file_signature
ImportError: cannot import name 'file_signature' from 'utils' (/home/<user>/.hermes/hermes-agent/utils.py)
```

The same traceback repeated for a second atexit callback (`_emergency_cleanup_all_sessions`).

**This does not reproduce on retry** — a second `hermes update` run immediately afterward
completed with no error. Filing this because the existing, documented mitigation for exactly this
symptom class apparently didn't fully prevent it this one time, which seems worth a maintainer
look even though it's low severity and self-resolved.

## Steps to Reproduce

Not reliably reproducible — occurred once during a routine `hermes update` (no gateway configured
or running on this machine; CLI-only usage). A second `hermes update` run right after did not
reproduce it. Best guess at contributing factors: the updated version added `file_signature` to
`utils.py`, and the update process had already imported the old `utils` module earlier in its own
run before the git pull landed.

## Expected Behavior

`hermes update` completes without any `ImportError`, or — if a stale-module race is unavoidable
in some code paths — the gateway-restart phase and atexit handlers fail without printing a raw
Python traceback to the user.

## Actual Behavior

See the traceback above. The update itself succeeded (code, config migration, skills sync,
cua-driver upgrade all completed and reported success) — only the gateway-restart phase and the
process's own atexit cleanup hit the `ImportError`. Verified independently that this was cosmetic/
non-blocking: `utils.py` on disk genuinely defines `file_signature`; a fresh `hermes --version`
and fresh one-shot invocation both worked immediately afterward (exit 0); `hermes gateway status`
showed no gateway running at all, so the gateway-restart phase had nothing real to restart on this
machine; all local config was intact post-update.

## Affected Component

- Setup / Installation
- CLI (interactive chat)

## Messaging Platform (if gateway-related)

N/A (CLI only) — no gateway was configured or running when this occurred.

## Debug Report

Skipped the automatic `hermes debug share` upload for this report: previewed it locally
(`hermes debug share --local`) first, and the last-200-lines `agent.log` excerpt it includes would
have pulled in unrelated content from other conversations in the same log file that I'd rather not
put on a public paste service. Providing the directly relevant info by hand instead (see
`hermes dump`-equivalent fields below, and the traceback above, which is copied verbatim from the
terminal aside from redacting the home directory path to `/home/<user>/`).

## Operating System

Ubuntu (Linux 6.8.0-138-generic x86_64)

## Python Version

3.11.16

## Hermes Version

0.21.3 (the version being updated *to*; commit `30b22b54` at the time of the failure — current
`main` has since moved to `10652c93`)

## Additional Logs / Traceback (optional)

Already included verbatim above (Bug Description section) — this is the complete output relevant
to the failure, not truncated.

## Root Cause Analysis (optional)

Traced this before filing, since the relevant fix already exists in the codebase and is clearly
labeled:

`hermes_cli/update_cmd_maint.py`'s `_purge_stale_hermes_modules()` (around line 111) evicts every
checkout-owned module from `sys.modules` after a pull, specifically to prevent this class of bug —
its own docstring for `_stale_purge_prefixes()` (around line 92) names this *exact* symptom as the
motivating case:

> "the symbol that breaks the next update is in whichever one drifted out — `utils` gaining
> `base_url_origin` / `file_signature` were the field cases."

It's called from `update_cmd_config.py:186` (every update-completion path, citing issue `#111271`
in its own comment) and from `update_cmd_fleet.py:362` and `:1304` — the second call site's own
comment says it purges "FIRST" specifically because "the import below loads new gateway source
into this pre-update interpreter, and a cached sibling missing a symbol the new source expects
would ImportError and abort the whole phase."

That's exactly what happened here anyway. I didn't dig further into *why* the purge didn't fully
prevent it in this instance, but `_purge_stale_hermes_modules()`'s own docstring already flags a
plausible limit: "Purging (unlike reload) only drops the `sys.modules` entry — running frames keep
their module objects." If some other already-executing frame in the same update process held a
live reference to the old `utils` module object (bound before the purge ran), evicting the
`sys.modules` entry wouldn't fix that already-bound name — only a fresh import from that point
forward. That's a guess at the mechanism, not a confirmed diagnosis; flagging it as the most
promising lead for whoever picks this up, since you clearly already understand this bug class
better than an outside report can.

## Proposed Fix (optional)

No specific fix proposed — the existing `_purge_stale_hermes_modules()` mechanism looks like the
right general approach, this is just a report that it (or its call-site placement) didn't fully
cover this particular process/import-graph shape. Might be worth an `importlib.reload()` pass (not
just eviction) for modules with live bound references from earlier frames in the same process,
if that's in fact the mechanism — but that's a guess from outside the codebase, not a real fix.

## Are you willing to submit a PR for this?

No — filing for visibility/reproduction data, not planning to submit a fix myself.

**Comment by TQMatvey** [comment]
bump, same, cant update

**Comment by gokhanyildirimlar** [comment]
Root-caused this on Windows (git install) — hit the identical signature today updating 0.21.2 (`6bc0e9e6`) → 0.21.3 (`3abeca16e6`), and there is a subtlety worth recording for whoever triages:

**The failure is pre-pull purge code, and the fix that already landed on main only arms on the *next* update.**

Mechanics, verified against both trees locally:

1. The updater process executes the **pre-pull** checkout's code for the whole run — the `hermes_cli.update_*` family is deliberately protected from the post-pull stale-module purge (`_STALE_PURGE_PROTECTED_PREFIX`, receipt/plan state would break otherwise).
2. The pre-fix purge covered only five top-level packages: `_STALE_PURGE_PREFIXES = ("hermes_cli", "gateway", "tools", "tui_gateway", "agent")` — root-level modules like `utils` were **not** purged (verified: my launching tree `db64ddb5` has this list, and its `utils.py` has no `file_signature`).
3. The pulled tree's `hermes_cli/config.py` added `from utils import ..., file_signature`. The gateway-restart phase purges `hermes_cli.*` and re-imports fresh → new `config.py` meets the **cached old `utils`** → the `ImportError` → `_warn_gateway_restart_phase_aborted` prints the "Update incomplete" block. The two atexit tracebacks are the same mixed-graph import firing in `origin_module()`'s fresh-import fallback.
4. Fixed on main by #109314 (`29758a4eb` + follow-ups `9395f2f0d`/`d6ea7aa00`/`5341f135a`, Sep 15): the purge is now scanned from the checkout (`_stale_purge_prefixes()` — every top-level module, `utils` included), and its docstring names this exact field case.

**The transition window:** because of (1), the update that *pulls* the fix still runs the old purge — which is why this report fired on a target tree that already contains `29758a4eb` (confirmed: `29758a4eb` is an ancestor of `30b22b54`, 301 commits ahead). One update later the scan purge is the launching code and this failure class can't reproduce. My landed tree (`3abeca16e6`) contains the scan purge, so our next update is expected clean.

Suggested resolution: **fixed on main / transition-window** — no new fix needed at the updater layer. The atexit half is already covered by the racing hardening PRs #112439 (verified on Windows: base propagates the field `ImportError` out of both hooks, PR branch silent, `test_browser_cleanup.py` 8/8) and #112530 (same intent via a `_safe_atexit` wrapper).

**Comment by WizSoloMaster** [comment]
Independent recurrence on a different host and a different pull — and I don't think "transient" is the right frame: the mechanism looks deterministic.

Run: `hermes update` on Linux, git install, systemd `--user` gateway + dashboard. Pre-pull `d8053f48` → post-pull `16bf9a1c49` (840 commits, v0.21.3):

```
✓ Update complete! (v0.21.3) [main @ 16bf9a1c]
  ✓ Restarted supervised gateway(s) in a fresh process (systemd-verified active): default
⚠ Update incomplete — gateway auto-restart failed: cannot import name 'file_signature' from 'utils' (/home/<user>/.hermes/hermes-agent/utils.py)
```

Why it happens (measured, not inferred):

1. The updater process executes the **pre-pull** code, so it runs the **pre-pull purge**. At the pre-pull commit, `hermes_cli/update_cmd_maint.py:30` was `_STALE_PURGE_PREFIXES = "hermes_cli", "gateway", "tools", "tui_gateway", "agent"` and line 90 filtered on it, so a root-level module such as `utils` is **never evicted** and the cached pre-pull `utils` object stays in `sys.modules`.
2. The post-pull chain (`hermes_cli.gateway` → … → `model_tools`) does `from utils import file_signature`, and `file_signature` was added to `utils.py` *inside this same pull* (commit `a1e7f74e64`, 2026-09-15T13:29Z, "stat signatures cover inode + ctime everywhere config identity is cached").
3. The fix for that exact gap — `29758a4eb2` ("purge every top-level checkout module, not just five packages", 2026-09-15T16:27Z, which closed #111944) — landed in the same pull. So the run that carried the fix still aborted: a pull cannot protect itself, because the process executing it is pre-pull.

That makes it repeatable rather than flaky: it recurs on any update that crosses a commit adding a symbol to a root-level module that post-pull code imports. `base_url_origin` and `file_signature` are the two field cases. 29758a4eb2 covers later updates; I'd suggest linking this report to #111944 as its root cause (or retitling away from "transient").

Downstream damage on this run, for the record: the run wrote **no receipt** (`~/.hermes/logs/update_receipts/latest.json` stayed on the previous run), the post-restart tail never printed (the same path printed `Tip:` and the fleet version check the day before), and the leftover `fleet_restart_pending` marker kept the "did not restart running gateways" notice on every CLI/gateway start — even though the fresh-process recovery restart did put the gateway on `16bf9a1c49`.

**Comment by seaavey** [comment]
I hit the same issue on Linux after updating with `hermes update` from v0.21.3 git install.

Relevant output:

```text
Exception ignored in atexit callback: <function _stop_browser_cleanup_thread at 0x7582316462a0>
...
ImportError: cannot import name 'file_signature' from 'utils' (/usr/local/lib/hermes-agent/utils.py)

Exception ignored in atexit callback: <function _emergency_cleanup_all_sessions at 0x758231646940>
...
ImportError: cannot import name 'file_signature' from 'utils' (/usr/local/lib/hermes-agent/utils.py)
```

The update itself reported:

```text
✓ Update complete! (v0.21.3) [main @ 6cd2502629]
⚠ Fleet version check returned no rows even though gateway runtimes were expected — verification incomplete.
```

Environment:
- OS: Linux 6.14.11-4-pve
- Install: `/usr/local/lib/hermes-agent`
- Hermes: v0.21.3, commit `6cd2502629`
- cua-driver: 0.28.2

This appears to be the same mixed old/new module graph during the update restart/atexit cleanup described in this issue. The installation completed, but the atexit callbacks still emitted the ImportError and fleet verification remained incomplete.

**Comment by MoJo-Spy** [comment]
Native-Windows confirmation of the same stale-module failure, following the junction failure documented in #97173.

Environment:
- Windows 11 x64, build 26100
- Git install, Hermes Agent v0.21.2 -> v0.21.3
- Target commit: `main @ 6bea68a1de`

After removing the dangling skill junction, the update reached:

```text
✓ Code updated! [main @ 6bea68a1de]
✓ Update complete! (v0.21.2 -> v0.21.3)
⚠ Update incomplete — gateway auto-restart failed: cannot import name `file_signature` from `utils`
```

The same `ImportError` then appeared in the browser cleanup atexit callbacks. A fresh one-shot Python process confirmed that the updated `utils.py` on disk does define `file_signature`; this was only the updater process retaining a pre-pull `utils` module while loading post-pull code.

Recovery was successful with a fresh process:
- `hermes gateway restart` started the gateway
- `hermes gateway status` reported the gateway running
- Hermes Desktop launched and remained responsive

So this is reproducible on the Windows Desktop/gateway path even when the code update itself completes; the failure is in the in-process post-update restart/cleanup phase.

**Comment by grzegorzsunmed-debug** [comment]
Another live repro — different platform, different launch path — confirming this is deterministic, not transient.

**Environment:** Raspberry Pi 5 (ARM64, Debian), git install, systemd `--user` gateways (default profile + one named profile), v0.21.2 → v0.21.3. The update was launched detached via a transient `systemd-run --user` unit (updating from inside the gateway's own cgroup), target `main @ 4e9d3c71`.

**Same signature:**
```
✓ Update complete! (v0.21.2 → v0.21.3) [main @ 4e9d3c713a]
⚠ Update incomplete — gateway auto-restart failed: cannot import name 'file_signature' from 'utils' (/home/<user>/.hermes/hermes-agent/utils.py)
  Any gateway still running is serving pre-update code
  (mixed sys.modules) against the updated checkout.
```

**Fleet reality vs. the report:** both gateways had in fact restarted onto the new checkout (SIGUSR1 drain on the default profile, systemd restart on the named one; verified via each `gateway_state.json` — `code_sha` == `git rev-parse HEAD`, fresh start timestamps). The "auto-restart failed" line is a false alarm for the fleet here.

**Downstream effects (matching #113133):** `⚠ Fleet version check returned no rows…` → exit 1; **no receipt written** to `~/.hermes/logs/update_receipts/`; and a stale `~/.hermes/fleet_restart_pending` marker left behind — which then prints the "did not restart running gateways" warning on every `hermes` invocation. Closed the marker manually after verifying evidence (`git merge-base --is-ancestor <expected_sha> HEAD`; both gateways on HEAD); with carried local commits the auto-discharge can never fire — details in #109573.

**Timeline note:** the pre-pull updater here was `31d0a242` (predates the purge fix), while the post-update checkout `4e9d3c71` already contains the scan-based purge (`_stale_purge_prefixes`). Consistent with the triage note in #113133 — the next update hop from this tree should not reproduce it.
