### PR TITLE
feat(gateway): expose cron run history and output over HTTP

### LINKED ISSUE #93299: API server: expose cron run history (and run output) over HTTP
### Is your feature request related to a problem?

We run a self-hosted Hermes backend and are building a small browser workspace for its Bot Mode (a roster of named agents with persistent chats and cron routines). The Routines pane can show that a job's latest attempt took 14m 22s and failed twice in a row — but it cannot show whether that is normal for the routine, how often it fails over time, or what the run actually produced.

Investigating this against `main` (2026-08-24) established two gaps in the API server's cron surface:

**Run history is one route away.** `cron/executions.py::list_executions(job_id=…, limit=…, before_claimed_at=…)` already returns indexed, newest-first, cursor-paginated history (verified against `main`). But nothing serves it over HTTP: `GET /api/jobs` attaches only `latest_execution`, the single newest row from the ledger. The data model and query path both exist — only the route is missing.

**Run output has no API surface at all.** A run's text goes to `HERMES_HOME/cron/output/<job id>/<timestamp>.md`, read back only by `cron.scheduler` (for `context_from`) or by a human with a shell. Even `hermes cron runs <id>` prints the ledger, not the output. For a `deliver: local` routine — which is what our UI creates — the result is invisible to the user who scheduled it.

### Describe the solution you'd like

Two additive, read-only routes:

- `GET /api/jobs/{job_id}/executions?limit=&before=` → what `list_executions` already returns.
- `GET /api/jobs/{job_id}/output` (latest) and `GET /api/jobs/{job_id}/output/{timestamp}` → reading the existing output files, with whatever job-id validation the writer (`_job_output_dir`) already applies.

One design note: the executions ledger's docstring calls itself an audit trail, so attaching run output to those rows would change its purpose. Serving the output files separately keeps the ledger's role intact and is the smaller ask of the two.

### Describe alternatives you've considered

A client co-located with the backend could read `HERMES_HOME/cron/output/` directly. We ruled it out deliberately: it couples the client to the backend's filesystem layout (which upstream may change), silently does nothing for non-co-located clients, and opens a second data path that bypasses Hermes' own API surface. Everything a custom client needs should flow through the API server.

### PR DESCRIPTION
**Pull request by chelsealong**
## What

Closes #93299.

`cron/executions.py::list_executions(job_id=…, limit=…, before_claimed_at=…)`
already returns indexed, newest-first, cursor-paginated execution history —
verified against `main` — but nothing serves it over HTTP. `GET /api/jobs`
only attaches `latest_execution`, the single newest ledger row
(`cron/jobs.py` around `list_jobs()`).

A run's text output goes to
`HERMES_HOME/cron/output/<job id>/<timestamp>.md`, read back only by
`cron.scheduler` (for `context_from`) or a human with a shell — even
`hermes cron runs <id>` prints the ledger, not the output. For a
`deliver: local` job, the result is invisible to a remote client.

This adds two additive, read-only routes, following the existing
`/api/jobs/*` handler pattern (auth check → cron-availability check →
job-id validation → job lookup):

- `GET /api/jobs/{job_id}/executions?limit=&before=` → what `list_executions`
  already returns.
- `GET /api/jobs/{job_id}/output` (latest run) and
  `GET /api/jobs/{job_id}/output/{timestamp}` (a specific run) → the saved
  output text.

Per the issue's design note, output is served as its own route rather than
attached to execution rows, since the ledger's docstring calls itself an
audit trail and attaching output would change that.

## How

- `cron/jobs.py`: added `list_job_outputs(job_id)` and
  `read_job_output(job_id, timestamp=None)`. Both reuse `_job_output_dir`'s
  existing path-escape guard; `read_job_output` additionally rejects any
  `timestamp` that doesn't match the exact filename stem
  `save_job_output` writes (`YYYY-MM-DD_HH-MM-SS`), so a caller can't walk
  the output directory with a crafted timestamp.
- `gateway/platforms/api_server.py`: registered the two routes and their
  handlers (`_handle_list_job_executions`, `_handle_get_job_output`),
  matching the auth/validation/error shape of the other `/api/jobs/*`
  handlers exactly.
- `website/docs/user-guide/features/api-server.md`: documented the new
  endpoints alongside the existing Jobs API section.

## Test plan

Added tests and confirmed they fail without the fix
(`git stash` the two source files, rerun, restore):

```
$ python3 -m pytest tests/cron/test_jobs.py tests/gateway/test_api_server_jobs.py -q
99 passed, 23 warnings in 3.23s
```

Without the fix (source files reverted, tests kept):

```
tests/cron/test_jobs.py: ImportError: cannot import name 'list_job_outputs' from 'cron.jobs'
tests/gateway/test_api_server_jobs.py: 6 failed — AttributeError: 'APIServerAdapter' object has no attribute '_handle_list_job_executions'
```

Also ran the full `cron/` suite and the `api_server`-related `gateway/`
suite to check for regressions:

```
$ python3 -m pytest tests/cron/ -q
877 passed, 1 skipped in 51.12s

$ python3 -m pytest tests/gateway/ -q -k api_server
253 passed, 2 skipped, 5931 deselected in 27.82s
```

`ruff check` on all changed files passes clean.

## AI assistance disclosure

This PR was written with AI assistance (Claude Code), reviewed and verified
against `main` before submission.

### CODE REVIEW

**Comment by chelsealong** [comment]
Addressed points 1 and 2 from the automated review in 3bf495152:

- `limit` is now clamped to `[1, 500]` server-side, so `?limit=1000000` no longer streams the whole ledger and negative values no longer reach `list_executions` (where SQLite treats negative `LIMIT` as unbounded).
- `before` is validated with `datetime.fromisoformat` and returns 400 on a malformed cursor instead of falling through to the generic 500.

Added tests for both cases in `tests/gateway/test_api_server_jobs.py` (confirmed they fail against the prior code). Left point 3 (distinguishing job-deleted-mid-request from output-not-found) as-is per the reviewer's own note that it "isn't worth much."

**Comment by brianoestberg** [comment]
Friendly nudge from a downstream consumer of this work 👋

I self-host Hermes and built a web workspace on top of the Runs/Jobs API (https://github.com/dotlegal-compliance/agent-os — sessions chat, routines pane, cross-bot delegation). The routines pane currently surfaces only `latest_execution` from `GET /api/jobs`, so a user can see their job took 14m 22s but has no way to know whether that's normal, how often it fails, or whether it's getting slower — exactly the gap #93299 describes.

This PR is the precise shape we're waiting for: it reuses the existing `list_executions` ledger and `save_job_output` stems instead of adding storage, and the two routes mirror the `/api/jobs/*` handler pattern. The automated review found only nits and the author addressed them same-day.

Is there anything blocking review here — more context, test coverage, or rebasing? Happy to help however useful. This (or #84045, which covers the output half) unblocking would let a downstream UI show real run history and output for scheduled jobs.

**Comment by brianoestberg** [comment]
@chelsealong — a rebased branch is available so this doesn't have to wait on a maintainer merge:

**`https://github.com/brianoestberg/hermes-agent` branch `rebase/cron-executions-output-api`** — your two commits cherry-picked onto current main (three textual conflicts resolved: the cron import block, the route table, and the `jobs.py` section header), plus one small follow-up commit.

**The follow-up is the part a plain rebase couldn't catch.** While the branch was out, main replaced the per-step helpers your new handlers were written against (`_check_auth` + `_check_jobs_available` + `_check_job_id`) with the shared `_cron_request_guard` prelude. Git resolved the merge cleanly without touching handler bodies — but at runtime the two new handlers crashed with `AttributeError: ... has no attribute '_check_jobs_available'`, surfacing as 9 quietly failing tests in `test_api_server_jobs.py`. Commit 3 (`refactor(gateway): port the two new cron handlers to _cron_request_guard`) rewrites their guards to the shared prelude — no behavior change relative to this PR as reviewed, just the same auth → cron-available → job-id order the sibling handlers now get.

**Verification:** `tests/gateway/test_api_server_jobs.py` + `tests/cron/test_jobs.py` — 148/148 passing. Full `tests/gateway/` (non-relay, non-platforms): 8401 passed, and the 12 failures are byte-identical to running the same suite on unmodified main (verified in a separate worktree) — two pre-existing on main, the rest environment-flaky under xdist, all passing in isolation. `ruff check .` green.

**One contract suggestion before this lands, from a downstream consumer** ([agent-os](https://github.com/dotlegal-compliance/agent-os), the run-history pane this unblocks): ledger rows carry UUID ids, output files are second-resolution timestamp stems, and `finished_at` ≠ stem (observed a 1.3s skew with concurrent attempts), so a client cannot reliably join an execution to its output by timestamp. Either an `output_stem` (or `output_id`) field on the execution record, or a `list_outputs` route whose entries carry the owning execution's id, would close it — cheap to add now while the response shape is still unfrozen, and it would let the UI link each historical run to its report from day one.

Happy to open a PR from the fork branch if that's easier to review, or to hand it back however you prefer.

**Comment by chelsealong** [comment]
Thank you — and yes, please open the PR from your fork. That is easier to review than a branch reference, and it keeps the follow-up commit attributable to you rather than folded into mine.

I checked your three claims against current main before replying, and all three hold:

- `_cron_request_guard` is defined once in `gateway/platforms/api_server.py` and used by seven handlers. `_check_jobs_available` and `_check_job_id` have zero definitions and zero references left; only `_check_auth` survives, called from inside the new prelude.
- Both handlers this PR adds call `self._check_jobs_available()` and `self._check_job_id(request)`. Nothing in the diff touches the lines where those helpers were removed, so git merges the branch cleanly and the failure only appears at runtime. That is a genuinely easy one to miss, and I would have missed it.
- Your commit `09c5f3989` is a faithful port: `+6/-18` in one file, same auth → cron-available → job-id order, no behaviour change. My two commits on your branch still carry my authorship, which I appreciate.

On the join-key point — you are right, and it is a real gap rather than a cosmetic one. The `executions` table keys on a UUID `id`, `save_job_output` names files `{YYYY-MM-DD_HH-MM-SS}.md`, and nothing records which execution produced which file. A client can only match on timestamp, at one-second resolution, against a `finished_at` written by a different code path — so your 1.3s skew under concurrent attempts is exactly the failure mode, not an edge case.

I would close it with an `output_stem` column on the execution record rather than a `list_outputs` route. The reason is that the join should be recorded by the code that knows both facts at the same moment, instead of reconstructed afterwards by whoever is reading. `_save_compose_deliver` already has the execution identity in scope and already receives the path back from `save_job_output`, so recording the stem there is a small change: one nullable column, one setter in `cron/executions.py`, one call at the write site, and the field surfaced in the `/executions` response. A route that lists outputs would still have to guess the mapping after the fact, and would guess it the same wrong way a client does today.

Two things I would keep separate, for the reviewers rather than out of caution:

1. This PR is `+308/-0` and read-only over storage that already exists. The stem is a write-path change touching the scheduler and a ledger schema migration. I think that is worth its own commit and its own review, even if it lands in the same PR.
2. Whether the field is named `output_stem` or `output_id` is a maintainer call, and so is whether a migration is acceptable here at all.

So: open your PR, and if the maintainers are happy to take the stem in the same change, I will write that commit against your branch and send it to you — you found the gap and you have the downstream use case, so it should not be me quietly appending to your work without asking first.

**Comment by brianoestberg** [comment]
@chelsealong PR is open: https://github.com/NousResearch/hermes-agent/pull/116142 — your two commits with authorship preserved, plus the guard-port commit (`09c5f3989`).

Since your review I merged main into the branch (no conflicts) and reran the checks — results are in the PR body, along with the join-key limitation and the `output_stem` question for the maintainers.

Thank you for checking the port analysis against main, and for offering to write the stem commit. For context on the downstream use: agent-os (https://github.com/dotlegal-compliance/agent-os), my self-hosted Hermes workspace. Its routines pane currently shows only `latest_execution`, so that 14m 22s run has no history to be measured against. Your two routes are the surface it has been waiting on.
