### ISSUE TITLE
MOA: _moa_prepared_request leaked to native OpenAI client when agent.client is replaced (fallback/rotation)

### ISSUE THREAD

**Issue by wanghaijian3-cell** [NousResearch/hermes-agent#78382]
## Bug
When an MOA preset is active, `_moa_prepared_request` is leaked into a native OpenAI `chat.completions.create()` call, raising:
`TypeError: Completions.create() got an unexpected keyword argument `_moa_prepared_request``

## Root cause
`conversation_loop.py` (lines 2182-2183) injects `_moa_prepared_request` into `api_kwargs` when `agent.provider == "moa"`. That key is only consumed by the in-process `MoAClient.create()` facade via `api_kwargs.pop(...)`.

After a client replacement — `run_agent.py:_replace_primary_openai_client` (credential rotation / dead-connection cleanup / fallback+restore), or any path that rebuilds `agent.client` from `_client_kwargs` — `agent.client` becomes a **native OpenAI client** (e.g. relay `https://yuanyuaicloud.cn/v1/`), but `agent.provider` stays `"moa"`.

Dispatch then hits `chat_completion_helpers.py:505-509`:
```python
if agent.provider == "moa":
    return agent.client.chat.completions.create(**api_kwargs)
```
`agent.client` is no longer the MoA facade, so `_moa_prepared_request` is passed to the native SDK → TypeError. It is non-retryable → every MOA turn on that session fails.

## Evidence
- Error log: `provider=moa base_url=https://yuanyuaicloud.cn/v1/ model=2 model`
- log line: `Completions.create() got an unexpected keyword argument `_moa_prepared_request`` → `Non-retryable client error`
- Request dump confirms `_moa_prepared_request=dict` survives to the serialization layer.
- OpenAI SDK 2.24.0, Windows 10, config: MOA enabled, `"3 model"` default preset, `"2 model"` fallback preset (both affected when fallback path is hit).

## Suggested fixes
Option 1 (defensive, minimal): guard the pop at the dispatch point
```python
if agent.provider == "moa":
    api_kwargs.pop("_moa_prepared_request", None)
    return agent.client.chat.completions.create(**api_kwargs)
```
Option 2 (architectural): only inject `_moa_prepared_request` in `conversation_loop.py` when `agent.client` is actually a `MoAClient` (`isinstance` check), not solely on `agent.provider == "moa"`.
Option 3: when replacing `agent.client` under provider `"moa"`, re-build the MoA facade (`build_moa_facade`) instead of a native OpenAI client.

## Files
- `agent/conversation_loop.py` injection point (2182-2183)
- `agent/chat_completion_helpers.py` dispatch point (505-509)
- `run_agent.py` `_replace_primary_openai_client` (4600-4608)

**Comment by teknium1** [comment]
Fixed by PR #83088, which consolidates the whole fix class with contributor authorship preserved:

- facade preservation at the `create_openai_client` choke point (thanks @x1051445024) so fallback/credential-rotation/stream-retry rebuilds keep the MoA facade instead of swapping in a native OpenAI client;
- the injection-site guard probing that the client actually consumes `_moa_prepared_request` (thanks @Drexuxux, cherry-picked from #82082);
- the defensive dispatch-point strip so a leaked key can never reach the native SDK (thanks @RelaxJonh, cherry-picked from #80132 — gated on a facade-capability probe so the real MoA facade still receives its handshake);
- the `_replace_primary_openai_client` facade helper + end-to-end regression test (thanks @burak33bb, cherry-picked from #78409).

Regression coverage is sabotage-verified: reverting the fixed files makes the new tests fail with exactly the reported `TypeError: Completions.create() got an unexpected keyword argument '_moa_prepared_request'` class of failure.
