### PR TITLE
fix(gateway): resolve @ references for active runtime

### LINKED ISSUE #62695: Gateway @ context-reference expansion never runs: AttributeError on nonexistent self._model, silently swallowed
## Summary

The gateway's "@" context-reference expansion (@file:, @folder:, @diff, ...) never runs. Every inbound message containing "@" hits an AttributeError that is silently swallowed, so references pass through to the model unexpanded.

## Root cause

`GatewayRunner._prepare_inbound_message_text` (gateway/run.py, ~10608-10648 on current main) reads `self._model` and `self._base_url`:

```python
_msg_ctx_len = await get_model_context_length_async(
    self._model,
    base_url=self._base_url or _msg_runtime.get("base_url") or "",
    ...)
```

Neither attribute is ever assigned on GatewayRunner (`grep -n "self\._model\s*=" gateway/run.py` returns nothing). The block was introduced in da44c196b as a copy of the HermesCLI implementation, where `self.model` / `self.base_url` are real attributes. In the gateway class the first read raises AttributeError, which the surrounding `except Exception as exc: logger.debug(...)` hides at debug level.

## Repro

Call `_prepare_inbound_message_text` with a message containing `@file:notes.txt`: the debug log shows `@ context reference expansion failed: 'GatewayRunner' object has no attribute '_model'` and the returned text is unchanged.

## Fix

PR incoming: resolve model/provider/base_url via `self._resolve_session_agent_runtime(...)` (the same session-aware resolution the hygiene compression block uses later in the file), and raise the swallow log to warning so future breakage of this feature is visible.

### PR DESCRIPTION
**Pull request by kshitijk4poor**
## Summary
Gateway `@file:`, `@folder:`, and `@diff` references now expand using the active session/channel runtime instead of failing on nonexistent runner attributes.

This salvages #62696 and closes #62695.

## Changes
- Preserve @TheTom's fix for the swallowed `GatewayRunner._model` / `_base_url` failure.
- Resolve custom-provider context limits for the active endpoint.
- Keep a default model's `context_length` from masking a distinct session or channel runtime.
- Scope inbound preprocessing to the routed profile before loading config or credentials in multiplexed gateways.

## Validation
- 58 targeted gateway tests passed: context-reference runtime, empty-model recovery, multiplex profile, and channel override coverage.
- Real async custom-provider context resolution returned the configured 222222-token limit.
- Final-head Phase 2 review found no critical issues or warnings.
- Ruff/ty checks: no new diagnostics.

## Credit
Salvaged from #62696 by @TheTom; the original commit retains contributor authorship.

Closes #62696
Fixes #62695

### CODE REVIEW

**Comment by kshitijk4poor** [comment]
Closing in favor of #62783, the stronger salvage of #62696: it preserves @TheTom's fix and additionally scopes normal and queued @-reference preprocessing to the routed multiplex profile, honors custom-provider context limits, and covers effective runtime budgets. #62783 has green required CI.
