### ISSUE TITLE
Bedrock Converse conversion crashes (AttributeError) on an image_url part with a null url

### ISSUE THREAD

**Issue by MaxFreedomPollard** [NousResearch/hermes-agent#55686]
### What happens

When the active provider is Bedrock and a user message carries an image part whose `url` is null (or a non-string), converting the message to the Converse format crashes with `AttributeError: 'NoneType' object has no attribute 'startswith'`. The exception aborts conversion of the entire message, so the turn errors out.

### Where

`agent/bedrock_adapter.py`, in `_convert_content_to_converse`:

```python
elif part_type == "image_url":
    image_url = part.get("image_url", {})
    url = image_url.get("url", "") if isinstance(image_url, dict) else ""
    if url.startswith("data:"):
        ...
```

`image_url.get("url", "")` only falls back to `""` when the `url` key is absent. If the key is present with value `None`, `url` is `None`, and `url.startswith("data:")` raises.

### Reproduction

```python
from agent.bedrock_adapter import _convert_content_to_converse

_convert_content_to_converse([
    {"type": "text", "text": "look"},
    {"type": "image_url", "image_url": {"url": None}},
])
# AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Expected

A null/non-string url should be tolerated (the unusable image skipped), not crash the conversion. The Gemini converter (`_extract_multimodal_parts`, `((item.get("image_url") or {}).get("url") or "")`) and the Codex converter (`if not isinstance(url, str) or not url: continue`) already handle this shape; the Bedrock converter is the one that crashes.

A fix with regression tests is in #55685.

**Comment by GottZ** [comment]
> *This was generated by AI during triage.*

#### Summary

Four PRs address or reference #55686. #55685 and closed #55752 use explicit string normalization to prevent the reported Bedrock crash, while #55699 and #55996 only coalesce falsey values and therefore leave truthy non-string inputs unsafe; #55996 also includes separate lifecycle-status hardening.

#### Related pull requests

- #55685 `best fix` — (+46/-1) — best fix: Explicitly normalizes dict and bare-string image URLs before `startswith`, preserving valid data URLs while safely skipping null or non-string values. Its regression tests cover null, truthy non-string, and bare-string data-URL cases, matching and extending the reported failure boundary.
- #55699 `partial` — (+2/-2) — partial fix: `(url or "")` prevents the reported `None` crash but still calls `startswith` on truthy non-string values, adds no regression tests, and includes an unrelated lifecycle hunk that does not normalize a non-dict/null lifecycle container. Despite the keep_open review on #55699, that review itself documents these diff-level gaps, all of which #55685 avoids for the issue scope.
- #55752 **[closed]** `fixes` — (+16/-1) — fixes but superseded: The closed PR explicitly type-checks `image_url.url` and adds an end-to-end null regression test, so it remains relevant as a valid reference implementation. It is nevertheless superseded by earlier #55685, which covers the same cause plus non-string and bare-string cases more comprehensively.
- #55996 `partial` — (+2/-2) — partial superset: It coalesces null image URLs and null lifecycle statuses, but truthy non-string values can still reach both string methods and neither branch has regression coverage. Despite the keep_open review on #55996, the diff does not meet that review's requested explicit type normalization and tests; its separate lifecycle concern should be handled independently or ported with those safeguards.

#### Duplicates

#55685 and #55752 implement substantially the same typed image-URL fix, with #55685 providing broader coverage. #55699 duplicates #55996 exactly at the diff level; both overlap #55685 on the issue fix, while their lifecycle-status hunk is separate from #55686.

#### Suggested consolidation

Merge #55685 as the canonical fix: it is the earliest open PR, directly addresses null and truthy non-string URLs, and includes the strongest targeted regression coverage. Keep #55752 closed as superseded, close #55699 as an incomplete duplicate, and close #55996 for this issue after splitting or separately tracking its lifecycle-status hardening with explicit type normalization and tests; this differs from the keep_open reviews on #55699 and #55996 because their visible diffs retain documented non-string failure paths that #55685 already resolves.

#### Complex graph

```mermaid
flowchart LR
    classDef open fill:#dbeafe,stroke:#1d4ed8,color:#1e3a8a
    classDef merged fill:#dcfce7,stroke:#15803d,color:#14532d
    classDef closed fill:#e5e7eb,stroke:#6b7280,color:#1f2937
    classDef unverified fill:#f3f4f6,stroke:#9ca3af,color:#374151
    classDef best stroke-width:3px,stroke:#b45309
    classDef target stroke-width:3px,stroke:#4338ca
    I55686(["issue #55686 (open)"])
    subgraph Dup55685 ["PRs duplicating each other"]
        P55685["PR #55685 (open)"]
        P55752["PR #55752 (closed)"]
    end
    subgraph Dup55699 ["PRs duplicating each other"]
        P55699["PR #55699 (open)"]
        P55996["PR #55996 (open)"]
    end
    P55685 -->|best fix| I55686
    P55699 -.->|partial| I55686
    P55752 -->|fixes| I55686
    P55996 -.->|partial| I55686
    class I55686 open
    class I55686 target
    class P55685 open
    class P55699 open
    class P55752 closed
    class P55996 open
    class P55685 best
    click I55686 "https://github.com/NousResearch/hermes-agent/issues/55686"
    click P55685 "https://github.com/NousResearch/hermes-agent/pull/55685"
    click P55699 "https://github.com/NousResearch/hermes-agent/pull/55699"
    click P55752 "https://github.com/NousResearch/hermes-agent/pull/55752"
    click P55996 "https://github.com/NousResearch/hermes-agent/pull/55996"
```
*Graph: solid arrow = fixes / best fix, dashed arrow = partial or unverified (see edge label); boxed group = PRs duplicating each other; amber border = best fix; indigo border = target; gray node = closed or no verify verdict yet (state tag in the node label).*

_Cross-PR triage: Reviewed 4 pull requests and 1 issue in this complex. Each diff was read against this issue; Assessment working set: 8 kB of PR diffs, 6 kB of issue/PR text, 4 kB of discussion (7 comments), 7 verify verdicts. verdicts reflect diff content, not PR titles. Part of an automated triage batch._

**Comment by JiaDe-Wu** [comment]
## Still live on `main`, broader than "null", and only one of the three PRs actually closes it

Confirmed on `main` (`2659c917c1`), `agent/bedrock_adapter.py:915`. The crash is not limited to `None` — **every** non-string `url` raises, and the `or ""` idiom the two other PRs use does not fix that.

### Which shapes crash, per patch

Running each patch's expression verbatim, then `url.startswith("data:")`:

| `image_url` | `main` | #55699 / #55996 | #55685 |
|---|---|---|---|
| `{"url": None}` | **AttributeError** | ok | ok |
| `{"url": 123}` | **AttributeError** | **AttributeError** | ok |
| `{"url": [1]}` | **AttributeError** | **AttributeError** | ok |
| `{"url": True}` | **AttributeError** | **AttributeError** | ok |
| `{"url": []}` | **AttributeError** | ok | ok |
| `{"url": {}}` | **AttributeError** | ok | ok |
| `{"url": 0}` | **AttributeError** | ok | ok |
| `{"url": ""}` | ok | ok | ok |
| `{"url": "data:…"}` | ok | ok | ok |

`(image_url.get("url") or "")` filters **falsiness, not type**. `None`, `[]`, `{}` and `0` are falsy so they get replaced; `123`, `True` and any non-empty list are truthy and pass straight through to `.startswith`. So #55699 and #55996 fix the exact literal in the report and leave the general defect — which the report itself names: *"whose `url` is null (or a non-string)"*.

`#55685`'s `if not isinstance(url, str): url = ""` is the right shape, because the requirement is a type guard.

### #55685 also fixes a silent-data-loss case the others don't

Some producers send `image_url` as a bare URL string rather than `{"url": …}`. `main` and both `or ""` patches discard it:

```
image_url="https://x/y.png"   main -> ''        #55699 -> ''        #55685 -> 'https://x/y.png'
```

On `main` that path yields `[{'text': '[Image: ]'}]` — an empty placeholder, no error, image gone. #55685's `url = image_url` when not a dict recovers it. Worth calling out because it is invisible in testing: nothing raises, the turn just silently loses the image.

### #55699 and #55996 are byte-identical

Same author, same two-line diff, no difference between them. One should close as a duplicate of the other regardless of which approach wins.

### Their second change is real but unattested

Both also harden discovery: `(lifecycle.get("status") or "").upper()`. I checked whether a null/missing `modelLifecycle.status` occurs — `ListFoundationModels` in `us-east-1`, all 122 models:

```
'ACTIVE': 105    'LEGACY': 17    missing/None: 0
```

So it guards a case AWS does not currently produce. That is cheap, harmless hardening and I would take it — as a small separate change, not as a reason to prefer these PRs over the one that closes the actual bug.

### Suggested consolidation

Merge **#55685** (@MaxFreedomPollard): it is the only one that covers every non-string shape, it is the only one that recovers the bare-string `image_url` case, and it is the only one with tests. Close **#55996** as a duplicate of **#55699**, and either rescope #55699 to just the `modelLifecycle.status` guard or fold that one line into #55685.

Method: each patch's `url` expression extracted verbatim and evaluated against the nine shapes above followed by `.startswith("data:")`; `_convert_content_to_converse()` from `main` at `2659c917c1` for the `main` column and the `[Image: ]` output; `bedrock:ListFoundationModels` for the lifecycle census.
