### PR TITLE
fix(browser): avoid auto-install during tool discovery

### PR DESCRIPTION
**Pull request by vernonstinebaker**
## What does this PR do?

Fixes a gateway hang where Hermes could go silent on Discord/Mattermost before any model call if browser tools were unavailable.

The root cause was `check_browser_requirements()` calling `_find_agent_browser()`, which could trigger `ensure_dependency("browser")` during normal tool discovery. In a Docker deployment without browser/Node prerequisites, that path attempted dependency bootstrap and blocked agent initialization instead of simply marking browser tools unavailable.

This change makes browser tool discovery non-installing by default: availability checks call `_find_agent_browser(auto_install=False)`, while explicit browser execution paths keep the existing install-capable lookup behavior.

## Related Issue

Fixes #

## Type of Change

- [x] 🐛 Bug fix (non-breaking change that fixes an issue)
- [ ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 🔒 Security fix
- [ ] 📝 Documentation update
- [x] ✅ Tests (adding or improving test coverage)
- [ ] ♻️ Refactor (no behavior change)
- [ ] 🎯 New skill (bundled or hub)

## Changes Made

- Updated `tools/browser_tool.py` so `_find_agent_browser()` accepts `auto_install=True|False`
- Changed `check_browser_requirements()` to use `_find_agent_browser(auto_install=False)`
- Added regression coverage in `tests/tools/test_browser_homebrew_paths.py` to verify browser requirements checks do not attempt auto-install
- Updated existing test doubles to accept the new kwarg where needed

## How to Test

1. Run `scripts/run_tests.sh tests/tools/test_browser_homebrew_paths.py tests/tools/test_browser_hardening.py`
2. Verify browser availability still works when `agent-browser` is installed
3. Verify `check_browser_requirements()` returns `False` rather than attempting install/bootstrap when browser dependencies are missing

### Code

- [x] I've read the [Contributing Guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md)
- [x] My commit messages follow [Conventional Commits](https://www.conventionalcommits.org/) (`fix(scope):`, `feat(scope):`, etc.)
- [x] I searched for [existing PRs](https://github.com/NousResearch/hermes-agent/pulls) to make sure this isn't a duplicate
- [x] My PR contains **only** changes related to this fix/feature (no unrelated commits)
- [ ] I've run `pytest tests/ -q` and all tests pass
- [x] I've added tests for my changes (required for bug fixes, strongly encouraged for features)
- [x] I've tested on my platform: macOS 15 / Dockerized Hermes gateway repro

### Documentation & Housekeeping

- [x] I've updated relevant documentation (README, `docs/`, docstrings) — or N/A
- [x] I've updated `cli-config.yaml.example` if I added/changed config keys — or N/A
- [x] I've updated `CONTRIBUTING.md` or `AGENTS.md` if I changed architecture or workflows — or N/A
- [x] I've considered cross-platform impact (Windows, macOS) per the [compatibility guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md#cross-platform-compatibility) — or N/A
- [x] I've updated tool descriptions/schemas if I changed tool behavior — or N/A

## Screenshots / Logs

Relevant repro milestone before this fix in a live gateway deployment:

- `Agent init: loading tool definitions provider=xai-oauth model=grok-4.3 platform=discord`
- `Tool definitions: checking availability for browser_back (toolset=browser)`
- no subsequent `Agent init: loaded ...` or conversation start/return log

After applying this change in the same deployment, both Discord and Mattermost resumed responding normally.

### CODE REVIEW

**Review by outsourc-e — COMMENTED** [review]
I like the direction, but I could not clear this branch locally as submitted. The new auto_install kwarg breaks existing zero-arg monkeypatch assumptions in the broader browser test surface, so I would treat it as not merge-ready until the affected tests are updated or the API shape is made less brittle.

**Comment by outsourc-e** [comment]
I reproduced the broader browser-suite regression here: the new `check_browser_requirements()` call path invokes `_find_agent_browser(auto_install=False)`, which breaks existing zero-arg monkeypatched stubs in `tests/tools/test_browser_chromium_check.py` with `TypeError: ... got an unexpected keyword argument auto_install`.

I opened a clean replacement that preserves the no-install discovery behavior but falls back to the legacy no-arg call shape only for older monkeypatched stubs: #28216.

Validation on the replacement branch:
- `python3 -m pytest -q -o addopts= tests/tools -k browser`
- result: `344 passed, 20 skipped`

**Comment by vernonstinebaker** [comment]
Thanks for tracking down the broader regression and carrying this forward in #28216.

Since #28216 supersedes this PR, could you add `Closes #28027` to the replacement PR description so this one auto-closes when it merges? Happy to close this manually instead if you prefer.

File: tools/browser_tool.py [hunk 1]
```diff
@@ -3497,7 +3503,7 @@ def check_browser_requirements() -> bool:
```
Comment (teknium1) [inline tools/browser_tool.py:3503]: This no-install lookup fixes the discovery path, but it also changes the monkeypatch contract for `_find_agent_browser`; existing browser requirement tests still install zero-arg stubs, so this should either catch `TypeError` and retry the legacy no-arg shape or update all sibling stubs.

**Review by teknium1 — COMMENTED** [review]
Thanks for isolating this browser discovery hang. I verified the premise against current main: `check_browser_requirements()` calls `_find_agent_browser()` at `tools/browser_tool.py:3680`, and `_find_agent_browser()` can reach `ensure_dependency("browser")` at `tools/browser_tool.py:1827` during availability checks.

### Problems

- This branch changes the requirement check to `_find_agent_browser(auto_install=False)`, but current main still has zero-argument monkeypatched stubs in `tests/tools/test_browser_chromium_check.py:79` and `tests/tools/test_browser_chromium_check.py:96`. Those would raise `TypeError` when this branch's changed call runs.
- The follow-up #28216 already carries this commit and adds the compatibility fallback in commit `589f1448d13da512a5c93caa71139b9e2f61ae5a`, which preserves no-install discovery while supporting older no-arg stubs.

### Suggested changes

- If this branch is carried forward directly, add the same fallback as #28216 or update every browser-test monkeypatch to accept `*args, **kwargs`.

Automated hermes-sweeper review.

**Comment by teknium1** [comment]
This appears to be implemented on current `main` now. Automated hermes-sweeper review found the same behavioral guarantee already present.

Evidence:
- `tools/browser_tool.py:4252` now has `check_browser_requirements()` call `_find_agent_browser(validate=False)` for browser tool availability/schema discovery.
- `tools/browser_tool.py:2107` shows the `validate=False` path raises `FileNotFoundError` before the lazy `ensure_dependency("browser")` bootstrap block, so discovery does not auto-install.
- `tests/tools/test_browser_chromium_check.py:105` adds regression coverage asserting the startup check uses the lightweight lookup: `seen == [{"validate": False}]`.
- The current implementation was added in `9a0010fd469f0de6c7e2146f955ed9980d02b397`.

Thanks for the original fix and for the follow-up discussion around #28216; the no-install discovery behavior is now covered on main.
