### PR TITLE
fix(qqbot): accept is_reconnect kwarg in QQAdapter.connect

### PR DESCRIPTION
**Pull request by Timeral**
## Summary

`QQAdapter.connect()` violated the `BasePlatformAdapter.connect(*, is_reconnect: bool = False)` contract introduced in #52844 — it was bare `async def connect(self)`. The gateway's reconnect watcher (`gateway/run.py`) recovers a platform after a **fatal adapter error** by building a fresh adapter and calling `connect(is_reconnect=True)`. For QQBot, that call raised:

```
TypeError: connect() got an unexpected keyword argument 'is_reconnect'
```

so the watcher could never re-establish QQBot through the fatal-recovery path.

## Live symptom

After a fatal QQBot adapter error (e.g. WebSocket close that exhausts the in-process retry ladder), the watcher's `Reconnecting qqbot (attempt N)...` step crashes with the `TypeError`. QQBot never comes back online, and the bot stops responding to messages until a full gateway restart.

## Why QQBot doesn't need special reconnect logic for the flag (contract conformance only)

`is_reconnect` exists so adapters with a **server-side update queue** (e.g. Telegram's Bot API) preserve that queue across an outage instead of dropping it (#52844). QQBot has no such queue — the QQ gateway delivers messages over the live WebSocket connection, and the adapter re-authenticates with a fresh `/gateway` request on every connect(). There is no server-side state to preserve, and the watcher already disconnects the old adapter (cancelling the WebSocket supervisor) before building a fresh one.

So QQBot must **accept** the kwarg for contract conformance, and correctly has nothing special to do with it at the adapter layer — the existing `connect()` body already handles both cold boot and reconnect correctly once the `TypeError` is removed.

## Changes

- `gateway/platforms/qqbot/adapter.py`: Added `*, is_reconnect: bool = False` to `QQAdapter.connect()` to match the `BasePlatformAdapter` contract. Updated docstring to document the parameter.

## Tests

Existing `test_connect_uses_redirect_guard_hook` calls `adapter.connect()` without `is_reconnect`, which continues to work (the parameter defaults to `False`). No regression risk.

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #52966 -- identical one-line contract-conformance fix adding the keyword-only `is_reconnect: bool = False` to `QQAdapter.connect()` (gateway/platforms/qqbot/adapter.py) so the gateway reconnect watcher's `connect(is_reconnect=True)` no longer raises TypeError. This is a heavily saturated cluster fixing #52914; the original anchor #52922 is now CLOSED, so #52966 is the earliest still-OPEN canonical fix (siblings #53948/#54029/#54037/#53540/#53546 already deduped into it). related_to the bug #52914.

**Review by tonydwb — COMMENTED** [review]
## Code Review Summary

**Verdict: Approved (LGTM)**

Contract conformance fix for QQAdapter.connect(). Adds `is_reconnect` kwarg to match the BasePlatformAdapter interface, with clear explanation of why no special reconnect logic is needed for QQBot. Clean and minimal.

### What Looks Good
- Minimal, targeted change
- Clear explanation of design rationale
- No security or debug artifacts

---
*Reviewed by Hermes Agent*

**Review by tonydwb — COMMENTED** [review]
## Code Review Summary

**Verdict: LGTM**

Tiny fix (+7/-2) accepting `is_reconnect` kwarg in `QQAdapter.connect`.

### Looks Good
- Minimal change, correct pattern
- No security or performance concerns

---
*Reviewed by Hermes Agent*

**Review by tonydwb — COMMENTED** [review]
Supplementary review: confirms LGTM. QQAdapter is_reconnect kwarg fix is a small, clean addition. Prior COMMENT found no issues. No additional concerns.

---
*Reviewed by Hermes Agent*

**Comment by teknium1** [comment]
Thanks for the focused QQBot contract fix. The requested behavior is already on current `main`, so this duplicate can be closed.

- Automated hermes-sweeper review verified `QQAdapter.connect(self, *, is_reconnect: bool = False)` at `gateway/platforms/qqbot/adapter.py:281`.
- Current main includes the regression test at `tests/gateway/test_qqbot.py:193`, covering both the default call and `connect(is_reconnect=True)`.
- The canonical work was cherry-picked through merged PR #61767; commit `276542c729c10ff9d093760897f4c2d1256a79ce` contains the QQBot implementation and test.
- The duplicate relationship noted by @alt-glitch is therefore now superseded by the merged implementation.

This is an automated hermes-sweeper review.
