### PR TITLE
fix(bedrock): tolerate null/non-string image_url in Converse content conversion

### LINKED ISSUE #55686: Bedrock Converse conversion crashes (AttributeError) on an image_url part with a null url
### What happens

When the active provider is Bedrock and a user message carries an image part whose `url` is null (or a non-string), converting the message to the Converse format crashes with `AttributeError: 'NoneType' object has no attribute 'startswith'`. The exception aborts conversion of the entire message, so the turn errors out.

### Where

`agent/bedrock_adapter.py`, in `_convert_content_to_converse`:

```python
elif part_type == "image_url":
    image_url = part.get("image_url", {})
    url = image_url.get("url", "") if isinstance(image_url, dict) else ""
    if url.startswith("data:"):
        ...
```

`image_url.get("url", "")` only falls back to `""` when the `url` key is absent. If the key is present with value `None`, `url` is `None`, and `url.startswith("data:")` raises.

### Reproduction

```python
from agent.bedrock_adapter import _convert_content_to_converse

_convert_content_to_converse([
    {"type": "text", "text": "look"},
    {"type": "image_url", "image_url": {"url": None}},
])
# AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Expected

A null/non-string url should be tolerated (the unusable image skipped), not crash the conversion. The Gemini converter (`_extract_multimodal_parts`, `((item.get("image_url") or {}).get("url") or "")`) and the Codex converter (`if not isinstance(url, str) or not url: continue`) already handle this shape; the Bedrock converter is the one that crashes.

A fix with regression tests is in #55685.

### PR DESCRIPTION
**Pull request by MaxFreedomPollard**
### Summary

`_convert_content_to_converse` (agent/bedrock_adapter.py) reads an image part's url with:

```python
url = image_url.get("url", "") if isinstance(image_url, dict) else ""
if url.startswith("data:"):
```

The `""` default only applies when the `url` key is missing. When the key is present but its value is `None` (or any non-string), `url` becomes that value and `url.startswith("data:")` raises `AttributeError: 'NoneType' object has no attribute 'startswith'`. The exception propagates out of `convert_messages_to_converse`, so the whole user message fails to convert and the turn errors out instead of degrading gracefully.

### Reproduction

```python
from agent.bedrock_adapter import _convert_content_to_converse

_convert_content_to_converse([
    {"type": "text", "text": "look"},
    {"type": "image_url", "image_url": {"url": None}},
])
# AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Consistency

The sibling converters already tolerate this. Gemini's `_extract_multimodal_parts` uses `((item.get("image_url") or {}).get("url") or "")`, and Codex's `_chat_content_to_responses_parts` does `if not isinstance(url, str) or not url: continue`. Bedrock is the one converter that crashes.

### Fix

Resolve the url for both the dict (`{"url": ...}`) and bare-string forms, then coerce a null/non-string url to an empty string before the `data:` check. As a side benefit, a bare-string `data:` url now converts to an image block instead of being silently dropped (the previous `else ""` discarded it).

### Tests

Adds regression tests for the null-url crash, the non-string-url crash, and bare-string `data:` url conversion. The first two fail with `AttributeError` before the change and pass after.

Fixes #55686

### CODE REVIEW

**Comment by MaxFreedomPollard** [comment]
Issue with reproduction: #55686

**Comment by teknium1** [comment]
Thanks for the focused Bedrock regression fix. The premise remains valid on current `main`: `agent/bedrock_adapter.py:522-523` can retain `None` from `image_url["url"]` and immediately call `startswith` on it. User content reaches that helper through `convert_messages_to_converse` at `agent/bedrock_adapter.py:641-642`.

The proposed `isinstance(url, str)` guard prevents that failure while retaining the existing data-URL and remote-reference behavior. The added null, non-string, and bare-string data-URL tests exercise the changed branches. The PR is currently reported mergeable by GitHub.

Automated hermes-sweeper review.
