### ISSUE TITLE
[Feishu] Approval buttons broken: allow_permanent argument error after gateway restart

### ISSUE THREAD

**Issue by MoraGG** [NousResearch/hermes-agent#110960]
## Environment

- Hermes version: 0.21.0 (Quicksilver, 2026.8.31)
- Feishu connection mode: WebSocket
- OS: Linux

## Bug Description

After upgrading to v0.21.0, Feishu approval buttons suddenly stopped working. When a dangerous command triggers an approval request, the interactive card with Approve/Deny buttons is sent, but clicking the buttons has no effect — the request just waits indefinitely.

## Root Cause

The gateway log shows:

```
WARNING gateway.run: Button-based approval failed, falling back to text: FeishuAdapter.send_exec_approval() got an unexpected keyword argument allow_permanent
```

The gateway core calls `send_exec_approval()` with an `allow_permanent` keyword argument, but `FeishuAdapter.send_exec_approval()` does not accept this parameter, causing the button click handler to throw and fall back to text mode.

## Timeline

- Upgraded to v0.21.0 on Aug 31 — buttons worked fine after upgrade
- The bug only surfaced today (Sep 14) after a gateway restart
- Before the restart, buttons resolved correctly: `"Feishu button resolved 1 approval(s)"`
- After the restart, every approval click fails with the `allow_permanent` error

This suggests the v0.21.0 code was already buggy but only took effect on hot reload after the restart.

## Related Issues

- #7675 (Issue 2: Approval buttons not working) — open since Apr 11, 2026
- The `allow_permanent` regression appears to be a separate new bug introduced in v0.21.0

## Current Workaround

Use `/approve` text command instead of clicking the card buttons.

## Expected Behavior

Clicking the Approve/Deny buttons on the interactive card should resolve the pending approval request, same as typing `/approve`.

**Comment by KeyArgo** [comment]
Checked the file named in the warning against the release you are on, and the signature it reports as missing is present in both revisions I can read.

- At tag `v2026.8.31` (the release you listed), `plugins/platforms/feishu/adapter.py:2059` already declares `async def send_exec_approval(self, chat_id, command, session_key, description="dangerous command", metadata=None, allow_permanent=True, allow_session=True, smart_denied=False)` — `allow_permanent` is an accepted keyword there, so that copy cannot raise the TypeError on its own.
- On current main the per-adapter override is gone entirely: `send_exec_approval` lives on `BasePlatformAdapter` with the same three flags, and Feishu supplies `_send_exec_approval_prompt`, which is what the gateway's `_renders_exec_approval_buttons()` class check looks for. The call site passes those flags as keywords into the shared method.

So the missing keyword most likely belongs to a different copy of the adapter than the released one — a stale `adapter.py` reachable through a user plugin directory on that host would be picked up at import time, and a gateway restart is exactly when that becomes visible, which matches the timeline in the report.

One question that would settle it: on the affected host, does `~/.hermes/plugins/platforms/feishu/adapter.py` (or a project-level `.hermes/plugins/...` copy) exist? If it does, comparing its `send_exec_approval` signature against the release file should show the missing keyword, and the fix is removing that copy rather than changing `gateway/run.py`.

**Comment by teknium1** [comment]
Thanks @MoraGG for the detailed report and timeline, and thanks @KeyArgo for the line-level check — I confirmed both halves against the repo.

- At the release you are on (`v2026.8.31`), `plugins/platforms/feishu/adapter.py:2059` declares `send_exec_approval(self, chat_id, command, session_key, description=…, metadata=None, allow_permanent=True, allow_session=True, smart_denied=False)`. `allow_permanent` is accepted there, so that file cannot raise the `TypeError` in your log.
- On `origin/main` (`ad305bead5659`, refactor: `send_exec_approval` became a `BasePlatformAdapter` template method; Feishu only implements `_send_exec_approval_prompt`) a live probe with a temp `HERMES_HOME` imports `FeishuAdapter` and `inspect.signature(FeishuAdapter.send_exec_approval)` still contains `allow_permanent: bool = True`.

The signature the error names does not exist in any shipped revision, which points at a second copy of the adapter being imported after the restart — typically `~/.hermes/plugins/platforms/feishu/adapter.py` or a project-level `.hermes/plugins/...` copy that shadows the bundled one at import time (a gateway restart is exactly when that becomes visible).

Closing as not reproducible on the shipped code. Please reopen with: `python -c "import plugins.platforms.feishu.adapter as m; print(m.__file__)"` run from the venv the gateway uses, and the output of `ls ~/.hermes/plugins/platforms/feishu 2>/dev/null` — if that shows a stale copy, removing it should bring the buttons back.
