### ISSUE TITLE
fix(desktop): preserve node-pty spawn-helper execute bit on macOS

### ISSUE THREAD

**Issue by wanqinglei** [NousResearch/hermes-agent#61396]
## Summary

On macOS arm64, Hermes Desktop's integrated terminal can fail to start with:

```text
Terminal failed to start: Error invoking remote method 'hermes:terminal:start': Error: posix_spawnp failed
```

The root cause is that `node-pty`'s macOS `spawn-helper` is staged into the app bundle without its executable bit preserved.

## Environment

- Hermes Agent: v0.18.2
- Desktop package version: 0.17.0
- macOS: arm64
- Electron: 40.10.2
- node-pty: 1.1.0

## Reproduction

1. Build/package the Desktop app on macOS arm64.
2. Launch Hermes Desktop.
3. Open the integrated terminal from the right rail.

## Actual result

The terminal fails immediately with `posix_spawnp failed`.

## Root cause

The packaged/staged `spawn-helper` exists, but is copied with non-executable permissions:

```text
-rw-r--r-- spawn-helper
```

Trying to execute it directly returns `Permission denied`, and `node-pty.spawn('/bin/sh')` throws `posix_spawnp failed`.

## Fix

After copying `spawn-helper`, explicitly restore executable permissions (`0o755`) in both places that can stage/rebuild the helper:

- `apps/desktop/scripts/stage-native-deps.mjs`
- `apps/desktop/scripts/rebuild-native.mjs`

## Verification

After applying the fix:

- `spawn-helper` becomes executable:

```text
-rwxr-xr-x .../spawn-helper
```

- Node smoke test passes:

```text
NODE_EXIT {"exitCode":0,"signal":0} OUT "NODE_VERIFY_OK\r\n"
```

- Electron smoke test passes:

```text
ELECTRON_EXIT {"exitCode":0,"signal":0} OUT "ELECTRON_VERIFY_OK\r\n"
```

I also have a clean commit for this fix and tried to open a PR, but my current GitHub token can read the upstream repo and create local commits, while fork creation is blocked with:

```text
HTTP 403: Resource not accessible by personal access token
```

So I'm filing the bug report with the root cause + verified fix first.

**Comment by wanqinglei** [comment]
Verified fix patch:

- Gist patch: https://gist.github.com/HEROISM-WQL/1d6ed37ab4da3ea897a776830c690fba

What the patch does:

- restores `spawn-helper` to `0o755` after copying it in `apps/desktop/scripts/stage-native-deps.mjs`
- also restores executable permissions after `@electron/rebuild` in `apps/desktop/scripts/rebuild-native.mjs`

I also verified locally that after the patch:

```text
NODE_EXIT {"exitCode":0,"signal":0} OUT "NODE_VERIFY_OK\\r\\n"
ELECTRON_EXIT {"exitCode":0,"signal":0} OUT "ELECTRON_VERIFY_OK\\r\\n"
```

I tried to open a PR too, but the current GitHub token available to the CLI can create/edit issues via REST yet is still blocked from fork/create-repo/GraphQL PR flow, so I'm attaching the ready-to-apply patch here for maintainers.

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #61389 — same macOS `posix_spawnp failed` root cause (node-pty `spawn-helper` losing its executable bit during staging). #61389 was filed earlier and is broader (it also covers the `app.asar.unpacked.unpacked` double-rewrite). Open fix PR #61395 addresses both halves. Consolidating under #61389; the executable-bit fix here is folded into that cluster.

**Comment by StarStone233** [comment]
Also hit this on v0.18.2 / macOS arm64. The workaround works but regresses on every update:

```
chmod +x ~/.hermes/hermes-agent/apps/desktop/dist/node_modules/node-pty/prebuilds/darwin-arm64/spawn-helper
```

Would be great to get the fix merged.

**Comment by GottZ** [comment]
> *This was generated by AI during triage.*

#### Summary

Thirteen PRs address or reference #61396's macOS node-pty failure cluster. The diffs separate into the reported execute-bit defect, the complementary ASAR double-rewrite, distinct Windows/Linux/dev-flow problems, and a separate proposed macOS long-path workaround; merged #65611 is the consolidated packaged-build implementation for both causes documented in the anchor issue.

#### Related pull requests

- #61395 **[closed]** `fixes` — (+44/-4) — fixes: Patches staged unixTerminal.js to avoid app.asar.unpacked.unpacked, restores spawn-helper mode in both staging layouts, and adds bundle assertions, covering the execute-bit cause in #61396 plus the complementary ASAR cause. Although its keep_open review found no blocker, it remains relevant as the closed source implementation superseded by merged #65611.
- #61829 **[closed]** `unverified` — (+96/-2) — unverified: Replaces recursive cpSync with a per-file directory walk to avoid a Windows packaging crash; it does not restore spawn-helper execute permissions or guard ASAR rewriting. The closed PR remains relevant only as the earlier version of open #61832, not as a fix for #61396.
- #61832 `unverified` — (+132/-4) — unverified: Avoids recursive cpSync in the Windows node-pty staging paths and adds regression tests, including the newline-tolerant guard requested by its keep_open review. This is a distinct Windows build-crash fix and does not address #61396's macOS execute-bit cause.
- #62328 **[closed]** `partial` — (+11/-1) — partial_fix: Adds chmod 0755 only when copying a prebuilt spawn-helper, directly addressing one #61396 staging path but leaving build/Release and the ASAR double-rewrite uncovered. It was closed by its author in favor of broader #61395 and is subsumed by merged #65611.
- #62329 `fixes` — (+88/-6) — fixes: Makes spawn-helper mode 0755 in both prebuild and build/Release staging paths and tests both from non-executable fixtures, directly fixing #61396's stated cause. Despite the keep_open review finding this narrow patch salvageable, merged #65611 now contains both staging-path chmod behavior and the complementary ASAR guard, so #62329 is superseded.
- #62442 `unverified` — (+154/-9) — unverified: Copies the Darwin helper to dist/bin and patches unixTerminal.js to prefer that shorter path, targeting #62429's claimed macOS path-length failure rather than merely the missing execute bit in #61396. Its keep_open review found no diff-level blocker; #65611 does not implement this short-path fallback, so #62442 should be evaluated separately rather than closed as an exec-bit duplicate.
- #62564 **[closed]** `unverified` — (+276/-2) — unverified: Detects absent pty.node artifacts, fails staging, and forces rebuilding stale packaged Desktop artifacts, targeting the distinct Linux startup crash in #62462. The closed PR remains relevant to that Linux repair/validation path but does not fix #61396's present-but-non-executable Darwin helper.
- #63184 `fixes` — (+30/-3) — fixes: Restores mode 0755 for spawn-helper in both staging layouts and adds packaged-bundle executability validation, directly covering #61396's permission defect. Despite its keep_open review identifying the still-uncovered build/Release path on then-current main, merged #65611 implements that path and tests both helper layouts, making #63184 a duplicate/superseded variant.
- #63475 **[closed]** `unverified` — (+242/-1) — unverified: Makes both app.asar and node_modules.asar rewrites idempotent with negative-lookahead replacements and behavioral tests, covering the complementary path-corruption cause but not #61396's execute-bit cause. It remains relevant as the closed ASAR-only duplicate of #61395 whose behavior was incorporated into #65611.
- #63652 **[closed]** `partial` — (+25/-2) — partial_fix: Chmods spawn-helper in both staging layouts, but suppresses chmod failures and adds no regression coverage; it addresses the permission cause but not ASAR path corruption. It remains relevant as a closed duplicate of the earlier and better-tested #62329, subsequently superseded by #65611.
- #63789 `fixes` — (+9/-2) — fixes: Chmods both prebuilt and build/Release helpers, but its keep_open review notes that current main already covered the prebuild branch, the diff targeted an older layout, lacked regression tests, and did not establish that chmod alone fixed #63784. Merged #65611 performs the narrower salvage requested by that review while also guarding ASAR rewrites, so #63789 is superseded.
- #65611 **[merged]** `best fix` — (+109/-4) — fixes: The merged consolidation patches both ASAR replacements to avoid double-unpacking, normalizes prebuilt and build/Release spawn-helper copies to 0755, and adds fixture-level behavioral coverage for both path forms and helper layouts. It is the merged reference implementation for #61396's execute-bit cause and the complementary #61389 path cause, superseding #61395 and #63789.
- #66734 **[merged]** `unverified` — (+288/-0) — unverified: The merged PR repairs non-executable spawn-helper files resolved directly from raw node_modules immediately before a dev terminal spawn, with unit coverage for candidate discovery and chmod behavior. It remains relevant as complementary dev-flow protection; it is not a duplicate of #65611's packaged-build staging fix.

#### Duplicates

#62328, #62329, #63184, #63652, and #63789 are substantially the same spawn-helper chmod change, with differing path/test coverage; #61395 is the broad earlier version consolidated into #65611, while #63475 duplicates its ASAR-rewrite half. #61829 is the closed predecessor of #61832. #62442, #62564, and #66734 target distinct long-path, Linux-artifact, and dev-flow mechanisms respectively.

#### Suggested consolidation

Merge #65611 (already merged) as the consolidation winner: its diff combines the packaged-build execute-bit repair from the #62329/#63184/#63789 family with the ASAR idempotence repair from #61395/#63475 and tests both staging layouts. Close or retain closed #61395, #62328, #62329, #63184, #63475, #63652, and #63789 as superseded duplicates; this explicitly departs from the visible keep_open reviews on #61395, #62329, #63184, and #63789 because #65611 now contains their supported staging behavior on the consolidated code path and, for #63789, the requested build/Release coverage. Keep #61832 and #62442 separate for their distinct reviewed Windows-copy and Darwin short-path claims, and treat #62564 and merged #66734 as separate Linux-artifact and dev-flow work.

#### Complex graph

```mermaid
flowchart TD
    classDef open fill:#dbeafe,stroke:#1d4ed8,color:#1e3a8a
    classDef merged fill:#dcfce7,stroke:#15803d,color:#14532d
    classDef closed fill:#e5e7eb,stroke:#6b7280,color:#1f2937
    classDef unverified fill:#f3f4f6,stroke:#9ca3af,color:#374151
    classDef best stroke-width:3px,stroke:#b45309
    classDef target stroke-width:3px,stroke:#4338ca
    I61389(["issue #61389 (closed)"])
    I61396(["issue #61396 (open)"])
    I62324(["issue #62324 (open)"])
    I62429(["issue #62429 (open)"])
    I62462(["issue #62462 (open)"])
    I62642(["issue #62642 (open)"])
    I63784(["issue #63784 (open)"])
    P62442["PR #62442 (open)"]
    P62564["PR #62564 (closed)"]
    subgraph Dup61395 ["PRs duplicating each other"]
        P61395["PR #61395 (closed)"]
        P62328["PR #62328 (closed)"]
        P62329["PR #62329 (open)"]
        P63184["PR #63184 (open)"]
        P63475["PR #63475 (closed)"]
        P63652["PR #63652 (closed)"]
        P63789["PR #63789 (open)"]
        P65611["PR #65611 (merged)"]
    end
    subgraph Dup61829 ["PRs duplicating each other"]
        P61829["PR #61829 (closed)"]
        P61832["PR #61832 (open)"]
    end
    More["+1 more PRs not shown"]
    MoreI(["+1 more issues not shown"])
    P61395 -->|fixes| I61396
    P61829 -.->|unverified| I61396
    P61832 -.->|unverified| I61396
    P62328 -.->|partial| I61396
    P62329 -->|fixes| I61396
    P62442 -.->|unverified| I61396
    P62564 -.->|unverified| I61396
    P63184 -->|fixes| I61396
    P63475 -.->|unverified| I61396
    P63652 -.->|partial| I61396
    P63789 -->|fixes| I61396
    P65611 -->|best fix| I61396
    P61395 -->|fixes| I61389
    P62328 -.->|partial| I61389
    P62329 -.->|partial| I61389
    P62442 -.->|partial| I61389
    P63184 -.->|partial| I61389
    P63475 -.->|partial| I61389
    P63652 -.->|partial| I61389
    P63789 -.->|partial| I61389
    P65611 -->|best fix| I61389
    P61395 -->|fixes| I62324
    P62328 -.->|partial| I62324
    P62329 -->|fixes| I62324
    P63184 -->|fixes| I62324
    P63652 -.->|partial| I62324
    P63789 -->|fixes| I62324
    P65611 -->|best fix| I62324
    P62442 -->|best fix| I62429
    P62564 -->|best fix| I62462
    P61395 -->|fixes| I62642
    P62329 -->|fixes| I62642
    P63184 -->|fixes| I62642
    P63652 -.->|partial| I62642
    P63789 -->|fixes| I62642
    P65611 -->|best fix| I62642
    P61395 -.->|partial| I63784
    P62442 -.->|partial| I63784
    P63789 -.->|partial| I63784
    P65611 -->|best fix| I63784
    class I61389 closed
    class I61396 open
    class I62324 open
    class I62429 open
    class I62462 open
    class I62642 open
    class I63784 open
    class I61396 target
    class P61395 closed
    class P61829 closed
    class P61832 open
    class P62328 closed
    class P62329 open
    class P62442 open
    class P62564 closed
    class P63184 open
    class P63475 closed
    class P63652 closed
    class P63789 open
    class P65611 merged
    class P62442 best
    class P62564 best
    class P65611 best
    class P65611 best
    class P65611 best
    class P65611 best
    class P65611 best
    class More closed
    class MoreI closed
    click I61389 "https://github.com/NousResearch/hermes-agent/issues/61389"
    click I61396 "https://github.com/NousResearch/hermes-agent/issues/61396"
    click I62324 "https://github.com/NousResearch/hermes-agent/issues/62324"
    click I62429 "https://github.com/NousResearch/hermes-agent/issues/62429"
    click I62462 "https://github.com/NousResearch/hermes-agent/issues/62462"
    click I62642 "https://github.com/NousResearch/hermes-agent/issues/62642"
    click I63784 "https://github.com/NousResearch/hermes-agent/issues/63784"
    click P61395 "https://github.com/NousResearch/hermes-agent/pull/61395"
    click P61829 "https://github.com/NousResearch/hermes-agent/pull/61829"
    click P61832 "https://github.com/NousResearch/hermes-agent/pull/61832"
    click P62328 "https://github.com/NousResearch/hermes-agent/pull/62328"
    click P62329 "https://github.com/NousResearch/hermes-agent/pull/62329"
    click P62442 "https://github.com/NousResearch/hermes-agent/pull/62442"
    click P62564 "https://github.com/NousResearch/hermes-agent/pull/62564"
    click P63184 "https://github.com/NousResearch/hermes-agent/pull/63184"
    click P63475 "https://github.com/NousResearch/hermes-agent/pull/63475"
    click P63652 "https://github.com/NousResearch/hermes-agent/pull/63652"
    click P63789 "https://github.com/NousResearch/hermes-agent/pull/63789"
    click P65611 "https://github.com/NousResearch/hermes-agent/pull/65611"
```
*Graph: solid arrow = fixes / best fix, dashed arrow = partial or unverified (see edge label); boxed group = PRs duplicating each other; amber border = best fix; indigo border = target; gray node = closed or no verify verdict yet (state tag in the node label).*

_Cross-PR triage: Reviewed 13 pull requests and 8 issues in this complex. Each diff was read against this issue; Assessment working set: 85 kB of PR diffs, 63 kB of issue/PR text, 18 kB of discussion (29 comments), 60 verify verdicts. verdicts reflect diff content, not PR titles. Part of an automated triage batch._

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Re-triage correction: #61389 is closed, and merged #65611 carries this packaging fix on current main. This remains related history rather than a live duplicate.

**Comment by andrexibiza** [comment]
Triage: this cluster (node-pty spawn-helper losing the execute bit during desktop staging -> posix_spawnp failed on macOS) is fully resolved on current main.

Merged fixes:
- #65611 (7d8c499893, 2026-07-16): chmod 0o755 on both staging paths in apps/desktop/scripts/stage-native-deps.mjs (makeExecutable at :32-34, build/Release :102-107, prebuild :271-275), with behavioral tests asserting 0o755 (stage-native-deps.test.mjs:329-332)
- #66734 (da805810d4, 2026-07-18): lazy exec-bit restore for dev terminals (apps/desktop/electron/spawn-helper-perms.ts)
- #71171 (ac327dfa38, 2026-07-25): resolve app.asar.unpacked spawn-helper before runtime chmod

Duplicate-of-this-cluster PRs #62329, #63184, #63789 remain open; all predate the #65611 merge and have been commented with the same evidence. Proposing this issue be closed as completed (see also dup #62324, #62642; anchor #61389 already closed completed).

**Comment by OutThisLife** [comment]
Fixed on main: Desktop restores execute permissions on node-pty spawn-helper in both packaged staging layouts and repairs the actual unpacked helper before terminal startup. This addresses the reported macOS posix_spawnp permission failure, not unrelated terminal failures. See https://github.com/NousResearch/hermes-agent/pull/71171 and the staging/runtime source at https://github.com/NousResearch/hermes-agent/blob/731e99d15d93c60e73323a80d704357f0d010e98/apps/desktop/scripts/stage-native-deps.mjs and https://github.com/NousResearch/hermes-agent/blob/731e99d15d93c60e73323a80d704357f0d010e98/apps/desktop/electron/spawn-helper-perms.ts . Current focused staging/permission tests pass. Release availability has not been verified.
