### PR TITLE
feat(api): add voice session endpoints

### PR DESCRIPTION
**Pull request by ghostmfr**
## Summary
- Add lightweight API-server voice session endpoints for a mobile/iOS MVP (`POST/GET/DELETE /v1/voice/sessions`, `POST /v1/voice/sessions/{voice_session_id}/turns`).
- Reuse the existing Hermes server-side `AIAgent` session path for text turns, preserving short-term turn history and honoring `X-Hermes-Session-Key`/JSON `session_key` memory scoping when authenticated.
- Advertise the voice contract in `/v1/capabilities` and support best-effort TTS output using the existing `text_to_speech_tool`, with optional base64 embedding.
- Add focused aiohttp endpoint tests covering session lifecycle, text turns, TTS payload shape, auth/session-key behavior, and the explicit audio-upload boundary.

## Test plan
- `PYTHONPATH=. python -m pytest -o addopts='' tests/gateway/test_api_server_voice_sessions.py` ✅
- `python -m py_compile gateway/platforms/api_server.py tests/gateway/test_api_server_voice_sessions.py` ✅
- `git diff --check` ✅

Note: I also attempted `PYTHONPATH=. python -m pytest -o addopts='' tests/gateway/test_api_server.py tests/gateway/test_api_server_voice_sessions.py`; the run exhausted local file descriptors in aiohttp (`OSError: [Errno 24] Too many open files`) after 122 existing tests had passed. The new voice-session test file passes independently.

## iOS MVP contract
1. Dial/start: `POST /v1/voice/sessions`
   - Optional JSON: `{ "system_prompt": "...", "session_key": "stable-user-or-device-key" }`
   - Auth: `session_key` requires the configured API bearer key, matching `X-Hermes-Session-Key` semantics.
   - Response includes `id`, `hermes_session_id`, `status`, `turn_count`, and capabilities.
2. Talk/text turn: `POST /v1/voice/sessions/{voice_session_id}/turns`
   - JSON: `{ "text": "transcribed user speech", "tts": true, "include_audio_base64": false }`
   - Response includes `transcript`, `reply`, `usage`, and optional `audio` (`file_path`, `media_tag`, `mime_type`, optional `base64`).
3. Hang up: `DELETE /v1/voice/sessions/{voice_session_id}`
   - Marks the session `ended`; later turns return 409.

## Boundary / caveat
This is not realtime VoIP and does not implement server-side audio upload/STT yet. Audio-only turn requests return `501 voice_audio_not_supported`; iOS should use on-device speech recognition or another STT service and submit the transcript as `text` for this MVP.

### CODE REVIEW

**Comment by ghostmfr** [comment]
Closing this upstream PR and moving the work to Garrett's fork/local repo per owner request: https://github.com/ghostmfr/hermes-agent/pull/2
