### PR TITLE
feat(fast): resolve /fast against the full route, not the model id alone

### PR DESCRIPTION
**Pull request by Kyzcreig**
## The problem

`/fast` is one command name over three different vendor features:

| Feature | Wire | Parameter |
|---|---|---|
| OpenAI Priority Processing | OpenAI-style (chat completions / responses) | `service_tier="priority"` |
| Codex Fast | Codex Responses subscription backend | `service_tier="fast"` |
| Anthropic Fast Mode | native Anthropic Messages | `speed="fast"` + `fast-mode-*` beta |

Support was resolved from the model id alone (`resolve_fast_mode_overrides(model_id)`), which cannot tell those apart. Two cases resolve wrong today on `main`:

**1. The Anthropic `speed` parameter leaks off its wire.**

```python
>>> resolve_fast_mode_overrides("claude-opus-4-6")
{'speed': 'fast'}   # ...whatever route that model is reached over
```

`speed` is a native Messages parameter. Serve the same model id through a third-party endpoint and it receives a parameter it cannot honour — which is exactly why `anthropic_adapter` already has to re-check `_is_third_party_anthropic_endpoint` and strip it defensively on the way out. The gate and the adapter disagreeing is the bug; the defensive strip is the symptom.

**2. The Codex backend is sent the wrong tier value.**

`gpt-5.4` on the `openai-codex` subscription backend was sent `service_tier="priority"`. That backend sells a `fast` tier, not `priority`.

Both are silent: the user toggles `/fast`, the command says it worked, and the request either drops the parameter downstream or asks for a tier that doesn't exist there.

## The change

Resolution now takes the full `(model, provider, api_mode)` route and returns one `FastModeCapability` — `supported`, `family`, `request_overrides`, and a human `reason` — shared by the command surface, the picker inventory and the request builder, so what `/fast` advertises, what it explains, and what actually reaches the wire cannot drift apart.

`request_overrides` is empty whenever `supported` is false, so a caller structurally cannot ship a parameter whose gate said no.

**The per-family gates deliberately differ, matching how each vendor fails:**

- **Anthropic Fast Mode** requires the native Messages route *and* an exact model from a dated contract. `speed` does not exist on other wires, and is a hard 400 on other Claude models — so it fails closed.
- **Codex Fast** requires the Codex Responses backend and its own (much shorter) model contract, because the tier *value* differs from the OpenAI API's.
- **Priority Processing** keeps the existing permissive pattern gate on any OpenAI-style wire. `service_tier` is *ignored* rather than rejected by endpoints that don't sell it, so breadth is free here and a narrower list would hide the toggle from a newly released flagship. This preserves the documented existing judgment — including that a model reached through a routing proxy keeps working.

That asymmetry is the point: the tightening lands only where the vendor actually rejects, and nothing that works today stops working.

Two smaller fixes fall out of the same seam:

- `/fast` now resolves against the route the session's **next turn** will use, so a session-scoped `/model` switch is reflected instead of reporting on the configured route the session no longer uses. `--global` still gates on the configured gateway route, since that's what the persisted default applies to.
- An unsupported route now explains *why* (naming the route) instead of accepting the toggle and silently sending nothing. Turning `/fast` **off** is never blocked by an unsupported route.

New dated contracts live in `hermes_cli/fast_mode_contracts.py` with a source URL and check date per family, so refreshing one when a vendor updates its list is a single-file edit.

## Prompt caching

The flag rides the **request params only**. `request_overrides` is merged into `api_kwargs`/`extra_body` at the transport (`transports/chat_completions.py`, `transports/codex.py`, `anthropic_adapter`) and never touches the system prompt, message history, or tool schema — so toggling `/fast` mid-conversation cannot invalidate a cached prefix.

This is asserted structurally rather than claimed, in `TestPromptCacheSafety`:

- `test_toggling_fast_changes_only_request_overrides` — resolves the same turn with the toggle off and on, and asserts the set of differing keys is **exactly** `{"request_overrides"}`.
- `test_cache_identity_inputs_are_unchanged_by_fast` — `model`, `runtime` and the cache `signature` are byte-identical across the toggle, *and* the toggle demonstrably took effect (so the assertion isn't vacuously green).
- `test_fast_overrides_carry_no_prompt_or_context_keys` — no emitted override key may be `system`/`messages`/`input`/`instructions`/`tools`/`prompt`/`prompt_cache_key`, for every supported family.

`/fast` also does not re-route: `test_route_runtime_is_not_switched_by_fast` pins that provider, `api_mode`, `base_url` and model are untouched.

## Cost

Priority and fast tiers **bill above the standard tier** on every provider that offers them. This PR does not change who pays or when: the command stays explicit, per-session, opt-in, and off by default. `--global` continues to require the flag and is gated on the configured gateway route.

## Tests

23 new tests across three files, plus one existing test re-pointed:

- `tests/cli/test_fast_route_capability.py` — the resolver: wire-specific keys, exact-vs-pattern contracts, the fail-closed invariant, and unpinned (`auto`) provider handling. Includes `test_anthropic_capability_agrees_with_adapter_gate`, which pins the command gate against `anthropic_adapter._supports_fast_mode` so the two cannot drift again.
- `tests/gateway/test_fast_route_injection.py` — the injection seam, asserting the **wire payload** rather than reply text, plus `TestPromptCacheSafety`.
- `tests/gateway/test_fast_session_route.py` — session-route resolution and preference persistence (including that an explicit `normal` is presence-sensitive and must beat a config default without leaking to other sessions).
- `tests/gateway/test_turn_request_overrides.py` — the fast-mode case previously stubbed the resolver by name; it now exercises a genuinely fast-capable route, and gains a sibling asserting a provider's `extra_body` still survives when the route has *no* fast contract.

**RED-proofs** (each mutation applied in isolation against the finished branch, then reverted):

| Mutation | Named tests that go red |
|---|---|
| Anthropic gate stops checking the provider (back to model-only) | `test_third_party_anthropic_messages_route_emits_nothing`, `test_third_party_messages_route_injects_nothing` (gateway + CLI), `test_concrete_provider_is_not_rerouted`, `test_structural_invariant[claude-opus-4-6-openrouter-anthropic_messages]` — **5 red** |
| Codex branch emits `priority` instead of `fast` | `test_codex_backend_emits_service_tier_fast`, `test_same_model_on_openai_api_emits_priority_instead`, `test_codex_backend_injects_fast_tier_not_priority`, `test_codex_backend_injects_fast_tier` — **4 red** |
| Session `/model` override stops steering the fast route | `test_session_model_override_steers_the_route`, `test_override_without_api_mode_is_rederived_not_inherited`, `test_switching_the_session_model_switches_the_fast_key` — **3 red** |
| Preference sentinel collapses explicit-`normal` into unset | `test_clear_falls_back_to_the_config_default`, `test_override_does_not_leak_to_other_sessions`, `test_session_fast_override_beats_config_default` — **3 red** |

**Suite results** (hermetic `uv sync`, same file list on both trees):

```
tests/gateway/      origin/main : 11 failed, 6921 passed, 45 skipped, 2 xfailed
                    this branch : 11 failed, 6944 passed, 45 skipped, 2 xfailed
                    -> identical failure sets (diff is empty); +23 net new tests
```

The 11 are pre-existing on `main` and unrelated (discord attachments, systemd abstract sockets, teams dotenv isolation, scale-to-zero) — several are macOS/env-specific and pass in isolation.

Focused blast radius, all green:

```
tests/hermes_cli/test_inventory.py tests/cli/test_fast_command.py
tests/cli/test_fast_route_capability.py tests/cli/test_reasoning_command.py
tests/cli/test_cli_approval_ui.py tests/agent/test_anthropic_adapter.py
tests/agent/test_switch_model_request_overrides.py
tests/agent/test_credential_pool_routing.py
tests/agent/test_custom_provider_extra_body_matching.py
-> 239 passed
```

## Locales

11 new keys (`family_*`, `state_*`, `route_*`) across all 17 locale files, translated rather than English-filled, matching each file's existing convention for the `Priority Processing` product name (kept in Latin script in `de`/`ja`/`ru`, translated as 优先处理 in `zh`/`zh-hant`, full-width punctuation preserved). Placeholder sets, code spans and bold markers were validated programmatically per key per locale.

Four now-superseded keys (`not_supported`, `saved`, `session_only`, `status`) are left in place rather than deleted — happy to remove them in a follow-up if you'd prefer the cleanup separated from the behaviour change.

### CODE REVIEW

**Comment by Kyzcreig** [comment]
The `Python tests / Run tests` failure on this PR is **inherited from `main`**, not introduced here.

Failing:
```
tests/gateway/test_buzz_thread_topology.py::TestReplyThreadingConfig::test_standalone_send_threads_by_default
tests/gateway/test_buzz_thread_topology.py::TestReplyThreadingConfig::test_standalone_send_honors_opt_out

TypeError: fake_exec() got an unexpected keyword argument 'auth_tag'
plugins/platforms/buzz/adapter.py:1849: TypeError
```

Reproduced on a clean checkout of `origin/main` at `26f178e5fa` ("fix(terminal): gate the BUZZ_* terminal carve-out on actual Buzz agent context"), with no changes from this branch applied:

```
$ git log --oneline -1
26f178e5fa fix(terminal): gate the BUZZ_* terminal carve-out on actual Buzz agent context

$ pytest tests/gateway/test_buzz_thread_topology.py -q -p no:randomly
FAILED ...::TestReplyThreadingConfig::test_standalone_send_honors_opt_out
FAILED ...::TestReplyThreadingConfig::test_standalone_send_threads_by_default
2 failed, 15 passed
```

Byte-identical failures and count on this branch. This PR touches no Buzz files — `git show --stat HEAD | grep -i buzz` is empty (28 files: `hermes_cli/`, `gateway/run.py`, `gateway/slash_commands.py`, `cli.py`, `locales/`, `tests/`).

Cause looks like a stub/signature skew: `972f0314de` ("feat(buzz): compose thread-topology cluster…") added an `auth_tag` kwarg at the `adapter.py:1849` call site, but the two `fake_exec` closures in `TestReplyThreadingConfig` don't accept it. The sibling tests in the same file that already take `**kwargs` pass. Happy to open a separate one-line PR widening those two stubs if that's useful — flagging rather than fixing it here to keep this diff scoped.

Differential attribution for the rest of the gateway suite, run locally on both trees with the same file list:

```
origin/main : 11 failed, 6921 passed, 45 skipped, 2 xfailed
this branch : 11 failed, 6944 passed, 45 skipped, 2 xfailed   (+23 new tests)

$ diff <(grep ^FAILED base.log) <(grep ^FAILED branch.log)   # empty
```

Identical failure sets → no regressions from this change. Every other required check on this PR is green, including `check-attribution`, `ruff enforcement (blocking)`, `ruff + ty diff`, `Windows footguns (blocking)`, `macOS-only tests`, `e2e`, OSV and supply-chain scans, and both docker builds.

**Comment by teknium1** [comment]
Closing as implemented via #101285 (merged, c7e2e0b779): `resolve_fast_mode_overrides` now takes the route (provider/base_url) and is the single gate for static and bounded fast modes, so `service_tier`/`speed` are only sent on first-party Anthropic/OpenAI/xAI routes. Your PR identified the same problem; the landed version is the ~30-line variant. Thanks!
