### PR TITLE
fix(tools): swallow stale-module ImportError in browser atexit cleanup

### LINKED ISSUE #112522: [Bug]: hermes update — transient ImportError (cannot import file_signature from utils) in gateway-restart phase and atexit cleanup
## Bug Description

`hermes update` (upgrading from an earlier commit to v0.21.3, `main @ 30b22b54`) printed a
gateway-restart failure at the end of an otherwise-successful run, and the same `ImportError`
fired again, uncaught, in two atexit cleanup callbacks at process exit:

```
✓ Update complete! (v0.21.3) [main @ 30b22b54]
→ Refreshing cua-driver (Computer Use)...
✓     cua-driver upgraded: cua-driver 0.28.1 → cua-driver 0.28.2

⚠ Update incomplete — gateway auto-restart failed: cannot import name 'file_signature' from 'utils' (/home/<user>/.hermes/hermes-agent/utils.py)
  Any gateway still running is serving pre-update code
  (mixed sys.modules) against the updated checkout.
  Restart it manually, then verify:
    hermes gateway restart
    hermes gateway status

Exception ignored in atexit callback: <function _stop_browser_cleanup_thread at 0x...>
Traceback (most recent call last):
  File ".../tools/browser_tool_lifecycle.py", line 425, in _stop_browser_cleanup_thread
    _bt._cleanup_running = False
  File ".../tools/browser_tool_origin.py", line 84, in __setattr__
    setattr(origin_module(3), name, value)
  File ".../tools/browser_tool_origin.py", line 70, in origin_module
    import tools.browser_tool as mod
  File ".../tools/browser_tool.py", line 25, in <module>
    from hermes_cli.config import DEFAULT_CONFIG, cfg_get
  File ".../hermes_cli/config.py", line 33, in <module>
    from utils import atomic_replace, atomic_yaml_write, fast_safe_load, file_signature
ImportError: cannot import name 'file_signature' from 'utils' (/home/<user>/.hermes/hermes-agent/utils.py)
```

The same traceback repeated for a second atexit callback (`_emergency_cleanup_all_sessions`).

**This does not reproduce on retry** — a second `hermes update` run immediately afterward
completed with no error. Filing this because the existing, documented mitigation for exactly this
symptom class apparently didn't fully prevent it this one time, which seems worth a maintainer
look even though it's low severity and self-resolved.

## Steps to Reproduce

Not reliably reproducible — occurred once during a routine `hermes update` (no gateway configured
or running on this machine; CLI-only usage). A second `hermes update` run right after did not
reproduce it. Best guess at contributing factors: the updated version added `file_signature` to
`utils.py`, and the update process had already imported the old `utils` module earlier in its own
run before the git pull landed.

## Expected Behavior

`hermes update` completes without any `ImportError`, or — if a stale-module race is unavoidable
in some code paths — the gateway-restart phase and atexit handlers fail without printing a raw
Python traceback to the user.

## Actual Behavior

See the traceback above. The update itself succeeded (code, config migration, skills sync,
cua-driver upgrade all completed and reported success) — only the gateway-restart phase and the
process's own atexit cleanup hit the `ImportError`. Verified independently that this was cosmetic/
non-blocking: `utils.py` on disk genuinely defines `file_signature`; a fresh `hermes --version`
and fresh one-shot invocation both worked immediately afterward (exit 0); `hermes gateway status`
showed no gateway running at all, so the gateway-restart phase had nothing real to restart on this
machine; all local config was intact post-update.

## Affected Component

- Setup / Installation
- CLI (interactive chat)

## Messaging Platform (if gateway-related)

N/A (CLI only) — no gateway was configured or running when this occurred.

## Debug Report

Skipped the automatic `hermes debug share` upload for this report: previewed it locally
(`hermes debug share --local`) first, and the last-200-lines `agent.log` excerpt it includes would
have pulled in unrelated content from other conversations in the same log file that I'd rather not
put on a public paste service. Providing the directly relevant info by hand instead (see
`hermes dump`-equivalent fields below, and the traceback above, which is copied verbatim from the
terminal aside from redacting the home directory path to `/home/<user>/`).

## Operating System

Ubuntu (Linux 6.8.0-138-generic x86_64)

## Python Version

3.11.16

## Hermes Version

0.21.3 (the version being updated *to*; commit `30b22b54` at the time of the failure — current
`main` has since moved to `10652c93`)

## Additional Logs / Traceback (optional)

Already included verbatim above (Bug Description section) — this is the complete output relevant
to the failure, not truncated.

## Root Cause Analysis (optional)

Traced this before filing, since the relevant fix already exists in the codebase and is clearly
labeled:

`hermes_cli/update_cmd_maint.py`'s `_purge_stale_hermes_modules()` (around line 111) evicts every
checkout-owned module from `sys.modules` after a pull, specifically to prevent this class of bug —
its own docstring for `_stale_purge_prefixes()` (around line 92) names this *exact* symptom as the
motivating case:

> "the symbol that breaks the next update is in whichever one drifted out — `utils` gaining
> `base_url_origin` / `file_signature` were the field cases."

It's called from `update_cmd_config.py:186` (every update-completion path, citing issue `#111271`
in its own comment) and from `update_cmd_fleet.py:362` and `:1304` — the second call site's own
comment says it purges "FIRST" specifically because "the import below loads new gateway source
into this pre-update interpreter, and a cached sibling missing a symbol the new source expects
would ImportError and abort the whole phase."

That's exactly what happened here anyway. I didn't dig further into *why* the purge didn't fully
prevent it in this instance, but `_purge_stale_hermes_modules()`'s own docstring already flags a
plausible limit: "Purging (unlike reload) only drops the `sys.modules` entry — running frames keep
their module objects." If some other already-executing frame in the same update process held a
live reference to the old `utils` module object (bound before the purge ran), evicting the
`sys.modules` entry wouldn't fix that already-bound name — only a fresh import from that point
forward. That's a guess at the mechanism, not a confirmed diagnosis; flagging it as the most
promising lead for whoever picks this up, since you clearly already understand this bug class
better than an outside report can.

## Proposed Fix (optional)

No specific fix proposed — the existing `_purge_stale_hermes_modules()` mechanism looks like the
right general approach, this is just a report that it (or its call-site placement) didn't fully
cover this particular process/import-graph shape. Might be worth an `importlib.reload()` pass (not
just eviction) for modules with live bound references from earlier frames in the same process,
if that's in fact the mechanism — but that's a guess from outside the codebase, not a real fix.

## Are you willing to submit a PR for this?

No — filing for visibility/reproduction data, not planning to submit a fix myself.

### PR DESCRIPTION
**Pull request by chelsealong**
Fixes #112522

## What

`hermes update`'s post-pull `_purge_stale_hermes_modules()` evicts checkout-owned
modules from `sys.modules` so later phases reimport the freshly-pulled source. Its
own docstring already flags the limit: eviction only drops the `sys.modules`
entry — a frame that already bound a name to the old module object keeps that
stale reference. When that race lands inside the two `tools.browser_tool`
atexit cleanup callbacks (`_emergency_cleanup_all_sessions`,
`_stop_browser_cleanup_thread`), `origin_module()`'s atexit fallback
(`tools/browser_tool_origin.py`) does a bare `import tools.browser_tool`,
which can hit a transient `ImportError` (`cannot import name 'file_signature'
from 'utils'` in the reported traceback) and propagate all the way out of the
atexit callback, printing a raw "Exception ignored in atexit callback"
traceback to the user at process exit — right after `hermes update` already
reported success.

The issue's reporter traced this precisely and noted the update itself is
unaffected; only the gateway-restart phase and the atexit handlers surface a
raw traceback for what is a cosmetic, self-resolving race (a second
`hermes update` run immediately after did not reproduce it). Their "Expected
Behavior" section asks for exactly this: "if a stale-module race is
unavoidable in some code paths, the gateway-restart phase and atexit handlers
fail without printing a raw Python traceback to the user."

## Fix

Wrap both `atexit.register()` callbacks in `tools/browser_tool.py` with a new
`_safe_atexit()` helper that logs (debug) and swallows any exception instead
of letting it escape the callback. This matches the existing pattern in the
same file: `_stop_browser_cleanup_thread()` already catches
`KeyboardInterrupt`/`SystemExit` around its thread `.join()` for the same
reason ("letting it propagate only prints 'Exception ignored in atexit
callback'").

This does not change the root-cause module-purge/reimport race (which the
issue's own reporter couldn't fully pin down and didn't propose a fix for) —
it only stops that rare, already-cosmetic race from printing a raw traceback
at exit, which is the concrete, user-visible part of the report.

## Test plan

Added `TestSafeAtexitSwallowsStaleModuleRace` to
`tests/tools/test_browser_cleanup.py`, verifying `_safe_atexit()` swallows an
`ImportError` shaped exactly like the one in the report instead of letting it
propagate.

Confirmed the test fails without the fix (reverted only `tools/browser_tool.py`
to `HEAD~1`, restored after):

```
$ python3 -m pytest tests/tools/test_browser_cleanup.py::TestSafeAtexitSwallowsStaleModuleRace -v
...
AttributeError: module 'tools.browser_tool' has no attribute '_safe_atexit'
1 failed in 1.02s
```

And passes with the fix:

```
$ python3 -m pytest tests/tools/test_browser_cleanup.py -v
...
tests/tools/test_browser_cleanup.py::TestSafeAtexitSwallowsStaleModuleRace::test_wrapped_callback_does_not_raise PASSED [100%]
8 passed in 1.04s
```

Also ran the full `tests/tools/ -k browser` slice (785 tests) before and after
the change: same 4 pre-existing failures on unmodified `main` (test-isolation
artifacts from running many files in one pytest process — `test_engine_cache_reset`'s
live-system-guard `os.kill` mock leak and a `get_secret` patch-target leak in
`test_strict_provider_selection.py`; both pass in isolation and are unrelated
to this change), 780/781 passed either way (+1 for the new test).

`ruff check tools/browser_tool.py tests/tools/test_browser_cleanup.py` and
`scripts/check-windows-footguns.py` both pass clean.

## AI assistance disclosure

This PR was authored with Claude Code (Anthropic) as part of an automated
contribution pipeline: it located the code path, wrote the fix and test, and
verified the fix against a revert. A human reviews and is accountable for
what's submitted.

### CODE REVIEW

**Comment by chelsealong** [comment]
Closing as superseded: the linked issue #112522 was closed as completed on 2026-09-16, so the underlying bug is fixed on main. I checked the current tree and main's fix does not use this branch's code — it was resolved a different way — so there is nothing left for this PR to contribute. Closing rather than leaving a stale branch open against a resolved issue.
