### PR TITLE
fix(copilot): surface 'no paid subscription' instead of model_not_supported

### PR DESCRIPTION
**Pull request by vincez-hms-coder**
## Summary

When a GitHub account has no paid Copilot subscription (`access_type_sku: free_limited_copilot`), `GET /copilot_internal/v2/token` returns **HTTP 404**. The current code silently catches that and falls back to using the raw `gho_*` OAuth token directly against `api.githubcopilot.com`, which then rejects every request with `HTTP 400 model_not_supported` — sending users down a rabbit hole trying different model names.

This PR detects the 404 specifically, stops the silent fallback for that case, and surfaces a clear error pointing users either at the upgrade page or at signing in with a different GitHub account.

## Changes

- **`hermes_cli/copilot_auth.py`**
  - New `CopilotSubscriptionError(ValueError)` — subclass so existing `except ValueError` handlers keep catching it.
  - `exchange_copilot_token`: catch `urllib.error.HTTPError` separately; raise `CopilotSubscriptionError` on 404, plain `ValueError` for other HTTP codes.
  - `get_copilot_api_token`: re-raise `CopilotSubscriptionError` (raw token is useless for chat completions, falling back masks the real error). Log the warning once per token fingerprint per process. Other transient errors still fall back to the raw token, preserving accounts/PATs that don't need exchange.

- **`hermes_cli/auth.py`**
  - `_resolve_api_key_provider_secret`: catch `CopilotSubscriptionError` ahead of the generic `ValueError` branch and raise a structured `AuthError(code=\"copilot_subscription_required\")` so the request layer surfaces it instead of attempting a doomed call.
  - `format_auth_error`: friendly message pointing at https://github.com/settings/copilot or `hermes auth add copilot` for switching accounts.

- **Tests** (6 new in `test_copilot_token_exchange.py`)
  - `test_raises_subscription_error_on_404` — 404 → `CopilotSubscriptionError`
  - `test_other_http_errors_are_plain_value_error` — 500 → plain `ValueError`
  - `test_subscription_error_propagates` — wrapper does **not** silently fall back
  - `test_subscription_warning_logged_once_per_token` — repeated calls log once
  - `test_auth_resolve_surfaces_subscription_error` — surfaces as `AuthError`
  - `test_format_auth_error_subscription_message` — friendly message rendering

## Reproduction (before this PR)

```
$ hermes -p writer
> hi
Error code: 400 - {'error': {'message': 'The requested model is not supported.',
                             'code': 'model_not_supported', ...}}
```

The user changed model names (`claude-opus-4.6-1m` → `claude-opus-4.6` → `claude-sonnet-4.6`) — every one rejected. Actual cause: `gh auth token` returned a `gho_*` for an account whose `/copilot_internal/v2/token` returns 404. Probing manually:

```
$ curl -H \"Authorization: token gho_***\" \\
       https://api.github.com/copilot_internal/user
{\"login\":\"...\",\"access_type_sku\":\"free_limited_copilot\",\"chat_enabled\":true,...}

$ curl -H \"Authorization: token gho_***\" \\
       https://api.github.com/copilot_internal/v2/token
HTTP 404 {\"message\":\"Not Found\"}
```

After this PR the user sees the actual cause on first run.

## Test plan

- [x] `pytest tests/hermes_cli/test_copilot_token_exchange.py` — 18 passed (12 original + 6 new)
- [x] `pytest tests/hermes_cli/test_copilot_auth.py tests/hermes_cli/test_copilot_catalog_oauth_fallback.py tests/hermes_cli/test_copilot_context.py` — 45 passed (no regressions in adjacent suites)
- [ ] Smoke test by reviewer with a paid Copilot account — exchange should still work normally (cache, fallback for non-404 errors, etc.).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by vincez-hms-coder** [comment]
The 15 test failures in the `test` job are **pre-existing on upstream `main`** and not introduced by this PR.

**Verification:** I checked out upstream `main` directly (commit `5d3be898a`) without any of my changes and reproduced the same failure:

```
$ pytest tests/run_agent/test_concurrent_interrupt.py::test_concurrent_interrupt_cancels_pending
AttributeError: '_Stub' object has no attribute '_tool_guardrails'
run_agent.py:9447: AttributeError
```

This PR only changes 3 files: `hermes_cli/auth.py`, `hermes_cli/copilot_auth.py`, `tests/hermes_cli/test_copilot_token_exchange.py`. None of the failing tests touch any of these — they're in `run_agent.py`, ACP server, Teams gateway, systemd unit generator, Dockerfile, TUI session handling, etc.

**This PR's own tests pass cleanly:**

```
$ pytest tests/hermes_cli/test_copilot_token_exchange.py
18 passed in 2.12s
```

Supply chain audit also passes after rebasing onto current upstream/main (the earlier failure was a false positive caused by the branch being based on a stale fork main, which made the diff include `hermes_cli/setup.py` even though I never touched it).

**Comment by teknium1** [comment]
Thanks for the careful 404 disambiguation, including the paid-account fallback described in the follow-up comment. The underlying fallback remains on current main: `hermes_cli/copilot_auth.py:345-349` converts exchange failures to `ValueError`, and `:429-434` returns the raw token; that path reaches runtime resolution through `hermes_cli/auth.py:575-584`.

### Problems
- The PR is based on the old token API. Current `exchange_copilot_token()` returns `(api_token, expires_at, base_url)` at `hermes_cli/copilot_auth.py:307-380`, and `get_copilot_api_token()` returns `(api_token, base_url)` at `:415-434` (introduced by `fbd15e285` / `15e44527a`). The implementation and tests need adaptation rather than a direct cherry-pick.
- The proposed `AuthError` would escape `get_api_key_provider_status()`: it directly invokes the resolver at `hermes_cli/auth.py:6200`, while `get_auth_status()` dispatches Copilot to that function at `:6275-6277` without handling it.

### Suggested changes
- Preserve the current tuple/base-URL contracts and add coverage for the runtime and status paths.
- Make the status path return actionable structured failure information rather than raising.

Automated hermes-sweeper review.
