### ISSUE TITLE
Bug: `RuntimeError: 'dict' object has no attribute 'model_dump'` after v0.21 upgrade (12 cron jobs broken)

### ISSUE THREAD

**Issue by manaswai07014** [NousResearch/hermes-agent#107967]
# Bug: `RuntimeError: 'dict' object has no attribute 'model_dump'` after v0.21 upgrade

## Summary

After upgrading from Hermes v0.17.0 to v0.21.0 (commit `245e48008f`), **all 11 of my Hermes-internal scheduled cron jobs fail with the same error**: `RuntimeError: 'dict' object has no attribute 'model_dump'`.

## Environment

- **Hermes version**: v0.21.0 (v2026.8.31)
- **Python**: 3.11.16
- **OS**: WSL2 Ubuntu 24.04 (Windows host)
- **Upgrade path**: `hermes update --yes --backup` (clean upgrade from v0.17.0)
- **Reproduction date**: 2026-09-10 (first failure); ongoing as of 2026-09-11

## Affected jobs (11 total, all `[active]` but failing)

| Job ID | Name | Schedule | Last error |
|---|---|---|---|
| `790ec44db276` | Daily News to Telegram | `0 7 * * *` | `'dict' object has no attribute 'model_dump'` |
| `28891864a449` | Trend Report to Telegram | `20 7 * * *` | Same |
| `53b00759f029` | Daily Status Report | `0 8 * * *` | Same |
| `c55fc2a67778` | Daily Backup | `20 8 * * *` | Same |
| `9d9905a8dcad` | Daily Competitor Report (Phase 1+2+3 Plus) | `0 9 * * *` | Same |
| `34ff6f88e89a` | Daily Auto-Wiki Ingestion | `0 10 * * *` | Same |
| `fec17b8749a1` | Daily Topic Priority Report | `0 11 * * *` | Same |
| `c9be5d41daa7` | Daily Smoke Test (Noon) | `0 12 * * *` | Same |
| `3a6c0a84e726` | Auto-fill triples from wiki | `0 2 * * *` | Same (2 days failing) |
| `67355bdc2cc4` | Daily Wiki Sync + Lint | `45 7 * * *` | Same (5 days failing) |
| `9da97fe3ea48` | Memory Health Check (Daily) | `0 6 * * *` | Different: `triples.jsonl` STALE 86 days |

### Source code scan

I grep'd the entire `apps/hermes-agent/` source tree for unguarded `.model_dump(` calls. Findings:

\`\`\`
agent/api_request_hooks.py:104:  if hasattr(value, "model_dump"):
agent/relay_tools.py:80:        model_dump = getattr(value, "model_dump", None)
agent/chat_completion_helpers.py:1571: def _dump_if_model(value):
agent/anthropic_message_convert.py:219: dumped = value.model_dump(warnings=False)
\`\`\`

These all have proper guards (`hasattr`, `getattr`, `_dump_if_model` wrapper). So the source code is correct **at these sites**.

### Suspect: deep Pydantic v2 transition

The error suggests an object is being passed where a Pydantic model is expected, but the object is a plain `dict`. Likely caused by one of:
- A v0.17→v0.21 migration path that converted some Pydantic models to dicts somewhere
- A third-party plugin (car-evolution, skill-trigger-map) returning dicts where v0.21 expects Pydantic models
- The `jobs.json` config schema changed but migration kept old format

### No full traceback available

`hermes cron incidents list` and `hermes cron runs <job_id>` only show the final `RuntimeError` line, not the full Python traceback. So I can't pinpoint the exact call site from the user side.

## Workaround (what I did)

I ran `hermes cron pause <job_id>` on all 11 failing jobs. They are now `[paused]` and don't dispatch. This stops the error spam and prevents wasted scheduler wakes, but obviously defeats the purpose of scheduled jobs.

I'd like to keep these jobs active. Could you:
1. **Reproduce locally** with any agent-mode cron job, and capture the full Python traceback?
2. **Identify the call site** where a `dict` is being passed to `.model_dump()` (or where pydantic's internal `model_dump` is being called on a non-model object).
3. **Ship a patch** — even if it's a one-line guard change in the right place.

## Reproduction

Minimal repro: any of the 11 failing jobs, dispatched automatically by cron. No manual steps needed. Just observe the agent's `last_error` field after the schedule fires.

```markdown
hermes cron run 3a6c0a84e726
\`\`\`
should produce the same `RuntimeError` (though `hermes cron run` requires correct CLI args I haven't fully verified).

## Environment details

\`\`\`
$ hermes version
Hermes Agent v0.21.0 (v2026.8.31) · upstream 245e4800
Project: /home/hermes/apps/hermes-agent
Python: 3.11.16
OpenAI SDK: 2.32.0

$ pip show pydantic
Name: pydantic
Version: 2.11.x
\`\`\`

## Priority

Medium — all scheduled jobs are non-critical (manual triggers still work for individual operations), but the daily/weekly automation is completely broken.

Thanks for the great work on the v0.21 release. The new `hermes peer` and Bot Mode features look great; I'm looking forward to using them once the cron framework is back online.
```

---

Alternatively, manually:
\`\`\`bash

**Comment by kokhlo** [comment]
Я беру. **Diagnosis + plan: PR within the hour.** ✅ **PR #107971 opened.**

---

**Диагноз:** cron-движок после v0.21 передаёт dict где ожидается Pydantic-модель с `.model_dump()`. Промежуточная миграция jobs.json или reasoning_config оставила object без guard. Симптом 100% воспроизводим на 11 jobs, но user не видит полного traceback (только RuntimeError верхний).

**Фикс (PR #107971):**
1. Добавил утилиту `_safe_dict(obj)` в `cron/scheduler.py`, которая вызывает `.model_dump()` на Pydantic-моделях и оставляет dict как есть.
2. Обернул возврат `_resolve_job_reasoning_config` в `_safe_dict()`, чтобы любой reasoning_config (будь то dict или Pydantic-модель из старого jobs.json) превращался в чистый dict.
3. Юнит-тесты: `tests/cron/test_safe_dict_guard.py` — оба зелёные.

**Время:** начал 06:08 UTC, PR открыт 06:29 UTC (21 минута).

**Ссылка:** https://github.com/NousResearch/hermes-agent/pull/107971
