### ISSUE TITLE
v0.18.0: QQBot adapter fails to connect - QQAdapter.connect() missing is_reconnect parameter

### ISSUE THREAD

**Issue by kk51740** [NousResearch/hermes-agent#58049]
## Description

After upgrading to v0.18.0, the QQ Bot adapter fails to start with:

`
ERROR gateway.run: qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
`

The Gateway started successfully but with zero connected platforms:
`
WARNING gateway.run: Gateway started with no connected platforms
WARNING gateway.run: No adapter could be created for any of the 1 configured platform(s)
`

## Root Cause

In v0.18.0, gateway/run.py passes an is_reconnect keyword argument to ALL platform adapters' connect() methods (lines 3334, 3337). All platform adapters were updated to accept this parameter **except** the QQ Bot adapter.

**Affected file:** gateway/platforms/qqbot/adapter.py, line 281

**Current (broken):**
`python
async def connect(self) -> bool:
`

**All other adapters have (correct):**
`python
async def connect(self, *, is_reconnect: bool = False) -> bool:
`

For comparison, here are the adapters that DO accept is_reconnect:
- gateway/platforms/base.py:2864
- gateway/platforms/api_server.py:4744
- gateway/platforms/bluebubbles.py:235
- gateway/platforms/signal.py:341
- gateway/platforms/webhook.py:156
- gateway/platforms/weixin.py:1264
- gateway/platforms/whatsapp_cloud.py:351
- gateway/platforms/yuanbao.py:5179
- gateway/relay/adapter.py:118
- plugins/platforms/dingtalk/adapter.py:242
- plugins/platforms/discord/adapter.py:896
- plugins/platforms/email/adapter.py:551
- plugins/platforms/feishu/adapter.py:1700
- plugins/platforms/google_chat/adapter.py:764

The QQ Bot adapter at gateway/platforms/qqbot/adapter.py:281 is the only one missing it.

## Fix

A one-line change in gateway/platforms/qqbot/adapter.py line 281:

`python
# Before:
async def connect(self) -> bool:

# After:
async def connect(self, *, is_reconnect: bool = False) -> bool:
`

## Environment

- Hermes Agent: v0.18.0 (2026.7.1)
- Python: 3.12.3
- OS: Windows 10
- Platform: QQ Bot (app_id configured)

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #52914 — same root cause: `QQAdapter.connect()` in `gateway/platforms/qqbot/adapter.py` is missing the keyword-only `is_reconnect: bool = False` parameter that `gateway/run.py` passes to every adapter, so the QQBot adapter fails to connect. Fix PRs are tracked in #52966 / #57652.

**Comment by needles-mybot** [comment]
Duplicate of PR #58128 (fix qqbot: accept is_reconnect kwarg). Closing as duplicate.

**Comment by dupl** [comment]
Such a long time without any result and explaination is unacceptable!

**Comment by teknium1** [comment]
Thanks for the clear reproduction. This is already fixed on current `main` by the merged reconnect-contract work.

- Automated hermes-sweeper review verified `QQAdapter.connect(self, *, is_reconnect: bool = False)` at `gateway/platforms/qqbot/adapter.py:281`.
- Commit `276542c729c10ff9d093760897f4c2d1256a79ce` added the QQBot implementation and regression coverage at `tests/gateway/test_qqbot.py:193`, including `connect(is_reconnect=True)`.
- Merged PR #61767 also added repository-wide adapter reconnect-contract coverage, preventing this signature drift from recurring.

Closing as implemented on main.
