### PR TITLE
fix(tools): convert MCP timeout values to timedelta for HTTP transports

### LINKED ISSUE #49629: HTTP MCP timeout type mismatch: int passed where timedelta expected
## Description

After upgrading to v0.17.0, all `url:` type (HTTP) MCP connections fail with:

```
'float' object has no attribute 'seconds'
```

stdio type (`command:`) MCPs (e.g. tdx-mcp) are not affected.

## Root Cause

`StreamableHTTPTransport.__init__()` in the `mcp` library expects `timeout` and `sse_read_timeout` as `timedelta` objects. Hermes passes plain `int`/`float` values from `config.yaml` directly.

## Temporary Fix

Applied to `mcp/client/streamable_http.py`:

```python
if isinstance(timeout, (int, float)):
    timeout = timedelta(seconds=timeout)
if isinstance(sse_read_timeout, (int, float)):
    sse_read_timeout = timedelta(seconds=sse_read_timeout)
```

This is a third-party library patch and will be overwritten on pip upgrade.

## Proper Fix

Hermes should convert config values to `timedelta` before passing to `StreamableHTTPTransport`. The fix belongs in Hermes' MCP connection startup code.

## Environment
- Hermes Agent v0.17.0
- mcp library v1.8.0

### PR DESCRIPTION
**Pull request by lennney**
## What does this PR do?

Fixes HTTP-type MCP connections failing with `'float' object has no attribute 'seconds'` by converting float timeout values to `timedelta` objects as required by the MCP library.

## Related Issue

Fixes #49629

## Type of Change

- [x] 🐛 Bug fix (non-breaking change that fixes an issue)

## Changes Made

- `tools/mcp_tool.py` — Added `timedelta` to imports; converted 3 timeout values from `float` to `timedelta(seconds=...)`

## Root Cause

The MCP library's `StreamableHTTPTransport` and SSE client expect `timeout` and `sse_read_timeout` as `timedelta` objects. Hermes was passing plain `float` values from `config.yaml`:

```python
# Before (broken)
"timeout": float(connect_timeout),      # 60.0
"sse_read_timeout": 300.0,              # 300.0

# After (fixed)
"timeout": timedelta(seconds=float(connect_timeout)),
"sse_read_timeout": timedelta(seconds=300.0),
```

## Scope

- Affects: SSE transport and deprecated Streamable HTTP API (mcp < 1.24.0)
- Not affected: New Streamable HTTP API (mcp >= 1.24.0) — already uses `httpx.Timeout` which accepts floats
- Not affected: stdio transport — no timeout passthrough to MCP library

## How to Test

1. Configure an HTTP MCP server in `~/.hermes/config.yaml`:
   ```yaml
   mcp_servers:
     test_server:
       url: "https://your-mcp-server/mcp"
       timeout: 60
       connect_timeout: 30
   ```
2. Run `hermes mcp test test_server` — should connect successfully
3. Previously: `'float' object has no attribute 'seconds'`

## Checklist

- [x] Commit messages follow Conventional Commits
- [x] Searched for existing PRs (no duplicates)
- [x] PR contains only related changes
- [x] Fix is minimal and targeted (4 lines changed)
- [x] No new dependencies added

### CODE REVIEW

**Comment by alt-glitch** [comment]
Duplicate of #49646 — same fix for #49629 (legacy/SSE HTTP MCP timeouts must be passed as timedelta, not float, in tools/mcp_tool.py). #49646 (by Tranquil-Flow) is the earliest open PR with this mechanism; #49648 is already marked a duplicate of it. (Note: this branch's diff also carries unrelated holographic-memory/skill files from an unclean base — only the tools/mcp_tool.py change matches the title.)

**Comment by lennney** [comment]
Closing in favor of #49646 (same fix, submitted earlier).
