### PR TITLE
feat(dashboard): select profile model and reasoning effort

### PR DESCRIPTION
**Pull request by Space-Hermes**
## What does this PR do?

This lets users choose a profile's main model, reasoning effort, and **fallback chain** directly from the dashboard Profiles page, and adds **per-model reasoning-effort levels** so the reasoning picker only shows the dial values a model actually accepts. Previously, those settings were handled through separate paths, and a reasoning-only save could rewrite model configuration unnecessarily; now one save updates only the selected profile and leaves unchanged model metadata intact.

## Related Issue

No single issue is closed by this PR. Related repository work is listed below.

## Type of Change

- [x] New feature (non-breaking change that adds functionality)
- [x] Tests (adding or improving test coverage)

## Changes Made

- Add a profile-scoped `PUT /api/profiles/{name}/settings` endpoint that persists model and reasoning effort in one config write.
- Keep the existing profile model-only and reasoning-only endpoints, routed through the shared persistence helper.
- Validate provider/model pairs and preserve existing model metadata when only reasoning effort changes.
- **Profile fallback chain**: `GET/PUT /api/profiles/{name}/fallbacks` persist an ordered fallback chain with per-entry reasoning policy, credential-preserving route matching (provider edits never inherit old secrets), and duplicate-route rejection. The editor supports add/remove/reorder plus a custom-endpoint readout.
- **Per-model reasoning levels**: `ProviderProfile.reasoning_effort_levels()` hook lets providers declare the exact Hermes effort levels each model accepts (`None` = unknown/full list, `[]` = no dial). `OpenCodeGoProfile` implements it: deepseek-v4-*/reasoner accept the full scale minus `ultra` (relay rejects it), kimi-k2* accept none+low/medium/high, glm-5.2 accepts none+high/max, and MiMo/Nemotron/other GLM get no reasoning params (dial hidden). `/api/model/info` and `/api/model/options` capabilities now carry `reasoning_levels`, and the dashboard ReasoningPicker (sidebar + ProfilesPage, including each fallback entry) filters options to the model's accepted levels and hides entirely when the model has no dial.
- Update the Profiles page to send model and reasoning changes together, including safe handling for unchanged or unlisted models.
- Add frontend API types and regression coverage for the combined payload, model-selection flow, fallback chain, and reasoning-level filtering.
- Add backend coverage for profile isolation, single-write behavior, context-length preservation, changed-model metadata clearing, invalid model pairs, fallback credential preservation, and per-model reasoning-level reporting.

## Related repository work

- [#25001](https://github.com/NousResearch/hermes-agent/pull/25001) — existing open PR for a per-profile model configuration popup. This is directly overlapping prior art, not a dependency. This PR keeps the current Profiles-page flow, adds reasoning-effort selection, and makes model + reasoning persistence a single scoped save; maintainer guidance on whether the two approaches should be combined or superseded is welcome.
- [#72861](https://github.com/NousResearch/hermes-agent/pull/72861) — preserves session-level `reasoning_effort` across runtime `/model` switches. That is a separate runtime path; this PR covers profile-level defaults edited from the dashboard.
- [#24493](https://github.com/NousResearch/hermes-agent/issues/24493) — discusses per-model `context_length` overlays. This PR does not implement overlays; it specifically ensures a reasoning-only profile save does not erase an existing `context_length` value.

## How to Test

Affected backend and frontend checks:

1. `python3 -m pytest -q tests/hermes_cli/test_opencode_go_reasoning_levels.py` — 6 passed.
2. `python3 -m pytest -q tests/hermes_cli/test_web_server.py` — 104 passed.
3. `npm --workspace web test` — 164 tests passed.
4. `npm --workspace web run typecheck` — passed.
5. `npm --workspace web run build` — passed.

## Known limitations

- This PR configures the profile's main model, reasoning effort, and fallback chain; auxiliary model slots remain managed elsewhere.
- Per-model reasoning levels are provider-known for OpenCode Go today; other providers fall back to the full option list until their profiles declare `reasoning_effort_levels()`.
- The repository-wide `npm run check` could not complete in this checkout because unrelated workspaces are missing their optional desktop/bootstrap/TUI dependencies (`@tauri-apps/*`, `@assistant-ui/*`, and `plist`). The affected `web` workspace checks above pass independently.

### Code

- [x] I've read the [Contributing Guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md)
- [x] My commit messages follow [Conventional Commits](https://www.conventionalcommits.org/)
- [x] I searched for existing PRs and linked the directly overlapping work above.
- [x] My PR contains only changes related to this feature.
- [x] I've added tests for the changed behavior.
- [x] I've tested on Linux.

### Documentation & Housekeeping

- [x] Relevant behavior is documented in the implementation and tests; no user-guide/config documentation is needed.
- [x] No new configuration keys were added.
- [x] Cross-platform impact was considered; the change uses existing Python/frontend APIs.

## Scope and review questions

Please review the overlap with [#25001](https://github.com/NousResearch/hermes-agent/pull/25001), especially whether profile model-option discovery should be unified with that PR's profile-auth-scoped picker implementation.

### CODE REVIEW

**Comment by teknium1** [comment]
Thanks for adding profile-level reasoning defaults and combining the profile save path.

### Problems
- The profile picker still loads one unscoped catalog: `web/src/pages/ProfilesPage.tsx:371-393` calls `api.getModelOptions()` without the profile under edit. Main already supports `api.getModelOptions(profile)` (`web/src/lib/api.ts:527-545`) and scopes the server-side picker through `_profile_scope(profile)` (`hermes_cli/web_server.py:6102-6139`). Editing a non-dashboard profile can therefore show the dashboard profile's available providers/models.

### Suggested changes
- Load model options for the target profile and add a two-profile isolation regression test.
- Salvage the backend route and payload work into the current extracted surfaces: `hermes_cli/web_routers/profiles.py` and `hermes_cli/web_models.py`. GitHub currently reports this PR as conflicting, and these definitions no longer live in the PR's original `web_server.py` locations.

Automated hermes-sweeper review.
