### ISSUE TITLE
[Bug]: non-default profile can keep stale runtime after update, causing ImportError

### ISSUE THREAD

**Issue by pepelaskov** [NousResearch/hermes-agent#56717]
### Summary

A non-default profile (`bruce`) appears to remain behind or keep running stale Hermes code even when the default profile reports "Up to date". This can lead to an import mismatch at runtime:

```text
error: cannot import name 'is_output_cap_error' from 'agent.model_metadata' (~/.hermes/hermes-agent/agent/model_metadata.py)
```

The current checkout does contain `is_output_cap_error`, and importing it directly succeeds, so this looks like a stale/mixed profile, gateway, dashboard, or virtualenv/runtime issue rather than the function being missing from the current source tree.

### Environment

- OS: macOS 26.5.1
- Hermes Agent: `v0.18.0 (2026.7.1)`
- Upstream commit: `4d5d9fff`
- Python: `3.11.15`
- OpenAI SDK: `2.24.0`
- Repo: `https://github.com/NousResearch/hermes-agent.git`

`hermes --version` and `hermes --profile default --version` both report:

```text
Hermes Agent v0.18.0 (2026.7.1) · upstream 4d5d9fff
Up to date
```

### Profile state

```text
Profile: bruce
Path:    ~/.hermes/profiles/bruce
Model:   gpt-5.5 (openai-codex)
Gateway: running
Skills:  50
.env:    exists
SOUL.md: exists
```

`hermes profile info bruce` reports:

```text
Profile 'bruce' is not a distribution (no distribution.yaml).
```

### Diagnostics

The current checkout contains the symbol:

```text
agent/model_metadata.py:
def is_output_cap_error(error_msg: str) -> bool:
    ...
```

Direct import from the checkout succeeds:

```text
from agent.model_metadata import is_output_cap_error
import_ok True
```

There are long-running Hermes processes for the non-default profile, including a dashboard process launched from the Hermes virtualenv and a profile-specific gateway process:

```text
~/.hermes/hermes-agent/venv/bin/hermes --profile bruce dashboard --isolated ...
python -m hermes_cli.main --profile bruce gateway run --replace
```

This suggests the profile/gateway/dashboard may continue using stale code after an update, while the default profile/version check reports current.

### Expected behavior

Updating Hermes should either:

1. Update/restart all profile-specific runtimes that use the shared checkout, or
2. Clearly warn that non-default profile gateways/dashboards are still running stale code and need to be restarted, or
3. Make `hermes update`/version checks profile-aware so a non-default profile cannot remain silently behind.

The non-default profile should not enter a mixed state where current modules import symbols from stale modules and fail on startup/runtime.

### Actual behavior

The default profile reports up to date, but the `bruce` profile appears to lag or continue running stale code and fails with:

```text
cannot import name 'is_output_cap_error' from 'agent.model_metadata'
```

### Related

Possibly related to stale update/banner behavior in #20728, but this issue includes an actual runtime import failure from a non-default profile/gateway/dashboard stale-code state.

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Related: this looks like the multi-profile side of #51336 (OPEN) — `hermes update`'s post-update restart only catches the default gateway unit, so a non-default profile's long-lived gateway/dashboard keeps serving pre-update code and hits an `ImportError` on a symbol added in the update. Keeping this open as the macOS-side report; #51336 broadens the restart glob for the systemd case.

**Comment by xiawiie** [comment]
Status update: this issue is still open, and #56723 is an open PR that addresses the dashboard side of the stale-runtime sweep.

I reviewed #56723 and opened #56745 as a draft follow-up built on top of that work. The goal is to keep the original fix intact while covering two adjacent edge cases from the same non-default-profile stale-runtime class:

- Dashboard/serve stale-process detection now strips profile selectors token-by-token, covering `--profile name`, `-p name`, `--profile=name`, and `-p=name` on both POSIX and Windows WMIC scan paths.
- Systemd gateway discovery now uses a shared `hermes*gateway*` glob so update-related restart/exclusion paths can see both `hermes-gateway.service` and profile-shaped units such as `hermes-secondbrain-gateway.service`.

Validation on the draft PR branch:

```text
scripts/run_tests.sh tests/hermes_cli/test_stale_dashboard_profile_detection.py tests/hermes_cli/test_gateway.py tests/hermes_cli/test_update_stale_dashboard.py tests/hermes_cli/test_dashboard_lifecycle_flags.py tests/test_windows_subprocess_no_window_flags.py -q
# 106 tests passed, 0 failed

uv run --frozen --extra dev ruff check hermes_cli/main.py hermes_cli/gateway.py tests/hermes_cli/test_stale_dashboard_profile_detection.py tests/hermes_cli/test_gateway.py tests/test_windows_subprocess_no_window_flags.py
# All checks passed
```

I left #56745 as a draft because it intentionally builds on #56723, and I am happy to adapt it based on maintainer preference.

**Comment by sene1337** [comment]
Fresh multi-profile reproduction on macOS 26.5.1 using a shared Hermes checkout and separate launchd gateways.

We observed this twice with different late-import symbols:

```text
2026-07-05:
cannot import name '_is_hermes_internal_secret'
from 'tools.environments.local'

2026-07-11:
cannot import name 'skill_matches_platform_list'
from 'agent.skill_utils'
```

In both cases, the referenced symbol existed in the current checkout and succeeded in a fresh out-of-process import. Restarting the affected named-profile gateway resolved the runtime failure.

The failure mechanism matches this issue: a long-lived named-profile gateway retains previously imported modules while later imports read modules from the newly updated shared checkout, producing a mixed old-memory/new-disk module graph.

Current local checkout: `5e849942c3b9d36fdd48c80e9d13cb66212d9731`.

This affected both interactive Telegram handling and a profile-owned cron job. The latter is important because the gateway can appear connected and the cron ticker can still be running while agent startup fails on a late import.

Suggested acceptance criteria for the fix:

- restart every running named-profile gateway using the updated shared checkout;
- do not start intentionally stopped profiles;
- verify a new PID/process start time per affected gateway;
- run a clean out-of-process import/tool-startup smoke after restart;
- do not report update completion while an affected gateway remains on the old runtime.

**Comment by Budoman** [comment]
Confirming this on **macOS (launchd-managed gateways, multi-profile), on a direct upstream checkout with no local source modifications**, after `hermes update` to a revision that added a new importable symbol. This may help decide the "virtualenv/runtime vs missing symbol" question in this issue.

### Symptom
Every **non-default profile** gateway fails on its next agent turn with:

```
ImportError: cannot import name 'hermes_home_key' from 'hermes_constants'
```

via `run_agent.py` → `tools/browser_tool.py` (`from hermes_constants import …, hermes_home_key`). The **default/invoking profile is unaffected** (its turn path does not import `browser_tool`), which lines up with #73625.

The current source is correct — a fresh `./venv/bin/python -c "import hermes_constants, tools.browser_tool"` from the install **succeeds**. So this is a stale runtime/bytecode problem, not a symbol missing from source.

### The existing mitigation did not prevent it
The update's built-in bytecode handling clearly ran — `_clear_bytecode_cache(PROJECT_ROOT)` (both sweeps) and `_reload_updated_runtime_modules()` (`importlib.invalidate_caches()` + `importlib.reload()`) — yet the sibling gateways still came up serving stale code. A **full manual gateway restart on its own also did not fix it.** Only a complete bytecode wipe **plus** restart resolved it.

### Workaround
```bash
find "$HOME/.hermes/hermes-agent" -path '*/venv/*' -prune -o -name __pycache__ -type d -exec rm -rf {} +
# then restart each profile gateway, e.g. launchctl kickstart -k gui/$(id -u)/ai.hermes.gateway-<profile>
```

### Breadcrumbs toward root cause (hypothesis, not confirmed)
Since the built-in clear+reload already runs, the interesting question is *why it is defeated here*. One avenue that looks worth checking in `update_cmd.py`: the clear/reload steps execute **before** the launchd sibling-profile restart, and `_reload_updated_runtime_modules()` reloads modules in the still-running *pre-update* interpreter (which regenerates `.pyc`). So bytecode written or left after the **final** `_clear_bytecode_cache` may not be re-cleared before the sibling gateways are restarted, leaving those gateways to start against a mixed on-disk cache. A cheap belt-and-suspenders would be a final `_clear_bytecode_cache(PROJECT_ROOT)` + `importlib.invalidate_caches()` as the **last** step immediately before the gateway-restart block (after reload and dependency install). Flagging as a hypothesis for someone who knows the update flow to confirm.

Related: #73625 (macOS sibling-profile restart coverage), #85753 (macOS autostash prompt stalling the post-update restart).

Environment: macOS 15, launchd-supervised gateways, direct upstream checkout, no local source modifications.

**Comment by AlexMnrs** [comment]
### Additional Windows/cron evidence (with caveat)

Environment: Windows 11 25H2, non-default `research` profile, gateway-backed cron.

On 2026-08-14, the cron job `Radar HN — descubrimiento` failed before its collector ran with:

```text
cannot import name `_canonical_file_mutation_path` from `agent.tool_dispatch_helpers`
```

The symbol existed in the on-disk checkout, and a fresh out-of-process import succeeded. The gateway had started before local uncommitted changes to `run_agent.py` and `agent/tool_dispatch_helpers.py`, so this is not a clean released-update reproduction; it is a mixed old-in-memory/new-on-disk module graph after runtime files changed while the gateway remained alive.

Running the collector directly succeeded. Restarting only the `research` gateway was the remediation; the next scheduled run was left as the end-to-end validation. This adds a Windows + cron example to the stale-runtime/import-mismatch class, while making the local-checkout caveat explicit.

**Comment by tjwill1965** [comment]
Reproduced this on Linux with the `researcher` profile after updating to v0.21.2 (upstream d595e636).

**Environment:**
- OS: Ubuntu (kernel 7.0.0-31-generic)
- Hermes Agent: v0.21.2 (2026.9.11), git install
- Python: 3.11.15
- Profile: `researcher` (non-default)
- Gateway: photon (iMessage) sidecar

**What happened:**
After `hermes update`, the gateway stayed running and outbound messages worked fine. But every inbound iMessage crashed the gateway child process (`run_agent.py`) with:

```
ImportError: cannot import name 'request_yield' from 'tools.interrupt'
```

A second import failure also appeared:

```
cannot import name 'STEER_DISPLAY_KIND' from 'agent.prompt_builder'
```

The user-facing symptom on the messaging platform was: "Sorry, I encountered an unexpected error. Try again or use /reset to start a fresh session." — which was particularly confusing because `/reset` and `/new` appeared to work (they're handled by the gateway process itself, not the child).

**Root cause:**
Stale `.pyc` files in `~/.hermes/hermes-agent/` `__pycache__` directories. The source files had the new symbols (`request_yield` at line 66 of `tools/interrupt.py`, `STEER_DISPLAY_KIND` at line 519 of `agent/prompt_builder.py`), but the cached bytecode predated the update. The running gateway process had the correct code in memory, but each inbound message spawned a fresh child that loaded the stale cache.

**Fix that worked:**
```bash
find ~/.hermes/hermes-agent -type d -name "__pycache__" -exec rm -rf {} +
systemctl --user restart hermes-gateway
```

**Why the update sweep didn't catch it:**
`_clear_bytecode_cache(PROJECT_ROOT)` in `hermes_cli/main.py` walks the source tree but the stale `.pyc` files survived the sweep (possibly regenerated by a post-sweep import, as the code comments at `update_cmd_deps.py:1046` acknowledge: "stale bytecode self-heals next launch"). The self-healing assumption doesn't hold for gateway child processes — they reload from cache on every inbound message, so the stale bytecode persists indefinitely until manually cleared.

The "self-heals next launch" comment is the key gap: a gateway that's already running doesn't relaunch. Its child processes keep loading the same stale cache on every message, for hours or days, until someone manually restarts.
