### ISSUE TITLE
[Bug]: `hermes --tui` fails to build on main — TS2322 in ops.ts /reload-mcp params

### ISSUE THREAD

**Issue by Heltman** [NousResearch/hermes-agent#17773]
## Summary

On `main` (current HEAD `828d3a320`, after `4d7fc0f37`), `hermes --tui` fails to build out of the box with a TypeScript error. First invocation on a fresh install dies during the auto-build step:

```
❯ hermes --tui
Installing TUI dependencies…
TUI build failed.
> hermes-tui@0.0.1 build
> npm run build --prefix packages/hermes-ink && tsc -p tsconfig.build.json && npm run build:compile && chmod +x dist/entry.js

> @hermes/ink@0.0.1 build
> esbuild src/entry-exports.ts --bundle --platform=node --format=esm --packages=external --outfile=dist/ink-bundle.js

src/app/slash/commands/ops.ts(86,9): error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

  dist/ink-bundle.js  416.8kb

⚡ Done in 21ms
```

`dist/entry.js` is never produced → subsequent `hermes --tui` attempts re-run `npm run build` and fail the same way. TUI is effectively unusable on current `main`.

## Environment

- hermes-agent `main` @ 828d3a320 (PR context)
- macOS 14, Node v22.22.2, npm 11.6.4
- Clean `node_modules` (post `npm install`)

## Root cause

`ui-tui/src/app/slash/commands/ops.ts` (introduced in 4d7fc0f37):

```ts
const params: { session_id: string; confirm?: boolean; always?: boolean } = {
  session_id: ctx.sid
}
```

But in `ui-tui/src/app/slash/types.ts`:

```ts
sid: null | string
```

Every other slash command that forwards `ctx.sid` — `prompt.background`, `config.set`, `session.compress`, `session.branch`, `image.attach` in `session.ts` — just passes it through without type-narrowing; the gateway already handles a null session_id. `ops.ts` is the outlier that declares the narrower `string`, so strict TS rejects the assignment.

## Fix

Widen the param type to `string | null` to match the rest of the codebase and the actual `ctx.sid` type. PR: **#NNN** *(replace with link)*.

## Regression

Introduced in `4d7fc0f37` — `feat(gateway,cli): confirm /reload-mcp to warn about prompt cache invalidation`.

Probably slipped through because the TUI dev loop (`npm run dev` → `tsx --watch`) doesn't run `tsc -p tsconfig.build.json`, so the stricter build-time typecheck never fires until end users hit `hermes --tui`'s on-demand build path.

**Comment by Heltman** [comment]
PR: #

**Comment by flo-hermes** [comment]
## Additional reproduction: triggered by `hermes update`

Same TS2322 error reproduced on a different environment during `hermes update`:

```
$ hermes update
→ Fetching updates...
→ Found 34 new commit(s)
→ Pulling updates...
→ Restoring local changes...
→ Updating Python dependencies...  (fails — see #17795)
✗ Update failed

$ hermes chat --tui
Installing TUI dependencies…
TUI build failed.
> hermes-tui@0.0.1 build
> npm run build --prefix packages/hermes-ink && tsc -p tsconfig.build.json && npm run build:compile && chmod +x dist/entry.js

> @hermes/ink@0.0.1 build
> esbuild src/entry-exports.ts --bundle --platform=node --format=esm --packages=external --outfile=dist/ink-bundle.js

src/app/slash/commands/ops.ts(86,9): error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

  dist/ink-bundle.js  416.8kb

⚡ Done in 131ms
```

This is notable because:

1. **The TUI build failure compounds the update failure** — even if the Python deps issue is worked around, the TUI is broken until the TS error is fixed, making `hermes --tui` completely unusable on `main` after an update.

2. **Environment**: Linux, hermes-agent git-installed, updated from `v2026.4.23-1068-gcdcb27c74` pulling 34 commits including `4d7fc0f37`.

3. **Local workaround** for the null-safety issue (adding `if (!ctx.sid) return` guard before the param assignment) was stashed and restored during update — but the TS rebuild runs on the full codebase so any upstream null-safety gap still triggers the build error.

**Comment by teknium1** [comment]
Fixed on `main` in #17836 (`fd0796947`) — same one-line TS widen @Heltman also proposed in #17774. Both were merged/closed in quick succession. Thanks to everyone who triaged this.
