### PR TITLE
test(interrupt-propagation): seed provider attr on bare agent to match __init__

### PR DESCRIPTION
**Pull request by briandevans**
## TL;DR

Same class of bug as my landed #12574 — a test stub that uses `AIAgent.__new__(AIAgent)` skips `__init__` and therefore misses `self.provider`. The full `tests/` suite under pytest-xdist intermittently hits a code path that reads `self.provider` directly (without `getattr`), causing `AttributeError: 'AIAgent' object has no attribute 'provider'`.

Test-only change. Zero production-code touched.

## Symptom

From the Tests run on #12889 ([24655153236](https://github.com/NousResearch/hermes-agent/actions/runs/24655153236)):

```
FAILED tests/run_agent/test_interrupt_propagation.py::TestInterruptPropagationToChild::test_interrupt_during_child_api_call_detected
- AttributeError: 'AIAgent' object has no attribute 'provider'
```

Appears on every recent PR's Tests job under `-n auto`; passes in isolation and under most narrower invocations.

## Root cause

`AIAgent.__init__` sets `self.provider` at `run_agent.py:736`. The bare-agent helper in this test file bypasses `__init__`:

```python
def _make_bare_agent(self):
    from run_agent import AIAgent
    agent = AIAgent.__new__(AIAgent)
    agent._interrupt_requested = False
    # … other interrupt-related attrs …
    # provider is NOT set
    return agent
```

`test_interrupt_during_child_api_call_detected` sets `child.client = MagicMock()` expecting the Mock fast-path in `_create_request_openai_client` to short-circuit:

```python
# run_agent.py:4921
if isinstance(primary_client, Mock):
    return primary_client  # short-circuit
```

Under pytest-xdist worker-import ordering, the short-circuit doesn't always engage, and the code reaches `_create_openai_client` at `run_agent.py:4660`/`4671`:

```python
if self.provider == "copilot-acp" or ...:   # direct access — no getattr
if self.provider == "google-gemini-cli" or ...:
```

→ `AttributeError`.

## Fix

Seed `agent.provider = ""` in `_make_bare_agent`, matching what `__init__` would produce:

```python
# AIAgent.__init__ sets ``provider`` (run_agent.py:736).  The
# client-creation path at ``_create_openai_client`` (run_agent.py:4660, 4671)
# accesses ``self.provider`` directly — not via ``getattr`` — so a bare agent
# built with ``__new__`` that reaches that path raises AttributeError.
# Seed the attribute defensively so these interrupt tests don't depend on
# worker-import ordering.
agent.provider = ""
```

## Narrow scope — explicitly not changed

* **No production-code change.** The `self.provider` accesses in `_create_openai_client` are correct for the real call path (real agents always have `provider` set by `__init__`); the test harness just needs to mirror that invariant.
* **No other bare-agent attributes added.** Only the one the reported failure references, same as the #12574 precedent. If a future refactor adds another missing attr it can be a separate follow-up.
* **No change to `_make_bare_agent`'s intent** — it's still a bare stub wiring only what interrupt tests need.

## Validation

```bash
source venv/bin/activate
python -m pytest tests/run_agent/test_interrupt_propagation.py -q
# 7 passed
```

Broader `tests/run_agent/` under `-n auto` → **781 passed, 7 skipped, 0 new failures**. The 2 `test_concurrent_interrupt` failures that remain are the separately-tracked baseline handled by **#12574** (landed as `1cf10b45`).

## Related

Same surgical pattern as **#12574** (landed — `_Stub` in `test_concurrent_interrupt.py` missing `_apply_pending_steer_to_tool_results`). Each time a prod refactor adds a new attribute or method read unconditionally along a path the test stub reaches, the bare-stub test harness drifts and needs a one-line seed. Each fix is test-only and reduces the baseline-flake set that blocks every contributor's CI.

---

<sub>Co-authored via LLM assistance; I've reviewed every line and am responsible for correctness.</sub>

### CODE REVIEW

**Comment by briandevans** [comment]
Self-correction: my initial commit only seeded `provider`. The follow-up CI run ([24655838688](https://github.com/NousResearch/hermes-agent/actions/runs/24655838688)) showed the same test now tripping on `self.model`:

```
FAILED test_interrupt_during_child_api_call_detected
- AttributeError: 'AIAgent' object has no attribute 'model'
```

Hit pattern #8 from my pre-push self-review checklist ("fixed one call site, missed sibling with same pattern"). `_create_openai_client` reads `self.provider`, `self.model`, AND `self.base_url` directly — any of the three can surface as its own AttributeError when the mocked-client short-circuit doesn't engage (apparently the case under xdist here).

Pushed `4725a861` which seeds all three core `AIAgent.__init__` identity attrs defensively. 7 focused tests still pass. Zero production change.

Baseline-failure classification for the Tests job is unchanged (same 4 pre-existing xdist flakes; `test_interrupt_propagation` now fixed by this PR, the others covered by separate PRs or still baseline).

**Comment by briandevans** [comment]
CI on `4725a861` ([24656377417](https://github.com/NousResearch/hermes-agent/actions/runs/24656377417)):

✅ **`test_interrupt_propagation::test_interrupt_during_child_api_call_detected` now passes in CI** — the trio-seed (`provider` + `model` + `base_url`) closed the remaining AttributeError path.

Remaining failures on this run (3, down from 4 on the initial push) are all standing baselines that pre-exist this PR and reproduce on clean `origin/main`:

- `test_gemini_provider.py::test_provider_models_exist` — catalog drift (`gemini-2.5-pro` dropped from curated list)
- 2× `test_modal_sandbox_fixes.py::TestToolResolution` — xdist worker-import ordering (the exact same flake pattern as the other baseline failures I've audited across the repo)

None touch `test_interrupt_propagation.py` or anything this PR changes.

**Comment by briandevans** [comment]
**Supply-chain `FAILURE` on this PR is a false positive from a scan bug, not a real finding.** Opened **#13411** with a root-cause analysis and a one-character fix.

Quick version: `.github/workflows/supply-chain-audit.yml` computes the PR diff with `git diff "$BASE".."$HEAD"` (two-dot) which includes every file main has drifted through since the PR was forked. On this PR, that adds `hermes_cli/setup.py` (modified upstream, not by this PR) to the scan's file list, which trips the install-hook check. The 3-dot merge-base diff shows only this PR's actual 2 files (neither of which matches any attack pattern).

Was masked pre-`19db7fa3` because that commit changed the fail condition from `critical == 'true'` to `found == 'true'`, unmasking the pre-existing 2-dot bug.

**Comment by briandevans** [comment]
Closing as superseded — all three attrs this PR seeded (`provider`, `model`, `_base_url`) are now set on the bare-agent fixture upstream via `62cbeb63` (#13363 "test: stop testing mutable data"). Current `origin/main` `tests/run_agent/test_interrupt_propagation.py`:

```python
agent.provider = "openrouter"
agent.model = "test/model"
agent._base_url = "http://localhost:1234"
```

Exactly the trio this PR proposed. Clean landing via the broader test-robustness sweep — closing to keep the queue tidy.
