### PR TITLE
fix(tests): repair three test-isolation leaks in tests/gateway

### PR DESCRIPTION
**Pull request by Labsmates**
## What does this PR do?

Fixes three independent test-isolation bugs in `tests/gateway/`. Each of the six affected tests passes on its own and fails in a full `pytest tests/gateway/` run, so the failures look flaky while the causes are deterministic — each is one test leaving global state behind for the next.

**1. `test_discord_imports` leaks a discord-less adapter module.**

The test simulates a missing `discord.py` and re-imports `plugins.platforms.discord.adapter` so the module body runs with the dependency unavailable. That import caches the resulting copy under the real module name and rebinds it on the parent package. `monkeypatch.delitem` only restores what was cached on entry, so when the adapter had not been imported yet, nothing was restored and the broken copy survived for the rest of the process.

Four tests died on `AttributeError: None has no attribute 'File'` as a result:

- `test_discord_send.py::test_send_video_uses_path_based_files_kwarg`
- `test_discord_send.py::test_send_video_fails_loud_when_message_has_no_attachments`
- `test_discord_send.py::test_send_file_attachment_forum_uses_files_kwarg`
- `test_send_multiple_images.py::TestDiscordMultiImage::test_url_batch_follows_safe_redirect_location_header`

The fix snapshots the cached module objects and the parent-package attribute on entry and puts them back at the end. Restoring the original objects rather than re-importing matters: fixtures built from the old module object keep patching the same one the code under test uses. (Re-importing instead makes `test_url_batch_follows_safe_redirect_location_header` fail, because its `adapter` fixture then patches a different module object than the one running.)

**2. `test_subsequent_progress_is_silent` reads records from before its `at_level` block.**

The test primes `_record_polling_progress` once outside the block — the call that is *meant* to log — then asserts no `confirmed healthy` record was captured for the two calls inside it. But `caplog` collects for the whole test, so the priming call is captured as soon as any earlier test leaves the `plugins.platforms.telegram.adapter` logger at INFO, and the assertion fails on a record the test itself provoked. A `caplog.clear()` after the priming call scopes the assertion to the calls under test.

**3. `test_session_store_default_db_uses_runtime_hermes_home` never reaches the branch it is named after.**

The test sets `HERMES_HOME` and expects `SessionDB` to resolve its default path from it. `_default_db_path()` gives precedence to a re-pointed `DEFAULT_DB_PATH`, and the hermetic conftest re-points that constant at its own sandbox — so the first branch always wins and the assertion compares the sandbox path against the fixture path. Restoring the import-time value for the duration of the test makes the runtime lookup reachable. `HERMES_HOME` still points at the `tmp_path` fixture, so no real `state.db` is touched.

## Related Issue

No issue filed. On the third commit: #94004 and #50695 both work on the production side of this default-path resolution. This change is test-only and touches no `hermes_state.py`, so it should not conflict with either.

## Type of Change

- [x] ✅ Tests (adding or improving test coverage)
- [x] 🐛 Bug fix (non-breaking change that fixes an issue)

## Changes Made

- `tests/gateway/test_discord_imports.py` — snapshot and restore `sys.modules` entries and the parent-package attribute around the simulated-missing-dependency import
- `tests/gateway/test_telegram_polling_health_confirmation.py` — `caplog.clear()` after the priming call
- `tests/gateway/test_session_store_prune.py` — restore the import-time `DEFAULT_DB_PATH` so the `HERMES_HOME` fallback is exercised

No production code is touched.

## How to Test

1. Reproduce the leak in isolation:
   `pytest tests/gateway/test_discord_imports.py tests/gateway/test_discord_send.py -q`
   — 3 failed before, 12 passed after.
2. Same for the caplog bleed, which needs a run where something leaves the logger at INFO:
   `pytest tests/gateway/ -q` — `test_subsequent_progress_is_silent` failed before, passes after.
3. Full suite: `pytest tests/gateway/ -q` — **6228 passed, 29 skipped, 1 xfailed, 0 failed** (was 6 failed).

### Code

- [x] I've read the Contributing Guide
- [x] My commit messages follow Conventional Commits
- [x] I searched for existing PRs to make sure this isn't a duplicate
- [x] My PR contains **only** changes related to this fix (three test files, one commit each)
- [ ] I've run `pytest tests/ -q` and all tests pass — I ran `pytest tests/gateway/ -q` (6228 passed, 0 failed), which covers every test involved. The full `tests/` suite was not run.
- [x] I've added tests for my changes — N/A, this repairs existing tests
- [x] I've tested on my platform: Debian 13 (trixie), Python 3.11.15

### Documentation & Housekeeping

- [x] I've updated relevant documentation — N/A
- [x] I've updated `cli-config.yaml.example` if I added/changed config keys — N/A
- [x] I've updated `CONTRIBUTING.md` or `AGENTS.md` — N/A
- [x] I've considered cross-platform impact — the fixes are platform-independent (`sys.modules` bookkeeping, caplog scoping, a module constant); only tested on Linux
- [x] I've updated tool descriptions/schemas — N/A

### CODE REVIEW

**Comment by Enough1122** [comment]
> AI code review — automated review for reference, author can ignore or act on any point.

Overall: three genuine test-isolation fixes, each correctly diagnosed (module-cache rebinding on the parent package, conftest's re-pointed `DEFAULT_DB_PATH` shadowing the runtime lookup — `_IMPORT_DEFAULT_DB_PATH` does exist at `hermes_state.py:389`, and caplog's whole-test accumulation). One ordering issue:

1. **Restore code runs after the assertions it protects** — `tests/gateway/test_discord_imports.py`: the snapshot-restore block sits *below* `assert module.DISCORD_AVAILABLE is False` / `assert module.discord is None`. If either assertion fails, the function exits with the polluted state still installed — every subsequent test in the session then sees the discord-less adapter, producing confusing cascading failures that mask the real one. Move the restoration into a `try/finally` (or register it via `request.addfinalizer` right after taking the snapshot) so cleanup is unconditional regardless of test outcome.

2. Minor: in the same test, consider restoring inside `finally` even for the `saved_parent_attr` branch — same reasoning; `delattr`/reassign of `platforms_pkg.discord` currently only happens on the success path.
3. Nit: `caplog.clear()` placement is correct here, but worth one more comment noting it must stay *after* the first `_record_polling_progress(1)` call that seeds the "first poll logs" behavior — someone reordering those lines would silently break the silence assertions.
4. The comment quality across all three fixes is excellent — each explains which layer (conftest, import machinery, pytest) caused the coupling, which is exactly what future debuggers need.
