### PR TITLE
fix(cli): parse provider:model syntax in both -m/--model (interactive) and -z/--oneshot

### PR DESCRIPTION
**Pull request by ygd58**
## Context

Follow-up per @teknium1's review. This PR's scope has expanded: it originally only covered the oneshot path and claimed to supersede #74214, but #74214 was closed without merging -- so the interactive `HermesCLI` (`-m/--model`) fix it contained was never actually applied to main. This PR now carries BOTH fixes.

## Problems fixed

1. **Test fixture breakage.** The new `parse_model_input` import in `oneshot.py` broke an existing isolated-module test fixture in `test_tui_resume_flow.py` (CI failure: `ImportError: cannot import name 'parse_model_input'`). Fixed by adding the missing stub.
2. **Interactive path never actually fixed.** `cli.py`'s `HermesCLI.__init__` still forwarded a compound `-m` value unsplit. Carried the original interactive-path fix forward from the pre-split branch, along with its regression tests.

## Verification

6/6 pass in the new interactive-path test class; 27/27 across all four affected/related test files (no regression). The previously CI-failing `test_oneshot_wires_session_db_for_recall` now passes.

### CODE REVIEW

File: hermes_cli/oneshot.py [hunk 1]
```diff
@@ -339,6 +339,27 @@ def _run_agent(
...
+    # compound string straight through detect_provider_for_model() /
+    # resolve_runtime_provider() unsplit -- so `hermes -z -m
+    # "custom:local-vllm:my-model" "prompt"` silently sent the prompt to
+    # the default provider instead of the named local endpoint (review of
+    # #74214, sibling gap to the HermesCLI fix). Only applies when
+    # --provider wasn't explicitly passed, matching that fix's precedence
+    # rule (an explicit --provider flag still wins).
+    _oneshot_provider_override: Optional[str] = None
+    if not (provider or "").strip() and effective_model:
+        from hermes_cli.models import parse_model_input
```
Comment (teknium1) [inline hermes_cli/oneshot.py:356]: This import breaks the existing isolated-module fixture in `tests/hermes_cli/test_tui_resume_flow.py:188-190`, which supplies only `detect_provider_for_model`. Merge CI fails that test with `ImportError`; update the fixture to provide `parse_model_input` (or retain the real models module).

**Review by teknium1 — COMMENTED** [review]
Thanks for tracing the separate oneshot entry point; the current-head premise is valid: `hermes_cli/oneshot.py:340-387` forwards a compound model without `parse_model_input()`.

### Problems
- The new import at `hermes_cli/oneshot.py:356` breaks the existing isolated-module fixture in `tests/hermes_cli/test_tui_resume_flow.py:188-190`. The PR merge CI fails `test_oneshot_wires_session_db_for_recall` with `ImportError: cannot import name 'parse_model_input'`.
- This PR says it supersedes #74214, but that PR is closed unmerged. Current `cli.py:4356` retains the raw `-m` value and `cli.py:4397-4403` derives the provider without parsing it, so the interactive sibling remains unfixed.

### Suggested changes
- Make the existing fixture expose `parse_model_input`, then rerun the affected test slice.
- Carry the focused interactive `-m/--model` patch and regression coverage from #74214 into this salvage, or revise the scope/claim accordingly.

Automated hermes-sweeper review.

**Comment by ygd58** [comment]
Both confirmed and fixed.

1. Added parse_model_input to the isolated-module stub in test_tui_resume_flow.py (a safe passthrough matching that tests plain model name with no provider prefix). test_oneshot_wires_session_db_for_recall now passes.
2. Youre right that the supersedes claim was wrong -- #74214 closed unmerged, so the interactive HermesCLI (-m/--model) fix was never actually on main. Carried the original interactive-path fix and its regression test class forward from the pre-split branch into this PR, so it now covers both the interactive and oneshot paths in one place. Updated the PR title/description to reflect this.

6/6 pass in the new interactive-path test class; 27/27 across all four affected/related test files.

**Comment by kshitijk4poor** [comment]
Closing — the fix for #73943 landed via #115293 (merge b2d2cf4e24). Between your PR and now the provider/model decoding in `HermesCLI.__init__` and oneshot moved into `hermes_cli.model_switch.resolve_startup_model_route`, so the landed fix is at that single owner (which also serves the TUI entry path) rather than in `cli.py`/`oneshot.py`; both surfaces you covered here are covered there. Credit went to @Drexuxux (#74082, first submitter, 2026-07-29); your #74214 and this PR reached the same both-paths diagnosis and are cited in the PR body. Thank you.
