### PR TITLE
fix: handle None metadata in skill frontmatter to prevent crash

### PR DESCRIPTION
**Pull request by 0xbyt4**
## Summary

`build_skills_system_prompt()` crashes with `AttributeError: 'NoneType' object has no attribute 'get'` when a SKILL.md file has `metadata:` with no value (YAML null).

```python
# Old (crashes when metadata value is None):
hermes_meta = frontmatter.get("metadata", {}).get("hermes", {})

# Fixed (handles both missing key and null value):
hermes_meta = (frontmatter.get("metadata") or {}).get("hermes") or {}
```

`dict.get(key, default)` only returns default when key is **missing**. When key exists with value `None`, it returns `None` — so the chained `.get()` fails.

Introduced in 20cc1731 (perf: avoid redundant file re-read for skill conditions).

## Test plan

- [x] Verified: `metadata: None` no longer crashes
- [x] Verified: normal metadata still works
- [x] Verified: missing metadata key returns `{}`
- [x] `tests/agent/test_prompt_builder.py` — 95/96 passed (1 pre-existing env-dependent failure)

### CODE REVIEW

**Comment by teknium1** [comment]
Already fixed on main — commit d218cf91 (March 25) applied the exact same fix, and it was further refactored in 5127567d which extracted the logic into `extract_skill_conditions()` in `agent/skill_utils.py`. The vulnerable line no longer exists in `prompt_builder.py`. Thanks for catching the same issue though!
