### ISSUE TITLE
Matrix: send_voice() missing **kwargs - [MEDIA:] audio delivery fails with TypeError

### ISSUE THREAD

**Issue by arminmarth** [NousResearch/hermes-agent#114134]
## Bug

`[MEDIA:]`-tagged audio (and TTS voice delivery) fails on the Matrix adapter with:

```
WARNING gateway.platforms.base: [Matrix] Error sending media: MatrixAdapter.send_voice() got an unexpected keyword argument 'is_voice'
```

## Cause

The base-class media dispatcher (`gateway/platforms/base.py`, ~line 2753 and `_send_one` at ~3734) calls `send_voice(..., is_voice=is_voice)`. Every platform adapter accepts `**kwargs` except the Matrix plugin adapter (`plugins/platforms/matrix/adapter.py`, line 1558), whose signature is:

```python
async def send_voice(self, chat_id, audio_path, caption=None, reply_to=None, metadata=None) -> SendResult:
```

The `is_voice=True` kwarg raises `TypeError`, the send aborts, and no fallback notice is delivered — the user just never sees the attachment.

## Fix

Add `**kwargs` to the Matrix adapter's `send_voice()` signature (matching signal.py, whatsapp_cloud.py, qqbot, bluebubbles, etc.):

```python
async def send_voice(self, chat_id: str, audio_path: str, caption: Optional[str] = None,
                     reply_to: Optional[str] = None, metadata: Optional[Dict[str, Any]] = None,
                     **kwargs) -> SendResult:
```

## Environment

- Hermes v0.19.1, official Docker image (install_method: docker, build ecfcbb62762a)
- Platform: Matrix (self-hosted Synapse)
- Note: `_send_one` also passes `is_voice` to the other media methods, so `send_document`/`send_video` on the same adapter may need the same treatment if they lack kwargs.

**Comment by KeyArgo** [comment]
Confirmed the mechanism in this report against current `main` (98f758ae7e8), driving the real dispatcher rather than reasoning from the signature: `gateway/platforms/base.py` `_send_one` (~L3953) calls `send_voice(chat_id=..., audio_path=..., metadata=..., is_voice=is_voice)`, `MatrixAdapter.send_voice` (`plugins/platforms/matrix/adapter.py:1596`) accepts no `**kwargs`, so the call raises before any upload and the loop's `except` logs the exact warning quoted here:

```
[Matrix] Error sending media: MatrixAdapter.send_voice() got an unexpected keyword argument 'is_voice'
  dispatch result: success=False -> attachment silently dropped
```

A sweep of every `send_voice` override in-tree finds four without `**kwargs` tolerance — Matrix, Mattermost, LINE and Weixin — so the note at the end of the report is right: this is a class, not a one-off.

This is already carried, so nothing new is needed here: the broadest open PR is #113952 (Matrix + Mattermost + LINE + weixin, with a regression test), and Matrix-only variants are open as #107289, #104248, #100679 and #99712. Two earlier PRs proposing the same one-line relaxations (#102344, #100287) were closed as duplicates. I verified #113952's RED/GREEN independently on current `main` — all four adapters go from `success=False` (TypeError) to `success=True` — and posted the receipts there.

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #102221 — same Matrix send_voice is_voice TypeError and dropped audio; #113952 is the open union repair.

**Comment by teknium1** [comment]
Thanks @arminmarth — confirmed on current `main`: `plugins/platforms/matrix/adapter.py:1596` `send_voice()` still takes no `**kwargs`, so the `is_voice=` keyword from `gateway/platforms/base.py::_send_one` raises at argument binding and the attachment is logged as `Error sending media` and dropped. Your closing note is right that it is a class: Mattermost (:313), LINE (:820) and Weixin (`gateway/platforms/weixin.py:1115`) have the same gap.

This is the same defect as #102221 (Matrix voice delivery broken in v0.21.0). Closing as a duplicate; open PR #113952 is the union repair for all four adapters with a regression test and is linked there.
