### PR TITLE
fix(bedrock): guard against null url in image_url parts and lifecycle status (#55686)

### LINKED ISSUE #55686: Bedrock Converse conversion crashes (AttributeError) on an image_url part with a null url
### What happens

When the active provider is Bedrock and a user message carries an image part whose `url` is null (or a non-string), converting the message to the Converse format crashes with `AttributeError: 'NoneType' object has no attribute 'startswith'`. The exception aborts conversion of the entire message, so the turn errors out.

### Where

`agent/bedrock_adapter.py`, in `_convert_content_to_converse`:

```python
elif part_type == "image_url":
    image_url = part.get("image_url", {})
    url = image_url.get("url", "") if isinstance(image_url, dict) else ""
    if url.startswith("data:"):
        ...
```

`image_url.get("url", "")` only falls back to `""` when the `url` key is absent. If the key is present with value `None`, `url` is `None`, and `url.startswith("data:")` raises.

### Reproduction

```python
from agent.bedrock_adapter import _convert_content_to_converse

_convert_content_to_converse([
    {"type": "text", "text": "look"},
    {"type": "image_url", "image_url": {"url": None}},
])
# AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Expected

A null/non-string url should be tolerated (the unusable image skipped), not crash the conversion. The Gemini converter (`_extract_multimodal_parts`, `((item.get("image_url") or {}).get("url") or "")`) and the Codex converter (`if not isinstance(url, str) or not url: continue`) already handle this shape; the Bedrock converter is the one that crashes.

A fix with regression tests is in #55685.

### PR DESCRIPTION
**Pull request by AlexFucuson9**
## Summary

Prevent `AttributeError` crash when Bedrock Converse encounters an `image_url` part with a null `url` field, or a model lifecycle entry with a null `status`.

## Problem

Two `.get(key, "")` patterns crash when the key exists with value `None`:

1. **`image_url.get("url", "")`** returns `None` (not `""`) when `url` is explicitly null → `url.startswith("data:")` raises `AttributeError: 'NoneType' object has no attribute 'startswith'`

2. **`lifecycle.get("status", "").upper()`** returns `None` when `status` is null → `.upper()` raises `AttributeError`

The `dict.get(key, default)` default only applies when the key is **absent**, not when it is present with value `None`.

## Fix

Use `(x.get("key") or "")` which coalesces both absent-key and None-value to empty string:
- `image_url.get("url") or ""` — null URL parts are safely skipped (empty string doesn't match `data:` prefix)
- `lifecycle.get("status") or ""` — null status is treated as non-ACTIVE (model skipped)

Fixes #55686

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Related: this fixes the same `image_url` null-url crash (#55686) as the earlier open PRs #55685 (earliest, has regression tests) and #55699, and additionally guards a null `modelLifecycle.status` in `discover_bedrock_models`. It's a superset of the null-url fix, not a duplicate. Maintainer to pick the canonical PR for the shared `image_url` fix (#55685 looks canonical: earliest + regression tests) and decide whether to fold in this PR's extra lifecycle-status guard.

**Review by teknium1 — COMMENTED** [review]
Thanks for the focused Bedrock hardening. The stated null cases remain reproducible from current main: `agent/bedrock_adapter.py:522-523` can call `startswith` on a null URL, and `agent/bedrock_adapter.py:1147-1148` can call `upper` on a null lifecycle status.

### Problems
- The PR changes only `agent/bedrock_adapter.py`; it adds no regression coverage. Existing tests cover a valid image data URL at `tests/agent/test_bedrock_adapter.py:332-348` and ACTIVE/LEGACY lifecycle states at `:711-773`, not either null case.
- The proposed `or ""` expressions fix `None`, but truthy non-string values can still reach `startswith` or `upper`. The analogous Gemini converter uses an explicit string guard at `agent/gemini_native_adapter.py:213-215`.

### Suggested changes
- Add direct null-URL and null-lifecycle-status regression tests in `tests/agent/test_bedrock_adapter.py`.
- Use explicit string normalization for both values before their string-method calls.

Automated hermes-sweeper review.

File: agent/bedrock_adapter.py [hunk 1]
```diff
@@ -519,7 +519,7 @@ def _convert_content_to_converse(content) -> List[Dict]:
                 blocks.append({"text": text if text else " "})
             elif part_type == "image_url":
                 image_url = part.get("image_url", {})
-                url = image_url.get("url", "") if isinstance(image_url, dict) else ""
+                url = (image_url.get("url") or "") if isinstance(image_url, dict) else ""
```
Comment (teknium1) [inline agent/bedrock_adapter.py:522]: This fixes `None`, but a truthy non-string value such as `123` still reaches `url.startswith(...)` below. Please normalize with an explicit `isinstance(url, str)` guard, matching the defensive Gemini converter.

File: agent/bedrock_adapter.py [hunk 2]
```diff
@@ -1145,7 +1145,7 @@ def discover_bedrock_models(
 
             # Only include active, streaming-capable, text-output models
             lifecycle = summary.get("modelLifecycle", {})
-            if lifecycle.get("status", "").upper() != "ACTIVE":
+            if (lifecycle.get("status") or "").upper() != "ACTIVE":
```
Comment (teknium1) [inline agent/bedrock_adapter.py:1148]: This coalesces null status values, but truthy non-strings still reach `.upper()`. Normalize to a string before comparison so malformed lifecycle payloads cannot retain the same crash class.
