### ISSUE TITLE
Bundled chronos plugin fails to load on v0.18.2: 'PluginContext' object has no attribute 'register_cron_scheduler'

### ISSUE THREAD

**Issue by iwillnotbecomeu** [NousResearch/hermes-agent#62951]
### Summary

The **bundled** `chronos` cron-provider plugin fails to load on v0.18.2 because it calls a `PluginContext` API that no longer exists:

```
WARNING hermes_cli.plugins: Failed to load plugin 'chronos': 'PluginContext' object has no attribute 'register_cron_scheduler'
```

The warning fires on every session start when the plugin is enabled. Since the plugin ships with the install (source: `bundled` in `hermes plugins list`), this looks like the `PluginContext` interface drifted during the v0.18.x window without the bundled chronos plugin being updated to match.

### Environment

- Hermes Agent v0.18.2 (2026.7.7.2), git install, upstream `4281151a`
- Python 3.11.15, Debian 13 (LXC)
- `plugins.enabled` included `chronos`; `cron.provider` unset (built-in ticker in use)

### Impact

- Chronos (Nous Portal cron provider) can never activate — anyone relying on it gets a silent fallback to the built-in ticker.
- Log noise on every session for anyone with the plugin enabled.

### Workaround

`hermes plugins disable chronos` (built-in cron ticker is unaffected and keeps running jobs).

### Expected

Either the bundled plugin is updated to the current `PluginContext` API, or `register_cron_scheduler` is restored/deprecated with a shim.

**Comment by GottZ** [comment]
> *This was generated by AI during triage.*

#### Summary

One PR addresses #62951. #62960 fixes the reported PluginContext API failure by keeping cron scheduler providers out of the general plugin loader and routing Chronos exclusively through its dedicated cron-provider discovery path.

#### Related pull requests

- #62960 `best fix` — (+80/-9) — fixes: Skips bundled cron providers in general discovery, marks Chronos as exclusive, auto-detects user cron scheduler providers, aligns plugin listing, and adds regression coverage; this directly prevents the invalid `PluginContext.register_cron_scheduler` call while preserving activation through `cron.provider: chronos`.

#### Suggested consolidation

Merge #62960 — it directly fixes the loader/provider-path mismatch identified in #62951, includes focused regression tests, and its keep_open review reports no blocking issues. There are no duplicate PRs to close.

#### Complex graph

```mermaid
flowchart LR
    classDef open fill:#dbeafe,stroke:#1d4ed8,color:#1e3a8a
    classDef merged fill:#dcfce7,stroke:#15803d,color:#14532d
    classDef closed fill:#e5e7eb,stroke:#6b7280,color:#1f2937
    classDef unverified fill:#f3f4f6,stroke:#9ca3af,color:#374151
    classDef best stroke-width:3px,stroke:#b45309
    classDef target stroke-width:3px,stroke:#4338ca
    I62951(["issue #62951 (open)"])
    P62960["PR #62960 (open)"]
    P62960 -->|best fix| I62951
    class I62951 open
    class I62951 target
    class P62960 open
    class P62960 best
    click I62951 "https://github.com/NousResearch/hermes-agent/issues/62951"
    click P62960 "https://github.com/NousResearch/hermes-agent/pull/62960"
```
*Graph: solid arrow = fixes / best fix, dashed arrow = partial or unverified (see edge label); boxed group = PRs duplicating each other; amber border = best fix; indigo border = target; gray node = closed or no verify verdict yet (state tag in the node label).*

_Cross-PR triage: Reviewed 1 pull request and 1 issue in this complex. Each diff was read against this issue; Assessment working set: 7 kB of PR diffs, 3 kB of issue/PR text, <1 kB of discussion (1 comments), 2 verify verdicts. verdicts reflect diff content, not PR titles. Part of an automated triage batch._

**Comment by engradnansw** [comment]
Still reproduces on **v0.20.4 (2026.8.18)** — Windows 11 Pro 10.0.26200, Python 3.11.15, ZIP install (non-git).

Fires on every startup, both for the CLI and for the dashboard/desktop backend:

```
2026-08-20 15:30:47,116 WARNING hermes_cli.plugins: Failed to load plugin 'chronos': 'PluginContext' object has no attribute 'register_cron_scheduler'
```

The mismatch is unchanged from the original report — `plugins/cron_providers/chronos/__init__.py:267` calls it:

```python
ctx.register_cron_scheduler(ChronosCronScheduler())
```

and `hermes_cli/plugins.py` still defines no such method (`grep -c "def register_cron_scheduler"` → `0`), while `plugins/cron_providers/__init__.py` provides a test double that does have it — so the plugin only ever works against the fake context, never the real one.

Impact is as described: cron itself is fine (`cron.scheduler_provider: In-process cron scheduler started (interval=60s)`), so this is a silent capability loss plus per-startup log noise rather than a functional break. The `hermes plugins disable chronos` subcommand is still present, so the documented workaround should still apply (I did not exercise it).

Adding the version data point since the report is against v0.18.2 and #62960 is still open — the diagnosis needs no revision.

**Comment by wdmason** [comment]
Root-caused this on `main` (`21b2095d`, v0.21.0) — the failure is not in chronos or in `PluginContext`, it's a routing gap in the generic plugin manager's kind heuristic.

## Root cause

`hermes_cli/plugins.py::_detect_kind_from_source()` (currently lines 985–1001) exists to route plugins that belong to *other* discovery systems away from the generic `PluginManager` — it detects memory providers (`register_memory_provider` → kind `exclusive`) and model providers (`register_provider` + `ProviderProfile` → kind `model-provider`). It has **no branch for cron providers**.

So a cron-provider plugin (whose `register(ctx)` calls `ctx.register_cron_scheduler(...)` per the contract in `plugins/cron_providers/__init__.py`) classifies as `standalone`. The generic manager then loads it and calls `register(ctx)` with the real `PluginContext` — which exposes 26 `register_*` methods, none of them `register_cron_scheduler` (verified live) — and every session load warns.

Meanwhile the intended path, `plugins/cron_providers/__init__.py::_load_provider_from_dir()`, has its own loader with a `_ProviderCollector` fake context that *does* implement `register_cron_scheduler`. The double-loading the kind heuristic exists to prevent is exactly what happens for this category.

## Affected class

Every cron-provider plugin — bundled (`plugins/cron_providers/chronos/`) and any user-installed provider under `$HERMES_HOME/plugins/` — not just chronos. Note the functional cron path (`load_cron_scheduler` / `discover_cron_schedulers`) works independently and providers are inert unless `cron.provider` selects them, so the impact is the spurious warning plus a permanently failed registration entry per process start. But this has now been misread twice in the wild (this issue + user reports post-v0.21.0) as a plugin/API breakage.

## Suggested fix

Mirror the `exclusive` handling:

1. Extend `_detect_kind_from_source()` with a cron-provider branch (`register_cron_scheduler` or `CronScheduler` in the first 8 KB of `__init__.py` — matching the existing heuristic in `plugins/cron_providers/__init__.py::_is_cron_provider_dir`).
2. Add the kind to `_VALID_PLUGIN_KINDS`.
3. In the generic manager's enabled-plugin path, skip loading for that kind the way `exclusive` is skipped (record the manifest for introspection, leave activation to the cron discovery system).

This fixes the whole class, not just chronos. Happy to open a PR if the approach sounds right.

**Comment by bertheto** [comment]
**Reproduced on v0.21.2** (`code_sha 939e45c91d75`) — the bug is still present three releases after the v0.18.2 report, so #100362 is still needed.

Evidence from a fleet install where `chronos` was listed in `plugins.enabled` (not in `cron.provider`):

- `WARNING hermes_cli.plugins: Failed to load plugin 'chronos': 'PluginContext' object has no attribute 'register_cron_scheduler'` — **17 occurrences** in `errors.log`.
- `plugins/cron_providers/__init__.py::_is_cron_provider_dir()` detects the directory by testing `"register_cron_scheduler" in source` — i.e. it identifies the plugin as a cron provider *by the very attribute the general context lacks*, and the general `PluginManager` still tries to load it.
- **Workaround confirmed**: removing the `chronos` line from `plugins.enabled` yields a clean startup at the next gateway start. Cron keeps running on the built-in scheduler; nothing else changes.
- The correct activation path is `cron.provider`, so listing the entry under `plugins.enabled` has no functional upside today — it only produces the warning. The failure is silent (the plugin becomes a no-op), which is why it goes unnoticed unless you read `errors.log`.
