### ISSUE TITLE
Gateway @ context-reference expansion never runs: AttributeError on nonexistent self._model, silently swallowed

### ISSUE THREAD

**Issue by TheTom** [NousResearch/hermes-agent#62695]
## Summary

The gateway's "@" context-reference expansion (@file:, @folder:, @diff, ...) never runs. Every inbound message containing "@" hits an AttributeError that is silently swallowed, so references pass through to the model unexpanded.

## Root cause

`GatewayRunner._prepare_inbound_message_text` (gateway/run.py, ~10608-10648 on current main) reads `self._model` and `self._base_url`:

```python
_msg_ctx_len = await get_model_context_length_async(
    self._model,
    base_url=self._base_url or _msg_runtime.get("base_url") or "",
    ...)
```

Neither attribute is ever assigned on GatewayRunner (`grep -n "self\._model\s*=" gateway/run.py` returns nothing). The block was introduced in da44c196b as a copy of the HermesCLI implementation, where `self.model` / `self.base_url` are real attributes. In the gateway class the first read raises AttributeError, which the surrounding `except Exception as exc: logger.debug(...)` hides at debug level.

## Repro

Call `_prepare_inbound_message_text` with a message containing `@file:notes.txt`: the debug log shows `@ context reference expansion failed: 'GatewayRunner' object has no attribute '_model'` and the returned text is unchanged.

## Fix

PR incoming: resolve model/provider/base_url via `self._resolve_session_agent_runtime(...)` (the same session-aware resolution the hygiene compression block uses later in the file), and raise the swallow log to warning so future breakage of this feature is visible.
