### PR TITLE
fix(gateway): scope the OpenAI-compat Idempotency-Key cache by profile

### PR DESCRIPTION
**Pull request by nftpoetrist**
## What

`_run_idempotent()` (the shared wrapper behind `POST /v1/chat/completions` and `POST /v1/responses`) keys the process-global `_idem_cache` purely on the client-supplied `Idempotency-Key` header plus a body-field fingerprint — no profile identity anywhere in the key.

Under `gateway.multiplex_profiles`, every native route is auto-mirrored at `/p/<profile>/...` behind `_make_profile_prefix_middleware()`, which sets the `_api_request_profile` ContextVar per request. `_run_idempotent()` never reads it, so two different profiles' clients hitting the same gateway process (native route + `/p/<profile>/...` mirror, or two different `/p/<profile>/...` mirrors) share the exact same cache.

**Concrete failure:** a client (or an SDK/automation script that derives its Idempotency-Key deterministically from request content, a common pattern) sends the same `Idempotency-Key` + a body matching on the fingerprinted fields (`model`, `messages`, etc.) to two different profiles. The second request never runs its own turn — it silently gets back the first profile's cached response (including its `X-Hermes-Session-Id`).

## Fix

Fold the request's profile into the cache key inside `_run_idempotent()`, mirroring the sibling `/v1/runs` admission API's own established pattern: `_run_idempotency_scope()` already scopes its namespace with `_api_request_profile.get() or "default"`. This change reuses that exact expression rather than inventing a new one.

```python
profile = _api_request_profile.get() or "default"
scoped_key = f"{profile}\0{idempotency_key}"
```

Both call sites (`chat completions`, `responses`) funnel through this one function, so both get the fix automatically — no other call site touches `_idem_cache`.

## Scope note

- Open PR #51519 ("scope idempotency fingerprint to session/memory context") fixes a *different, complementary* axis: it folds `session_id`/`gateway_session_key`/`conversation_history` into the *fingerprint* so two requests with different session context don't collide within the same profile. It never touches profile identity, so this fix's cross-profile gap survives even if #51519 merges — the two are non-overlapping and can land in either order.
- Open PR #83546 is a byte-verbatim extraction of `_IdempotencyCache`/`_idem_cache`/`_make_request_fingerprint` into a new module with a re-export shim back through `gateway.platforms.api_server` — this PR's `_run_idempotent()` import of `_idem_cache` continues to resolve through that shim unchanged, no conflict.

## Testing

Added `TestRunIdempotentProfileScope` to `tests/gateway/test_api_server.py`:
- `test_same_key_different_profiles_do_not_share_a_cached_response` — two profiles with the same key must each run `compute()`.
- `test_same_key_same_profile_still_dedupes` — regression guard: the fix must not break same-profile dedup, which is the entire point of the Idempotency-Key contract.
- `test_unset_profile_defaults_consistently` — no `/p/<profile>/` prefix (multiplexing off) still dedupes correctly under the shared `"default"` scope.

Mutation-verified: reverting the source change makes `test_same_key_different_profiles_do_not_share_a_cached_response` fail exactly as predicted (`1 == 2`, cross-profile reuse) while the other two tests correctly still pass.

`tests/gateway/test_api_server.py` (113 tests) and the sibling `test_api_server_runs.py` / `test_api_server_run_idempotency.py` / `test_api_server_declared_conversation.py` / `test_api_server_runs_extraction.py` (121 tests) all pass.

## Update: addressed review feedback

@andrexibiza's review (tracked issue #84256, `SECURITY-CLASS-83eab80a8a2dfca6`) correctly identified that the profile-only fix above closed one of three namespace dimensions the issue requires. This update closes the other two.

**1. Endpoint/route discriminator.** `_run_idempotent()` is shared by `POST /v1/chat/completions` and `POST /v1/responses`, but `_IdempotencyCache._store` keeps the fingerprint only as a *value* inside the settled slot — the slot key itself was route-agnostic. As the review pointed out, that means a client reusing one `Idempotency-Key` across both routes could have the second route's settled write silently overwrite the first route's storage slot, so a legitimate retry of the first request would recompute instead of replaying its own cached result — even though the differing fingerprints already prevented direct cross-route payload reuse.

Fix: each call site now passes an explicit, stable logical route discriminator (`route="chat_completions"` / `route="responses"`) that is folded directly into the cache key, not derived from `request.path` (so `/v1/...` and its `/p/<profile>/v1/...` alias remain the same logical route, per the review's explicit guidance).

**2. Authenticated principal.** The sibling durable `/v1/runs` admission API's `_run_idempotency_scope()` already composes `sha256(profile \0 expected-api-key-or-sentinel)` for its non-room case. Rather than re-deriving a second, subtly different principal scope (the review's stated preference), `_run_idempotent()` now delegates directly to `self._run_idempotency_scope(request)` — this method already exists on `APIServerAdapter` (both mixins compose onto the same adapter instance) and is unreachable for standard OpenAI-compat clients' room-grant branch, since that branch only activates on an `Authorization: hermesroom <token>` scheme, never the `Bearer` scheme OpenAI SDKs send.

The composite cache key is now:

```python
principal_scope = self._run_idempotency_scope(request)  # sha256(profile \0 expected-api-key-or-sentinel)
scoped_key = f"{principal_scope}\0{route}\0{idempotency_key}"
```

**Testing added**, all in `TestRunIdempotentProfileScope`:
- `test_same_key_different_routes_do_not_share_a_cached_response` and `test_chat_then_responses_then_chat_retry_replays_first_chat_result` — the exact chat → responses → chat retry scenario from the review; proves the first route's cached slot survives the second route's write.
- `test_concurrent_different_profiles_have_isolated_inflight_tasks` — the #84256 acceptance contract's concurrent-inflight case: two profiles racing the same Idempotency-Key get distinct, independently-gated in-flight compute tasks (not one blocking on/replaying the other).
- `test_principal_rotation_does_not_replay_old_principals_response` — a profile whose `API_SERVER_KEY` rotates mid-cache-lifetime cannot have a new principal replay the old principal's cached response.
- `test_same_key_same_profile_same_principal_still_dedupes_via_run_idempotency_scope` — confirms `_run_idempotent` actually delegates to `_run_idempotency_scope()` (spied) rather than reimplementing its own definition, per the review's explicit ask.
- Existing profile-isolation and default-profile tests updated for the new required `route` parameter; all continue to pass.

**Mutation-verified with three independent negative controls:**
1. Reverting the whole diff → `TypeError: unexpected keyword argument 'route'` on all 8 new/updated tests (proves every test actually exercises the new signature).
2. Keeping `route` as a parameter but not folding it into the cache key → only the two route-isolation tests (`test_same_key_different_routes_do_not_share_a_cached_response`, `test_chat_then_responses_then_chat_retry_replays_first_chat_result`) fail; the six profile/principal-focused tests correctly still pass.
3. Keeping the call to a shared scope helper but reverting it to a bare `_api_request_profile.get() or "default"` (no principal) → only the two principal-focused tests fail; the others correctly still pass.

All three controls confirm each test targets its intended dimension in isolation.

**Test results:** `tests/gateway/test_api_server.py` — 118 passed. `tests/gateway/test_api_server_runs.py`, `tests/gateway/test_api_server_run_idempotency.py`, `tests/gateway/test_api_server_runs_extraction.py` — 72 passed.

**Scope note (textual proximity, not a semantic conflict):** open PR #102492 ("Responses session id header") also touches the `/v1/responses` `_run_idempotent()` call site — it replaces the `body` argument with a `fingerprint_body` copy and adds two new `fingerprint_keys` entries for session-id continuity. It does not touch the cache-key namespace (no `route` concept, no change to `_run_idempotency_scope`), so the two changes are complementary and can land in either order with an ordinary line-adjacent rebase.

**Competitor check (fresh, at time of this update):** searched `gh pr list --search "idempotency"` across all states and confirmed no other open or merged PR implements route or principal scoping for this cache; issue #84256 has no other implementation PR linked.

### CODE REVIEW

**Review by andrexibiza — COMMENTED** [review]
Reviewed exact head `2babba58ce4b7a4f81bd029672dd54d0011916bf` against base/current `main` `9dd6634c5635321cf38840cc30e9b51226689128`, including the full two-file diff, the current `_IdempotencyCache` storage/inflight semantics, `_make_profile_prefix_middleware()` / `_profile_scope()` ownership boundary, both `_run_idempotent()` call sites, the sibling durable `/v1/runs` scope implementation, exact-head CI, and the live idempotency/profile issue graph.

The profile slice itself is good. `_api_request_profile` is set by the profile-prefix middleware before the handler runs, `None -> "default"` matches the existing default-profile runtime scope, the scope is captured before `_idem_cache.get_or_set()` can await, and the NUL separator avoids trivial concatenation ambiguity. The three added tests also prove the intended local delta: cross-profile reuse is broken, same-profile reuse is retained, and the unprefixed/default case stays stable. Exact-head CI, Docker, and Nix are green, and there were no existing submitted reviews or inline review threads on this head when I checked.

I do have a blocker before treating this as the landing fix for the defect class, because this PR has rediscovered only one dimension of an already-owned HIGH security class.

**1. This is a partial implementation of #84256, and the two remaining namespace dimensions are still missing.**

#84256 (`SECURITY-CLASS-83eab80a8a2dfca6`, part of #82591) predates this PR and defines the shared idempotency-cache defect as a composite namespace of **profile + authenticated principal/tenant + endpoint + Idempotency-Key**, captured before the first await. Its acceptance contract also explicitly covers concurrent profile A/B inflight isolation. That issue is still open and currently has no implementation PR linked back to it. Please preserve that lineage/credit rather than treating the profile collision as a standalone first discovery.

The current patch produces only:

`profile + NUL + Idempotency-Key`

so it closes the profile dimension but not the full known class.

**2. Endpoint/route omission is not theoretical: the current cache storage shape can destroy retry idempotency across the two OpenAI routes.**

`_run_idempotent()` is shared by both `POST /v1/chat/completions` and `POST /v1/responses`. `_IdempotencyCache._store` is keyed by the supplied cache key alone; the fingerprint is only a value inside that one slot. `_inflight` uses `(key, fingerprint)`, but settled storage does not.

That means, within one profile:

1. chat request A with key K stores `store[profile\0K] = {fp: F_chat, resp: A}`;
2. responses request B reuses K, has a different route-specific fingerprint, computes independently, then overwrites that same storage slot with `{fp: F_responses, resp: B}`;
3. a legitimate retry of A now sees the wrong stored fingerprint and computes A again instead of replaying A.

So even though the differing fingerprints prevent direct chat↔responses payload reuse, the shared settled slot still loses the first route's idempotency record and can duplicate a turn. The endpoint needs to be part of the immutable cache namespace, not merely indirectly represented by differing fingerprint fields.

I would make the route discriminator explicit at the two call sites (a stable logical value such as `chat_completions` / `responses`) rather than keying on raw `request.path`, because `/v1/...` and `/p/<profile>/v1/...` are aliases for the same logical endpoint and should not accidentally become different namespaces after profile resolution.

**3. Authenticated principal is also still absent, while the sibling implementation cited by this PR already includes it.**

The PR says it mirrors `/v1/runs`, but current `_run_idempotency_scope()` for non-room runs actually hashes both:

`(_api_request_profile.get() or "default", self._expected_api_key() or "unauthenticated-test-listener")`

The OpenAI-compatible cache should preserve the same authority boundary without persisting raw bearer material. Today each profile resolves its expected API key dynamically. If that credential/principal changes while the process-global five-minute cache is alive, a newly authorized caller in the same profile can present the same Idempotency-Key/body fingerprint and receive the previous principal's cached response because the cache has no principal generation/identity in its namespace.

Please compose an opaque principal scope (hash/domain-separated identifier is fine; raw credentials should not become cache keys) with profile + logical endpoint + client idempotency key. If there is a clean shared helper to factor from the non-room portion of `/v1/runs`, that is preferable to having two subtly different definitions of API principal scope.

**Required verification for the completed key shape:**

- keep the current profile A/B regression;
- add the #84256 concurrent A/B case so distinct inflight tasks are proven, not only sequential settled-cache behavior;
- add same-profile, same client key, **chat → responses → chat retry** and prove the final chat call replays its first result rather than recomputing;
- add a same-profile principal/key-rotation case and prove the new principal cannot replay the old principal's cache entry;
- retain same-profile/same-route dedupe and default-profile compatibility.

An endpoint-level multiplex test through the real profile middleware would also strengthen the current direct-ContextVar unit tests by proving the resolved routing boundary and cache namespace compose in the actual request path.

**Interlocks / merge ownership:**

- **#84256 / #82591 — direct owner / parent campaign.** This PR is a partial implementation of that existing class. Once the composite contract is complete, this should link it with the required closing/interlock language; until then, #84256 must remain open rather than being silently fragmented.
- **#51519 — complementary, not duplicate.** That work expands the *fingerprint* with session/memory/history context. This PR owns the *cache namespace*. Both dimensions must compose. #51519 is still based on the older `api_server.py` layout, so it will need ordinary rebase reconciliation against the current extracted route code, but its semantic contribution remains distinct.
- **#83546 — adjacent structural extraction, not a functional substitute.** Its behavior-neutral `_IdempotencyCache` extraction/re-export can coexist with this caller-side namespace repair; preserve its structural authorship rather than folding it into the security fix.
- **#84253 — other side of the profile-isolation shape, but separately owned.** The durable ResponseStore/conversation namespace is also process/global. Fixing transient idempotency must not be used as evidence that durable response history is profile-safe; #84253 has its own storage/migration acceptance contract.

So: **the patch is correct for the profile-only symptom and the exact-head verification is solid, but I would not merge it as the final functional fix while the known composite namespace contract remains open.** Completing principal + logical endpoint scope here is small, keeps one owner for one cache defect class, and avoids immediately revisiting the same key format and acceptance surface.

Nice work on the mutation check and on keeping the change in the extracted route module rather than regrowing `api_server.py`. The remaining work is about finishing the already-mapped authority boundary, not undoing the useful slice that is here.

**Comment by nftpoetrist** [comment]
Thanks for the thorough review — this is exactly right, and I've pushed a second commit closing both gaps.

**Route discriminator:** each call site (`_handle_chat_completions`, `_handle_responses`) now passes an explicit `route="chat_completions"` / `route="responses"` literal, folded into the cache key rather than derived from `request.path` (so the `/p/<profile>/...` alias stays the same logical route, per your guidance). This also fixes the specific overwrite scenario you described — I added `test_chat_then_responses_then_chat_retry_replays_first_chat_result`, which runs exactly your chat → responses → chat-retry sequence and proves the first route's cached slot survives the second route's settled write.

**Authenticated principal:** rather than re-deriving profile + API key independently, `_run_idempotent()` now calls `self._run_idempotency_scope(request)` directly — the same method the `/v1/runs` admission API already exposes on the shared `APIServerAdapter` instance. I confirmed this is safe for OpenAI-compat callers: its room-grant branch only activates on `Authorization: hermesroom <token>`, never the `Bearer` scheme OpenAI SDKs send, so standard clients always resolve through the non-room `sha256(profile \0 expected-api-key-or-sentinel)` path you cited. One definition of "who is this request for," not two.

Added `test_principal_rotation_does_not_replay_old_principals_response` (a rotated `API_SERVER_KEY` can't replay the old principal's cached entry) and `test_concurrent_different_profiles_have_isolated_inflight_tasks` for the concurrent A/B inflight case from #84256's acceptance contract.

Mutation-verified with three separate negative controls (full revert, route-param-present-but-not-keyed, and shared-scope-call-reverted-to-bare-profile) — each isolates exactly the tests targeting that dimension; details in the PR body's "Update" section. `tests/gateway/test_api_server.py` (118) and the sibling runs/idempotency suites (72) all pass.

Noted PR #102492 in the body as a textual-proximity (not semantic) neighbor on the same `_run_idempotent()` responses call site — it enriches the fingerprint for session continuity, doesn't touch the key namespace, so the two compose fine.

Left #84256 open per your note — happy to have this PR link/close it once you're satisfied the composite contract is met.

File: tests/gateway/test_api_server.py [hunk 1]
```diff
@@ -147,6 +148,287 @@ async def compute():
         assert first_result == second_result == ("response", {"total_tokens": 1})
 
 
+class TestRunIdempotentProfileScope:
```
Comment (andrexibiza) [inline tests/gateway/test_api_server.py:151]: **[P2] Move this new regression class into a bounded test module.**

The structural prerequisite in [#84256](https://github.com/NousResearch/hermes-agent/issues/84256) explicitly forbids this hardening change from growing an already over-2,000-line touched file. This module was already over that limit at the merge base ([existing lines 2001–2010](https://github.com/NousResearch/hermes-agent/blob/9dd6634c5635321cf38840cc30e9b51226689128/tests/gateway/test_api_server.py#L2001-L2010)); the present diff adds 282 lines to it.

Keep all eight new scope tests, but place them in a dedicated module with a small isolated/shared adapter fixture, and remove this PR’s additions and newly introduced `_api_request_profile` import from the oversized original file. That preserves the security coverage without making this fix depend on a large mixed-purpose test-file rewrite. If a broader shard is necessary, keep it separate and behavior-neutral as the issue requires.

I missed this existing placement constraint in my first review. This is a structural acceptance correction, not a claim that these tests introduce a runtime vulnerability.

**Review by andrexibiza — COMMENTED** [review]
## Security re-review — the namespace corrections address my earlier findings; one structural correction remains

Reviewed nftpoetrist’s exact head `f827eb18b922d722463091d1288e164c7e082843`, both changed files, the previous discussion, and the authentication/profile/cache dependencies. This supersedes the functional objections in [my previous review](https://github.com/NousResearch/hermes-agent/pull/103871#pullrequestreview-5122925407); it is not a claim that every adjacent API ownership problem is resolved.

### Functional disposition

The two requested additions are implemented at the correct boundary:

- **Route isolation:** both non-streaming call sites pass explicit logical route constants, and the route is in the storage key, not merely the fingerprint. That separates both settled slots and in-flight tasks and preserves the chat → responses → chat retry case. Raw URL aliases do not become different logical routes.
- **Principal/profile isolation:** `_run_idempotent()` delegates to the existing `_run_idempotency_scope()` instead of maintaining another definition. The resulting opaque digest and route are captured before awaiting cache access; the bearer credential is not stored in the cache key. Named-profile authentication reads the request’s middleware-installed secret mapping. I traced `_profile_runtime_scope()` → `_load_profile_secret_scope()` → `build_profile_secret_scope()`, which constructs that mapping, rather than treating every `_expected_api_key()` call as a fresh read of a changing `.env` file. I did not establish a production credential-rotation race and am not reporting one.

I also checked the room-auth interaction: these OpenAI handlers retain their admission/authentication decorator, while the room-token parser selects the separate `hermesroom` scheme. Reusing the runs helper does not, by itself, admit room grants to the keyed OpenAI routes. Streaming still bypasses this non-streaming cache; this change does not claim streaming idempotency.

### Required correction: test-module placement

**[P2] The new regression class grows a file that #84256 explicitly requires this security change not to grow.** `tests/gateway/test_api_server.py` already extends beyond 2,000 lines at the actual merge base, and this diff adds another 282 lines. The issue’s structural prerequisite applies to touched files, including this test module. I missed this placement constraint in the first review; the existing debt is not something the route/principal follow-up introduced.

The narrow correction is to move the new scope regressions into a dedicated, bounded test module, with a small isolated adapter fixture or an appropriate shared fixture, and remove this PR’s additions/import change from the oversized original module. Preserve all eight cases and their negative controls. A wider existing-file split, if needed, should remain a separate behavior-neutral change rather than be mixed into the security fix. The inline comment anchors this requirement to the added class.

### Verification and its limits

I executed an **isolated harness using transcribed executable bodies** of the pinned cache, fingerprint, scope helper, and idempotency wrapper, with explicit adapter/credential/compute fixtures: **14 passed**. This covered settled and concurrent separation independently for profile, principal, and route; same-scope in-flight deduplication; default/logical-alias equivalence; cancellation isolation; failed-compute cleanup and retry; no-key bypass; opaque key construction; existing fingerprint-mismatch behavior; and settled eviction/expiry.

Behavioral negative controls, with the call signature retained: removing profile separation produced **3 failed / 11 passed**; removing principal separation produced **2 failed / 12 passed**; removing route separation produced **2 failed / 12 passed**. The corresponding settled/in-flight isolation checks failed. These are stronger behavioral witnesses than a whole-revert `TypeError` alone.

**That harness is not a repository checkout, a run of the PR’s eight tests, or an actual registered-route/middleware HTTP integration run.** I am not presenting it as any of those. The author’s reported 118-test and 72-test runs remain separately attributed to nftpoetrist.

A useful additional regression in the bounded module would exercise actual registered routes plus profile middleware: independently credentialed A/B requests with the same key/body, warm-cache rejection of invalid credentials, and native/default-alias replay. The current added tests call the private wrapper directly and simulate principal changes. This is a coverage recommendation, not a second demonstrated production defect.

### CI and current-main provenance

Both commits have successful CI, Docker, and Nix workflow runs:

| Commit | CI | Docker | Nix |
| --- | --- | --- | --- |
| `2babba58ce4b7a4f81bd029672dd54d0011916bf` | [success](https://github.com/NousResearch/hermes-agent/actions/runs/33989483407) | [success](https://github.com/NousResearch/hermes-agent/actions/runs/33989483087) | [success](https://github.com/NousResearch/hermes-agent/actions/runs/33989483089) |
| `f827eb18b922d722463091d1288e164c7e082843` | [success](https://github.com/NousResearch/hermes-agent/actions/runs/34146721812) | [success](https://github.com/NousResearch/hermes-agent/actions/runs/34146721040) | [success](https://github.com/NousResearch/hermes-agent/actions/runs/34146721047) |

The older commit also has cancelled/skipped **Label rerun** automation; those are not being relabeled as successful tests.

The actual diff merge base is `9dd6634c5635321cf38840cc30e9b51226689128`. The head CI run references merge candidate `d8c1a7fb544c2995dcffc21fb48a23ff0a5aeab9`; I verified that candidate’s parents are `233757037df1f03f9fe1cfddc097acd5ad7f7510` and the reviewed head. During this review the live `refs/heads/main` advanced six commits to `e9bccc90a5e314ddf6dd4bd3772d50cb40027275`. The comparison does not change either PR-touched file, `api_server.py`, `api_server_runs.py`, or `agent/secret_scope.py`, although other gateway files changed. Therefore these green receipts must not be described as verification of a newly generated merge candidate against that later main. Refresh the landing evidence on the actual candidate after the test relocation.

### Scope, attribution, and closure

nftpoetrist owns this implementation. Axl Ibiza (`andrexibiza`) supplied the tracked class contract in [#84256](https://github.com/NousResearch/hermes-agent/issues/84256), under [#82591](https://github.com/NousResearch/hermes-agent/issues/82591). Que0x’s [#51519](https://github.com/NousResearch/hermes-agent/pull/51519) concerns session/memory fingerprint context; BananaLoaf’s [#102492](https://github.com/NousResearch/hermes-agent/pull/102492) concerns Responses session continuity and its fingerprint inputs; Axl Ibiza’s [#83546](https://github.com/NousResearch/hermes-agent/pull/83546) is the separate cache extraction. Those scopes are not superseded by this namespace fix. In particular, resolving #84256 does not resolve the distinct response-store ownership class [#84253](https://github.com/NousResearch/hermes-agent/issues/84253).

**Disposition:** the earlier route/principal objections are addressed. Retain this PR as the implementation for #84256, make the bounded-test correction, and obtain fresh evidence for the resulting landing candidate. Then add the issue’s required closing linkage and retain the issue/epic backlinks, without closing the broader campaign or complementary work. No additional demonstrated security defect in this namespace delta was found in this pass.

**Comment by teknium1** [comment]
Landed on `main` in #108705. Both commits cherry-picked with authorship preserved — 2b7eb97fbf6 (profile-scoped cache) and 3d59486a86e (route + authenticated principal folded into the key); 055e307b487 trims the docstring and the test file down to the two invariants we keep per fix (cross-profile isolation, same-namespace dedup). `_run_idempotent` now keys on `_run_idempotency_scope` + logical route + client key, so `/p/alpha/` and `/p/beta/` sharing an `Idempotency-Key` no longer replay each other's response. Thanks, @nftpoetrist.
