### PR TITLE
fix(config): retry skipped config migrations

### LINKED ISSUE #119658: migrate_config stamps _config_version to latest even when a migration step failed and was skipped, so the skipped step never re-runs
## Bug Description

`migrate_config` writes `_config_version: <latest>` even when one of the migration steps raised and was skipped. The skipped step then never re-runs: `hermes doctor` reads the version as current, `hermes doctor --fix` has nothing to fix, and the update receipt records no skip. The only trace is one WARNING line.

**Version:** observed on two Linux git installs on 2026-09-22, both migrating inside `hermes update` to v0.21.4 (`94e8a255`), from v0.21.3 (`9326d9cd`) and from v0.21.0. Logic below checked against `94e8a255` and current `main`.

## What happened

During the update, migration 44→45 raised and was skipped — loudly, as designed:

```
2026-09-22 13:47:33,370 WARNING hermes_cli.config_migrations: config migration to v45 failed and was skipped: cannot import name '_configurable_keys' from 'hermes_cli.tools_config' (.../hermes_cli/tools_config.py)
```

(The import failure itself is the pre/post-pull module mix already covered by #111271 / #118154 and should stop happening once the source of an update carries the post-swap hand-off. This report is about what happens *after* any step is skipped, whatever raised.)

`config.yaml` was then stamped `_config_version: 45` on both boxes. Consequences:

- `hermes doctor` → config version current; `hermes doctor --fix` → nothing to do.
- The v45 step (`platform_toolsets` lists predating the connections toolset) is never applied.
- The update receipt has `skips: []` and no config step; `outcome` is unrelated to the skip.
- On a `--yes` run the console line scrolls past with the rest of the update output.

## Where

- `hermes_cli/config_migrations.py::run_migrations` — catches per step, appends to `results["warnings"]`, logs, continues. The comment on that branch already names the gap: *"Quiet callers (profile creation, unattended update) discard `results` and migrate_config still stamps the latest version, so without a log line the skipped step vanishes for good."*
- `hermes_cli/config.py::migrate_config` (≈L1443 on `94e8a255`): `if current_ver < latest_ver and not floor_refused: config["_config_version"] = latest_ver` — unconditional on whether every step succeeded.

## Repair used

On both boxes: set `_config_version` back to 44 by hand, run `hermes doctor --fix`. The step applied cleanly on the now-consistent tree.

## Suggestion

Stamp the highest *contiguous* successfully-applied version instead of `latest_ver`: if step N raised, write `N-1` and keep the warning. Then `hermes doctor` shows "Config version outdated (v(N-1) → vlatest)" and `--fix` re-runs exactly the skipped step, which is what the loud-not-silent intent of the per-step skip (#116593) seems to want. If a step is meant to stay non-blocking (a malformed nested value the user has to fix by hand), record it in the receipt's `skips` so it does not depend on someone reading `agent.log`.

Happy to test a patch on both boxes.

### PR DESCRIPTION
**Pull request by KoNit-K**
## What does this PR do?

Fixes a migration retry bug in `migrate_config`. When one migration callback raised, the
ladder logged the skipped step and continued, but the caller still persisted the latest
`_config_version`. The next startup therefore saw the config as current and never retried the
failed step. This change stamps the latest version only after the migration ladder completes
without adding a skipped-step warning, so a later invocation can retry the incomplete ladder.

## Related Issue

Fixes #119658

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)

## Changes Made

- `hermes_cli/config.py` — records whether `run_migrations` completed without skipped-step warnings and writes `_config_version` only after that successful completion.
- `tests/hermes_cli/test_config_migration_nested_guards.py` — verifies a failed v13 migration leaves version 12 on disk, retains the warning/log contract, and succeeds when the normal ladder is retried.

## How to Test

- [x] `scripts/run_tests.sh tests/hermes_cli/test_config_migration_nested_guards.py` — 7 passed, 0 failed.
- [x] `.venv/bin/ruff check hermes_cli/config.py tests/hermes_cli/test_config_migration_nested_guards.py` — all checks passed.
- [x] CONTROL: the six parameterized malformed-nested-value migration cases still complete with no warnings in the same focused file.

## Evidence

- BEFORE RED: the new regression assertion requires a config starting at version 12 to remain at 12 after the v13 callback raises. The previous unconditional version write would instead persist the latest version (46), preventing a retry.
- AFTER GREEN: the focused Python command reports 7 passed and 0 failed; the retry invocation uses the original ladder and advances the retained version to the current latest value.
- CONTROL: normal guarded migration paths retain their existing behavior. Their six parameterized cases validate v12, v14, v16, and v17 shape recovery with an empty warnings list.
- CI lane: this diff changes Python production code and Python tests, so the focused Python lane was run. No Desktop/TS or bootstrap-installer Rust files changed. Docker and Windows publish coverage remain CI/platform work rather than a claim of local all-platform coverage.

## Review follow-up

The completion signal intentionally observes warnings added by the migration ladder only; earlier migration-independent warnings do not exist on this path. The fix preserves the non-fatal behavior of a malformed step while ensuring its schema version remains eligible for retry.

### Code

- [x] I've read the Contributing Guide
- [x] My commit messages follow Conventional Commits
- [x] I searched for existing PRs to make sure this isn't a duplicate
- [x] My PR contains only changes related to this fix
- [x] I've run relevant tests locally (see How to Test)
- [x] I've added tests for my changes
- [x] I've tested on my platform: macOS

### Documentation & Housekeeping

- [x] Documentation update: N/A; runtime behavior and regression coverage are self-contained
- [x] `cli-config.yaml.example`: N/A; no configuration option changed
- [x] `CONTRIBUTING.md` or `AGENTS.md`: N/A; contribution guidance is unchanged
- [x] Cross-platform impact considered; the Python behavior is platform-independent, with Windows/Docker CI left to their platform lanes
- [x] Tool descriptions/schemas: N/A; no tool surface changed

### CODE REVIEW

**Review by arkheioncorp — COMMENTED** [review]
## Review: fix(config) - retry skipped config migrations

**Verdict: APPROVE**

### Summary
Fixes a bug where a failing migration step would still stamp the latest config version, making the skip permanent on the next run. Now the version is only stamped when all migrations complete.

### Findings
- `migration_ladder_completed` flag tracks whether warnings count stayed the same after running migrations
- Version is only stamped when `current_ver < latest_ver and not floor_refused and migration_ladder_completed`
- Test renamed from `test_failing_step_is_skipped_with_warning_and_config_still_migrates` to `test_failing_step_is_skipped_without_stamping_version_and_retries`
- Test now verifies version stays at 12 after skip, and retries succeed on second run

### Security
No concerns. Config migration logic only.

---

**Approved.**
