### PR TITLE
fix(bedrock): tolerate null image_url values

### LINKED ISSUE #55686: Bedrock Converse conversion crashes (AttributeError) on an image_url part with a null url
### What happens

When the active provider is Bedrock and a user message carries an image part whose `url` is null (or a non-string), converting the message to the Converse format crashes with `AttributeError: 'NoneType' object has no attribute 'startswith'`. The exception aborts conversion of the entire message, so the turn errors out.

### Where

`agent/bedrock_adapter.py`, in `_convert_content_to_converse`:

```python
elif part_type == "image_url":
    image_url = part.get("image_url", {})
    url = image_url.get("url", "") if isinstance(image_url, dict) else ""
    if url.startswith("data:"):
        ...
```

`image_url.get("url", "")` only falls back to `""` when the `url` key is absent. If the key is present with value `None`, `url` is `None`, and `url.startswith("data:")` raises.

### Reproduction

```python
from agent.bedrock_adapter import _convert_content_to_converse

_convert_content_to_converse([
    {"type": "text", "text": "look"},
    {"type": "image_url", "image_url": {"url": None}},
])
# AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Expected

A null/non-string url should be tolerated (the unusable image skipped), not crash the conversion. The Gemini converter (`_extract_multimodal_parts`, `((item.get("image_url") or {}).get("url") or "")`) and the Codex converter (`if not isinstance(url, str) or not url: continue`) already handle this shape; the Bedrock converter is the one that crashes.

A fix with regression tests is in #55685.

### PR DESCRIPTION
**Pull request by kyssta-exe**
Fixes #55686.\n\nBedrock Converse conversion now treats non-string image_url.url values as an empty URL before checking for data URLs, avoiding AttributeError on null values. Added a regression test covering the null-url case.\n\nTests:\n- scripts/run_tests.sh tests/agent/test_bedrock_adapter.py -k 'image_url_with_null_url or image_data_url_converted'

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #55685 — same bug, same file (`agent/bedrock_adapter.py` `_convert_content_to_converse`), same mechanism (coerce a null/non-string `image_url.url` to `''` before the `data:` check so a present `url=None` no longer raises AttributeError), both fixing issue #55686. #55685 is the earliest OPEN fix — canonical. Related to the other competing OPEN fix #55699 and to issue #55686.

**Comment by kyssta-exe** [comment]
Stale — 14-24 days without merge activity.
