### ISSUE TITLE
Bug: RuntimeError 'dict' object has no attribute 'model_dump' after v0.21 upgrade (12 cron jobs broken)

### ISSUE THREAD

**Issue by manaswai07014** [NousResearch/hermes-agent#109663]
# Bug: `RuntimeError: 'dict' object has no attribute 'model_dump'` after v0.21 upgrade (cron jobs broken)

## Status (updated 2026-09-13)

- **Root cause identified**: `agent/chat_completion_helpers.py::_model_dump_safe`
- **Local fix applied**: Added `hasattr(obj, "model_dump")` guard before calling `.model_dump()`. Verified by directly testing with a dict (which previously raised AttributeError) and a Pydantic mock object (which still works).
- **Verification**: Sep 13 12:00 Smoke Test (c9be5d41daa7) re-triggered after fix → **succeeded**. No more RuntimeError.
- **12 affected cron jobs resumed** and active.

Filing this upstream so others on v0.21 with the same Hermes-internal cron config aren't stuck.

## Summary

After upgrading from Hermes v0.17.0 to v0.21.0 (commit `245e48008f`), **all 11 of my Hermes-internal scheduled cron jobs fail with the same error**: `RuntimeError: 'dict' object has no attribute 'model_dump'`. Direct dispatch of the same code paths works fine in CLI/gateway contexts; only `cron scheduler → agent.run_conversation` triggers it.

## Environment

- **Hermes version**: v0.21.0 (v2026.8.31)
- **Python**: 3.11.16
- **OS**: WSL2 Ubuntu 24.04 (Windows host)
- **Upgrade path**: `hermes update --yes --backup` (clean upgrade from v0.17.0)
- **Reproduction date**: 2026-09-10 (first failure); ongoing as of 2026-09-11

## Affected jobs (12 total, all `[active]` but failing in v0.21)

| Job ID | Name | Schedule | Last error |
|---|---|---|---|
| `790ec44db276` | Daily News to Telegram | `0 7 * * *` | `'dict' object has no attribute 'model_dump'` |
| `28891864a449` | Trend Report to Telegram | `20 7 * * *` | Same |
| `53b00759f029` | Daily Status Report | `0 8 * * *` | Same |
| `c55fc2a67778` | Daily Backup | `20 8 * * *` | Same |
| `9d9905a8dcad` | Daily Competitor Report (Phase 1+2+3 Plus) | `0 9 * * *` | Same |
| `34ff6f88e89a` | Daily Auto-Wiki Ingestion | `0 10 * * *` | Same |
| `fec17b8749a1` | Daily Topic Priority Report | `0 11 * * *` | Same |
| `c9be5d41daa7` | Daily Smoke Test (Noon) | `0 12 * * *` | Same |
| `3a6c0a84e726` | Auto-fill triples from wiki | `0 2 * * *` | Same |
| `67355bdc2cc4` | Daily Wiki Sync + Lint | `45 7 * * *` | Same |
| `4c53c4e39798` | healthy-recipes-p45-watchdog | `5 3 * * *` | Same + Telegram 403 |
| `9da97fe3ea48` | Memory Health Check (Daily) | `0 6 * * *` | Different: `triples.jsonl` STALE 86d |

All jobs use `skills: [car-evolution, skill-trigger-map]` or just `car-evolution`. No `script` (no_agent) jobs except `9da97fe3ea48`.

### Investigation done

I grep'd the entire `apps/hermes-agent/` source tree for unguarded `.model_dump(` calls. Found that the unguarded site is in `chat_completion_helpers.py`:

```python
# /home/hermes/apps/hermes-agent/agent/chat_completion_helpers.py:1563
def _model_dump_safe(obj):
    """``model_dump(warnings=False)`` (avoids pydantic serializer UserWarnings on
    generic-union SDK models), falling back for shims that reject the kwarg."""
    try:
        return obj.model_dump(warnings=False)
    except TypeError:
        return obj.model_dump()
```

The function tries `model_dump(warnings=False)` and falls back to `model_dump()` on `TypeError` — but does NOT guard against `AttributeError` raised when `obj` is a plain `dict` (which has no `.model_dump` attribute at all). Other call sites in the same codebase DO use `hasattr(value, "model_dump")` or `getattr(value, "model_dump", None)`:

- `agent/api_request_hooks.py:104`: `if hasattr(value, "model_dump"): return recurse(_model_dump(value))`
- `agent/relay_tools.py:80`: `model_dump = getattr(value, "model_dump", None); if callable(model_dump): ...`
- `agent/anthropic_message_convert.py:215`: `if hasattr(value, "model_dump"):`
- `agent/relay_llm.py:838`: `getattr(value, "model_dump", None)`

So the inconsistency is real: `chat_completion_helpers.py` is the odd one out.

### Repro

```python
import sys
sys.path.insert(0, '/home/hermes/apps/hermes-agent')
from agent.chat_completion_helpers import _model_dump_safe
_model_dump_safe({'foo': 'bar'})  # AttributeError: 'dict' object has no attribute 'model_dump'
```

`_dump_if_model()` already exists (line 1572) and DOES guard properly:
```python
def _dump_if_model(value):
    return _model_dump_safe(value) if hasattr(value, "model_dump") else value
```

So somewhere in the cron dispatch path, `_model_dump_safe()` is being called directly without the `_dump_if_model()` wrapper.

## Workaround (local fix applied)

Patched `_model_dump_safe()` to handle dicts as pass-through:

```python
def _model_dump_safe(obj):
    """..."""
    # W83: pass-through for non-Pydantic values (dicts, strings, primitives).
    if not hasattr(obj, "model_dump"):
        return obj
    try:
        return obj.model_dump(warnings=False)
    except TypeError:
        return obj.model_dump()
```

After this fix:
- `_model_dump_safe({'foo': 'bar'})` → `{'foo': 'bar'}` ✅
- `_model_dump_safe(<PydanticModel>)` → `<dumped dict>` ✅
- Manual `hermes cron run c9be5d41daa7` → `succeeded` ✅

## Reproduction steps (for maintainers)

1. Upgrade from v0.17.0 to v0.21.0.
2. Configure any `agent_mode` cron job (with skills: [car-evolution] or any skill).
3. Wait for the scheduler to fire.
4. Observe `RuntimeError: 'dict' object has no attribute 'model_dump'`.
5. Direct CLI dispatch of the same agent + prompt works fine — only `cron → agent.run_conversation` triggers it.

## Suggested upstream fix

Add the same `hasattr` guard to `_model_dump_safe()` (single-line change):

```python
def _model_dump_safe(obj):
    try:
        return obj.model_dump(warnings=False)
    except (TypeError, AttributeError):  # AttributeError covers raw dicts
        try:
            return obj.model_dump()
        except AttributeError:
            return obj  # dicts / primitives pass through unchanged
```

Or better, route through `_dump_if_model()` everywhere.

## Environment details

```
$ hermes version
Hermes Agent v0.21.0 (v2026.8.31) · upstream 245e4800
Project: /home/hermes/apps/hermes-agent
Python: 3.11.16
OpenAI SDK: 2.32.0

$ pip show pydantic
Name: pydantic
Version: 2.11.x
```

## Priority

Medium — all scheduled jobs are non-critical (manual triggers still work for individual operations), but the daily/weekly automation is completely broken without this fix.

Thanks for the great work on the v0.21 release. The new `hermes peer` and Bot Mode features look great; I'm looking forward to using them once the cron framework is back online.

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #107967 (same reporter, same bug, same 12 jobs). The root-cause update here (`_model_dump_safe` hasattr guard) is useful; consider posting it on #107967 so it sits next to the open fix PR #107971.
