### ISSUE TITLE
[Bug]: Windows: AttributeError: module 'asyncio' has no attribute 'start_unix_server' in shutdown_watchdog (v0.21.0)

### ISSUE THREAD

**Issue by whxyw4** [NousResearch/hermes-agent#99895]
### Bug Description

After upgrading to v0.21.0 (2026.8.31), Hermes Gateway fails to initialize the shutdown watchdog thread on native Windows. The application throws an AttributeError because asyncio.start_unix_server is used, which is not available on Windows Python.
The gateway still runs partially, but the liveness/heartbeat watchdog subsystem crashes repeatedly on startup.

### Steps to Reproduce

1.	Upgrade Hermes Agent to latest main branch (b20cc5f7)
2.	Run hermes gateway stop to clean old process
3.	Run hermes gateway
4.	Watch startup logs — watchdog thread crashes immediately

### Expected Behavior

he watchdog logic should gracefully fallback on Windows:
•	Skip unix socket initialization on Windows
•	Fallback to simple interval heartbeat without socket
•	No crash, no AttributeError

### Actual Behavior

The watchdog logic should gracefully fallback on Windows:
•	Skip unix socket initialization on Windows
•	Fallback to simple interval heartbeat without socket
•	No crash, no AttributeError

### Affected Component

Gateway (Telegram/Discord/Slack/WhatsApp)

### Debug Report

```shell
Full Error Log
python
2026-09-01 08:36:46,896 WARNING gateway.shutdown_watchdog: Loop tick socket unavailable — liveness probes will have no loop-scheduling witness and will not escalate on a stale heartbeat
Traceback (most recent call last):
  File "C:\Users\AdminUser\AppData\Local\hermes\hermes-agent\gateway\shutdown_watchdog.py", line 572, in loop_heartbeat_forever
    tick_server = await asyncio.start_unix_server(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'start_unix_server'
```

### Operating System

Windows 10 / Windows 11 (native PowerShell, no WSL)

### Python Version

3.11.15 (official Hermes managed venv)

### Hermes Version

v0.21.0 (2026.8.31) — current latest main branch

### Additional Logs / Traceback (optional)

```shell
All other warnings in the log are normal tool availability checks and unrelated to this crash.
This is a pure cross-platform compatibility bug, no local environment misconfiguration.
```

### Root Cause Analysis (optional)

Root Cause Analysis
asyncio.start_unix_server() is a Unix-domain socket API that only exists on Linux / macOS / WSL.
Windows native Python does NOT support unix sockets for asyncio, so calling this method directly causes a hard attribute crash.
The new shutdown_watchdog heartbeat logic added in v0.21.0 has no Windows platform guard clause.

### Proposed Fix (optional)

Add platform detection before calling start_unix_server in shutdown_watchdog.py line 572:
•	If sys.platform == "win32": skip unix server creation, use fallback loop tick
•	Isolate Unix-only socket logic from Windows runtime
•	Preserve full functionality for Linux/macOS

### Are you willing to submit a PR for this?

- [ ] I'd like to fix this myself and submit a PR

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #96956: both report the same unguarded POSIX-only asyncio.start_unix_server call in the Windows shutdown watchdog.

**Comment by MilkyWay008** [comment]
Saw the `asyncio.start_unix_server` AttributeError too, that watchdog code is unix-only and the win32 guard never got added. This one's tracked as a duplicate of #96956, so that thread's where the real fix will land. Quick workaround until then: early-return on `sys.platform == "win32"` near line 572 in gateway/shutdown_watchdog.py, the watchdog falls back to the interval heartbeat and stops crashing at startup. oh also, btw, I built a portable Hermes OTG and keep it on a USB stick as my rescue agent, it runs side by side so you can diagnose the broken install from a working one, https://github.com/MilkyWay008/Hermes-OTG if you want to check it.

**Comment by teknium1** [comment]
Fixed on main in #100915 (salvage of #96989 by @Jackal991), merge commit 57d305d5: `asyncio.start_unix_server` is now skipped explicitly on non-POSIX, so Windows gateway starts no longer log the WARNING + AttributeError traceback. Behavior is otherwise unchanged (`loop_tick_socket=false`, probes classify UNKNOWN, graceful-drain backstop).

If you still see the gateway going silent after the traceback is gone, please open a fresh issue — that would be a separate path from this one.
