### PR TITLE
fix(agent): omit unsupported metadata on Relay scope.pop (#78993)

### LINKED ISSUE #78993: Memory leak: relay_runtime.pop() TypeError crashes Gateway and fills SWAP to 100%
## Bug Description

After upgrading Hermes to v0.20.0 ("The Herald Release"), the Gateway process experienced a memory leak caused by an unhandled TypeError in `relay_runtime.py`. This caused the container's memory and SWAP usage to steadily climb to nearly 100%, blocking the event loop and eventually requiring a container restart to recover.

## Steps to Reproduce

1. Run Hermes v0.20.0 in a Docker container
2. Use the agent to perform tool calls (terminal, etc.)
3. Observe repeated `relay finalization failed` errors in `errors.log`
4. Memory and SWAP usage steadily increase without bound
5. Event loop becomes stalled (8.1s → 40.9s)
6. Container becomes unresponsive; manual restart required

## Error Log

```
TypeError: pop() got an unexpected keyword argument 'metadata'
  File "/opt/hermes/agent/relay_runtime.py", line 217, in run_in_session
    return context.run(invoke)
  File "/opt/hermes/agent/relay_runtime.py", line 213, in invoke
    return callback(*args, **kwargs)
```

Repeated ~15 times, followed by:
```
agent.relay_llm: Hermes Relay logical LLM finalization failed
agent.relay_runtime: Hermes Relay logical LLM finalization failed
agent.relay_runtime: turn finalization failed
hermes_cli.web_server: event loop stalled 8.1s (GIL pressure suspected)
hermes_cli.web_server: event loop stalled 40.9s (GIL pressure suspected)
```

## Root Cause Analysis

In `relay_runtime.py:217`, the `pop()` method is called with a `metadata=...` keyword argument that the underlying dictionary/API does not support. This raises `TypeError`, which is not caught properly. Each failed invocation:
- Leaves old Python object stacks uncleaned
- Causes the Gateway to retry the tool call in a loop
- Accumulates unreleased objects in memory

Eventually this fills the container's physical memory and spills into SWAP until the event loop stalls and the container becomes unresponsive.

## Environment

- **Hermes version:** v0.20.0 ("The Herald Release")
- **Container:** Docker (hermes-gateway)
- **Runtime:** Python 3.13
- **System:** Debian (1Panel container on Proxmox VE)
- **Memory:** 7.5 GiB container limit, SWAP 7.5 GiB
- **Date:** 2026-08-04

## Workaround

Restart the container via 1Panel to release all leaked memory. Monitor `errors.log` for `relay finalization failed` — if it appears repeatedly, restart proactively before SWAP fills.

## Related

The `pop()` call at line 217 of `relay_runtime.py` should be fixed to not pass `metadata` as a keyword argument, or the TypeError should be caught and handled gracefully.

### PR DESCRIPTION
**Pull request by astraltrekkin**
## What does this PR do?

Fixes a Gateway finalization crash where Hermes called `relay.scope.pop(..., metadata=...)` and older NeMo Relay bindings (e.g. 0.3.x) raised `TypeError: pop() got an unexpected keyword argument 'metadata'`. That failure left scopes unclosed and produced the repeated `relay finalization failed` / event-loop stall symptoms reported in #78993.

Adds `pop_relay_scope()`, which inspects the live `scope.pop` signature and only forwards kwargs the binding accepts. On 0.4+ / 0.6.x, `metadata` is still passed; on 0.3.x it is omitted so turn/session/logical/shared-metrics close can complete.

## Related Issue

Fixes #78993

## Type of Change

- [x] 🐛 Bug fix (non-breaking change that fixes an issue)
- [ ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 🔒 Security fix
- [ ] 📝 Documentation update
- [x] ✅ Tests (adding or improving test coverage)
- [ ] ♻️ Refactor (no behavior change)
- [ ] 🎯 New skill (bundled or hub)

## Changes Made

- `agent/relay_runtime.py` — add `pop_relay_scope()`; use it for session close, turn finalization, and logical-LLM finalization
- `agent/relay_llm.py` — route logical LLM completion through `pop_relay_scope()`
- `hermes_cli/observability/relay_shared_metrics.py` — route task-scope close through `pop_relay_scope()`
- `tests/agent/test_relay_scope_pop_metadata.py` — unit coverage for omit/forward behavior + end-turn regression matching #78993

## How to Test

1. With a `scope.pop` that rejects `metadata` (nemo-relay 0.3.x, or a monkeypatched pop without that kwarg), open a turn + logical LLM scope and call `SESSION_COORDINATOR.end_turn(...)`.
2. **Before:** `TypeError: pop() got an unexpected keyword argument 'metadata'` at `run_in_session` → `invoke`, with `logical LLM finalization failed` / `turn finalization failed` warnings.
3. **After:** no metadata TypeError; logical handles clear; turn closes cleanly.
4. Run: `pytest tests/agent/test_relay_scope_pop_metadata.py -v`
5. Optional smoke: `pytest tests/agent/test_relay_llm.py::test_non_stream_result_survives_logical_scope_close_failure -v`

### Code

- [x] I've read the [Contributing Guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md)
- [x] My commit messages follow [Conventional Commits](https://www.conventionalcommits.org/) (`fix(scope):`, `feat(scope):`, etc.)
- [x] I searched for [existing PRs](https://github.com/NousResearch/hermes-agent/pulls) to make sure this isn't a duplicate
- [x] My PR contains **only** changes related to this fix/feature (no unrelated commits)
- [ ] I've run `pytest tests/ -q` and all tests pass
- [x] I've added tests for my changes (required for bug fixes, strongly encouraged for features)
- [x] I've tested on my platform: macOS (darwin), Python 3.11.15

### Documentation & Housekeeping

- [x] I've updated relevant documentation (README, `docs/`, docstrings) — or N/A
- [x] I've updated `cli-config.yaml.example` if I added/changed config keys — or N/A
- [x] I've updated `CONTRIBUTING.md` or `AGENTS.md` if I changed architecture or workflows — or N/A
- [x] I've considered cross-platform impact (Windows, macOS) per the [compatibility guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md#cross-platform-compatibility) — or N/A
- [x] I've updated tool descriptions/schemas if I changed tool behavior — or N/A

## Screenshots / Logs

Reproduced against nemo-relay **0.3.0** before the fix:

```
TypeError: pop() got an unexpected keyword argument 'metadata'
  File "agent/relay_runtime.py", line 217, in run_in_session
    return context.run(invoke)
  File "agent/relay_runtime.py", line 213, in invoke
    return callback(*args, **kwargs)
```

Followed by `Hermes Relay logical LLM finalization failed` and `Hermes Relay turn finalization failed`.

After the fix (same 0.3.0 path): no metadata TypeError; turn finalization completes.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by spfcraze** [comment]
_This was generated by AI during triage._

When `inspect.signature(pop)` raises, `pop_relay_scope` skips its kwarg filter and forwards `metadata` anyway - the kwarg this PR exists to omit on older bindings.

`agent/relay_runtime.py:54-55` sets `params = {}` on introspection failure, and the filter at lines 56-59 runs only when `params` is truthy, so `output`, `metadata` and `timestamp` pass through unfiltered on that path. The PR description says the helper "only forwards kwargs the binding accepts", which does not hold for a `scope.pop` that cannot be introspected - such a binding that also rejects `metadata` would still hit the TypeError #78993 reports.

---

Checked against [`73b9930`](https://github.com/NousResearch/hermes-agent/pull/79016/commits/73b99307c7c386662d614b6337a3d148b85bb0c7) — the tip of `fix/relay-scope-pop-metadata` when this was written — and [`aec3318`](https://github.com/NousResearch/hermes-agent/commit/aec331899e4748739927fddf02a54327e64419a0), `main` at the same moment. Verified mechanically: the diff grep, the PR description and the issue text at the former; the code on main at the latter. The reading of intended scope is inference. If I have misread the intent here, please say so.

**Comment by teknium1** [comment]
Thanks for this fix! It was salvaged into #86755 (cherry-picked onto current main with your authorship preserved in the commit history) and is now merged. Closing since the work has landed.
