### PR TITLE
fix(tui): allow nullable session_id in /reload-mcp params

### LINKED ISSUE #17773: [Bug]: `hermes --tui` fails to build on main — TS2322 in ops.ts /reload-mcp params
## Summary

On `main` (current HEAD `828d3a320`, after `4d7fc0f37`), `hermes --tui` fails to build out of the box with a TypeScript error. First invocation on a fresh install dies during the auto-build step:

```
❯ hermes --tui
Installing TUI dependencies…
TUI build failed.
> hermes-tui@0.0.1 build
> npm run build --prefix packages/hermes-ink && tsc -p tsconfig.build.json && npm run build:compile && chmod +x dist/entry.js

> @hermes/ink@0.0.1 build
> esbuild src/entry-exports.ts --bundle --platform=node --format=esm --packages=external --outfile=dist/ink-bundle.js

src/app/slash/commands/ops.ts(86,9): error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

  dist/ink-bundle.js  416.8kb

⚡ Done in 21ms
```

`dist/entry.js` is never produced → subsequent `hermes --tui` attempts re-run `npm run build` and fail the same way. TUI is effectively unusable on current `main`.

## Environment

- hermes-agent `main` @ 828d3a320 (PR context)
- macOS 14, Node v22.22.2, npm 11.6.4
- Clean `node_modules` (post `npm install`)

## Root cause

`ui-tui/src/app/slash/commands/ops.ts` (introduced in 4d7fc0f37):

```ts
const params: { session_id: string; confirm?: boolean; always?: boolean } = {
  session_id: ctx.sid
}
```

But in `ui-tui/src/app/slash/types.ts`:

```ts
sid: null | string
```

Every other slash command that forwards `ctx.sid` — `prompt.background`, `config.set`, `session.compress`, `session.branch`, `image.attach` in `session.ts` — just passes it through without type-narrowing; the gateway already handles a null session_id. `ops.ts` is the outlier that declares the narrower `string`, so strict TS rejects the assignment.

## Fix

Widen the param type to `string | null` to match the rest of the codebase and the actual `ctx.sid` type. PR: **#NNN** *(replace with link)*.

## Regression

Introduced in `4d7fc0f37` — `feat(gateway,cli): confirm /reload-mcp to warn about prompt cache invalidation`.

Probably slipped through because the TUI dev loop (`npm run dev` → `tsx --watch`) doesn't run `tsc -p tsconfig.build.json`, so the stricter build-time typecheck never fires until end users hit `hermes --tui`'s on-demand build path.

### PR DESCRIPTION
**Pull request by Heltman**
Fixes #17773.

## Problem

`hermes --tui` fails to build on current `main` because the `/reload-mcp` slash command declares its params with a non-nullable `session_id: string`, but `ctx.sid` is typed as `string | null`:

```
src/app/slash/commands/ops.ts(86,9): error TS2322: Type 'string | null' is not assignable to type 'string'.
```

First invocation on a fresh install dies during the auto-build step; `dist/entry.js` is never produced; TUI is effectively unusable.

## Fix

Widen the param type to `string | null` to match `ctx.sid` and the convention used by every other slash command that forwards the session id (e.g. `session.ts` — `prompt.background`, `config.set`, `session.compress`, `session.branch`, `image.attach` all just spread `session_id: ctx.sid` without narrowing, and the gateway already handles null).

Smallest correct change; no runtime behavior difference.

## Verification

```
cd ui-tui && npm run build   # now clean
hermes --tui -z "smoke test" # → responds normally
```

## Regression introduced in

`4d7fc0f37` — `feat(gateway,cli): confirm /reload-mcp to warn about prompt cache invalidation`. The TUI dev loop (`tsx --watch`) skips `tsc -p tsconfig.build.json`, so the build-time typecheck only fires when end users hit the launcher's on-demand build path. A CI job running `npm run build` on the TUI would catch future regressions of this class.

### CODE REVIEW

**Comment by teknium1** [comment]
Thanks @Heltman — this was already fixed on `main` in #17836 (`fd0796947`) as part of a CI stabilization batch, landed a few hours before your PR. The fix on `main` is the same one-line widen you proposed (`session_id: string | null` in ops.ts line 85).\n\nYour diagnosis was spot-on — same regression commit (`4d7fc0f37`), same fix direction. Crediting you here; closing as superseded.\n\nIssue #17773 can be closed as well.
