### PR TITLE
fix(web): remove deprecated baseUrl from tsconfig.app.json for TS 5.9

### LINKED ISSUE #35685: web UI build: TS `baseUrl` deprecated in tsconfig.app.json breaks tsc -b (TypeScript 5.9)
### Bug description

`web/tsconfig.app.json` uses `"baseUrl": "."` on line 20, which is deprecated in TypeScript 5.9 and causes `tsc -b` to fail during the web UI build step.

```
tsconfig.app.json(20,5): error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0.
```

TypeScript 5.9 treats deprecations as errors in `tsc -b` mode, so the build fails before `vite build` ever runs.

### Steps to reproduce

```bash
cd web
npm run build   # or: tsc -b
```

This happens regardless of `NODE_ENV` — it is a code incompatibility between the committed `tsconfig.app.json` and the TypeScript version in `package.json` (`~5.9.3`).

### Expected behaviour

`tsc -b` succeeds and proceeds to `vite build`.

### Actual behaviour

`tsc -b` exits with code 2, build fails.

### Environment

- Hermes: v0.15.1
- TypeScript: 5.9.3 (from `web/package.json` devDependencies)
- OS: WSL2 Ubuntu 24.04 (but issue is OS-independent)

### Fix

Simply remove `"baseUrl": "."` from `web/tsconfig.app.json`. With `moduleResolution: "bundler"`, the `paths` configuration resolves correctly without `baseUrl`:

```diff
     /* Path aliases */
-    "baseUrl": ".",
     "paths": {
       "@/*": ["./src/*"]
     },
```

After this change, `tsc -b` succeeds and `vite build` runs to completion (verified locally).

Note: the error message suggests adding `"ignoreDeprecations": "6.0"` — but this does NOT work on TS 5.9 (produces `TS5103: Invalid value for '--ignoreDeprecations'`).

### PR DESCRIPTION
**Pull request by liuhao1024**
## What does this PR do?

Removes the deprecated `baseUrl` option from `web/tsconfig.app.json`, which causes `tsc -b` to fail with TS5101 on TypeScript 5.9.

## Related Issue

Fixes #35685

## Type of Change

- [x] 🐛 Bug fix (non-breaking change that fixes an issue)

## Changes Made

- `web/tsconfig.app.json`: Removed `"baseUrl": "."` — with `moduleResolution: "bundler"`, the `paths` configuration resolves correctly without `baseUrl`.

## How to Test

1. `cd web && npm install`
2. `npx tsc -b` — should succeed (currently fails with TS5101)
3. `npm run build` — should complete without errors
4. Verify `@/*` path alias still resolves: `grep -r 'from "@/' src/ | head -5` should import correctly

### Code

- [x] I've read the [Contributing Guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md)
- [x] My commit messages follow [Conventional Commits](https://www.conventionalcommits.org/) (`fix(scope):`, `feat(scope):`, etc.)
- [x] I searched for [existing PRs](https://github.com/NousResearch/hermes-agent/pulls) to make sure this isn't a duplicate
- [x] My PR contains **only** changes related to this fix/feature (no unrelated commits)
- [x] I've run `npx tsc -b` and it passes with this change
- [x] I've added tests for my changes — N/A (config-only change, tsc -b success is the test)
- [x] I've tested on my platform: macOS

### Documentation & Housekeeping

- [x] I've updated relevant documentation — N/A
- [x] I've updated `cli-config.yaml.example` — N/A
- [x] I've updated `CONTRIBUTING.md` or `AGENTS.md` — N/A
- [x] I've considered cross-platform impact (Windows, macOS) — N/A (TypeScript version-specific)
- [x] I've updated tool descriptions/schemas — N/A

## Code Intelligence

- Analyzed: `web/tsconfig.app.json` (single config file, no callers)
- Blast radius: LOW — only affects TypeScript compilation of the web UI
- Related patterns: `moduleResolution: "bundler"` resolves `paths` without `baseUrl` since TS 5.0

### CODE REVIEW

**Comment by teknium1** [comment]
Thanks for the focused TypeScript compatibility fix.

Automated hermes-sweeper review found that current `main` already contains this exact deletion:

- `web/tsconfig.app.json:20` now begins the `paths` mapping without a `baseUrl` entry.
- Commit `3bfbb3f2a0255acfd2cf8e18d702c0b291808047` (`change(tooling): typecheck in CI, update ts to 6`) removed the same line while updating the dashboard to TypeScript 6.
- That commit shipped in `v2026.6.19`.

Closing as implemented on main.
