### PR TITLE
fix(gateway): cross-platform process start-time for scoped-lock PID-reuse guard

### LINKED ISSUE #16586: Stale gateway lock files never cleared on macOS — process-start-time check is Linux-only
## Summary

On macOS, `acquire_scoped_lock()` in `gateway/status.py` cannot detect stale lock files when a previous gateway crashed and the PID was recycled to an unrelated OS process. The lock then persists indefinitely, blocking the platform forever (Slack, Feishu, Discord, etc.) until the user manually `rm`s the lock file.

## Repro

1. macOS host running `ai.hermes.gateway` via launchd
2. Gateway crashes ungracefully (kill -9, OOM, panic)
3. The orphaned lock file at `~/.local/state/hermes/gateway-locks/<scope>-<hash>.lock` retains the dead gateway's PID
4. macOS recycles that PID to a different process (e.g. `FamilyControlsAgent`)
5. New gateway starts, calls `acquire_scoped_lock()` → existing record found
6. Stale check at `gateway/status.py:500-529`:
   - `os.kill(existing_pid, 0)` succeeds (the recycled PID **is** alive, just unrelated)
   - `start_time` mismatch is checked next, but `_get_process_start_time(pid)` reads `/proc/<pid>/stat` (Linux-only) → returns `None` on macOS → comparison short-circuits
   - Stopped-process check at line 519-528 also reads `/proc/<pid>/status` → no-op on macOS
7. `stale = False` → `return False, existing` → platform marks as `slack-app-token_lock` / `feishu_app_lock` / etc., never recovers

In my case: the Slack lock file's `pid: 560` was written 2026-04-23. Days later, PID 560 had been recycled to `FamilyControlsAgent`. Hermes saw the alive PID and concluded another gateway held the token, even after dozens of restarts. Manually `rm`ing the lock file was the only fix.

## Affected code

`gateway/status.py`:
- `_get_process_start_time()` (lines 106-113) — only works on Linux
- `acquire_scoped_lock()` stale-detection block (lines 500-529) — relies entirely on `/proc/*` files for the strong check; PID-existence-only is insufficient on macOS

## Suggested fixes (any one, or layered)

1. **Use `psutil`** (already a transitive dep via `discord.py`/aiohttp ecosystems? if not, add it). `psutil.Process(pid).create_time()` works cross-platform and gives epoch seconds. Compare against the lock file's stored `start_time`.

2. **Use `proc_pidinfo` via `ctypes`** if avoiding `psutil`. macOS exposes `proc_pidinfo(pid, PROC_PIDTBSDINFO, ...)` returning `pbi_start_tvsec` — equivalent of Linux's start_time field.

3. **Add a max-age fallback**: if the lock file's `updated_at` is older than e.g. 24h, treat as stale regardless of PID liveness. Cheap, no syscalls, defensive.

4. **Compare cmdline**: read `/proc/<pid>/cmdline` on Linux or `ps -p <pid> -o command=` on macOS — if it doesn't contain `hermes` / `gateway` / etc., treat as stale.

(3) alone would unblock most users. (1) is the right architectural fix.

## Operational impact today

Without this fix, every macOS user who experiences a single ungraceful shutdown of hermes is one PID-recycle away from a permanently broken Slack/Feishu/Discord platform until they figure out the lock file path and `rm` it. The error message blames a PID that has nothing to do with the actual issue ("Slack app token already in use (PID 560). Stop the other gateway first.") which sends users hunting for a phantom process.

## Environment

- macOS 26.4.1 (Darwin 25.4.0, arm64)
- hermes-agent commit `283c8fd6` (Apr 2026)
- Python 3.11
- launchd-managed via `~/Library/LaunchAgents/ai.hermes.gateway.plist`

## Related

The same root-cause produces:
- `slack-app-token_lock` errors blaming dead/recycled PIDs
- `feishu_app_lock` errors with the same pattern
- General "platform fatal" states that don't recover across restarts

### PR DESCRIPTION
**Pull request by banditburai**
## Summary

The gateway's scoped-lock PID-reuse guard was effectively Linux-only. `_get_process_start_time` read `/proc/<pid>/stat` and returned `None` on any platform without `/proc`, so locks and markers stored `start_time: null` on macOS and Windows and the PID-reuse check was silently skipped. Once the OS recycled a recorded gateway PID into an unrelated process, the dead lock looked live and the adapter was blocked indefinitely — under launchd/systemd `KeepAlive` this turned into an endless restart-and-fail loop, and `hermes gateway run --replace` could no longer reclaim the token.

This switches the start-time source to `psutil.Process(pid).create_time()`, which works on all three platforms, and stores it as epoch microseconds in a new `start_time_us` field. The only production change is in one file, `gateway/status.py`.

## Root cause

- `_get_process_start_time` read only field 22 of `/proc/<pid>/stat`, so it returned `None` on macOS and Windows (`gateway/status.py:111`).
- With a null start time, the staleness check can only test PID liveness. `os.kill(pid, 0)` succeeds for a recycled PID — it really is alive, just unrelated — so the lock is treated as held forever.
- In practice the recycled PID lands on a launchd system agent (`FamilyControlsAgent`, `CloudDocs`, `TipsWidgetExtension`, `intelligentroutingd`, `TextInputMenuAgent`), and the user sees an error blaming a process that has nothing to do with Hermes.
- Under launchd/systemd `KeepAlive` the blocked adapter restart-fails forever, and `--replace` becomes a no-op.

## The fix

- `psutil.Process(pid).create_time()` rounded to epoch microseconds (`round(... * 1_000_000)`), identical on Linux/macOS/Windows (`gateway/status.py:127`). `psutil` is already a hard dependency; the import is guarded only so a broken environment fails safe to `None` rather than raising.
- The value is stored in a new field, `start_time_us` (`:224`); markers use `target_start_time_us` (`:862`, `:910`).
- The old `start_time` / `target_start_time` fields are written as explicit `null` rather than removed (`:222`, `:861`, `:909`). This is deliberate — see below.
- No `/proc` jiffies fallback and no schema version field. Both are intentional and explained in the next section.

## Why store a new field and null the old one

The hard requirement is that this must never evict a **live** gateway's lock, including when an old and a new binary read each other's records (rollback, a half-finished upgrade, two installs sharing a lock directory). Two choices make that safe:

**Nulling the legacy field (instead of removing it) protects against an old binary reading a new record.** A pre-fix binary only marks a lock stale when its `start_time` is a non-null integer that differs from the live value. A new record writes `start_time: null`, so the old binary skips that branch and falls through to its existing cmdline check, which recognises the live gateway and keeps the lock. If we had left a real integer in that field, an old binary reading a new record after a reboot could wrongly evict it — which is exactly the case the null guards against.

**Routing to the cmdline check whenever `start_time_us` is missing protects against a new binary reading an old record.** An old record has no `start_time_us`, so the new code never compares a Linux jiffies value against a psutil microsecond value (different units, guaranteed mismatch, wrong eviction). When the field is absent on either side, the code uses the cmdline/argv check instead. This same path also covers the case where psutil can't read a live process (e.g. `AccessDenied` on a system PID).

Across every old/new combination, the result is either a correct start-time comparison or the cmdline check — never a wrongful eviction of a live gateway.

## How eviction decides (`acquire_scoped_lock`, `gateway/status.py:616`)

- PID no longer exists → stale.
- Both start times present → stale when they differ (`:636`).
- Either side missing → fall back to the cmdline/argv check; only evict when both the live cmdline and the recorded argv look like something other than a gateway (`:637`).

One behaviour change worth flagging for reviewers: when a record has `start_time_us` but psutil can't read the live process, the old code kept the lock; the new code falls back to the cmdline check. That can only evict a PID whose live identity doesn't look like a gateway, so it's safer, not riskier.

## Where the field is read and written

Every site that previously used `start_time` now uses `start_time_us`:

- `acquire_scoped_lock` — self-owned short-circuit (`:622`) and eviction (`:631`, `:636`).
- `release_scoped_lock` (`:693`) — this one matters: comparing the now-null legacy field against a live microsecond value would refuse to unlink and leak the lock. It now reads `start_time_us`.
- `release_all_scoped_locks` (`:735`).
- `get_running_pid` (`:1026`).
- The takeover and planned-stop markers — write, consume, and probe (`:862`, `:886`, `:910`, `:925`, `:955`).
- `gateway/run.py:18732` is unchanged but stays consistent: it calls the public `get_process_start_time` (which now returns microseconds) and passes the result as `owner_start_time`, compared against the record's `start_time_us` — same units on both sides.

The only remaining write of the old `start_time` field is the intentional `null`.

## A note on the marker fallback

When both a marker and the current process have an unknown start time, the markers (`_consume_pid_marker_for_self`, `planned_stop_marker_targets_self`, `:985`) fall back to matching on PID alone, bounded by the marker's short TTL. This is required so a normal `hermes gateway stop` isn't misread as an unexpected exit and revived by the service manager (#34597, #33778). The migration actually shrinks the window for this fallback, since macOS now usually has a real start time and takes the strict comparison instead.

## Out of scope

- The merged #24610 cmdline/argv check is reused unchanged.
- The Linux-only stopped-process (`T`-state) check is left as-is and not ported to other platforms; the known split-brain edge there is a separate fix for later.

## Testing

```
uv run --extra dev python -m pytest \
  tests/gateway/test_process_start_time.py \
  tests/gateway/test_status.py \
  tests/gateway/test_planned_stop_watcher.py \
  tests/gateway/test_runner_startup_failures.py
```

89 passed with `psutil 7.2.2` installed.

> **Run with `--extra dev`.** Without it, `psutil` isn't installed and `_get_process_start_time` returns `None`, so the suite can pass without ever exercising the fix. The unit tests inject a fake `psutil` and are platform-independent, but the integration assertions need the real dependency.

What's covered:

- microsecond conversion rounds rather than truncates
- psutil errors (`NoSuchProcess`, `AccessDenied`, `ZombieProcess`, `OSError`, `ValueError`) and a missing `psutil` all return `None`
- records write `start_time_us` and null the legacy field
- acquire: same process keeps its lock, a reused PID is evicted, and a legacy record without `start_time_us` falls back to the cmdline check instead of being wrongly evicted
- release: a process unlinks its own lock and refuses to unlink one whose start time doesn't match
- `release_all_scoped_locks` respects the owner start time
- `get_running_pid` skips a reused PID
- markers: write, consume, reject a reused PID, and the both-unknown PID-only fallback
- downgrade safety: a pre-fix reader does not wrongly evict a new record

## Scope

Five files: one production file (`gateway/status.py`, net −1 line) and four test files — `tests/gateway/test_process_start_time.py` (new), plus updates to `test_status.py`, `test_planned_stop_watcher.py`, and `test_runner_startup_failures.py`.

## Compatibility and regressions

- On Linux a live gateway always has a readable start time (psutil reads the same `/proc` data the old code did), so it takes the start-time comparison and never reaches the cmdline fallback. Behaviour is unchanged for live gateways and only changes for dead or reused PIDs.
- Dropping the jiffies value removes a latent issue: jiffies are measured from boot and can repeat across reboots; epoch microseconds can't.
- One caveat on the full `tests/gateway` run: there are ~70 pre-existing failures in `test_ws_auth_retry`, `test_wecom_callback`, and `test_telegram_slash_confirm` caused by a test-isolation problem with a mocked XML parser (`'NoneType' object has no attribute 'fromstring'`). They pass in isolation and share no code with `gateway/status.py`, so they're unrelated to this change.

## Known limitations and follow-ups

- The marker PID-only fallback (above) can still match a reused PID if psutil fails to read a start time within the marker's TTL. This is pre-existing behaviour and is narrower after this change, not wider.
- When given an `owner_start_time`, `release_all_scoped_locks` skips locks written by an older binary (no `start_time_us`). It only ever skips a foreign lock, never the caller's own, and such locks are still reclaimed when the scope is next contended.
- PR #24595 included a `psutil.Process.name()` pre-filter and a `shutil.which("ps")` guard. Neither is needed for correctness (the cmdline match is authoritative), so they were left out; they'd make reasonable follow-ups.
- There's no schema version field, so a future reader can't tell "old record, never had a start time" apart from "new record, psutil returned None." Both fall back to the cmdline check, which is the safe behaviour either way.

## Closes

| Issue | Adapter | Recycled PID | How it's fixed |
|---|---|---|---|
| #16586 | Slack | FamilyControlsAgent | `create_time()` populates `start_time_us` cross-platform, so the PID-reuse guard runs on macOS |
| #18778 | Telegram | intelligentroutingd | the start-time guard was a no-op off-Linux; `start_time_us` makes it fire |
| #21596 | Slack (`--replace` loop) | TipsWidgetExtension | with the guard working, the reused PID is evicted so `--replace` can reclaim the token |
| #21613 | Telegram | start_time=null false positive | `start_time_us` is now non-null on macOS, so PID reuse is detected instead of accepted |
| #24067 | Telegram / Feishu / WeChat | CloudDocs (system process on the same PID) | the start-time mismatch is detected cross-platform; the fix is in the shared `status.py` helper, not `base.py` as the issue guessed |
| #31890 | Weixin | TextInputMenuAgent | `start_time_us` populated cross-platform; a null start time no longer blocks adapters |

## Supersedes

| PR | Approach | Difference here |
|---|---|---|
| #16423 | cmdline check only | doesn't fix the underlying start-time read; this keeps the cmdline check as a fallback and fixes the root cause |
| #22490 | psutil `create_time` but keeps the `/proc` jiffies fallback in the same field | mixing units in one field can misfire; this drops the fallback and nulls the old field |
| #24595 | psutil (ms) + cmdline + `name()` pre-filter + `which("ps")` guard | same core idea at microsecond precision; the pre-filter and guard are optional and noted above as follow-ups |
| #31923 | `ps lstart` string hashed to an int (`Union[int, str]` threaded through, locale-sensitive) | epoch-microsecond `int` is simpler and more robust; keeps the same "trust the live cmdline over the recorded argv" behaviour |

---

Closes #16586, #18778, #21596, #21613, #24067, #31890
Supersedes #16423, #22490, #24595, #31923

### CODE REVIEW

**Comment by alt-glitch** [comment]
Competing with #24595 and #31923 — all three use `psutil.Process.create_time()` to replace the Linux-only `/proc/<pid>/stat` reader in `gateway/status.py`. This PR is the most comprehensive (adds `start_time_us` field migration, stronger test coverage across 5 test files). Related issue: #18778.

**Review by tonydwb — APPROVED** [review]
## Code Review Summary

**Verdict: Approved** ✅

### Reviewed Changes
Cross-platform scoped-lock PID-reuse guard. Switches from `/proc/<pid>/stat` (Linux-only) to `psutil.Process(pid).create_time()` in epoch microseconds. Stores new `start_time_us` field; nulls legacy field for safe old-vs-new binary compatibility.

### ✅ Looks Good
- Root cause: `_get_process_start_time` returned None on macOS/Windows, so PID-reuse guard was silently skipped.
- Migration-safe: nulled legacy field protects old binaries reading new records; absent field triggers cmdline fallback for new binaries reading old records.
- 89 tests pass. Cross-platform tested.
- Closes 6 macOS issues (#16586, #18778, #21596, #21613, #24067, #31890).
- Well-documented design decisions and compatibility analysis.

---
*Reviewed by Hermes Agent*

**Comment by teknium1** [comment]
Thanks for the careful migration and compatibility analysis.

Automated hermes-sweeper review found that current `main` already provides the requested cross-platform PID-reuse protection:

- `gateway/status.py:157-170` falls back from `/proc/<pid>/stat` to `psutil.Process(pid).create_time()` and returns a stable integer on macOS/Windows.
- `tests/gateway/test_status.py:698-714` forces `/proc` unavailable and verifies that fallback is non-null and stable.
- This shipped in `012f40c98c18b6723e355abbba7544b752836276` (`fix(status): cross-platform start-time fingerprint via psutil fallback`), included in `v2026.7.1`.

Closing as implemented on main.
