### ISSUE TITLE
web UI build: TS `baseUrl` deprecated in tsconfig.app.json breaks tsc -b (TypeScript 5.9)

### ISSUE THREAD

**Issue by HeYiDuQingHuan** [NousResearch/hermes-agent#35685]
### Bug description

`web/tsconfig.app.json` uses `"baseUrl": "."` on line 20, which is deprecated in TypeScript 5.9 and causes `tsc -b` to fail during the web UI build step.

```
tsconfig.app.json(20,5): error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0.
```

TypeScript 5.9 treats deprecations as errors in `tsc -b` mode, so the build fails before `vite build` ever runs.

### Steps to reproduce

```bash
cd web
npm run build   # or: tsc -b
```

This happens regardless of `NODE_ENV` — it is a code incompatibility between the committed `tsconfig.app.json` and the TypeScript version in `package.json` (`~5.9.3`).

### Expected behaviour

`tsc -b` succeeds and proceeds to `vite build`.

### Actual behaviour

`tsc -b` exits with code 2, build fails.

### Environment

- Hermes: v0.15.1
- TypeScript: 5.9.3 (from `web/package.json` devDependencies)
- OS: WSL2 Ubuntu 24.04 (but issue is OS-independent)

### Fix

Simply remove `"baseUrl": "."` from `web/tsconfig.app.json`. With `moduleResolution: "bundler"`, the `paths` configuration resolves correctly without `baseUrl`:

```diff
     /* Path aliases */
-    "baseUrl": ".",
     "paths": {
       "@/*": ["./src/*"]
     },
```

After this change, `tsc -b` succeeds and `vite build` runs to completion (verified locally).

Note: the error message suggests adding `"ignoreDeprecations": "6.0"` — but this does NOT work on TS 5.9 (produces `TS5103: Invalid value for '--ignoreDeprecations'`).

**Comment by liuhao1024** [comment]
This is fixed by [#35689](https://github.com/NousResearch/hermes-agent/pull/35689) — fix(web): remove deprecated baseUrl from tsconfig.app.json.

**Comment by teknium1** [comment]
This is resolved on current `main`; closing via automated hermes-sweeper review.

- Commit `3bfbb3f2a0255acfd2cf8e18d702c0b291808047` (`change(tooling): typecheck in CI, update ts to 6`) removed the deprecated `"baseUrl": "."` entry from `web/tsconfig.app.json`.
- Current `main` has the path aliases at `web/tsconfig.app.json:20` without `baseUrl`, while `web/package.json:8` still runs `tsc -b && vite build`.
- Thanks for the linked PR #35689, which identified the same focused fix.
