### PR TITLE
fix(agent): guard _is_copilot_url() with getattr to prevent AttributeError (#59845)

### LINKED ISSUE #59845: [Bug] Cron job fails with AttributeError: 'AIAgent' object has no attribute '_is_copilot_url' (intermittent, non-Copilot providers)
## Summary

`agent/conversation_loop.py:1164` calls `agent._is_copilot_url()` **without a `getattr` guard**, in a code path that can be reached by an agent object that isn't a fully-initialized `AIAgent`. When that happens, every API call in the conversation dies with `AttributeError: 'AIAgent' object has no attribute '_is_copilot_url'` and the cron job fails.

The sibling check one line up — `getattr(agent, "_is_user_initiated_turn", False)` — is already guarded. The Copilot URL check should be too, returning `False` on missing.

## Repro

- **Hermes build:** `ba3169909 chore(providers): remove dead cloudcode-pa quota-fallback branches` is HEAD at time of incident; the bug landed in `6f052b7ff fix(copilot): set x-initiator per turn so user prompts bill as premium requests (salvage #4097) (#58544)`.
- **Trigger:** any cron tick that reaches the API call site (e.g. inbox non-empty).
- **Determinism:** seen twice in a row at 12:47:34 and 13:07:54, then self-cleared on the next tick at 13:23:39 with a clean `last_status: ok`. **Intermittent** — most likely a module-reload / hot-reload window where the agent object loses the method binding, or a code path that constructs an agent-like wrapper. Worth investigating the construction path.
- **Stack:** Python 3.11.15 on macOS 26.5.1, Nous inference provider (`https://inference-api.nousresearch.com/v1`), model `minimax/minimax-m3`. Base URL is Nous, **not** Copilot — so the failing call is a no-op for any provider that isn't Copilot. The guard should short-circuit on missing attribute, not crash.

## Failing code site

`agent/conversation_loop.py:1164`:
```python
if getattr(agent, "_is_user_initiated_turn", False) and agent._is_copilot_url():
    _xh = dict(api_kwargs.get("extra_headers") or {})
    _xh["x-initiator"] = "user"
    api_kwargs["extra_headers"] = _xh
    agent._is_user_initiated_turn = False
```

**Suggested fix** (one-liner, same pattern as the sibling guard one line up):
```python
if getattr(agent, "_is_user_initiated_turn", False) and getattr(agent, "_is_copilot_url", lambda: False)():
    ...
```

## What the user sees in the cron job

- `last_status: error` on the job
- `cron/output/<job_id>/<ts>.md` contains `RuntimeError: 'AIAgent' object has no attribute '_is_copilot_url'`
- `logs/agent.log` shows three WARNINGs ("API call failed (attempt 1/3)", "(attempt 2/3)", "(attempt 3/3)") all with the same AttributeError, then a final ERROR with the same message after 3 retries
- `logs/errors.log` mirrors it
- A `request_dump_cron_<job_id>_<ts>_<ts>.json` is written showing the HTTP request that never went out (helpful for confirming it was an agent-side failure, not an upstream API error)

## Files / line numbers for the fix author

- **Method definition (the canonical one):** `run_agent.py:1324` — `_is_copilot_url`
- **Method definition (also exists in test mirror):** `tests/test_copilot_initiator.py:55-60` — the same block is duplicated in the test fixture's `_inject` helper, so the fix has to land in both spots or the test will diverge from prod.
- **Unguarded call site (bug):** `agent/conversation_loop.py:1164`
- **Test that asserts the unguarded call works:** `tests/test_copilot_initiator.py:55` — the test's `_inject` helper does the unguarded call. If the suggested fix lands in `conversation_loop.py`, the test should be updated the same way (or it should import the production helper).
- **Construction path that hits the bug:** `cron/scheduler.py:2947-2948` calls `AIAgent(...)` from `from run_agent import AIAgent` at line 2517, so on a normal cron tick the method *is* bound — meaning the bug only fires on a subset of construction paths. The unguarded call is still the right place to add the guard.

## Severity

- **Impact:** any cron job using the default LLM-driven path can fail closed on an unlucky tick, lose the inbox file (the script already returned `INBOX_HAS_FILES` to the agent), and have to wait for the next tick to recover. Bridge protocols with `needs_response: true` accumulate latency on the other party.
- **Severity:** medium — service degrades but doesn't crash, and self-heals on the next 5m tick. The right fix is defensive, not urgent.
- **User workaround:** none needed; the job recovers.

## Suggested repro recipe for CI

1. Construct an `AIAgent` instance where `_is_copilot_url` is missing (e.g. via `del AIAgent._is_copilot_url` or a stub subclass) while `_is_user_initiated_turn = True`.
2. Call `agent._build_api_kwargs(...)` and then the API-call block at `agent/conversation_loop.py:1164-1168`.
3. **Expected (after fix):** the block is a no-op because `getattr(..., lambda: False)()` returns `False`.
4. **Current (before fix):** raises `AttributeError: 'AIAgent' object has no attribute '_is_copilot_url'`.

## Context

- Introduced in #58544 (merged 2026-07-04), which salvaged #4097 to set the `x-initiator: user` header on the first API call of a user-initiated turn so Copilot bills premium requests correctly.
- Distinct from closed #3040 (that one was about the header not being set; this one is about the *call that sets it* crashing on non-Copilot providers).
- No existing issue found for `_is_copilot_url` AttributeError; no follow-up issue on PR #58544.

### PR DESCRIPTION
**Pull request by webtecnica**
## Summary

`agent/conversation_loop.py:1164` calls `agent._is_copilot_url()` without a `getattr` guard. The sibling property `_is_user_initiated_turn` is already guarded (line above), but the method call is not — causing `AttributeError` when the method is absent (certain construction paths / module-reload windows during cron jobs).

## Fix

Changed `agent._is_copilot_url()` → `getattr(agent, "_is_copilot_url", lambda: False)()` in both production (`conversation_loop.py`) and test (`test_copilot_initiator.py`).

## Files Changed

| File | Δ |
|------|---|
| `agent/conversation_loop.py` | +1/-1 line |
| `tests/test_copilot_initiator.py` | +1/-1 line |

Closes #59845

### CODE REVIEW

**Comment by webtecnica** [comment]
@teknium1 2-line fix — cron jobs no longer crash with AttributeError on non-Copilot providers. Same getattr pattern as sibling guard. Closes #59845. 🙏

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #59847 — byte-identical fix (same `getattr(agent, "_is_copilot_url", lambda: False)()` guard at `agent/conversation_loop.py:1164` + the mirror edit in `tests/test_copilot_initiator.py`). #59847 is the earliest open PR for #59845; keeping it as canonical. See also the twin #59972.

**Comment by webtecnica** [comment]
Closing as duplicate — the sweeper identified this as already covered by another PR. Thanks for the contribution!
