### PR TITLE
test(web_server): skip host-header tests when fastapi/uvicorn absent

### PR DESCRIPTION
**Pull request by briandevans**
## Summary
- Adds a module-level import probe in \`test_web_server_host_header.py\`
- Uses \`pytestmark\` to skip all 8 tests when fastapi/uvicorn are absent (instead of failing with SystemExit)

## The bug
\`hermes_cli.web_server\` raises \`SystemExit\` at module import time when \`fastapi\`/\`uvicorn\` are not installed. \`test_web_server_host_header.py\` imports directly from the module inside each test method, so on installs without the optional deps all 8 tests fail with:

\`\`\`
SystemExit: Web UI requires fastapi and uvicorn.
Install with: ... -m pip install 'fastapi' 'uvicorn[standard]'
\`\`\`

This masks the real test result and inflates CI failure counts alongside the unrelated baseline failures.

## The fix
A module-level try/except wraps the import probe once. The resulting \`_WEB_SERVER_AVAILABLE\` flag drives a \`pytestmark = pytest.mark.skipif(...)\` that applies to both \`TestHostHeaderValidator\` and \`TestHostHeaderMiddleware\`, converting the 8 failures into 8 clean skips.

The guard pattern is identical to the one used in \`test_web_server.py\` (see also #16518).

## Test plan
- [x] **Before**: 8 \`FAILED\` with \`SystemExit\` on env without fastapi
- [x] **After**: 8 \`SKIPPED\` cleanly; no failures
- [x] **Regression guard**: removed the try/except → observed 8 failures with SystemExit; restored → 0 failures
- [x] Adjacent suites unchanged

## Related
- Companion to #16518 (same fix pattern, different test file)
- Introduced by 244ae6db1 which added \`test_web_server_host_header.py\` without a fastapi skip guard

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by briandevans** [comment]
@Copilot Finding addressed in commit `da922a7be`:

**Finding (line 27 — overly broad ImportError catch):** Narrowed from `except (ImportError, SystemExit)` to `except SystemExit`. `hermes_cli.web_server` already converts the fastapi ImportError into SystemExit at module-import time ([web_server.py:51-61](https://github.com/NousResearch/hermes-agent/blob/main/hermes_cli/web_server.py#L51-L61) — `except ImportError: raise SystemExit("Web UI requires fastapi and uvicorn...")`), so catching ImportError additionally only risks masking unrelated regressions in the import chain (e.g. a genuine break in `hermes_cli.config` or `gateway.status`).

**Bonus fix uncovered while addressing this:** narrowing the catch immediately surfaced a real `ImportError: cannot import name '__version__' from 'hermes_cli'` because `_repo = parents[1]` was the `tests/` directory, putting the empty `tests/hermes_cli/__init__.py` ahead of the real package on sys.path. Fixed to `parents[2]` to match every other test in [tests/hermes_cli/](https://github.com/NousResearch/hermes-agent/tree/main/tests/hermes_cli) (`test_setup_hermes_script.py`, `test_redact_config_bridge.py`, `test_launcher.py`). Under the previous broad catch this real ImportError was being silently swallowed as "fastapi/uvicorn not installed" even when fastapi was present — precisely the masked-failure scenario you flagged.

Verified locally: 8/8 tests pass when fastapi+uvicorn are installed; cleanly skip when those soft deps are absent.

**Comment by briandevans** [comment]
Closing to keep the queue clean — happy to reopen if this is still useful.
