### ISSUE TITLE
Bug: title_generation fails on DeepSeek provider — HTTP 400 "This response_format type is unavailable now"

### ISSUE THREAD

**Issue by liuyonghao156** [NousResearch/hermes-agent#84976]
## Summary

Since the title-generation rewrite in v0.20.0, every new session that resolves the
`title_generation` auxiliary task to a DeepSeek model fails with:

```
Auxiliary title generation failed: HTTP 400: This response_format type is unavailable now
```

DeepSeek is an officially supported provider (`DEEPSEEK_API_KEY`), so this hits any
user who points `title_generation` at DeepSeek — explicitly, or implicitly via
`provider: auto`, which falls back to the main model when no OpenRouter/Google key is
configured.

## Root cause

`agent/title_generator.py::generate_title()` hard-codes an OpenAI-style
structured-output constraint on every call:

```python
extra_body={"response_format": _TITLE_RESPONSE_FORMAT}
```

where `_TITLE_RESPONSE_FORMAT` is `{"type": "json_schema", "json_schema": {...}}`
(strict schema for a single `title` field). Introduced in commit f726090d4
("feat(sessions): name a session the moment it starts", 2026-08-08). Before that
commit the request carried no `response_format` at all — the prompt asked for JSON
and `_extract_title_text()` parsed the reply defensively.

DeepSeek's API does not implement the `json_schema` response_format type; it only
supports `{"type": "json_object"}`. The server rejects the request before inference:

```json
{"error":{"message":"This response_format type is unavailable now",
          "type":"invalid_request_error","code":"invalid_request_error"}}
```

## Reproduction (curl against https://api.deepseek.com/chat/completions)

1. `response_format` = `{"type":"json_schema", ...}`  → HTTP 400 (the failure above)
   - model `deepseek-v4-pro`   → 400
   - model `deepseek-v4-flash` → 400
2. `response_format` = `{"type":"json_object"}`        → HTTP 200, valid JSON
3. no `response_format`                                → HTTP 200

For contrast, `alibaba/qwen3.5-flash` accepts the identical `json_schema` payload and
returns 200.

## Environment

- Hermes v0.20.0 (2026.8.3), git HEAD c5097da1, pulled 2026-08-13
- Linux, local CLI (reproduces on gateway and on every profile, including
  `provider: auto` configs)
- `auxiliary.title_generation`: provider `deepseek`, model `deepseek-v4-pro`
  (`deepseek-v4-flash` fails identically)

## Impact

- The warning is emitted on every new session (CLI + gateway) for every DeepSeek
  user of the title feature. Titles silently degrade to the deterministic "derived"
  fallback, so nothing crashes, but the LLM upgrade stage is dead on this provider.
- The same `json_schema` pattern, if it spreads to other auxiliary tasks that can
  route to DeepSeek, would break them too.

## Suggested fix

Provider-aware downgrade at the transport layer. `json_schema` is the right default
for providers that implement it — it eliminated the whole class of "model answered
the prompt instead of titling it" failures, please keep it — but for providers that
only implement `json_object` (DeepSeek), either:

a) translate the constraint to `{"type": "json_object"}` (DeepSeek honors it —
   verified 200; the title prompt already contains the word "JSON" as required by
   most `json_object` implementations), or
b) strip `response_format` entirely and rely on the existing defensive parse chain
   in `_extract_title_text()` (fenced JSON → `json.loads` → loose regex → prose
   fallback), which is exactly how this worked before the rewrite.

Option (a) is the smallest diff and preserves the anti-preamble benefit plus the
`max_tokens=64` budget. A per-provider capability table (which providers support
`json_schema` vs `json_object` vs neither) would prevent this regression class for
other providers as well.

## Workaround (for users hitting this today)

Point the title slot at a json_schema-capable provider, e.g.:

```
hermes config set auxiliary.title_generation.provider alibaba
hermes config set auxiliary.title_generation.model qwen3.5-flash
```

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #83390: both reports identify DeepSeek rejecting the title-generation json_schema response_format with the same HTTP 400. Keeping #83390 as the canonical report/spec.

**Comment by upmeister** [comment]
Same failure on OpenCode Go (opencode.ai/zen/go/v1, Console Go upstream), model deepseek-v4-flash, since the 2026-08-09 update. Observed behavior:

- All LLM title upgrades fail with HTTP 400 `This response_format type is unavailable now`; sessions keep the stage-1 derived title (first message fragment).
- It **flaps**: brief windows where json_schema is accepted (e.g. ~13:00-13:04 on 2026-08-10), then 400 again. So it's not a permanent 'unsupported' — looks like upstream availability.
- Confirmed with raw curl (stream and non-stream): both 400 with the same message.

Local workaround (applied here, 20-line patch in `agent/title_generator.py`): on exception whose text contains 'response_format', retry the call once **without** `extra_body={"response_format": ...}`. `_extract_title_text` already falls back to a loose JSON scan / first-line prose, so the title still comes out usable. Suggested upstream fix: same retry-once-without-response_format fallback (or json_object instead of json_schema when the provider rejects it).

**Comment by kvnloo** [comment]
Ready to close — already labeled `duplicate`. Listed in the close table: https://github.com/NousResearch/hermes-agent/issues/109552

This account cannot close tickets here. The author or a maintainer can close this copy; keep the canonical named in triage.
