### PR TITLE
fix(dashboard): yield event loop after WebSocket accept in pty_ws handler

### LINKED ISSUE #19914: Dashboard TUI WebSocket handshake hangs on FastAPI 0.136 — /api/pty times out
## Bug Description

When running `hermes dashboard --tui`, the WebSocket connection to `/api/pty` hangs and times out during the opening handshake. The browser console shows:

```
WebSocket connection to ws://host:9119/api/pty?token=... failed
```

The HTTP portion works fine (GET / returns 200, GET /api/ws upgrades successfully), but `/api/pty` never completes the WebSocket upgrade — the server-side ws.accept() call appears to block indefinitely.

## Environment

- **Hermes version**: v0.12.0
- **Python**: venv at /root/.hermes/hermes-agent/venv/bin/python3
- **FastAPI**: 0.136.0
- **OS**: Linux (Ubuntu-based)
- **Deployment**: standalone (not Docker)

## Steps to Reproduce

1. Run `hermes dashboard --tui`
2. Open browser at http://server:9119
3. Click the **Chat** tab
4. Observe browser console error: WebSocket connection to /api/pty failed
5. The chat area shows [Session ended] — no input possible

## Technical Details

- `curl -v -H Upgrade: websocket ... http://127.0.0.1:9119/api/pty` — connection is accepted but HTTP 101 never returned — hangs
- Using websockets Python library to test locally: websockets.connect() to /api/pty — times out after open_timeout
- /api/ws endpoint works correctly — WebSocket handshake completes fine
- The issue appears to be in the PTY bridge code path — PtyBridge.spawn() seems to block before ws.accept() is called

## Probable Cause

FastAPI 0.136.0 may have a regression where calling ws.accept() inside a WebSocket handler that uses run_in_executor for a synchronous blocking operation (PtyBridge spawn) causes the handshake to hang.

## Expected Behavior

The Chat tab in the dashboard should display a working terminal/chat interface, allowing the user to type messages and interact with the agent — same as `hermes --tui` in the terminal.

## Workaround

Running `hermes --tui` via SSH terminal works fine. The bug is specifically in the WebSocket PTY bridge embedded in the web dashboard.

### PR DESCRIPTION
**Pull request by elmatadorgh**
Fixes #19914
Refs #22864, #21948

## Summary

The /api/pty WebSocket handler runs synchronous PTY/TUI startup (_resolve_chat_argv, PtyBridge.spawn) immediately after `await ws.accept()`. On slower hosts this blocks the event loop long enough that uvicorn never flushes the HTTP 101 Switching Protocols response before the client times out:

    InvalidMessage: did not receive a valid HTTP response

Adding `await asyncio.sleep(0)` right after `accept()` yields once so uvicorn drains the handshake before the synchronous PTY spawn re-takes the loop.

## Why this approach

Aware of the prior attempts in this area:

- **#19938** (open, unreviewed since 2026-05-04) diagnoses the issue as a FastAPI 0.136 close-before-accept regression and reorders accept() above close() in early-return paths. That doesn't address the success-path race — the spawn after a successful accept still blocks the loop.
- **#19943** (closed by the author via automation, deferring to #19938 — never reviewed) had the correct diagnosis ("running them inline starved uvicorn's websockets task so the HTTP 101 upgrade was never flushed") and wrapped `_resolve_chat_argv` and `PtyBridge.spawn` in `loop.run_in_executor(...)`.

The executor approach in #19943 works but is heavier than necessary: it moves blocking work off the loop entirely. The simpler shape is to keep the work on the loop and just yield once so uvicorn can flush the upgrade response — which is exactly what the issue submitter in #22864 verified locally.

This PR implements that one-line yield. Out of scope for this PR but worth a separate look: two other accept() call sites in the same file (lines ~3283 and ~3312) have a similar shape but their post-accept work is async, so they're not affected by this race.

## Tests

Adds `test_pty_ws_yields_to_event_loop_before_spawn` to `TestPtyWebSocket` in `tests/hermes_cli/test_web_server.py`. The test monkeypatches `asyncio.sleep` and `PtyBridge.spawn` to record calls into a shared list (filtered to the pty_ws frame to avoid capturing internal asyncio yields), connects via TestClient, and asserts the call ordering is exactly `["sleep_zero", "spawn"]`.

The test is skipped on Windows along with the rest of the `TestPtyWebSocket` class (PtyBridge is POSIX-only). Local verification on POSIX wasn't available; the test was reasoned through against the existing class conventions and will be verified on the Linux CI runner.

## How to test

Run the new test:

    pytest tests/hermes_cli/test_web_server.py::TestPtyWebSocket::test_pty_ws_yields_to_event_loop_before_spawn -v

Manual repro from #22864:

    hermes dashboard --host 127.0.0.1 --port 9119 --no-open --tui

Then connect a WebSocket client to /api/pty with the session token. Without the fix on a slow-spawn host, the handshake times out with `InvalidMessage: did not receive a valid HTTP response`. With the fix, the upgrade completes and PTY bytes start streaming.

### CODE REVIEW

**Comment by elmatadorgh** [comment]
Quick note on the red checks for the maintainer's reference:

**Tests / test** — the new test in this PR (`test_pty_ws_yields_to_event_loop_before_spawn`) passed. The 5 failures in this job are pre-existing on main:

- `test_restart_drain.py::test_restart_command_while_busy_requests_drain_without_interrupt` — the i18n string mismatch lines up with 7df611519 ("feat(gateway): also gate pre-restart Gateway restarting notification") plus the broader notification-mode changes in 448c11f16 / 236f3b052. The test wasn't updated to match.
- 3x `test_tts_media_routing.py` failures — the centralization refactor in #17833 (aa7bf329b "feat(gateway): centralize audio routing + FLAC support + Telegram doc fallback") didn't update the consumer tests. The error `'object' object has no attribute '_thread_metadata_for_source'` matches that surface.
- `test_async_httpx_del_neuter.py::test_same_key_replaces_stale_loop_entry` — likely the httpx import-deferral work in #22831 (550f6e2ef "perf(teams): defer httpx import to first webhook call"), which would shift what's in `sys.modules` when the test runs.

None of these tests import `hermes_cli/web_server.py` or touch the `/api/pty` path.

**Tests / e2e** — 9 failures all in `tests/e2e/test_platform_commands.py` (3 tests × 3 platforms via parametrization). Broken by #22687 (b9c001116 "feat: confirm prompt for destructive slash commands"): `/new` now goes through a confirm-then-execute step, but those tests still assert one-shot dispatch of `reset_session`.

**Lint (ruff + ty)** — the failure is the `actions/github-script` comment-post step at the end of the advisory `lint-diff` job hitting 403 (fork PRs can't write PR comments via `GITHUB_TOKEN`). The actual lint steps use `--exit-zero` and the blocking `ruff check .` passes locally on the full tree.

Happy to address anything specific if I missed something.

**Comment by teknium1** [comment]
Thanks for the focused investigation and regression test. This is an automated hermes-sweeper review: the dashboard PTY startup race is already addressed on current `main` with a stronger implementation.

- `d06104a9ee163e6369d3870f092de875b2f2ab0c` (`fix(dashboard): resolve chat TUI argv off event loop`, shipped in `v2026.6.19`) added `_resolve_chat_argv_async()`; it executes the potentially blocking resolver through `asyncio.to_thread()` at `hermes_cli/web_server.py:14650-14654`.
- `pty_ws` accepts the connection and awaits that wrapper at `hermes_cli/web_server.py:15372-15417`.
- The dashboard client supplies an attach token at `web/src/pages/ChatPage.tsx:799-810`; its normal `PtySessionRegistry.attach_or_spawn()` path offloads `PtyBridge.spawn` with `asyncio.to_thread()` at `hermes_cli/pty_session.py:159-165`.

This replaces the proposed single scheduling yield with off-loop startup work, so the behavioral goal is already implemented on main.
