### ISSUE TITLE
Photon Issue

### ISSUE THREAD

**Issue by UOD317** [NousResearch/hermes-agent#42454]
**Summary**
The Photon (iMessage) platform plugin is unusable on a fresh setup on current main. The sidecar pins spectrum-ts ^0.1.0 (→ 0.1.2), but that SDK's Spectrum Cloud host spectrum-cloud.photon.codes no longer exists (NXDOMAIN on public resolvers). spectrum-ts has since moved to 1.x (1.18.0, published 2026-05-31). Upgrading fixes connectivity, but the sidecar (written against 0.1.x) then breaks on the new space/send API.

**Environment**
hermes-agent main @ b5f8996c (v0.16.0), macOS 26, Node 22.22, Photon free tier.
**Repro**

1. hermes photon setup → hermes photon install-sidecar → enable the photon platform.
2. Gateway connect logs: photon = retrying — failed to start Photon sidecar: ... exited with code 1.
3. Sidecar stderr: TypeError: fetch failed ... [cause] getaddrinfo ENOTFOUND spectrum-cloud.photon.codes (at spectrum-ts/dist/providers/imessage/index.js fetchTokens).

**Root cause + evidence**

- plugins/platforms/photon/sidecar/package.json pins "spectrum-ts": "^0.1.0" → 0.1.2.
- In 0.1.2, SPECTRUM_CLOUD_URL defaults to spectrum-cloud.photon.codes:
- dig @1.1.1.1 spectrum-cloud.photon.codes → NXDOMAIN (same on 8.8.8.8).
- spectrum.photon.codes resolves but 404s the token path.
- npm view spectrum-ts version → 1.18.0 (photon-hq/spectrum-ts, 2026-05-31). Installing it, the sidecar connects ([spectrum.lifecycle] Spectrum started).

**Two further breaks after bumping to 1.18.0 (0.1.x → 1.x API drift), in sidecar/index.mjs**

1. resolveSpace() tries app.space(id) / app.spaces.get(id) / im.space({ id }) — none exist in 1.x. Correct call is im.space(target) where target is the handle/guid only — the 3rd ;-segment of Photon's native id (any;-;+E164 DM / any;+;<guid> group). Passing the full composite id resolves but throws at send: [spectrum-imessage] Target not allowed for this project.
2. space.send(text, { replyTo }) — 1.x send() is variadic-content, so the positional { replyTo } is treated as a second content item → TypeError: c.build is not a function (in resolveContents). Same for the /send-attachment path.

**Also worth wiring**
Inbound attachments are reduced to metadata-only ([Photon attachment received: … — no download URL yet], adapter.py ~L525). 1.x exposes im.getAttachment({ client }, guid, phone?), so real inbound media retrieval is now possible.

**Suggested fix**

- Bump spectrum-ts to ^1.18.0.
- resolveSpace: pass the segment-3 handle/guid to im.space().
- Drop the positional reply-opt from space.send() (or wire 1.x reply threading).
- Wire inbound getAttachment so the agent can actually read received images.

I have all four changes working locally against a live free-tier project (text both ways + outbound media verified) and am happy to open a PR.

**Comment by ethernet8023** [comment]
done on main

**Comment by mdgld** [comment]
IDK if this has been integrated on main yet but thanks @UOD317 your description helped me fix locally.
