### PR TITLE
fix(mcp): pass HTTP timeout as timedelta on the deprecated client (#49629)

### LINKED ISSUE #49629: HTTP MCP timeout type mismatch: int passed where timedelta expected
## Description

After upgrading to v0.17.0, all `url:` type (HTTP) MCP connections fail with:

```
'float' object has no attribute 'seconds'
```

stdio type (`command:`) MCPs (e.g. tdx-mcp) are not affected.

## Root Cause

`StreamableHTTPTransport.__init__()` in the `mcp` library expects `timeout` and `sse_read_timeout` as `timedelta` objects. Hermes passes plain `int`/`float` values from `config.yaml` directly.

## Temporary Fix

Applied to `mcp/client/streamable_http.py`:

```python
if isinstance(timeout, (int, float)):
    timeout = timedelta(seconds=timeout)
if isinstance(sse_read_timeout, (int, float)):
    sse_read_timeout = timedelta(seconds=sse_read_timeout)
```

This is a third-party library patch and will be overwritten on pip upgrade.

## Proper Fix

Hermes should convert config values to `timedelta` before passing to `StreamableHTTPTransport`. The fix belongs in Hermes' MCP connection startup code.

## Environment
- Hermes Agent v0.17.0
- mcp library v1.8.0

### PR DESCRIPTION
**Pull request by koshaji**
Fixes #49629.

## Problem

On mcp < 1.24.0, every `url:` (HTTP / StreamableHTTP) MCP connection fails with:

```
'float' object has no attribute 'seconds'
```

stdio (`command:`) MCPs are unaffected.

## Root cause

In `tools/mcp_tool.py`, the deprecated-API branch (`mcp < 1.24.0`) calls `streamablehttp_client(url, timeout=float(connect_timeout), ...)`. That SDK expects `timeout` (and `sse_read_timeout`) as `timedelta` and does `.seconds` on it internally, so a raw float crashes the connection. (The newer `>=1.24.0` path builds its own `httpx.AsyncClient` and passes `http_client=`, so it isn't affected — which is why this only bites older mcp installs.)

## Fix

- Add an idempotent `_as_timeout_timedelta()` helper that coerces an int/float number of seconds to a `timedelta` (and passes `timedelta` through unchanged).
- Use it when building the deprecated-path `streamablehttp_client` kwargs.

Minimal and scoped to the broken branch; the modern path is untouched.

## Tests

`tests/tools/test_mcp_http_timeout.py`: float→timedelta, int→timedelta, timedelta passthrough, and that the result exposes `.seconds` (the attribute the crash was about). All pass locally.

### CODE REVIEW

**Comment by alt-glitch** [comment]
Duplicate of #49646 — same fix for #49629. Both add an idempotent seconds-to-timedelta coercion helper and apply it at the identical deprecated-branch (`mcp < 1.24.0`) `streamablehttp_client` `timeout` kwarg in `tools/mcp_tool.py`. #49646 is the earliest open PR and also coerces `sse_read_timeout`. (See also #49648, #49721 against the same anchor.)

**Comment by koshaji** [comment]
Bump — checking in on review status for the HTTP timeout timedelta fix. Glad to make any changes if there is feedback.

**Comment by koshaji** [comment]
Closing as duplicate of #49646, which is the earliest PR for this crash and a strict superset (also coerces `sse_read_timeout`). Keeping both open just splits reviewer attention for the same one-line fix. Happy to port any improvements onto #49646 if needed.
