### PR TITLE
fix(cli): guard null quick-command alias target against None-deref

### PR DESCRIPTION
**Pull request by pierrenode**
## What does this PR do?
`process_command()`'s local quick-command alias dispatch (`cli.py`, `HermesCLI.process_command`) reads `qcmd.get("target", "").strip()`. A `config.yaml` `quick_commands` entry with `target:` left blank (or explicitly `null`) parses as `target: None`. Since the key is PRESENT (not absent), `dict.get(key, default)` returns `None`, not the `""` default — `.strip()` then raises `AttributeError: 'NoneType' object has no attribute 'strip'`.

This crashes the whole interactive CLI session: the prompt_toolkit main-input-loop call site (`cli.py`, around the primary REPL dispatch) only wraps `process_command()` in `except KeyboardInterrupt`, not a general `except Exception`, so the `AttributeError` propagates and kills the session.

This is a sibling of the quick-command alias `target: null` guard added earlier today in `gateway/run.py` (2 call sites, part of a codebase-wide sweep of `.get(key, "").method()` None-deref sites reading user-editable config). That sweep's own PR body explicitly validated `target: null` → "no command defined" message as one of its fixed behaviors, but only touched the gateway-routed dispatch path. `cli.py`'s own local `/command` handler is a separate, third call site reading the exact same `quick_commands.<name>.target` config key, which the sweep did not reach.

Fix: `(qcmd.get("target") or "").strip()`, mirroring the gateway fix exactly. Falls through to the existing "no target defined" message instead of crashing.

## Related Issue
N/A — found via a sibling-site sweep of the `quick_commands.<name>.target` config key after today's gateway-side null-guard fix.

## Type of Change
- [x] 🐛 Bug fix

## Changes Made
- `cli.py`: `qcmd.get("target", "").strip()` → `(qcmd.get("target") or "").strip()` (+1/-1)
- `tests/cli/test_quick_commands.py`: add `test_alias_null_target_shows_error`, mirroring the existing `test_alias_no_target_shows_error` but with `target: None` instead of `target: ""` (+10)

## How to Test
```
pytest tests/cli/test_quick_commands.py -v
```
All 19 tests in the file pass. Mutation-verified: reverting the one-line fix reproduces `AttributeError: 'NoneType' object has no attribute 'strip'` at `cli.py:8953` in the new test.

## Checklist
- [x] Read the Contributing Guide
- [x] Conventional Commits format
- [x] No duplicate PR
- [x] Single logical change
- [x] Tests added
- [x] Platform tested: macOS
- [x] Docs: N/A
- [x] Cross-platform: N/A

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Related: sibling of the merged salvage #61849, which widened the `.get(key, '').method()` None-deref sweep to 5 config-derived sites (including `gateway/run.py`'s quick-command alias target) but did not reach `cli.py`'s own local `/command` handler. This patches that third call site; the buggy `qcmd.get("target", "").strip()` is still present on `main` (cli.py:8953).

**Comment by teknium1** [comment]
Thanks for the focused regression fix. Current main still dereferences a null alias target at `cli.py:8959`; the proposed guard preserves the existing error branch, and the added test covers that exact configuration case.

Automated hermes-sweeper review.

**Comment by pierrenode** [comment]
Rebased onto current `upstream/main` and squashed to a single commit.

`cli.py`'s own fix line (`target = (qcmd.get("target") or "").strip()`) auto-merged cleanly with no conflict. The only conflict was in the test file: upstream's test-pruning sweep removed several pre-existing, unrelated tests in this class (`test_exec_command_stderr_shown_on_no_stdout`, `test_alias_command_routes_to_target`, `test_unsupported_type_shows_error`, etc. — none of them touch the `target` null-guard). Kept upstream's pruning and restored only this PR's own new test (`test_alias_null_target_shows_error`), verified against the original commit's diff to confirm it — and only it — was added by this PR.

Targeted suite (9 tests) passes, mutation-verified (reverting the guard reproduces `AttributeError: 'NoneType' object has no attribute 'strip'` in the new test). Full `tests/cli/` sweep (956 tests) has one unrelated failure (`test_resume_quiet_stderr.py::test_session_not_found_goes_to_stdout_in_full_mode`) that also passes in isolation and passes when run paired with just this PR's test file — confirmed pre-existing test-order pollution, unrelated to this change. Ruff clean. Fresh competitor search found no other PR touching this call site.
