### PR TITLE
fix(browser): atexit hooks stay silent when the origin module is unimportable

### LINKED ISSUE #112437: [Bug]: hermes update prints 'Exception ignored in atexit callback' — browser atexit hooks fresh-import against a half-updated tree
## Bug Description

On macOS (git install), `hermes update` prints two `Exception ignored in atexit callback` tracebacks on exit, both ending in:

```
ImportError: cannot import name 'file_signature' from 'utils' (/Users/david/.hermes/hermes-agent/utils.py)
```

Full tracebacks:

```
Exception ignored in atexit callback: <function _stop_browser_cleanup_thread at 0x10c8f7100>
Traceback (most recent call last):
  File "tools/browser_tool_lifecycle.py", line 425, in _stop_browser_cleanup_thread
    _bt._cleanup_running = False
  File "tools/browser_tool_origin.py", line 84, in __setattr__
    setattr(origin_module(3), name, value)
  File "tools/browser_tool_origin.py", line 70, in origin_module
    import tools.browser_tool as mod
  File "tools/browser_tool.py", line 25, in <module>
    from hermes_cli.config import DEFAULT_CONFIG, cfg_get
  File "hermes_cli/config.py", line 33, in <module>
    from utils import atomic_replace, atomic_yaml_write, fast_safe_load, file_signature
ImportError: cannot import name 'file_signature' from 'utils'
```

```
Exception ignored in atexit callback: <function _emergency_cleanup_all_sessions at 0x10c8f67a0>
Traceback (most recent call last):
  File "tools/browser_tool_lifecycle.py", line 75, in _emergency_cleanup_all_sessions
    if _bt._cleanup_done:
  File "tools/browser_tool_origin.py", line 81, in __getattr__
    return getattr(origin_module(3), name)
  ...same import chain...
ImportError: cannot import name 'file_signature' from 'utils'
```

The update itself succeeds (`git status` clean, `hermes --version` reports the new build); this is exit-time noise, not a failed update.

## Steps to Reproduce

1. Have a checkout from just before `182ec5c28d`/`a1e7f74e64`/`b797e9d7b3` (the commits that added `file_signature` to `utils.py` and made `hermes_cli/config.py` import it).
2. Run `hermes update` so the pull lands the new `hermes_cli/config.py` while the process is exiting.
3. The atexit-registered `_stop_browser_cleanup_thread` / `_emergency_cleanup_all_sessions` resolve state through the `_OriginProxy`, which falls back to a **fresh** `import tools.browser_tool` when frame-walk/`sys.modules` miss — that import executes the new `config.py` against the not-yet-updated `utils.py` (same class of failure as #88274's stale-bytecode `bounded_probe_run`, but here it is file-level skew, not \_\_pycache\_\_).

## Expected Behavior

atexit cleanup hooks never print tracebacks: if the origin module is unimportable during interpreter shutdown, there is no session state to clean and the hooks should return silently (same spirit as `c59c1a98e3`, which suppressed the Ctrl+C traceback in the same function).

## Actual Behavior

Two `Exception ignored in atexit callback` tracebacks on every update that lands an import-level change to the `tools.browser_tool` chain.

## Proposed Fix

Guard the origin-state accesses at the top of the two atexit entry points in `tools/browser_tool_lifecycle.py` (`_emergency_cleanup_all_sessions`, `_stop_browser_cleanup_thread`) so an unresolvable origin returns silently instead of propagating `ImportError` out of the atexit callback. Happy to submit the PR.

## Operating System

macOS (darwin)

## Python Version

3.11.15

## Hermes Version

v0.21.3 (2026.9.14), install method: git

## Are you willing to submit a PR for this?

- [x] I'd like to fix this myself and submit a PR

### PR DESCRIPTION
**Pull request by thedavidweng**
Fixes #112437.

Mid-`hermes update` the on-disk tree can be half-new (new `config.py` importing a name the old `utils.py` lacks yet), so the fresh `import tools.browser_tool` in `origin_module()` raises `ImportError` and both atexit callbacks (`_emergency_cleanup_all_sessions`, `_stop_browser_cleanup_thread`) print `Exception ignored in atexit callback` tracebacks. The update itself succeeds; this is exit-time noise.

This guards the origin-state accesses at the top of both entry points in `tools/browser_tool_lifecycle.py`: an unresolvable origin means no session state to clean, so return silently (same spirit as `c59c1a98e3` for Ctrl+C in the same function). Normal-path behavior is unchanged — the guard only triggers when `_bt` attribute resolution itself raises.

Includes a regression test in `tests/tools/test_browser_cleanup.py` (`TestAtexitOriginUnimportable`) that makes `origin_module` raise `ImportError` and asserts both hooks stay silent.

Verified: `tests/tools/test_browser_cleanup.py` (8 passed) plus `test_browser_orphan_reaper.py` / `test_browser_hardening.py` / `test_browser_lightpanda.py` (91 passed).

### CODE REVIEW

**Review by gokhanyildirimlar — COMMENTED** [review]
Verified on Windows 11 (git install layout, Python 3.11.15, isolated venv) — this is the exact failure shape from #112437 and the fix holds.

**Field-failure reproduction on base (`origin/main` @ `5d07f7fe66`):** with `origin_module` stubbed to raise the field `ImportError` in the atexit context, both hooks propagate on base:

```
_emergency_cleanup_all_sessions: PROPAGATED ImportError: cannot import name 'file_signature' from 'utils'
_stop_browser_cleanup_thread:    PROPAGATED ImportError: cannot import name 'file_signature' from 'utils'
```

**On this PR:** both hooks return SILENT, and `tests/tools/test_browser_cleanup.py` passes 8/8 on Windows (the regression test included).

**No regressions vs base:** the four adjacent browser suites (`test_browser_cleanup`, `test_browser_orphan_reaper`, `test_browser_hardening`, `test_browser_lightpanda`) produce identical results on base and on this PR — the 6 failures that appear in my minimal venv appear identically on both sides (missing optional deps in my env, e.g. `httpx`/`dotenv` gaps, unrelated to this diff), and the PR adds exactly one new passing test.

Two non-blocking notes:

- The guard also covers plain interpreter-shutdown cases where the origin fresh-import fails for other reasons, which matches the design intent documented in `browser_tool_origin.py` (`origin_module` already special-cases being called directly by the interpreter at atexit).
- #112522 reports the same `ImportError` also firing in the updater's **gateway-restart phase** (mid-run, not atexit). Correctly out of scope here — but whoever picks that up should treat it at the updater's error-handling site, not in `browser_tool`.
