### ISSUE TITLE
HTTP MCP timeout type mismatch: int passed where timedelta expected

### ISSUE THREAD

**Issue by weidzhou** [NousResearch/hermes-agent#49629]
## Description

After upgrading to v0.17.0, all `url:` type (HTTP) MCP connections fail with:

```
'float' object has no attribute 'seconds'
```

stdio type (`command:`) MCPs (e.g. tdx-mcp) are not affected.

## Root Cause

`StreamableHTTPTransport.__init__()` in the `mcp` library expects `timeout` and `sse_read_timeout` as `timedelta` objects. Hermes passes plain `int`/`float` values from `config.yaml` directly.

## Temporary Fix

Applied to `mcp/client/streamable_http.py`:

```python
if isinstance(timeout, (int, float)):
    timeout = timedelta(seconds=timeout)
if isinstance(sse_read_timeout, (int, float)):
    sse_read_timeout = timedelta(seconds=sse_read_timeout)
```

This is a third-party library patch and will be overwritten on pip upgrade.

## Proper Fix

Hermes should convert config values to `timedelta` before passing to `StreamableHTTPTransport`. The fix belongs in Hermes' MCP connection startup code.

## Environment
- Hermes Agent v0.17.0
- mcp library v1.8.0

**Comment by GottZ** [comment]
> *This was generated by AI during triage.*

Four of the five listed PRs address #49629 by converting numeric MCP HTTP timeout values to datetime.timedelta; #49742 instead implements the unrelated multi-schedule request from #49711. The focused candidates all target the legacy Streamable HTTP path, while some additionally cover sse_read_timeout or the SSE transport.

- #49646 (+55/-2) — fixes, preferred: Converts timeout and sse_read_timeout to timedelta in the affected legacy Streamable HTTP branch and adds a branch-level regression test; the contributor review found no substantive defect but requires transplanting the small change to the startup code's current location.
- #49648 **[closed]** (+21/-6) — fixes, duplicate: Applies equivalent timedelta coercion to both legacy Streamable HTTP and SSE call sites, but also includes an unrelated .gitignore change. It remains relevant as broader-path evidence, but was closed as a duplicate of the earlier #49646 following contributor review.
- #49721 **[closed]** (+5953/-10) — fixes, high-risk duplicate: Its tools/mcp_tool.py change addresses the same timeout-type mismatch across legacy HTTP/SSE paths, but the branch contains thousands of unrelated holographic-memory and skill-system changes. It was closed in favor of #49646 after a contributor identified the unclean scope.
- #49742 **[closed]** (+6214/-28) — unrelated: Implements multiple cron schedules for #49711 and does not address the MCP timeout failure in #49629; its branch also carries extensive unrelated files. It was closed as a duplicate of #44572 and has no implementation value for this issue.
- #49844 **[closed]** (+53/-2) — fixes, strict-subset duplicate: Adds idempotent numeric-to-timedelta coercion and tests for the affected legacy HTTP timeout, but does not also pass sse_read_timeout as #49646 does. It remains relevant as independent confirmation of the root cause, but was closed as a duplicate of #49646.

Duplicates: #49646, #49648, #49721, and #49844 implement substantially the same numeric-seconds-to-timedelta repair for the legacy MCP HTTP path; #49648 and #49721 also touch SSE, while #49844 is a strict subset of #49646. #49742 is unrelated to this duplicate set.

Suggested consolidation: Merge #49646 after transplanting/rebasing its focused coercion and regression test onto the current tools/mcp_tool.py legacy-kwargs location, as explicitly requested by the contributor review. Keep #49648, #49721, and #49844 closed as duplicates; keep #49742 out of this issue complex because it addresses #49711 and was itself closed as a duplicate of #44572.

```mermaid
flowchart LR
    I49629(["issue #49629 (open)"])
    classDef open fill:#dbeafe,stroke:#1d4ed8,color:#1e3a8a
    classDef merged fill:#dcfce7,stroke:#15803d,color:#14532d
    classDef closed fill:#e5e7eb,stroke:#6b7280,color:#1f2937
    classDef best stroke-width:3px,stroke:#b45309
    P49646["PR #49646 (open)"] -->|fixes| I49629
    P49648["PR #49648 (closed)"] -->|fixes| I49629
    P49721["PR #49721 (closed)"] -->|fixes| I49629
    P49844["PR #49844 (closed)"] -->|fixes| I49629
    P49646 -.->|dup| P49648
    P49646 -.->|dup| P49721
    P49646 -.->|dup| P49844
    P49648 -.->|dup| P49721
    P49648 -.->|dup| P49844
    P49721 -.->|dup| P49844
    class P49646 open
    class P49646 best
    class P49648 closed
    class P49721 closed
    class P49844 closed
    class I49629 open
```

_Cross-PR triage: Reviewed 5 pull requests and 2 issues in this complex. Each diff was read against this issue; Assessment working set: 49 kB of PR diffs, 12 kB of issue/PR text, 4 kB of discussion (10 comments), 18 verify verdicts. verdicts reflect diff content, not PR titles. Part of an automated triage batch._

**Comment by kshitijk4poor** [comment]
Verified obsolete on current main — closing with citation.

The crash site no longer exists: the HTTP MCP transport was refactored so Hermes builds its own `httpx.AsyncClient` with `httpx.Timeout(float(connect_timeout), read=300.0)` and passes it as `http_client=` to `streamable_http_client()` (`tools/mcp_tool.py` ~:3757-3795, `_MCP_NEW_HTTP` path) — the SDK's timedelta-typed `timeout`/`sse_read_timeout` parameters are never passed, so the `'float' object has no attribute 'seconds'` path is unreachable. Additionally `pyproject.toml` now pins `mcp==2.0.0` (issue was filed against 1.8.0); the legacy `mcp<1.24` branch that passed a float is unreachable with the pinned SDK.
