### ISSUE TITLE
[Bug]: Keet gateway setup crashes with TypeError: _n() missing required argument 'config'

### ISSUE THREAD

**Issue by Nikkiokeet** [NousResearch/hermes-agent#97065]
## Environment

- Hermes Agent: 0.20.6

- OS: Windows 11

- Node.js: v24.x

- Keet Desktop installed

- keet-platform plugin enabled

## Steps to reproduce

1. Run:

```bash

hermes gateway setup

```

2. Select:

```text

7. Keet

```
## Expected behavior

The Keet setup wizard should start and request the required configuration for the Keet gateway.

## Actual behavior

The setup immediately fails with:

```text

TypeError: _setup_fn() missing 1 required positional argument: 'config'

## Additional information

The following configuration and troubleshooting steps were already completed:

- Updated Hermes Agent to 0.20.6

- Installed and enabled `keet-platform`

- Installed Node.js

- Created a Keet room (`Hermes-Control`)

- Configured `env_KEET_HOME_CHANNEL`

- Verified bridge installation and `node_modules`

- Restarted the gateway

Gateway logs later show:

```text

KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'
The bridge appears to start loading, but connection setup fails due to the adapter error.

This looks like a compatibility issue between the current Hermes gateway API and the Keet adapter/plugin.

### Steps to Reproduce

Run `hermes gateway setup` 2. Select `7. Keet` 3. Wait for the setup wizard to start 4. The setup immediately fails Error: TypeError: _setup_fn() missing 1 required positional argument: 'config'

### Expected Behavior

Selecting "7. Keet" in `hermes gateway setup` should start the Keet configuration wizard and request the required configuration information.

### Actual Behavior

The setup wizard immediately crashes with:
2
 
3
TypeError: _setup_fn() missing 1 required positional argument: 'config'
4
 
5
After manually configuring the Keet environment and restarting the gateway, the gateway logs show:
6
 
7
KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'

### Affected Component

Gateway (Telegram/Discord/Slack/WhatsApp)

### Messaging Platform (if gateway-related)

_No response_

### Debug Report

```shell
Not available. Issue reproduced after: - Hermes Agent update to 0.20.6 - Gateway restart - Keet platform installation - Keet room creation Gateway logs contain: KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'
```

### Operating System

Windows 11

### Hermes Version

0.20.6

### Additional Logs / Traceback (optional)

```shell

```

### Are you willing to submit a PR for this?

- [ ] I'd like to fix this myself and submit a PR

**Comment by 686f6c61** [comment]
I'll take this: dispatch plugin setup_fn/connect by signature so a third-party adapter that takes config (or omits is_reconnect) does not crash hermes gateway setup.

**Comment by 686f6c61** [comment]
Opened https://github.com/NousResearch/hermes-agent/pull/97092 — setup_fn/connect dispatch inspects the plugin signature so Keet's setup_fn(config) and bare connect() no longer TypeError.

**Comment by Nikkiokeet** [comment]
### New observations after update

- Hermes Agent updated to 0.21.0
- Gateway restarted successfully
- Hermes Doctor reports no Keet configuration issues
- Keet plugin appears correctly configured
- Room `Hermes-Control` exists and receives messages
- Test messages are successfully sent to the room
- The room still appears to contain only 1 member
- Hermes never responds to messages                                                                                     This seems less likely to be a local configuration problem and more likely related to the Keet integration runtime or adapter behavior.

The previously reported error:

KeetAdapter.connect() got unexpected keyword argument 'is_reconnect'

remains the main suspected root cause.

**Comment by 686f6c61** [comment]
The original TypeError is still the live hole on v0.21.0 — #97092 is open and is not in that release.

Current main still calls `adapter.connect(is_reconnect=...)` unconditionally (`gateway/run_adapters.py`). Keet's `connect()` does not take that kwarg, so the receive path never starts. Outbound send can still work, which matches what you are seeing (room gets your test messages, Hermes never replies).

#97092 dispatches `connect`/`setup_fn` by signature so adapters that omit `is_reconnect` (or take `config`) no longer TypeError. Until that lands, the Keet plugin will keep looking one-way.

**Comment by Nikkiokeet** [comment]
Update after upgrading to Hermes Agent v0.21.1 (2026.9.7)

I updated Hermes today from v0.21.0 to v0.21.1.

Environment:

- Hermes Agent v0.21.1 (2026.9.7)
- upstream commit: c8aa5608
- Install method: git
- Python 3.11.15
- Windows

Previous issue:

The original error was:

KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'

After upgrading to v0.21.1, that specific error is no longer reproduced.

However, the Keet setup flow is still broken.

Steps to reproduce:

1. Run:

   hermes gateway setup

2. Select:

   7. Keet (configured)

3. Press Enter

Result:

The wizard immediately crashes with:

TypeError: _setup_fn() missing 1 required positional argument: 'config'

Full traceback:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\N.Florenzano\AppData\Local\hermes\bin\hermes.exe\__main__.py", line 10, in <module>
  File "C:\Users\N.Florenzano\AppData\Local\hermes\hermes

**Comment by 686f6c61** [comment]
The `connect(is_reconnect=...)` TypeError is gone on v0.21.1, as you saw.

The remaining crash is the other half of this issue: `hermes gateway setup` still calls `setup_fn()` with no arguments (`hermes_cli/gateway.py` `_configure_platform`), and Keet's `setup_fn(config)` needs that argument. That matches `_setup_fn() missing 1 required positional argument: 'config'`.

https://github.com/NousResearch/hermes-agent/pull/97092 covers that path (`invoke_setup_fn` inspects the signature and passes `config` when required). It is still open and is not in v0.21.1, so setup → Keet will keep raising until it lands.

**Comment by Nikkiokeet** [comment]
Additional evidence collected on v0.21.1.

gateway_state.json:
state=retrying

gateway.log:
KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'

No successful Keet connection observed.

This appears inconsistent with the statement that the is_reconnect TypeError is resolved in v0.21.1.

Can you advise whether:
- a migration step is required?
- a legacy configuration may be causing this?
- the Keet gateway plugin is versioned separately from the core agent?

**Comment by 686f6c61** [comment]
You're right — I overstated that.

v0.21.1 / `c8aa5608` still forwards `is_reconnect` into `adapter.connect()` (`gateway/run_adapters.py`, `_connect_adapter_with_timeout`: `adapter.connect(is_reconnect=is_reconnect)`). Current main still does the same. There is no migration step and Keet is not versioned separately from that call: `state=retrying` plus `KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'` is the core gateway hitting a plugin `connect()` that does not take the kwarg.

`hermes gateway setup` is a second hole (`setup_fn()` with no `config`). The log line you have is the first hole, on start/retry.

Both are still the dispatch in https://github.com/NousResearch/hermes-agent/pull/97092. That PR is not in v0.21.1.

**Comment by Nikkiokeet** [comment]
Follow-up Investigation and Potential Fix

After updating Hermes Agent from v0.21.2 to v0.21.3 (v2026.9.14), I manually asked Hermes to verify the status of the Keet gateway integration and determine whether the connection was operational.

Initial Findings

Hermes reported that the Hermes gateway itself was running correctly, but the Keet connection was not functioning. Evidence collected during the investigation included:

- Hermes gateway running successfully.
- Existing Keet configuration detected.
- Previous known error repeatedly observed:

  KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'

- Gateway status showing Keet in a failed/retrying state.

At this stage Hermes concluded that the gateway process was healthy, but the Keet platform adapter was failing during connection initialization.

Root Cause Investigation

Hermes inspected the gateway and plugin implementation and traced the issue to an interface mismatch.

The gateway base platform adapter was invoking:

  connect(is_reconnect=True)

while the Keet adapter implementation exposed:

  async def connect(self) -> bool:

which did not accept the keyword argument `is_reconnect`.

This perfectly matched the observed runtime exception:

  KeetAdapter.connect()
  got an unexpected keyword argument 'is_reconnect'

Proposed Fix

Hermes determined that the Keet adapter signature should match the gateway base interface.

Original implementation:

  async def connect(self) -> bool:

Updated implementation:

  async def connect(self, *, is_reconnect: bool = False) -> bool:

This allows the gateway to call:

  connect(is_reconnect=True)

without raising a TypeError.

Verification of Code Change

I explicitly asked Hermes to read the current adapter implementation and show the exact signature.

Hermes returned:

  async def connect(self, *, is_reconnect: bool = False) -> bool:

and confirmed that the previous version had been:

  async def connect(self) -> bool:

This indicates that the adapter signature now matches the gateway interface.

Post-Fix Verification

Hermes restarted the gateway and compared the observed state before and after the modification.

Before:

- Keet state: retrying
- Error:

  KeetAdapter.connect()
  got an unexpected keyword argument 'is_reconnect'

After:

- Gateway restarted successfully.
- Hermes gateway running normally.
- Keet platform state changed to:

  connected

- No gateway errors reported.

Hermes also reported the gateway state as:

  "keet": {
      "state": "connected",
      "error_code": null,
      "error_message": null
  }

Current Status

Confirmed:

✅ Original TypeError identified.

✅ Root cause identified as a signature mismatch between gateway base interface and Keet adapter implementation.

✅ Adapter signature updated to accept `is_reconnect`.

✅ Gateway restarted successfully.

✅ Keet state changed from "retrying" to "connected".

✅ No current gateway errors reported.

Still To Be Verified

End-to-end communication testing is still required:

  Keet
    ↓
  Gateway
    ↓
  Hermes
    ↓
  Response

Although the gateway now reports the Keet platform as connected and the original exception has disappeared, actual message exchange should be tested before considering the issue fully closed.

Suggested Issue Status

Root Cause: Confirmed

Fix Applied: Confirmed

Gateway Connectivity: Restored

End-to-End Messaging Validation: Pending

Current Assessment: High confidence (approximately 90-95%) that the original Keet connection issue caused by the `is_reconnect` signature mismatch has been resolved.

**Comment by Nikkiokeet** [comment]
Additional Validation Update

After updating from Hermes Agent v0.21.2 to v0.21.3 (v2026.9.14), I performed additional investigation directly on the affected installation.

Observed behavior before investigation:

- Gateway was running.
- Keet was configured.
- Connection failed with:

  KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'

Investigation:

Hermes analyzed the gateway and plugin implementation and identified a signature mismatch between the gateway base interface and the Keet adapter.

Gateway base interface expected:

  connect(is_reconnect=True)

Keet adapter implementation exposed:

  async def connect(self) -> bool:

which does not accept the is_reconnect keyword argument.

Proposed fix:

The adapter signature was updated to:

  async def connect(self, *, is_reconnect: bool = False) -> bool:

matching the gateway base interface.

Verification:

I explicitly asked Hermes to read the current implementation from:

  C:\Users\N.Florenzano\AppData\Local\hermes\plugins\keet-platform\adapter.py

Current method signature reported:

  async def connect(self, *, is_reconnect: bool = False) -> bool:

Previous signature:

  async def connect(self) -> bool:

Post-fix results:

Before:

- Keet state: retrying
- Error:
  KeetAdapter.connect() got an unexpected keyword argument 'is_reconnect'

After:

- Gateway restarted successfully.
- Hermes gateway running normally.
- Keet state: connected
- error_code: null
- error_message: null

Current assessment:

✅ Original TypeError reproduced and identified.

✅ Root cause identified as signature mismatch.

✅ Adapter signature updated.

✅ Gateway now transitions to "connected".

✅ Original exception no longer observed.

Remaining validation:

End-to-end messaging still needs verification:

  Keet
    ↓
  Gateway
    ↓
  Hermes
    ↓
  Response

At the moment I consider the original issue very likely resolved, but full message-flow testing is still pending before declaring the issue completely closed.

**Comment by Nikkiokeet** [comment]
Keet Architecture Clarification Request

The original TypeError appears resolved and the gateway now reports:

"state": "connected"

Before continuing with end-to-end testing I would like to verify that my Keet architecture is correct.

Current setup:

- Keet Desktop installed
- keet-platform installed
- Dedicated room created: Hermes-Control
- KEET_HOME_CHANNEL configured
- Gateway reports Keet = connected

Questions:

1. Is the expected architecture based on a dedicated Keet room?
2. Should Hermes/bridge appear as a visible participant in that room?
3. How can I verify that KEET_HOME_CHANNEL points to the correct room?
4. Is there a recommended way to validate that the bridge is subscribed to the room?
5. What is the expected end-to-end workflow for:
   User → Keet Room → Gateway → Hermes → Reply

I want to confirm the architecture before performing additional functional tests. Thanks a lot for your time and availability!!

**Comment by 686f6c61** [comment]
If `connect(is_reconnect=...)` no longer TypeErrors and gateway status is `connected`, the original hole in this issue (core calling a plugin `connect()` / `setup_fn()` with the wrong signature) is the part #97092 covers.

The dedicated-room / `KEET_HOME_CHANNEL` / participant questions are Keet plugin usage, not that TypeError. I would not treat a green `connected` as proof the room subscription is right — that is end-to-end on the plugin side. I do not have the keet-platform room-layout contract in this tree.

**Comment by Nikkiokeet** [comment]
Update:

The original TypeError appears resolved and the gateway now reports the Keet platform as connected.

At this point the remaining open questions are no longer related to the original bug, but to plugin usage and room architecture:

- Expected KEET_HOME_CHANNEL usage
- Expected room topology
- Bridge participation model
- End-to-end validation workflow

I will continue investigation separately. Any ideas or suggestions on this topic are always greatly appreciated, both here and via email. Let's work together to achieve this result. Thanks a lot for your time!

**Comment by Nikkiokeet** [comment]
Additional Investigation Results

The original TypeError appears resolved.

Current observations:

✅ Keet platform loads correctly.
✅ Gateway starts successfully.
✅ Adapter reports connected.
✅ Welcome room is created and monitored.
✅ No further is_reconnect TypeErrors observed after the signature fix.

However, an additional issue has been identified.

The keet-platform plugin appears to lack a target resolution path for `hermes send`.

Evidence gathered:

- Plugin has no parse_target_ref_fn.
- Plugin has no validate_target_ref_fn.
- channel_directory.json contains no Keet entries.
- KEET_HOME_CHANNEL is configured as:

  keet://chat/...

- The monitored welcome room uses a different internal room key.
- `hermes send --to keet` returns:

  No home channel set for keet

- `hermes send --to keet:CHANNEL` fails resolution.

Current assessment:

The original connection bug appears fixed.

The remaining problem appears to be channel resolution and message delivery through the CLI path rather than gateway connectivity.

Open question:

Is the current behavior expected for keet-platform, or should the plugin expose a parser / validator for KEET_HOME_CHANNEL and direct message delivery? Thanks a lot in advance for your support!

**Comment by 686f6c61** [comment]
The original TypeError (`connect(is_reconnect=...)` / `setup_fn()` missing `config`) is the core dispatch hole. If that is gone and the adapter reports `connected`, that part of this issue is done.

`hermes send` target resolution is a different layer. `parse_target_ref_fn` / `validate_target_ref_fn` and `channel_directory.json` entries are plugin contract, not the gateway connect path. `No home channel set for keet` with `KEET_HOME_CHANNEL=keet://chat/...` means the CLI never bound that URL as a home channel — expected until keet-platform exposes those hooks (or writes the directory itself).

I would file that as a new issue against the plugin (send/home-channel), not as a reopen of this TypeError. I do not have the keet-platform room-key vs `keet://chat/` contract in this tree.

**Comment by Nikkiokeet** [comment]
# Keet ↔ Hermes Integration Reality Check

After a practical validation session we collected the following observations.

## What works

✅ Keet plugin loads correctly.

✅ Hermes gateway starts correctly.

✅ Keet platform reports `connected`.

✅ Invite links are generated.

✅ Keet accepts the generated invite link format.

Technically, the Keet ↔ Hermes integration is functional.

---

## What we observed

The current workflow is difficult for non-technical users.

To successfully connect, we had to:

- inspect gateway logs
- identify the active invite link manually
- investigate gateway configuration
- debug allowlist behavior
- perform multiple validation cycles

This was only possible after a fairly extensive audit process.

---

## Main usability concern

The active invite link appears only in:

```text
gateway.log

**Comment by Nikkiokeet** [comment]
There is currently no obvious user-facing way to discover:

the active room
the current invite link
where Hermes is listening
whether the room is still valid after a restart

From an end-user perspective this creates confusion.

Typical users such as:

FSEs
Service Managers
Project Stakeholders

cannot realistically be expected to inspect logs in order to interact with Hermes.

Important finding

We initially assumed that Keet could be used as a persistent project collaboration space (for example: "Cisanello Installation", "Teramo Installation", etc.).

However, the observed behavior suggests something closer to:

Plain Text
1
Gateway restart
2
↓
3
New invite link
4
↓
5
New active room/session
Mostra più linee

If this is the intended design, then the integration behaves more like a temporary communication channel than a persistent project room.

We would appreciate clarification on whether this behavior is expected.

Questions

Is a new invite link generated intentionally after every gateway restart?

Is persistent-room operation supported?

Is there a supported workflow for project-based rooms that survive gateway restarts?

Is there an easier way for normal users to discover the active invite link?

Is there a user-facing method (UI/API/command) to identify the currently active Keet room?

Feedback

The technical integration appears to work.

The main challenge is usability.

We hope these findings help improve:

Keet ↔ Hermes onboarding
Documentation
Room discoverability
Real-world team collaboration workflows

A short end-user guide explaining how a normal user is expected to:

obtain the active invite link
join the correct room
verify that Hermes is listening
interact with Hermes

would be extremely valuable.

Thanks for your work on both Hermes and Keet.

**Comment by Nikkiokeet** [comment]
## Additional Findings – Keet ↔ Hermes Validation

After further testing we collected additional evidence.

### Confirmed Working

✅ Keet plugin loads correctly.

✅ Hermes gateway starts correctly.

✅ Keet platform reports `connected`.

✅ Invite links are generated.

✅ Invite links are accepted by the Keet client.

✅ `GATEWAY_ALLOW_ALL_USERS=true` is correctly loaded by the gateway.

✅ The previous allowlist warning disappears after enabling the variable.

### Still Unclear

Despite the successful connection state:

- Gateway = running
- Keet = connected
- Invite link = accepted by client

the Keet client still remains on:

> "Waiting for someone to let you in"

This suggests that the problem is no longer related to:
- invalid invite links
- gateway connectivity
- plugin loading
- allowlist configuration

### Key Open Question

At this point it is no longer clear what the expected user workflow is.

From the perspective of a normal user:

- How is the active room discovered?
- How is the current invite link obtained?
- Is a new room intended to be created after each gateway restart?
- Are rooms expected to be persistent?
- How should a small team collaborate with Hermes using Keet?

### Usability Observation

The technical integration appears functional.

However, discovering and joining the active room required:

- gateway log inspection
- configuration analysis
- invite link tracing
- multiple connectivity tests

A typical non-technical user would have significant difficulty reproducing these steps.

### Request

We would appreciate clarification regarding:

1. The intended end-user workflow.
2. Invite link lifecycle and persistence.
3. Room persistence expectations.
4. How users are expected to discover and join the active Hermes room.
5. Whether the current behavior is expected or indicates a configuration/network issue.

The goal of this investigation is not to

**Comment by Nikkiokeet** [comment]
Additional Observation

Join requests are synchronized across Keet clients.

A join initiated on iPhone was visible on Desktop and vice versa.
Cancelling the request on one device immediately removed it from the other.

This suggests that the join request is successfully created and propagated through the Keet system.

The remaining issue appears to occur after the join request has been created, during the admission/acceptance stage.
