### PR TITLE
fix(copilot): guard _is_copilot_url call with getattr to prevent AttributeError

### LINKED ISSUE #59845: [Bug] Cron job fails with AttributeError: 'AIAgent' object has no attribute '_is_copilot_url' (intermittent, non-Copilot providers)
## Summary

`agent/conversation_loop.py:1164` calls `agent._is_copilot_url()` **without a `getattr` guard**, in a code path that can be reached by an agent object that isn't a fully-initialized `AIAgent`. When that happens, every API call in the conversation dies with `AttributeError: 'AIAgent' object has no attribute '_is_copilot_url'` and the cron job fails.

The sibling check one line up — `getattr(agent, "_is_user_initiated_turn", False)` — is already guarded. The Copilot URL check should be too, returning `False` on missing.

## Repro

- **Hermes build:** `ba3169909 chore(providers): remove dead cloudcode-pa quota-fallback branches` is HEAD at time of incident; the bug landed in `6f052b7ff fix(copilot): set x-initiator per turn so user prompts bill as premium requests (salvage #4097) (#58544)`.
- **Trigger:** any cron tick that reaches the API call site (e.g. inbox non-empty).
- **Determinism:** seen twice in a row at 12:47:34 and 13:07:54, then self-cleared on the next tick at 13:23:39 with a clean `last_status: ok`. **Intermittent** — most likely a module-reload / hot-reload window where the agent object loses the method binding, or a code path that constructs an agent-like wrapper. Worth investigating the construction path.
- **Stack:** Python 3.11.15 on macOS 26.5.1, Nous inference provider (`https://inference-api.nousresearch.com/v1`), model `minimax/minimax-m3`. Base URL is Nous, **not** Copilot — so the failing call is a no-op for any provider that isn't Copilot. The guard should short-circuit on missing attribute, not crash.

## Failing code site

`agent/conversation_loop.py:1164`:
```python
if getattr(agent, "_is_user_initiated_turn", False) and agent._is_copilot_url():
    _xh = dict(api_kwargs.get("extra_headers") or {})
    _xh["x-initiator"] = "user"
    api_kwargs["extra_headers"] = _xh
    agent._is_user_initiated_turn = False
```

**Suggested fix** (one-liner, same pattern as the sibling guard one line up):
```python
if getattr(agent, "_is_user_initiated_turn", False) and getattr(agent, "_is_copilot_url", lambda: False)():
    ...
```

## What the user sees in the cron job

- `last_status: error` on the job
- `cron/output/<job_id>/<ts>.md` contains `RuntimeError: 'AIAgent' object has no attribute '_is_copilot_url'`
- `logs/agent.log` shows three WARNINGs ("API call failed (attempt 1/3)", "(attempt 2/3)", "(attempt 3/3)") all with the same AttributeError, then a final ERROR with the same message after 3 retries
- `logs/errors.log` mirrors it
- A `request_dump_cron_<job_id>_<ts>_<ts>.json` is written showing the HTTP request that never went out (helpful for confirming it was an agent-side failure, not an upstream API error)

## Files / line numbers for the fix author

- **Method definition (the canonical one):** `run_agent.py:1324` — `_is_copilot_url`
- **Method definition (also exists in test mirror):** `tests/test_copilot_initiator.py:55-60` — the same block is duplicated in the test fixture's `_inject` helper, so the fix has to land in both spots or the test will diverge from prod.
- **Unguarded call site (bug):** `agent/conversation_loop.py:1164`
- **Test that asserts the unguarded call works:** `tests/test_copilot_initiator.py:55` — the test's `_inject` helper does the unguarded call. If the suggested fix lands in `conversation_loop.py`, the test should be updated the same way (or it should import the production helper).
- **Construction path that hits the bug:** `cron/scheduler.py:2947-2948` calls `AIAgent(...)` from `from run_agent import AIAgent` at line 2517, so on a normal cron tick the method *is* bound — meaning the bug only fires on a subset of construction paths. The unguarded call is still the right place to add the guard.

## Severity

- **Impact:** any cron job using the default LLM-driven path can fail closed on an unlucky tick, lose the inbox file (the script already returned `INBOX_HAS_FILES` to the agent), and have to wait for the next tick to recover. Bridge protocols with `needs_response: true` accumulate latency on the other party.
- **Severity:** medium — service degrades but doesn't crash, and self-heals on the next 5m tick. The right fix is defensive, not urgent.
- **User workaround:** none needed; the job recovers.

## Suggested repro recipe for CI

1. Construct an `AIAgent` instance where `_is_copilot_url` is missing (e.g. via `del AIAgent._is_copilot_url` or a stub subclass) while `_is_user_initiated_turn = True`.
2. Call `agent._build_api_kwargs(...)` and then the API-call block at `agent/conversation_loop.py:1164-1168`.
3. **Expected (after fix):** the block is a no-op because `getattr(..., lambda: False)()` returns `False`.
4. **Current (before fix):** raises `AttributeError: 'AIAgent' object has no attribute '_is_copilot_url'`.

## Context

- Introduced in #58544 (merged 2026-07-04), which salvaged #4097 to set the `x-initiator: user` header on the first API call of a user-initiated turn so Copilot bills premium requests correctly.
- Distinct from closed #3040 (that one was about the header not being set; this one is about the *call that sets it* crashing on non-Copilot providers).
- No existing issue found for `_is_copilot_url` AttributeError; no follow-up issue on PR #58544.

### PR DESCRIPTION
**Pull request by isheng-eqi**
## Summary

Fixes [#59845](https://github.com/NousResearch/hermes-agent/issues/59845)

## Problem

The Copilot x-initiator injection block in `agent/conversation_loop.py:1173` calls `agent._is_copilot_url()` without a `getattr` guard, unlike the sibling `_is_user_initiated_turn` check one line above. On certain agent construction paths (module-reload, wrapper agents) `_is_copilot_url` may be missing, causing every API call in the conversation to fail with:

```
AttributeError: 'AIAgent' object has no attribute '_is_copilot_url'
```

This is intermittent and self-heals, but during the failure window the cron job errors out and loses the inbox file.

## Fix

Wrap `agent._is_copilot_url()` with `getattr(agent, '_is_copilot_url', lambda: False)()` — same pattern as the sibling `_is_user_initiated_turn` guard. Non-Copilot providers and partially-initialized agents fall through cleanly.

## Changes

- `agent/conversation_loop.py`: guard `_is_copilot_url` call with `getattr`
- `tests/test_copilot_initiator.py`: mirror the guard in `_inject` helper; add regression test `test_missing_is_copilot_url_does_not_crash`

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #59847 — twin fresh PR. Both apply the identical `getattr(agent, "_is_copilot_url", lambda: False)()` guard at the same Copilot x-initiator injection site in `agent/conversation_loop.py` and mirror it in `tests/test_copilot_initiator.py`. #59847 was opened first (2026-07-06 21:09 UTC vs this PR's 2026-07-07 03:09 UTC), so it's canonical. Note: this PR also bundles an unrelated `_restore_or_build_system_prompt` personality-override change. Both fix the same bug (#59845).

**Comment by isheng-eqi** [comment]
Duplicate of #59847 — already fixed. Closing.
