### PR TITLE
fix(copilot): guard _is_copilot_url() call with getattr to prevent AttributeError

### LINKED ISSUE #59845: [Bug] Cron job fails with AttributeError: 'AIAgent' object has no attribute '_is_copilot_url' (intermittent, non-Copilot providers)
## Summary

`agent/conversation_loop.py:1164` calls `agent._is_copilot_url()` **without a `getattr` guard**, in a code path that can be reached by an agent object that isn't a fully-initialized `AIAgent`. When that happens, every API call in the conversation dies with `AttributeError: 'AIAgent' object has no attribute '_is_copilot_url'` and the cron job fails.

The sibling check one line up — `getattr(agent, "_is_user_initiated_turn", False)` — is already guarded. The Copilot URL check should be too, returning `False` on missing.

## Repro

- **Hermes build:** `ba3169909 chore(providers): remove dead cloudcode-pa quota-fallback branches` is HEAD at time of incident; the bug landed in `6f052b7ff fix(copilot): set x-initiator per turn so user prompts bill as premium requests (salvage #4097) (#58544)`.
- **Trigger:** any cron tick that reaches the API call site (e.g. inbox non-empty).
- **Determinism:** seen twice in a row at 12:47:34 and 13:07:54, then self-cleared on the next tick at 13:23:39 with a clean `last_status: ok`. **Intermittent** — most likely a module-reload / hot-reload window where the agent object loses the method binding, or a code path that constructs an agent-like wrapper. Worth investigating the construction path.
- **Stack:** Python 3.11.15 on macOS 26.5.1, Nous inference provider (`https://inference-api.nousresearch.com/v1`), model `minimax/minimax-m3`. Base URL is Nous, **not** Copilot — so the failing call is a no-op for any provider that isn't Copilot. The guard should short-circuit on missing attribute, not crash.

## Failing code site

`agent/conversation_loop.py:1164`:
```python
if getattr(agent, "_is_user_initiated_turn", False) and agent._is_copilot_url():
    _xh = dict(api_kwargs.get("extra_headers") or {})
    _xh["x-initiator"] = "user"
    api_kwargs["extra_headers"] = _xh
    agent._is_user_initiated_turn = False
```

**Suggested fix** (one-liner, same pattern as the sibling guard one line up):
```python
if getattr(agent, "_is_user_initiated_turn", False) and getattr(agent, "_is_copilot_url", lambda: False)():
    ...
```

## What the user sees in the cron job

- `last_status: error` on the job
- `cron/output/<job_id>/<ts>.md` contains `RuntimeError: 'AIAgent' object has no attribute '_is_copilot_url'`
- `logs/agent.log` shows three WARNINGs ("API call failed (attempt 1/3)", "(attempt 2/3)", "(attempt 3/3)") all with the same AttributeError, then a final ERROR with the same message after 3 retries
- `logs/errors.log` mirrors it
- A `request_dump_cron_<job_id>_<ts>_<ts>.json` is written showing the HTTP request that never went out (helpful for confirming it was an agent-side failure, not an upstream API error)

## Files / line numbers for the fix author

- **Method definition (the canonical one):** `run_agent.py:1324` — `_is_copilot_url`
- **Method definition (also exists in test mirror):** `tests/test_copilot_initiator.py:55-60` — the same block is duplicated in the test fixture's `_inject` helper, so the fix has to land in both spots or the test will diverge from prod.
- **Unguarded call site (bug):** `agent/conversation_loop.py:1164`
- **Test that asserts the unguarded call works:** `tests/test_copilot_initiator.py:55` — the test's `_inject` helper does the unguarded call. If the suggested fix lands in `conversation_loop.py`, the test should be updated the same way (or it should import the production helper).
- **Construction path that hits the bug:** `cron/scheduler.py:2947-2948` calls `AIAgent(...)` from `from run_agent import AIAgent` at line 2517, so on a normal cron tick the method *is* bound — meaning the bug only fires on a subset of construction paths. The unguarded call is still the right place to add the guard.

## Severity

- **Impact:** any cron job using the default LLM-driven path can fail closed on an unlucky tick, lose the inbox file (the script already returned `INBOX_HAS_FILES` to the agent), and have to wait for the next tick to recover. Bridge protocols with `needs_response: true` accumulate latency on the other party.
- **Severity:** medium — service degrades but doesn't crash, and self-heals on the next 5m tick. The right fix is defensive, not urgent.
- **User workaround:** none needed; the job recovers.

## Suggested repro recipe for CI

1. Construct an `AIAgent` instance where `_is_copilot_url` is missing (e.g. via `del AIAgent._is_copilot_url` or a stub subclass) while `_is_user_initiated_turn = True`.
2. Call `agent._build_api_kwargs(...)` and then the API-call block at `agent/conversation_loop.py:1164-1168`.
3. **Expected (after fix):** the block is a no-op because `getattr(..., lambda: False)()` returns `False`.
4. **Current (before fix):** raises `AttributeError: 'AIAgent' object has no attribute '_is_copilot_url'`.

## Context

- Introduced in #58544 (merged 2026-07-04), which salvaged #4097 to set the `x-initiator: user` header on the first API call of a user-initiated turn so Copilot bills premium requests correctly.
- Distinct from closed #3040 (that one was about the header not being set; this one is about the *call that sets it* crashing on non-Copilot providers).
- No existing issue found for `_is_copilot_url` AttributeError; no follow-up issue on PR #58544.

### PR DESCRIPTION
**Pull request by liuhao1024**
## What does this PR do?

Guards the `_is_copilot_url()` call in `agent/conversation_loop.py:1164` with `getattr(..., lambda: False)()` to prevent `AttributeError` when the agent object doesn't have this method bound. This mirrors the existing guard pattern for `_is_user_initiated_turn` on the same line.

## Related Issue

Fixes #59845

## Type of Change

- [x] 🐛 Bug fix (non-breaking change that fixes an issue)

## Changes Made

- `agent/conversation_loop.py`: Guard `agent._is_copilot_url()` call with `getattr(agent, "_is_copilot_url", lambda: False)()`
- `tests/test_copilot_initiator.py`: Update `_inject()` test helper to match production guard pattern

## How to Test

1. Run `pytest tests/test_copilot_initiator.py -v` — all 14 tests pass
2. The guard short-circuits to `False` when `_is_copilot_url` is missing, preventing crash on non-Copilot providers during cron tick edge cases (module-reload windows, agent-like wrappers without full AIAgent initialization)

### Code

- [x] I've read the [Contributing Guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md)
- [x] My commit messages follow [Conventional Commits](https://www.conventionalcommits.org/) (`fix(scope):`, `feat(scope):`, etc.)
- [x] I searched for [existing PRs](https://github.com/NousResearch/hermes-agent/pulls) to make sure this isn't a duplicate
- [x] My PR contains **only** changes related to this fix/feature (no unrelated commits)
- [x] I've run `pytest tests/ -q` and all tests pass
- [x] I've added tests for my changes (required for bug fixes, strongly encouraged for features)
- [x] I've tested on my platform: macOS 26.5.1

### Documentation & Housekeeping

- [x] I've updated relevant documentation (README, `docs/`, docstrings) — or N/A
- [x] I've updated `cli-config.yaml.example` if I added/changed config keys — or N/A
- [x] I've updated `CONTRIBUTING.md` or `AGENTS.md` if I changed architecture or workflows — or N/A
- [x] I've considered cross-platform impact (Windows, macOS) per the [compatibility guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md#cross-platform-compatibility) — or N/A
- [x] I've updated tool descriptions/schemas if I changed tool behavior — or N/A

### CODE REVIEW

File: agent/conversation_loop.py [hunk 1]
```diff
@@ -1161,7 +1161,7 @@ def run_conversation(
                 # Copilot x-initiator: the first API call of a user turn is
                 # marked "user" so Copilot bills a premium request; tool-loop
                 # follow-ups keep the default "agent" header (#3040).
-                if getattr(agent, "_is_user_initiated_turn", False) and agent._is_copilot_url():
+                if getattr(agent, "_is_user_initiated_turn", False) and getattr(agent, "_is_copilot_url", lambda: False)():
```
Comment (teknium1) [inline agent/conversation_loop.py:1164]: This guard alone cannot guarantee an absent `_is_copilot_url` will not crash: current main still calls the method before this branch in Codex preflight and again in the retry preflight. Please either cover those direct call sites or demonstrate that the reported construction path cannot reach them.

File: tests/test_copilot_initiator.py [hunk 2]
```diff
@@ -52,7 +52,7 @@ def _make_agent(monkeypatch, base_url, api_mode="chat_completions"):
 
 def _inject(agent, api_kwargs):
     """Mirror the injection block in agent/conversation_loop.py."""
-    if getattr(agent, "_is_user_initiated_turn", False) and agent._is_copilot_url():
+    if getattr(agent, "_is_user_initiated_turn", False) and getattr(agent, "_is_copilot_url", lambda: False)():
```
Comment (teknium1) [inline tests/test_copilot_initiator.py:55]: Updating this mirrored helper does not test the regression. Add a test that invokes the production loop with the method intentionally absent, so the claimed fallback is exercised rather than duplicated in test-only logic.

**Review by teknium1 — COMMENTED** [review]
Thanks for the focused defensive fix. The current implementation needs a verified trigger and complete coverage before it can establish the claimed safety.

### Problems
- The changed branch is not the only direct call. Current main invokes `agent._is_copilot_url()` in Codex preflight at `agent/conversation_loop.py:1204`, before this branch, and again in retry preflight at `agent/conversation_loop.py:1356`; either path still raises if the method is absent.
- `tests/test_copilot_initiator.py:53-60` only mirrors the conditional. The existing injection tests at `tests/test_copilot_initiator.py:104-132` construct normal `AIAgent` instances and do not exercise the claimed absent-method case.
- Normal production execution forwards an `AIAgent` instance into the loop (`run_agent.py:5882-5894`), and that class defines `_is_copilot_url()` (`run_agent.py:1379-1384`). The cron/module-reload construction path needs a concrete reproduction.

### Suggested changes
- Add a production-path regression test for the supported missing-method scenario.
- Either cover all direct call sites or narrow the claimed guarantee to a path proven not to reach the Codex preflight calls.

This is an automated hermes-sweeper review.
