### PR TITLE
fix(daemon-pool): support Python 3.14 _worker signature change (#58596)

### LINKED ISSUE #58596: DaemonThreadPoolExecutor crashes on Python 3.14: `_initializer` attribute removed
## Bug Description

`DaemonThreadPoolExecutor._adjust_thread_count()` references `self._initializer` and `self._initargs`, which no longer exist in Python 3.14. This breaks **all** concurrent features: `delegate_task`, async delegation, skills hub fan-out, and memory sync.

```
Error during OpenAI-compatible API call: 'DaemonThreadPoolExecutor' object has no attribute '_initializer'
```

## Root Cause

Python 3.14 changed `ThreadPoolExecutor` internals:

| | Python ≤ 3.13 | Python ≥ 3.14 |
|---|---|---|
| Initializer storage | `self._initializer`, `self._initargs` (instance attrs) | `self._create_worker_context()` returns a `WorkerContext` |
| `_worker()` signature | `_worker(executor_ref, work_queue, initializer, initargs)` (4 params) | `_worker(executor_ref, ctx, work_queue)` (3 params) |
| Context management | None | `WorkerContext.initialize()` / `ctx.finalize()` lifecycle |

The code at `tools/daemon_pool.py:58-59` directly accesses the removed attributes.

## Affected Code

File: `tools/daemon_pool.py`, method `_adjust_thread_count`, lines 55-60:

```python
args=(
    weakref.ref(self, weakref_cb),
    self._work_queue,
    self._initializer,      # AttributeError in 3.14
    self._initargs,         # AttributeError in 3.14
),
```

## Reproduction

```
Python 3.14.6
from tools.daemon_pool import DaemonThreadPoolExecutor
e = DaemonThreadPoolExecutor(max_workers=1)
e.submit(lambda: 42)
# -> AttributeError: 'DaemonThreadPoolExecutor' object has no attribute '_initializer'
```

## Proposed Fix

Detect `_worker` signature at import time and branch accordingly:

```python
import inspect
from concurrent.futures.thread import _worker

_worker_uses_ctx = len(inspect.signature(_worker).parameters) == 3

# In _adjust_thread_count:
if _worker_uses_ctx:
    # Python >= 3.14: _worker(executor_ref, ctx, work_queue)
    args = (
        weakref.ref(self, weakref_cb),
        self._create_worker_context(),
        self._work_queue,
    )
else:
    # Python <= 3.13: _worker(executor_ref, work_queue, initializer, initargs)
    args = (
        weakref.ref(self, weakref_cb),
        self._work_queue,
        self._initializer,
        self._initargs,
    )
```

This fix:
- Uses `inspect.signature(_worker)` at import time (zero overhead per call)
- Passes `self._create_worker_context()` for 3.14 (returns a `WorkerContext` with `initialize()`/`finalize()` lifecycle)
- Falls back to old `_initializer`/`_initargs` for <= 3.13
- Preserves the original semantics (daemon=True, no `_threads_queues` registration)

## Environment

- Hermes Agent: v0.18.0 (2026.7.1)
- Python: 3.14.6
- Platform: aarch64-linux-android (Termux)
- Verified: patch applied locally, `DaemonThreadPoolExecutor` creates, submits tasks, and shuts down correctly

## Impact

**Critical** — on Python 3.14, every feature using `DaemonThreadPoolExecutor` crashes: `delegate_task`, `async_delegation`, `skills_hub`, `memory_manager`, `tool_executor`.

### PR DESCRIPTION
**Pull request by nankingjing**
## Summary
Python 3.14 changed `_worker` from 4 params to 3 params, replacing `initializer`/`initargs` with a `WorkerContext`. This caused `DaemonThreadPoolExecutor._adjust_thread_count` to crash with `AttributeError: DaemonThreadPoolExecutor object has no attribute _initializer`.

## Fix
- Detect `_worker` signature at import time via `inspect.signature`
- Branch in `_adjust_thread_count`:
  - Python >= 3.14: pass `self._create_worker_context()` as the ctx arg
  - Python <= 3.13: pass `self._initializer`/`self._initargs` as before

## Files changed
- `tools/daemon_pool.py` — add signature detection and version branch
- `tests/tools/test_daemon_pool.py` — 4 regression tests

## Test results
```
tests/tools/test_daemon_pool.py ........    [100%]
============================== 8 passed in 0.98s ==============================
```

All 4 existing tests + 4 new regression tests pass on Python 3.11 (which exercises the <= 3.13 code path).

Closes #58596

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #57459 (earlier open PR, created 2026-07-03). Both patch the same site -- `DaemonThreadPoolExecutor._adjust_thread_count` in `tools/daemon_pool.py` -- for the identical Python 3.14 crash (`_initializer`/`_worker` signature change). The mechanism difference (this PR's `inspect.signature`/`_WORKER_USES_CTX` branch vs #57459's `getattr` fallback) is minor and doesn't rescue the later PR; #57459 is the canonical (earliest open). #47634 / #50077 fix a different file (`tools/async_delegation.py`) and are related. Fixes #58596.

**Review by AmirF194 — COMMENTED** [review]
The arg-order handling is correct. I checked the CPython 3.14 source and `_worker(executor_reference, ctx, work_queue)` matches what you pass, and `_create_worker_context` is a genuine instance attribute set in `ThreadPoolExecutor.__init__`, so the call resolves. The `<=3.13` branch is identical to the original tuple, so this is a clean no-op on the versions we currently ship. I ran `tests/tools/test_daemon_pool.py` in a clean Python 3.11 container matching CI: 8 passed.

Two things worth sorting before this lands, neither a bug in the diff itself.

First, `pyproject.toml` still pins `requires-python = ">=3.11,<3.14"`, so a standard install will not even run on 3.14 and the fix is only reachable if you bypass that constraint. Do you want to bump the ceiling in this same PR so the fix is actually usable, or is the intent to hold off on 3.14 for now? That decision changes whether this should merge yet.

Second, the 3.14 path has no test coverage. CI provisions only 3.11, and each test here exercises whichever branch the running interpreter picks. I confirmed this directly: reverting `daemon_pool.py` to main makes the module fail to import (`_WORKER_USES_CTX` no longer exists) rather than fail a behavioral assertion, so on 3.11 the new tuple could be wrong and nothing would catch it. Could you add a test that patches `_WORKER_USES_CTX = True` and asserts the exact args tuple passed to the thread target, so the 3.14 branch is validated even when we run on 3.11? A 3.14 CI slice would be ideal, but the mocked test is the cheap floor.

**Comment by nankingjing** [comment]
Thanks for the thorough review, @AmirF194. Two responses:

**1. Mocked test for 3.14 branch (done)**

I've added `test_py314_worker_args_when_ctx_mocked` in [bb3f09e]. It patches `_WORKER_USES_CTX=True`, stubs `_create_worker_context` (which doesn't exist on 3.11) via `create=True`, and asserts the exact 3-tuple `(executor_ref, ctx, work_queue)` passed to `_worker`. This validates the 3.14 code path on any Python version, so CI running 3.11 still catches regressions in the branch that ships for 3.14 users. All 9 tests pass (5 existing + 4 regression = 9 total).

**2. pyproject.toml ceiling: keep `<3.14` for now**

The `<3.14` upper bound in `requires-python` is load-bearing, not cosmetic (see the comment at pyproject.toml lines 13-19). Rust-backed transitives like pydantic-core don't have cp314 wheels yet, so a `>=3.11,<3.14` pin makes uv refuse 3.14 with a clear error instead of falling back to a maturin source build that fails. This PR's fix is a forward-facing safety net — harmless on current Python (the `<=3.13` branch is identical to the original tuple) and ready to work the moment we raise the ceiling when cp314 wheels ship. Bumping the ceiling should be its own intentional PR (test 3.14 in CI, verify all Rust transitives have wheels, etc.), not a side effect of this bug fix.

**Comment by nankingjing** [comment]
Fair flag — this does overlap #57459 (@gysyl), same call site in \`_adjust_thread_count\`. One substantive difference for whoever consolidates: the two fixes are **not** equivalent on real 3.14.

- **#57459** keeps the 4-arg call `_worker(executor_ref, work_queue, initializer, initargs)` and only swaps the two attrs to `getattr(self, "_initializer"/"_initargs", None)`. That silences the missing-attribute error, but CPython 3.14's `_worker` is now **3-arg** — `(executor_reference, ctx, work_queue)` — so passing 4 positional args still raises `TypeError` once a worker thread spins up. It does not actually clear the 3.14 crash.
- **This PR** detects the signature at import (`inspect.signature(_worker)` → `_WORKER_USES_CTX`) and branches: the correct 3-tuple `(executor_ref, ctx, work_queue)` on ≥3.14, the original 4-tuple on ≤3.13 (a no-op there). It also adds regression tests, including a mocked 3.14-branch test that validates the new path on 3.11 CI.

@AmirF194 verified the arg order against the CPython 3.14 source and ran the suite green. Happy to defer to maintainers on which to land or whether to consolidate — just noting the mechanism difference is load-bearing here, not cosmetic.

**Comment by nankingjing** [comment]
Verified: branch is cleanly rebaseable on main (merge-base 1388cd1, test merge succeeds). The _worker signature detection at import time is a clean approach, and the mocked 3.14 test gives CI coverage on all Python versions. No conflicts, no surprises.

File: tests/tools/test_daemon_pool.py [hunk 1]
```diff
@@ -87,3 +88,122 @@ def _repo_root():
...
+
+def test_py313_branch_args_tuple_shape():
+    """When _WORKER_USES_CTX is False (current <= 3.13 default), the args
+    tuple must be the legacy 4-element shape with initializer/initargs."""
+    import unittest.mock as mock
+
+    pool = DaemonThreadPoolExecutor(
+        max_workers=1, initializer=lambda: None, initargs=()
+    )
+    assert not _WORKER_USES_CTX, (
```
Comment (teknium1) [inline tests/tools/test_daemon_pool.py]: On CPython 3.14 this flag is true by construction because `_worker` has the new three-argument signature, so this test fails on the target interpreter. Please skip this legacy-path test when `_WORKER_USES_CTX` is true, rather than asserting the runner is <=3.13.

**Review by teknium1 — COMMENTED** [review]
Thanks for adding a targeted cross-version fix and a mocked 3.14-path test. The implementation addresses the current main compatibility gap in `tools/daemon_pool.py:55-59`; its context argument order also matches CPython 3.14’s `_worker(executor_reference, ctx, work_queue)` contract (`Lib/concurrent/futures/thread.py:97`).

### Problems
- `tests/tools/test_daemon_pool.py:197` asserts `not _WORKER_USES_CTX`. On CPython 3.14, the PR computes that flag as true from the three-parameter `_worker` signature (`tools/daemon_pool.py:39`), so this test fails on the target interpreter rather than being skipped.

### Suggested changes
- Mark the legacy-shape test skipped when `_WORKER_USES_CTX` is true, or otherwise make its assertion conditional on the legacy runtime.

Automated hermes-sweeper review.

File: tests/tools/test_daemon_pool.py (hunk 1 above)
Comment (nankingjing) [reply tests/tools/test_daemon_pool.py]: Fixed in b88d4fb — replaced the hard `assert not _WORKER_USES_CTX` with `@pytest.mark.skipif(_WORKER_USES_CTX, reason="legacy 4-arg _worker signature only exists on Python <= 3.13")`, so the legacy-shape test skips on 3.14+ instead of asserting the interpreter version. Verified both ways: Python 3.12 → 10 passed (test still exercised); CPython 3.14 → 9 passed, 1 skipped with that reason.

**Comment by AIandI0x1** [comment]
**Verified the PR head and rebased onto current main — both green on real interpreters, including an actual 3.14.

We run hermes-agent in production on Fedora 44 (system Python 3.14.3), so this crash bites us on every daemon-pool submit: unpatched main dies with `AttributeError: 'DaemonThreadPoolExecutor' object has no attribute '_initializer'` on first submit — reproduced against `d3630f85`.

**Verification of this PR head (`3494b2b`):**

| Interpreter | `tests/tools/test_daemon_pool.py` |
|---|---|
| 3.14.3 — real 3.14, Fedora 44 system python | 9 passed, 1 skipped (`test_py313_branch_args_tuple_shape`, correctly version-gated) |
| 3.13.14 | 10 passed |
| 3.11 (CI's version) | 10 passed |

This empirically closes the `not _WORKER_USES_CTX` assertion flagged in the sweeper review — `3494b2b` resolves it, and the suite now passes on both sides of the signature split, including a real 3.14 interpreter that CI can't currently exercise due to the `<3.14` ceiling in `pyproject.toml`.

**Rebase:** main moved under this PR (`d3630f85` touched `tools/daemon_pool.py`), so I rebased the three commits onto current `main` (`1d1411df`). The only conflict was unioning the profile-carry comment (#54937) with the `_WORKER_USES_CTX` branch; authorship is fully preserved (all three commits credit @nankingjing). Rebased branch, same matrix green: [`daemon-pool-py314-58699-rebased`](https://github.com/AIandI0x1/hermes-agent/commits/daemon-pool-py314-58699-rebased)

```
git fetch https://github.com/AIandI0x1/hermes-agent.git daemon-pool-py314-58699-rebased
```

Happy to open it as a PR against `main` as a continuation of this one if that's easier for review — say the word.

**Comment by AIandI0x1** [comment]
**Blast-radius data from a full `tests/tools` sweep on a real 3.14.3 box (Fedora 44, production hermes deployment):**

Identical venv, only variable = this PR's diff:

| Scope | main (unpatched) | + this PR |
|---|---|---|
| `test_delegate.py` + `test_delegate_output_schema.py` + `test_cronjob_run_background.py` | **34 failed** / 88 passed | **122 passed, 0 failed** |
| full `tests/tools` (~370 files, ≈5.5k tests) | delegation cluster broken across ~20 files | green (± pre-existing/environmental) |

Every delegation/cron feature that funnels work through the async executor dies on 3.14 with the `_initializer` `AttributeError` — this PR isn't an edge fix, it's the unblock for the subsystem.

Also verified after applying the fix: **no other 3.14-specific failures surface in `tests/tools`** — the rest of the delta was missing-plugin/optional-dep noise from my venv, plus one pre-existing pair that fails identically on 3.11 (`test_browser_open_timeout.py::TestCommandTimeoutRecovery`, stale `stuck-command` registry entry — separate issue, not 3.14).

Method + full classification: I'll package the audit notes if useful. FYI @TheNeuralVault / @jooray — rebased branch from [my earlier comment](https://github.com/NousResearch/hermes-agent/pull/58699#issuecomment-5544943127) is still current against `main`.

**Comment by AIandI0x1** [comment]
Heads-up for whoever consolidates: this branch currently conflicts with main (the daemon-pool code moved during the tools refactor sweep). A rebased, cross-version-verified copy of these commits is carried with credit in #105970, whose CI runs the full suite on real 3.14.

**Comment by Ufonik88** [comment]
Not a competing fix - we closed #93802 in favour of this one. Two assertions from that abandoned test are not in this suite and may be worth folding in, since they pin things the tuple-shape tests don't:

1. `captured["target"] is concurrent.futures.thread._worker` - the pool still submits the stdlib worker rather than a private reimplementation of it.
2. `captured["daemon"] is True` - the worker stays a daemon, so a stuck worker can't block interpreter shutdown.

Both come from a `threading.Thread` interception that never spawns a real worker: patch `tools.daemon_pool.threading.Thread` with a subclass that records `self._args` / `self._target` / `self.daemon` in `start()`, call `pool._adjust_thread_count()`, then shut the pool down. Cheap enough to sit alongside the seven tests already here.

Caveat: our version keys off a module-level flag that only exists on our (now closed) branch, so it does not drop in as-is. The two assertions are the transferable part. Happy to open a test-only PR against this branch if you want them, or leave it entirely - your call, not a blocker either way.

**Comment by wyh7v7hykp-netizen** [comment]
Independent verification — Python 3.14.2 (CPython, native Windows), hermes-agent 0.21.3.

Same root cause reproduced here: on 3.14.2 every pool-backed tool (parallel tool execution, memory sync, subagent lifecycle, conversation_compression, relay) crashed on first submit with \AttributeError: 'DaemonThreadPoolExecutor' object has no attribute '_initializer'\, because 3.14 materializes _initializer/_initargs lazily inside its own _adjust_thread_count which this subclass overrides. delegate_task was affected too since child tool runs go through the same pool.

Applied the same signature-branch fix locally (capability/attr detection instead of inspect, same two worker-arg shapes) and verified:
- tests/tools/test_daemon_pool.py: 4 passed (daemon threads, idle reuse, non-blocking-exit, contextvars propagation)
- tests/agent/test_sequential_tool_timeout.py: 5 passed
- all five in-tree DaemonThreadPoolExecutor usage patterns (conversation_compression, memory_manager, relay_runtime, tool_executor, subagent_lifecycle) restored; hermes CLI starts normally.

Confirming the proposed approach works on a Windows + native 3.14.2 combo in addition to the existing Linux/gateway verifications. Thanks for the clean mocked-tuple coverage — it catches both the removed-attribute crash and the 3-vs-4-arg _worker TypeError this PR addresses.

**Comment by teknium1** [comment]
Thanks @nankingjing — this landed on `main` via #112209 (4432bccea8), which cherry-picked/salvaged this PR's work with your authorship preserved, or superseded it with the same fix plus the sibling paths the review turned up.

Closing in favour of the landed change. If anything from this PR is still missing on main, say so here and we'll pick it up.
