### PR TITLE
feat(gateway): honor disable_link_previews on Discord

### PR DESCRIPTION
**Pull request by syscrafter-dev**
## What does this PR do?

Discord expands URLs in bot messages into preview cards. Masked links (`[text](url)`) in the message body do **not** reliably suppress them — the only dependable lever is Discord's `SUPPRESS_EMBEDS` message flag, which has to be set per message at send time.

Telegram already exposes `platforms.telegram.extra.disable_link_previews`. The Discord adapter ignored the key entirely, so there was no supported way to stop preview-card clutter on Discord. This adds it.

It also adds a `"scheduled"` mode, which is the case that motivated the change: a recurring job that cites ten sources buries a channel under ten preview cards, while an ordinary chat reply sharing one link genuinely benefits from the card. `"scheduled"` suppresses only scheduled deliveries — identified by the `job_id` their route metadata already carries (`cron/scheduler.py`) — and leaves interactive chat untouched.

```yaml
gateway:
  platforms:
    discord:
      extra:
        disable_link_previews: false        # default — unchanged behavior
        # disable_link_previews: true       # suppress on every bot message
        # disable_link_previews: scheduled  # suppress only on cron deliveries
```

**Why this approach:**

- **Reuses the existing key name** rather than inventing a Discord-specific one. `true`/`false` behave exactly as they do on Telegram; `"scheduled"` is a superset, so the config stays portable between platforms.
- **The kwarg is passed only when suppressing.** `suppress_embeds=False` is Discord's default, so omitting it leaves the `channel.send()` call signature byte-identical for every existing caller and test double. Passing it unconditionally broke 3 existing tests whose fake `channel.send` stubs have fixed signatures — a good signal that the conditional form is the less invasive one.
- **`metadata["suppress_embeds"]` overrides the configured mode**, so a caller can force either behavior per message.

## Related Issue

Implements the request in #60942.

**Prior art — please read before reviewing this one.** #60975 and #60951 both predate this PR and address the same issue. #60975 in particular covers more delivery sites, including the standalone REST sender (`tools/send_message_tool.py` → `_standalone_send`) that this PR does **not** touch. The only thing unique here is the `"scheduled"` mode described above. See the discussion comment on this PR — I'd defer to #60975 on scope.

## Type of Change

- [x] ✨ New feature (non-breaking change that adds functionality)

## Changes Made

- `plugins/platforms/discord/adapter.py`
  - `_coerce_link_preview_mode()` — normalizes the extra into `never` / `scheduled` / `always`, accepting the same boolean spellings Telegram does
  - `_should_suppress_embeds()` — per-message decision; explicit metadata wins, then the configured mode
  - `send()` — builds `embed_kwargs` once and splats it into both `channel.send()` call sites (the main send and the no-reference retry)
- `tests/gateway/test_discord_suppress_embeds.py` — new, 21 tests
- `cli-config.yaml.example` — documents the key under `platforms.discord.extra`
- `website/docs/user-guide/messaging/discord.md` — new "Link Previews" section

Net: **+97 lines** across 3 files, plus the test file. No existing lines removed.

## How to Test

1. Set `gateway.platforms.discord.extra.disable_link_previews: scheduled` in `config.yaml`
2. Restart the gateway
3. Trigger a cron job that posts URLs — `hermes cron run <job_id>` — and confirm no preview cards
4. Send the same URL through interactive chat and confirm the preview card still renders
5. Flip to `true` and confirm both paths suppress; remove the key and confirm both show previews

Unit coverage: `pytest tests/gateway/test_discord_suppress_embeds.py -q` → 21 passed.

**Platforms tested:** Debian 13 (trixie), Python 3.11, discord.py 2.7.1. Running live against a Discord bot delivering 8 scheduled jobs.

## Checklist notes for the maintainers

- `pytest tests/gateway/ -k discord` → **4 failed, 330 passed**. The same 4 fail on a clean `main` checkout at `fcbd1076a9` (`test_discord_send.py` ×3 and `test_send_multiple_images.py` ×1, all `AttributeError: None has no attribute 'File'`, and only when the whole selection runs together — they pass in isolation). Pre-existing test-ordering fragility, unrelated to this change. Before: 4 failed / 309 passed. After: same 4 / 330 passed.
- `ruff check` on both changed Python files: **All checks passed.**
- I did not run `ruff format` — the existing test files in this repo don't satisfy it either, and only `PLW1514` is selected in `pyproject.toml`, so formatting appears not to be enforced.

## Possible follow-ups (deliberately out of scope)

- `edit_message()` takes the same streaming path and could honor the flag too; left alone to keep the PR to one logical change.
- `_coerce_bool_extra()` currently lives on the Telegram adapter. If maintainers want, it could move to `BasePlatformAdapter` so both platforms share one coercion helper — that's a refactor touching Telegram, so it isn't in here.

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Related: #60975 and #60951 implement the same Discord preview-suppression feature. This PR retains `disable_link_previews` parity and adds a scheduled-delivery-only mode; #60975 covers more delivery sites. Maintainers should choose or consolidate the preferred scope.

**Comment by syscrafter-dev** [comment]
Thanks for the triage — it's right, and I should have caught this before opening.

I missed the prior art. This implements what **#60942** asks for, and overlaps **#60975** and **#60951**. The "Related Issue: (none)" line in my description is simply wrong; #60942 is the issue, and I've corrected the body.

**On scope, #60975 is the more complete implementation and I'd defer to it.** Concretely, it covers a delivery path this PR does not: the standalone REST sender (`tools/send_message_tool.py` → `_standalone_send`), which @teknium1 flagged in review and @trevornk then fixed by setting the `SUPPRESS_EMBEDS` flag bit (`1 << 2`) on the JSON payloads. This PR only touches `DiscordAdapter.send()`, so out-of-process sends through that REST path would still render preview cards. #60975 also covers forum thread starters and overflow-split continuations, which this doesn't.

The one thing here that isn't in either of the other two is the **`"scheduled"` mode**: instead of a plain on/off, it suppresses previews only on scheduled deliveries — identified by the `job_id` their route metadata already carries in `cron/scheduler.py` — and leaves interactive chat alone. There's also a per-message `metadata["suppress_embeds"]` override.

That distinction matters for the use case #60942 describes. The motivating pain is a cron job posting several source URLs per run and burying the channel in cards; but a boolean means also losing the preview when someone shares a single link in conversation, where the card is genuinely useful. `"scheduled"` is a superset of the boolean — `true`/`false` behave exactly as they do on Telegram — so it doesn't break parity.

Happy to go whichever way you prefer:

1. **Close this in favor of #60975**, and once it lands I'll open a small follow-up adding the `"scheduled"` value on top of its config plumbing, covering all the send sites it introduces; or
2. Keep this open if you'd rather take the scheduled-delivery behavior now and layer the wider site coverage after.

I'd suggest (1) — #60975 got there first and covers more. Just say the word and I'll close.

One note in case it's useful to whoever picks this up: `pytest tests/gateway/ -k discord` has 4 pre-existing failures on a clean `main` (`AttributeError: None has no attribute 'File'` in `test_discord_send.py` ×3 and `test_send_multiple_images.py` ×1). They only fail when the whole selection runs together and pass in isolation, so it looks like test-ordering state leaking through the `sys.modules` discord mock. Unrelated to any of these PRs, but it makes CI noisy for anything touching this area.
