### PR TITLE
fix(dashboard): active_sessions count excludes child sessions (#15722)

### LINKED ISSUE #15722: Dashboard active_sessions count excludes child sessions (always shows 0)
## Bug Description

Dashboard shows `active_sessions: 0` even when there are active CLI/WeChat/Feishu sessions.

## Root Cause

In `hermes_cli/web_server.py` the `/api/status` endpoint counts active sessions using `SessionDB.list_sessions_rich()`, which by default excludes all sessions that have a `parent_session_id` set (i.e. child / sub-sessions).

Relevant code in `hermes_state.py`:
```python
if not include_children:
    where_clauses.append("s.parent_session_id IS NULL")
```

The counting logic in `web_server.py`:
```python
active_sessions = sum(
    1 for s in sessions
    if s.get("ended_at") is None
    and (now - s.get("last_active", s.get("started_at", 0))) < 300
)
```

The current session is an active CLI session with:
- `ended_at IS NULL` ✓
- Last message 142 seconds ago (< 300s) ✓
- But `parent_session_id` is set (it is a child session)

Because of the `parent_session_id IS NOT NULL` filter, this active session is excluded from the count, causing `active_sessions` to always be 0 for child sessions.

## Expected Behavior

Child sessions that are actively processing messages should also be counted toward `active_sessions`. The filtering logic for counting active sessions should be separate from the logic used to list sessions for display.

## Environment

- hermes-agent v0.10.0 (2026.4.16)
- macOS

### PR DESCRIPTION
**Pull request by briandevans**
## Summary
- `/api/status` was calling `list_sessions_rich()` without `include_children=True`, silently dropping all child sessions from the active count
- Any CLI, WeChat, or Feishu session running as a child (delegation, subagent, or compression continuation) was invisible to the counter
- One-line fix: pass `include_children=True` to the counting query

## The bug

`list_sessions_rich()` excludes rows where `parent_session_id IS NOT NULL` by default — by design, so the session browser shows a clean top-level view. The `/api/status` handler reused this listing call for counting active sessions without opting out of the filter. Users whose active session was a child (common in delegation and gateway flows) always saw `active_sessions: 0`.

## The fix

Pass `include_children=True` to `list_sessions_rich()` only for the active-session counting query. The sessions listing endpoint at `/api/sessions` is unaffected — it continues to filter children out of the UI list.

## Test plan
- [x] **Before**: `test_active_sessions_count_without_include_children_misses_child` documents the bug — count is 1 (child missing) without the flag
- [x] **After**: `test_active_sessions_count_includes_child` passes — both parent and child are counted
- [x] **Regression guard**: the new tests make the fix explicit in the SessionDB layer; `test_active_sessions_count_without_include_children_misses_child` documents what the old code produced
- [x] Full `tests/test_hermes_state.py` suite: 178 passed

## Related
- Fixes #15722

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by briandevans** [comment]
Rebased onto current `origin/main` (`9be3ab1a5`) — was 714 commits stale and conflicted with the 3 new tests in `TestListSessionsRich` (`test_branch_session_visible_in_list`, `test_subagent_session_still_hidden`, `test_compression_child_still_hidden`) added on main since this branch was opened.

Conflict resolution and adjustment:

- Kept all 3 new main tests untouched.
- Dropped my original `test_child_session_excluded_by_default` — it was a near-duplicate of main's new `test_subagent_session_still_hidden`.
- Renamed and tightened my remaining 3 tests to use the "subagent" terminology that main now uses (children where the parent did *not* end with `'branched'`):
  - `test_include_children_surfaces_subagent_sessions`
  - `test_active_sessions_count_includes_subagent_when_include_children`
  - `test_active_sessions_count_without_include_children_misses_subagent` (regression guard for #15722)

The production fix (`hermes_cli/web_server.py:566`) is unchanged: `list_sessions_rich(limit=50, include_children=True)`. After main's branch-vs-subagent split, the bug is now scoped specifically to subagents and compression continuations rather than all children, but the fix is still correct — `/api/status` should count any active session regardless of lineage.

Tests on the rebased branch (commit `55caaf3e8`):

- `tests/test_hermes_state.py::TestListSessionsRich` — 14/14 passed
- `tests/hermes_cli/test_web_server.py` (status endpoints) — 7/7 passed

**Comment by briandevans** [comment]
CI audit — all 37 `test` job failures on commit `c75ec8cc8` (PR/15773 merge) are pre-existing baselines on clean `origin/main` (`9be3ab1a5`, run [25130105696](https://github.com/NousResearch/hermes-agent/actions/runs/25130105696)). Zero failures intersect with touched code (`hermes_cli/web_server.py` `/api/status`, `tests/test_hermes_state.py::TestListSessionsRich`).

Breakdown:

- **33 / 37** appear identically on the `9be3ab1a5` main run (same tests, same error text). Examples: `tests/agent/test_minimax_provider.py::TestMinimaxPreserveDots::test_normalize_converts_without_preserve`, `tests/hermes_cli/test_web_server.py::TestBuildSchemaFromConfig::test_no_single_field_categories` (`Category 'telegram' has only 1 field(s) — should be merged`), `tests/hermes_cli/test_config_env_expansion.py::TestLoadConfigExpansion::*`, `tests/gateway/test_session.py` collection error (`cannot import name 'normalize_whatsapp_identifier' from 'gateway.session'`), etc.
- **4 / 37** are xdist-order flakes that flip across runs and pass in isolation:
  - `tests/test_cli_skin_integration.py::TestCompactBannerSkinIntegration::test_compact_banner_shows_version_label`
  - `tests/tools/test_clipboard.py::TestIsWsl::test_wsl1_detected` / `test_wsl2_detected` (module-level cache in `_is_wsl()`; main runs flake on different members of the same class — `test_proc_version_missing`, `test_regular_linux`, `test_result_is_cached`)
  - `tests/tools/test_docker_environment.py::test_run_as_host_user_warns_and_skips_when_no_posix_ids` (also flakes on the second main run [25130722163](https://github.com/NousResearch/hermes-agent/actions/runs/25130722163))

Touched-code coverage is green:

- `tests/test_hermes_state.py::TestListSessionsRich` — 14/14 passed locally with `uv run --with pytest --with pytest-xdist --with fastapi --with uvicorn`.
- `tests/hermes_cli/test_web_server.py` status-endpoint tests pass.

The dashboard `/api/status` fix is unaffected by these failures.

**Comment by briandevans** [comment]
Closing to keep the queue clean — base is 18 days behind main with ~50 commits to hermes_cli/web_server.py since. Happy to reopen and rebase if this is still useful.
