### PR TITLE
fix(agent): rotate Codex credentials on model entitlement rejection

### LINKED ISSUE #61660: codex_models.py: `*-pro` slugs in DEFAULT_CODEX_MODELS return HTTP 400 for ChatGPT accounts
# Issue Report: `gpt-5.6-sol-pro` 等 `-pro` 系列 Codex 預設清單對 ChatGPT 帳號無效

**Repo**: NousResearch/hermes-agent
**File**: `hermes_cli/codex_models.py` (`DEFAULT_CODEX_MODELS`, lines 14–52)
**Severity**: Medium — curated fallback 推送了 8 個 slugs，其中 1 個對所有 ChatGPT Pro 帳號必壞
**Reproducible**: 100% on every ChatGPT Pro account we tested (verified 2026-07-10)
**Versions tested**: hermes-agent v0.18.2 (2026.7.7.2) + `gpt-5.6-sol-pro` via `chatgpt.com/backend-api/codex/responses`

---

## Summary

`DEFAULT_CODEX_MODELS` 把 `gpt-5.6-sol-pro`、`gpt-5.6-terra-pro`、`gpt-5.6-luna-pro` 當成 ChatGPT OAuth 可用 fallback，但 **chatgpt.com Codex backend 對 `*-pro` 系列回 HTTP 400**，錯誤訊息明確：「The '&lt;model&gt;' model is not supported when using Codex with a ChatGPT account.」

同一份 curated 清單在「live discovery 失敗時 / 首次跑 / 短暫 API 故障」會 leak 這些 dead slugs 到 `/model` picker，使用者選到就 400 crash。

這跟 source code 註解提到的 `gpt-5.2-codex`、`gpt-5.1-codex-max`、`gpt-5.1-codex-mini` 屬於同一類歷史 bug（見 `codex_models.py:40–51` 註解），但 `-pro` 系列沒被同樣處理掉。

## Steps to Reproduce

```bash
hermes auth add openai-codex          # ChatGPT Plus / Pro account
```

選取 `gpt-5.6-sol-pro` 後跑任意查詢，會撞 HTTP 400：

```
POST https://chatgpt.com/backend-api/codex/responses
HTTP 400
{"detail":"The 'gpt-5.6-sol-pro' model is not supported when using Codex with a ChatGPT account."}
```

## Live Evidence (我的 ChatGPT Pro 帳號，2026-07-10)

對 `chatgpt.com/backend-api/codex/responses` (Bearer OAuth) 跑單 prompt (`"Reply with PONG"`)，streaming：

| Model | Status | Note |
|---|---|---|
| `gpt-5.5` | ✅ HTTP 200 | 正常 |
| `gpt-5.4` | ✅ HTTP 200 | 正常 |
| `gpt-5.3-codex-spark` | ✅ HTTP 200 | Pro-only，正常 |
| `gpt-5.6-sol` | ✅ HTTP 200 | 正常 |
| `gpt-5.6-terra` | ✅ HTTP 200 | 正常 |
| `gpt-5.6-luna` | ⚠️ HTTP 404 | 列入 live discovery 清單但實際 404（lifecycle 差異，次要） |
| `gpt-5.6-sol-pro` | ❌ HTTP 400 | `not supported when using Codex with a ChatGPT account` |
| `gpt-5.6-terra-pro` | ❌ HTTP 400 | 同上 |
| `gpt-5.6-luna-pro` | ❌ HTTP 400 | 同上 |

## Root Cause

`codex_models.py:14–22` 把三個 `*-pro` 系列列入 curated fallback：

```python
DEFAULT_CODEX_MODELS: List[str] = [
    "gpt-5.6-sol",
    "gpt-5.6-sol-pro",      # ← 400
    "gpt-5.6-terra",
    "gpt-5.6-terra-pro",    # ← 400
    "gpt-5.6-luna",
    "gpt-5.6-luna-pro",     # ← 400
    "gpt-5.5",
    ...
]
```

但 OpenAI ChatGPT 帳號 OAuth backend 不開 `-pro` slugs（`-pro` 是 OpenAI public API 上的標識，不是 Codex OAuth 通道路徑）。

## Suggested Fix

跟 `codex_models.py:40–51` 處理 `gpt-5.2-codex` 那段同樣手法 — 從 `DEFAULT_CODEX_MODELS` 移除這三個 `*-pro` slugs：

```diff
 DEFAULT_CODEX_MODELS: List[str] = [
     # GPT-5.6 series (Sol/Terra/Luna + -pro high-effort modes) — GA 2026-07-09
     # (previewed 2026-06-26).
     "gpt-5.6-sol",
-    "gpt-5.6-sol-pro",
     "gpt-5.6-terra",
-    "gpt-5.6-terra-pro",
     "gpt-5.6-luna",
-    "gpt-5.6-luna-pro",
     "gpt-5.5",
     ...
```

並在 `_FORWARD_COMPAT_TEMPLATE_MODELS` 同步移除對應條目（lines 54–69）。

註解應該點名這條歷史：`-pro` 標識對 OpenAI public API 有效，但對 `chatgpt.com/backend-api/codex` OAuth path 無效，不能當 curated fallback。

## Severity Justification (Medium, not Low/High)

- **不是 High**：live discovery `https://chatgpt.com/backend-api/codex/models` 本來就會回 200 OK 帶可用的 slug 清單，正常路徑下使用者不會撞 curated fallback。
- **不是 Low**：首次跑（token 剛換新）、live discovery 短暫故障、network 連通、cache 過期 → 4 條路徑都會 fall through 到 curated → 使用者選 `*-pro` → 100% 400。
- **撞過的人會以為「Hermes 整個 Codex 死了」**，但其實只是 curated 多塞了三個 slug。

## Compatibility / Risk

**後向相容**：使用者在 config 中已經手動設 `gpt-5.6-sol-pro` 的人會從能選變不能選 — 但他們目前撞 400，本來就不能用，所以是 **strictly better**。

**建議驗證**：先 grep upstream issues 看有沒有人回報過同樣事，再 merge。

---

## Append-only Notes

- 2026-07-10: Issue 已送出 → https://github.com/NousResearch/hermes-agent/issues/61660
- 提交者：sky770825（無 triage 權限，labels 由 bot/維護者加）
- 我的 MEMORY 已記下：「Codex OAuth 對 `-pro` slugs 全擋，回到 `gpt-5.5` 或 `gpt-5.6-sol` 系列」

### LINKED ISSUE #71970: Codex credential pool does not rotate on account-specific model entitlement HTTP 400
## Summary

When an `openai-codex` credential returns the account-specific HTTP 400 response

`The '<model>' model is not supported when using Codex with a ChatGPT account.`

Hermes does not classify it as a credential/model entitlement failure. The selected credential is retried or the request falls through as a generic format/request failure instead of trying the next eligible credential in the same provider pool.

## Reproduction

1. Configure at least two distinct `openai-codex` credential-pool entries.
2. Request a model that the active ChatGPT-backed credential rejects with the exact response above.
3. Keep a second configured credential eligible for that model.
4. Observe that the HTTP 400 is not attributed to the exact active credential and model, so same-provider credential rotation is not attempted.

This report is based on current `main` at `eb52760564dbba2e5971fa54bd67384e281cd3b8` and uses only the normalized public error text. No credential material or account identity is included.

## Expected behavior

- Classify only the exact normalized ChatGPT-account model rejection as an entitlement failure.
- Mark only the exact active credential + requested model unavailable.
- Try the next eligible `openai-codex` credential once.
- If every eligible credential rejects the same model, stop same-provider rotation and retain the existing configured provider fallback.
- Do not mark the credential globally unavailable for other models.
- Fail closed when the active credential cannot be attributed exactly.
- Clear model markers through the existing explicit credential-pool reset lifecycle.

## Non-goals

- Arbitrary HTTP 400 responses must not rotate credentials.
- HTTP 503 concurrency/overload must remain transient and must not persist credential death.
- This does not change static model catalogs or the model picker.
- This does not add background inference or a readiness probe.

## Related but not duplicate

- Static ChatGPT-account model compatibility: #61660 / #61665 and #23097 / #23175.
- Codex credential-pool recovery and multi-account support: #31032, #47096, and #68520.
- Quota/fallback handling (`usage_limit_reached`), which is a different failure class: #45646 and #46915.

A focused patch with classifier, exact-attribution, model-scoped persistence, reset-lifecycle, and fallback regression tests is ready for review.

### PR DESCRIPTION
**Pull request by kilhyeonjun**
## Summary

- classify the exact normalized ChatGPT-account Codex model rejection as a distinct entitlement failover reason
- persist model-scoped unavailability on the exact active `openai-codex` pool entry and rotate once to the next eligible credential
- fail closed on conflicting/missing credential attribution, preserve other-model eligibility, and clear model markers through the existing explicit pool reset lifecycle
- retain existing provider fallback after every same-provider credential rejects the requested model

Fixes #71970

## Root cause

The account-specific Codex HTTP 400 was treated as a generic request/format failure. Credential-pool recovery therefore had no narrow reason or model-scoped state with which to rotate a different credential, even when another configured ChatGPT subscription could use the requested model.

## Safety boundaries

- only the anchored, whitespace/case-normalized response `The '<model>' model is not supported when using Codex with a ChatGPT account.` is classified as entitlement
- arbitrary HTTP 400 responses do not rotate credentials
- HTTP 503 concurrency/overload remains transient and is not persisted as credential death
- 401 refresh, 429 reset-aware recovery, provider mismatch guards, and cross-provider fallback behavior are unchanged
- model markers are scoped to the exact pool entry + model; no token, account id, or stable identity is logged

## Tests

```text
scripts/run_tests.sh tests/agent/test_credential_pool.py tests/agent/test_error_classifier.py tests/run_agent/test_credential_pool_interrupt.py tests/run_agent/test_auth_provider_failover.py -q
# 321 passed, 0 failed; 7.2s runner wall

uv run ruff check agent/error_classifier.py agent/credential_pool.py agent/agent_runtime_helpers.py tests/agent/test_error_classifier.py tests/agent/test_credential_pool.py tests/run_agent/test_credential_pool_interrupt.py
# All checks passed

uv run python -m py_compile agent/error_classifier.py agent/credential_pool.py agent/agent_runtime_helpers.py
# passed
```

`ty check` on the touched large modules reports the repository's existing advisory diagnostics; the blocking Ruff gate and focused behavioral suites pass. Upstream CI can provide the canonical base-vs-head type-diagnostic diff.

## Related work

This complements static model compatibility fixes #61660 / #61665 and credential-pool work #31032 / #47096 / #68520. It is intentionally separate from quota-based `usage_limit_reached` handling in #45646 / #46915.

## Platform

Tested on macOS arm64 with Python 3.12 through the repository `uv` environment. No live credential or provider request was used by the tests.

### CODE REVIEW

**Comment by PRATHAMESH75** [comment]
Reviewed against the #71970 spec (static review, not run locally). This looks correct and complete — it maps cleanly onto every expected-behavior bullet in the issue:

- **Exact-only classification** — `_CHATGPT_ACCOUNT_MODEL_REJECTION.fullmatch` is `^…$`-anchored with a whitespace-free model token, so `prefix …`/`… suffix` correctly stay `format_error` (covered by `test_400_nonexact_chatgpt_account_text_remains_format_error`), and the structured-`code` check still wins over the text match (`test_400_structured_replay_code_beats_chatgpt_account_text`). Non-goal "arbitrary 400 must not rotate" is respected.
- **Model-scoped persistence, credential stays healthy** — `mark_entitlement_unavailable_and_rotate` only appends to `extra["unavailable_models"]`, so the credential remains selectable for other models; the rotate candidate filter excludes the failed model, so the same credential can't be re-picked for it.
- **Fail closed on conflicting attribution** — the `credential_id`+`api_key_hint` consistency gate returning `None` (and `test_codex_entitlement_requires_consistent_id_and_key_attribution`) matches "fail closed when the active credential cannot be attributed exactly."
- **Rotate once, then retain provider fallback** — when every eligible entry is blocked, `candidates` empties → `None` → `_rotate_failed_credential` returns `(False, …)`, preserving the existing provider fallback (`test_codex_entitlement_rotates_once_then_allows_provider_fallback`).
- **Reset lifecycle** — `reset_statuses` now clears the `unavailable_models` marker, so markers only clear through the explicit pool reset.

One minor, non-blocking note: when **neither** `credential_id` nor `api_key_hint` is supplied, the method falls through to `_current_unlocked()` rather than failing closed. In practice the caller (`agent_runtime_helpers.py:955-969`) almost always populates at least one hint, so this is an unlikely path — but if strict "no attribution ⇒ no marking" is intended, an early `if not identity_supplied: return None` would make that explicit. Not a merge blocker.

Verdict: **fixes the issue as specified**, with genuine failing-then-green regression coverage. Nice work @kilhyeonjun.

File: agent/credential_pool.py [hunk 1]
```diff
@@ -1923,6 +1923,42 @@ def mark_exhausted_and_rotate(
...
+            identity_supplied = bool(credential_id or api_key_hint)
+            id_entry = next((e for e in self._entries if credential_id and e.id == credential_id), None)
+            key_entry = next((e for e in self._entries if api_key_hint and e.runtime_api_key == api_key_hint), None)
+            if credential_id and api_key_hint and (id_entry is None or key_entry is None or id_entry.id != key_entry.id):
+                return None
+            entry = id_entry or key_entry
+            if entry is None and identity_supplied:
+                return None
+            entry = entry or self._current_unlocked()
+            if entry is None:
```
Comment (teknium1) [inline agent/credential_pool.py:1948]: This fallback violates the stated fail-closed rule: when neither hint identifies the issuer, `_current_unlocked()` is shared mutable state and may be a different healthy account. Return `None` unless an exact ID or key hint resolved the entry.

File: agent/credential_pool.py [hunk 2]
```diff
@@ -1923,6 +1923,42 @@ def mark_exhausted_and_rotate(
...
+                return None
+            blocked = set(entry.extra.get("unavailable_models", []))
+            blocked.add(model)
+            updated = replace(entry, extra={**entry.extra, "unavailable_models": sorted(blocked)})
+            self._replace_entry(entry, updated)
+            self._persist()
+            candidates = [
+                candidate for candidate in self._available_entries()
```
Comment (teknium1) [inline agent/credential_pool.py:1956]: This filters only the immediate recovery call. `CredentialPool.select()` on current main has no model argument and `_available_entries()` ignores `unavailable_models`, so a reloaded pool can select this marker-bearing credential again for the same model. Make the normal selection path model-aware and add a reload regression test.

**Review by teknium1 — COMMENTED** [review]
Thanks for the focused classifier and credential-pool work. The reported gap is real on current main: HTTP 400 reaches `_classify_400()` at `agent/error_classifier.py:1107` and currently falls through to generic `format_error` at `:1430`.

### Problems
- `agent/credential_pool.py:1948` in this diff falls back to `_current_unlocked()` when no credential identity is supplied. That contradicts the stated fail-closed boundary and can mark an unrelated credential; current recovery explicitly documents why the shared current pointer is unsafe for attribution in `agent/agent_runtime_helpers.py:980-990`.
- The persisted marker is not used by normal selection. Current `CredentialPool.select()` accepts no model (`agent/credential_pool.py:1593`) and `_available_entries()` does not inspect `unavailable_models` (`:1603-1726`), so reloading the pool can select the previously rejected account for the same model.

### Suggested changes
- Require an exactly resolved credential identity before writing a marker, with a no-hint regression test.
- Thread the requested model through normal selection and add a reload test proving model-specific exclusion while retaining eligibility for another model.
- Cover the all-marked case that returns control to provider fallback.

Automated hermes-sweeper review.

**Comment by GottZ** [comment]
> *This was generated by AI during triage.*

#### Summary

Twelve PRs address distinct layers of the same Codex model-compatibility failure family: provider/model normalization, auxiliary routing, authenticated and fallback catalogs, error classification, and credential-scoped entitlement recovery. The diffs range from already-landed catalog and routing fixes to open patches that still need current-main updates or correctness fixes before they can close the remaining issues.

#### Related pull requests

- #695 **[closed]** `best fix` — (+196/-2) — superseded implementation: Normalizes a non-Codex model after provider resolution, covering the direct cause of #651, but includes an unrelated gateway retry test; it remains relevant because its approach informed the landed fix in commit 95b1130.
- #696 **[closed]** `best fix` — (+173/-2) — superseded by 95b1130: Adds the same provider-resolution normalization as #695 plus provider-prefix stripping and four regression scenarios, directly addressing #651. It was closed after a contributor documented unrelated regressions in the stale branch, while the useful `_model_is_default` behavior and tests were incorporated into 95b1130.
- #17544 **[closed]** `partial` — (+17/-17) — superseded by #17765: Replaces the rejected hardcoded auxiliary model with `gpt-5.4`, fixing the immediate #17533 failure but retaining the stale-constant design. It remains relevant as the identified failure site and short-term alternative that motivated the durable removal in #17765.
- #17765 **[merged]** `best fix` — (+123/-61) — merged reference implementation: Removes the hardcoded Codex auxiliary model and excludes guessed Codex models from automatic fallback while preserving explicitly configured Codex routing, eliminating the recurring cause of #17533. It supersedes #17544 and landed as ce0c3ae4.
- #22991 **[merged]** `best fix` — (+156/-26) — merged entitlement-aware catalog reference: Restores `gpt-5.3-codex-spark`, preserves OAuth-only catalog entries, wires live discovery into the picker, and records Spark's context limit, addressing #16172 without treating an account-gated valid model as universally unsupported.
- #23175 **[closed]** `fixes` — (+31/-3) — superseded catalog subset: Removes three ChatGPT-account-rejected slugs from the offline fallback, directly addressing one source of #23097, but was closed in favor of #23189. Its removal was subsequently implemented by #33424 and commit e8955f222cecb6ed7ac3f0c541b9b5b02d22843f.
- #23189 `partial` — (+34/-13) — keep open with a salvage path: Correctly stops synthetic expansion of a successful authenticated catalog, addressing the live-catalog half of #23097 that the static removals do not cover. The keep_open review should be followed: retain the exact-list live-catalog assertion, but rebase and rewrite the stale fallback fixture around a currently supported template and current GPT-5.6 ordering.
- #33424 **[merged]** `best fix` — (+21/-10) — merged reference implementation: Removes `gpt-5.2-codex`, `gpt-5.1-codex-max`, and `gpt-5.1-codex-mini` from both fallback defaults and synthesis triggers, directly fixing the static-catalog cause of #23097. It landed as e8955f222cecb6ed7ac3f0c541b9b5b02d22843f and subsumes the useful scope of #23175.
- #52509 `best fix` — (+13/-19) — author action required: Removes dead `gpt-5.3-codex` catalog and synthesis paths for #52492, but the keep_open review identifies an automatic fallback at `cli.py:5338` that still selects the rejected slug and stale expectations that omit current GPT-5.6 synthesis. Rebase onto main and update that fallback and its regression test while preserving current synthesis behavior.
- #61665 `best fix` — (+29/-8) — keep open with a salvage path: Removes all three synthetic GPT-5.6 `-pro` slugs from both curated defaults and forward-compat templates while retaining the valid base models, directly matching #61660. The keep_open verdict reports no correctness or scope issue, and independent live evidence confirms that the authenticated catalog omits these variants while the synthesized choices fail with HTTP 400.
- #69022 **[closed]** `fixes` — (+67/-8) — closed as overlapping work with unique salvage: Its catalog changes duplicate #61665, while its distinct `error_classifier.py` change maps the Codex HTTP 400 to non-retryable model fallback. It remains relevant because commit f9f835313 contains focused classifier tests that can inform #71973, although its broad substring match is less exact than #71973's anchored entitlement classifier.
- #71973 `best fix` — (+201/-2) — author action required despite the earlier static fixes-issue review: The diff adds exact entitlement classification, model-scoped credential markers, rotation, reset handling, and regression tests for #71970, but the later contributor keep_open review identifies two blocking correctness gaps: no-hint attribution can mark `_current_unlocked()`, and normal/reloaded selection ignores `unavailable_models`. Rebase onto main, require exact credential attribution, make normal selection model-aware, and add the requested reload regression test; the diff does not implement the catalog correction for #61660 despite that structural closes edge.

#### Duplicates

#695 and #696 are substantially the same #651 normalization fix and were superseded by 95b1130. #17544 and #17765 address the same #17533 auxiliary fallback failure, with #17765 replacing the stale-constant approach. #23175 and #33424 remove the same dead fallback slugs for #23097, with #33424 landed; #23189 covers the separate live-catalog synthesis path. The catalog portion of #69022 duplicates #61665, while its classifier portion overlaps the narrower entitlement classification in #71973.

#### Suggested consolidation

Author action: rebase onto main, or split out the part that can merge. For #71973, first resolve the blocking contributor review by removing `_current_unlocked()` attribution fallback, threading the requested model through normal and reloaded pool selection, and adding a reload regression test; keep its exact classifier and model-scoped reset behavior as the salvage path. Keep #61665 open as the focused #61660 catalog correction, keep #23189 open for authoritative live-catalog handling after its stale fallback test is updated, and keep #52509 open only after its direct `cli.py:5338` fallback and current GPT-5.6 expectations are fixed. The already-closed duplicate chains remain #695/#696 → 95b1130, #17544 → #17765, and #23175 → #33424/e8955f222cecb6ed7ac3f0c541b9b5b02d22843f; #69022 can remain closed, with only its focused classifier evidence salvaged where useful.

#### Complex graph

```mermaid
flowchart LR
    classDef open fill:#dbeafe,stroke:#1d4ed8,color:#1e3a8a
    classDef merged fill:#dcfce7,stroke:#15803d,color:#14532d
    classDef closed fill:#e5e7eb,stroke:#6b7280,color:#1f2937
    classDef unverified fill:#f3f4f6,stroke:#9ca3af,color:#374151
    classDef best stroke-width:3px,stroke:#b45309
    classDef target stroke-width:3px,stroke:#4338ca
    I61660(["issue #61660 (open)"])
    I71970(["issue #71970 (open)"])
    P71973["PR #71973 (open)"]
    P71973 -.->|partial| I61660
    P71973 -->|best fix| I71970
    class I61660 open
    class I71970 open
    class P71973 open
    class P71973 best
    class P71973 target
    click I61660 "https://github.com/NousResearch/hermes-agent/issues/61660"
    click I71970 "https://github.com/NousResearch/hermes-agent/issues/71970"
    click P71973 "https://github.com/NousResearch/hermes-agent/pull/71973"
```
*Graph: solid arrow = fixes / best fix, dashed arrow = partial or unverified (see edge label); boxed group = PRs duplicating each other; amber border = best fix; indigo border = target; gray node = closed (state tag in the node label).*

_Cross-PR triage: Reviewed 12 pull requests and 7 issues in this complex. Each diff was read against this issue; Assessment working set: 103 kB of PR diffs, 49 kB of issue/PR text, 25 kB of discussion (28 comments), 24 verify verdicts. verdicts reflect diff content, not PR titles. Part of an automated triage batch._

**Comment by teknium1** [comment]
Thanks @kilhyeonjun — the work in this PR has landed on `main` via:

- #115760 — fix(agent): Codex pool rotates to the next account on a ChatGPT-account model entitlement 400 (#71970, salvage #71973) (landed in `f07afac38bc8`)

Your contribution is credited there (cherry-picked authorship / co-author trailer or credit in the PR body; see the linked PR for what was kept and what was trimmed). Closing this one as landed / superseded so the backlog reflects reality. If something in your original diff is still missing on current `main`, please comment and we'll reopen or follow up.
