### PR TITLE
fix(matrix): accept `is_voice kwarg` in `send_voice` to match base contract

### LINKED ISSUE #102221: Matrix voice delivery broken in v0.21.0: send_voice() got unexpected kwarg 'is_voice'
### Bug

Voice message delivery to Matrix rooms fails with a TypeError after v0.21.0. Every `[[audio_as_voice]]`-tagged MEDIA attachment dies at the send step. This regressed in the v0.21.0 (2026.8.31) release — zero voice delivery errors in our logs before Sept 2, 13:16 UTC (two hours after updating to v0.21.0), then consistent 100% failure on every subsequent attempt (5+ observed within hours).

### Environment

- Hermes Agent v0.21.0 (2026.8.31), upstream 562ee8ab
- Platform: Matrix (mautrix-python), self-hosted Synapse, E2EE enabled
- TTS providers tested: piper (local) and openai-compatible (Speaches) — failure is TTS-provider-independent

### Root cause

`gateway/platforms/base.py` line ~6983 (non-streaming media dispatch loop) passes a new `is_voice` kwarg to `send_voice()`:

```python
media_result = await self.send_voice(
    chat_id=event.source.chat_id,
    audio_path=media_path,
    metadata=_final_thread_metadata,
    is_voice=is_voice,
)
```

`should_send_media_as_audio()` (line ~209) returns True for Matrix for all audio extensions, so the call always routes to `send_voice`. But the Matrix adapter's `send_voice` signature (`plugins/platforms/matrix/adapter.py` line 2581) was not updated to accept it:

```python
async def send_voice(
    self,
    chat_id: str,
    audio_path: str,
    caption: Optional[str] = None,
    reply_to: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> SendResult:   # <-- no **kwargs, no is_voice param
```

The base-class `send_voice` (line 4777) accepts `**kwargs`, but the Matrix adapter overrides it with an exact signature and no `**kwargs`, so the kwarg propagation fails.

### Error

```
WARNING gateway.platforms.base: [Matrix] Error sending media: MatrixAdapter.send_voice() got an unexpected keyword argument 'is_voice'
```

The audio file is generated correctly (valid Ogg/Opus confirmed with `file`), written to the TTS cache, and then dropped at delivery. The user sees the text of the response but never the voice message. No fallback path exists for this failure — `should_send_media_as_audio` returned True, so document fallback is never attempted.

### Suggested fix

Add `is_voice: bool = False` (or `**kwargs`) to `MatrixAdapter.send_voice`'s signature. The adapter currently implements MSC3245 voice bubbles for Ogg/Opus input; `is_voice` could also be used to gate transcode-to-Ogg-Opus for non-Opus input (matching the Telegram adapter behavior noted in `should_send_media_as_audio`).

Alternatively, stop passing `is_voice` from the base dispatch loop and let `should_send_media_as_audio` be the single decision point, since for non-Telegram platforms it already returns True for all audio extensions.

### Notes

- Confirmed deliveries still work when the file goes through the auto-extracted local-file path (`extract_local_files` → `send_document`), which is why some audio sends appear to succeed — those are document attachments, not voice bubbles.
- Happy to test a patch.

### PR DESCRIPTION
**Pull request by bannert1337**
## Problem

`MatrixAdapter.send_voice` raises `TypeError: send_voice() got an unexpected keyword argument 'is_voice'` on **every** Matrix voice send since v0.21.0. The gateway swallows the exception as "Error sending media", so the user sees nothing — no audio, no error.

Introduced by ccc367dce0 ("universal voice-bubble transcode"), which made the shared caller (`gateway/platforms/base.py:3728`) pass `is_voice=is_voice` unconditionally. The base class accepts it (`**kwargs`, semantics documented at `base.py:2722`), but the Matrix override was never updated. Reported in #102221 with a reproducible 100%-failure window starting 2026-09-02.

## Fix

Two lines in `plugins/platforms/matrix/adapter.py`:

1. `send_voice` signature gains `is_voice: bool = True` — matching the base-class contract the shared caller already assumes.
2. The `_send_local_file` call forwards `is_voice=is_voice` instead of a hardcoded `True`, so `is_voice=False` still produces a plain `m.audio` without MSC3245 voice metadata, exactly as the base class documents.

## Tests

`tests/gateway/test_matrix_send_voice_is_voice.py` — two invariant tests:

- **signature contract**: the override must accept the kwarg the shared caller passes. Verified red on `origin/main`'s adapter (TypeError at collection of the call path), green with the fix.
- **forwarding contract**: `is_voice=False` must reach `_send_local_file` so plain audio goes out without voice metadata. Same red-on-main verification.

Sibling adapters (Mattermost, LINE, Weixin) have the same-shaped bug but are covered by #100021/#101381 — this PR stays scoped to the Matrix adapter from #102221.

## Risk

Minimal. Default `is_voice=True` preserves current intended behavior; the only behavioral change is that voice sends stop raising and `is_voice=False` callers get plain audio instead of a TypeError. No migrations, no config surface, no other call sites touched.

Fixes #102221

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #100679 - same `is_voice` signature fix for #102221 in `plugins/platforms/matrix/adapter.py`. This PR additionally forwards `is_voice` to `_send_local_file` and adds tests, which reviewers may prefer; #99712 is a broader competing fix. Flagging the cluster so one gets picked.
