### PR TITLE
fix(cron): nudge review of escaped-run failures too

### LINKED ISSUE #88655: Scheduler-level cron processing errors bypass failure_nudge alerting — jobs can die silently for hours
**Version:** v0.20.2

**What happened:** after an in-place update left our gateway running mixed code versions (see #88654), an every-10-minutes agent cron failed at the *scheduler* layer on every tick for ~5 hours:

```
ERROR cron.scheduler: Error processing job 593fab25e7f4: cannot import name '_MAX_TOOL_ERROR_CHARS' from 'tools.registry'
```

No alert was ever delivered. As documented, `cron.failure_nudge_threshold` counts **agent-run failures**; these errors happened before an attempt could record a durable state (later runs show as `unknown` after restart, which the docs correctly describe as audit records). The net effect: a critical automation was dead for hours with zero operator signal, while healthy-looking 'Next run' timestamps kept advancing.

**Suggested fix:** count scheduler-level processing exceptions for a job toward the same failure streak (or a parallel streak) so the failure nudge fires, and/or deliver a one-time 'job could not be processed' alert to the job's deliver target after N consecutive processing errors.

### PR DESCRIPTION
**Pull request by jackulau**
## What does this PR do?

Makes the repeated-failure review nudge reach the failures that need it most.

`_failure_streak_nudge` (#80752) appends "this job has failed N runs in a row, worth a review" to a recurring job's failure alert once its streak hits `cron.failure_nudge_threshold`. It is composed at exactly one place: the normal delivery in `_run_one_job_body`'s `try` body.

Eight days later, `4668750fa` gave the outer `except BaseException` handler a delivery of its own, so an exception that escapes the run body finally alerts instead of being bookkeeping-only. That new site calls `_summarize_cron_failure_for_delivery` **without** the nudge, so the nudge is unreachable for a job whose failures all escape.

That is not a hypothetical set of failures. It is the set that repeats:

- **The streak is layer-agnostic.** `mark_job_run(job_id, False, ...)` increments `failure_streak` regardless of which layer failed, and the escape handler calls it (right after the delivery, same ordering as the normal path, so the helper's `stored + 1` arithmetic is already correct there).
- **So the counter climbs and is spendable nowhere.** `hermes cron list` shows `(N failures in a row)`; the chat alert never says it. Chat is where an unattended operator actually is.
- **Escaped failures are deterministic by nature**: a bad import from a half-applied update, a provider client that cannot construct, a missing script interpreter. They fail identically on every tick. A job on `every 10m` sends 30 identical one-liners over five hours and is never told the automation is worth pausing, which is exactly what #88655 reports.

The fix is to compose the alert at the escape handler the same way the normal path composes it. Same helper, same config gate, same threshold gate: a first-time escaped failure is byte-for-byte what it was before.

**Why here and not inside the summarizer.** Folding the nudge into `_summarize_cron_failure_for_delivery` would make it unforgettable, which is tempting given this is the second delivery site to be written without it. I did not, for two reasons, and I will take a maintainer's call to the contrary: the summarizer is a pure formatting helper (folding it in makes it read config), and every existing caller composes the two explicitly, so folding in would double-append for anyone who keeps that composition, including the open #88493, which composes it at two call sites. Worth noting that PR rewrites both delivery sites and preserves this asymmetry; I have left a note there so it survives whichever of us rebases onto the other.

**What this does not cover.** `deliver: local` jobs still receive no alert at all, nudge or otherwise, because `_deliver_result` has nowhere to send it. That is a separate gap, already tracked as #86998 and addressed by #87024.

## Related Issue

Fixes #88655

## Type of Change

- [x] 🐛 Bug fix (non-breaking change that fixes an issue)
- [ ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 🔒 Security fix
- [ ] 📝 Documentation update
- [ ] ✅ Tests (adding or improving test coverage)
- [ ] ♻️ Refactor (no behavior change)
- [ ] 🎯 New skill (bundled or hub)

## Changes Made

- **`cron/scheduler.py`** (~line 6611): the `except BaseException` handler's `_deliver_result` call now sends `_summarize_cron_failure_for_delivery(job, _err_text) + _failure_streak_nudge(job)`, matching the normal failure delivery. A comment records why the two sites must stay in step.
- **`tests/cron/test_run_one_job.py`**: two cases on the escaped-failure delivery path, plus a small `_patch_escaped_failure` helper in the style of the existing escaped-failure tests from `4668750fa`.
- **`website/docs/user-guide/features/cron.md`**: the nudge section said the streak counts "consecutive runs where the agent failed". `mark_job_run` has never distinguished layers, and that sentence is what the reporter read before concluding their failures were out of scope by design. Corrected to match the code.

## How to Test

1. `pytest tests/cron/test_run_one_job.py -q` gives **10 passed**.
2. Revert the `cron/scheduler.py` hunk and re-run `-k escaped_failure`:

   ```
   >       assert "failed 3 runs in a row" in delivered[0]
   E       assert 'failed 3 runs in a row' in "⚠️ Cron 'scout' failed: cannot import name X"
   FAILED tests/cron/test_run_one_job.py::test_escaped_failure_delivery_carries_the_streak_nudge
   1 failed, 1 passed
   ```

   The threshold case fails with the exact pre-fix message; the below-threshold case passes either way, so it is a real guard against an unconditional nudge rather than a copy of the change.
3. End to end, without waiting for a real streak: create a recurring job whose prompt cannot run (e.g. a script job pointing at a missing interpreter), set `cron.failure_nudge_threshold: 1`, and let it fire. The delivered alert carries the review nudge; before this change it never did, at any threshold or streak length.

### Code

- [x] I've read the [Contributing Guide](https://github.com/NousResearch/hermes-agent/blob/main/CONTRIBUTING.md)
- [x] My commit messages follow [Conventional Commits](https://www.conventionalcommits.org/) (`fix(scope):`, `feat(scope):`, etc.)
- [x] I searched for [existing PRs](https://github.com/NousResearch/hermes-agent/pulls) to make sure this isn't a duplicate
- [x] My PR contains **only** changes related to this fix/feature (no unrelated commits)
- [x] I've run the affected suites and all tests pass, see the note below
- [x] I've added tests for my changes (required for bug fixes, strongly encouraged for features)
- [x] I've tested on my platform: Windows 11, Python 3.12

> On the full-suite box: `pytest tests/cron -q` gives **766 passed, 10 failed** here, and I checked every one of those 10 against the same commit with this diff stashed. Eight are POSIX-only and fail identically unpatched (`test_file_permissions.py` asserting `0700`/`0600` modes, `test_cron_workdir.py::test_tilde_expands`, `test_media_delivery_parity.py`). The other two (`test_cleanup_timeout.py::test_run_job_bounds_sessiondb_finalization`, `test_script_claim_heartbeat.py::test_repeated_heartbeat_errors_cancel_after_bounded_grace`) are wall-clock-bounded and pass in isolation with this diff applied, so they are load-sensitive under the full run rather than caused by this change. Linux CI is the authority on all ten.

### Documentation & Housekeeping

- [x] I've updated relevant documentation (README, `docs/`, docstrings): the cron nudge section, see above
- [x] N/A, no config keys added or changed (`cron.failure_nudge_threshold` already exists and is unchanged)
- [x] N/A, no architecture or workflow change
- [x] N/A, pure Python string composition, no platform-specific behaviour
- [x] N/A, no tool descriptions or schemas touched

## Screenshots / Logs

The reporter's incident, as it reads before and after. A job on `every 10m` whose every run dies at the scheduler layer:

**Before**, the same line, every ten minutes, for five hours:

```
⚠️ Cron 'morning-scout' failed: cannot import name '_MAX_TOOL_ERROR_CHARS' from 'tools.registry'
```

**After**, identical for the first two, then from the third onward:

```
⚠️ Cron 'morning-scout' failed: cannot import name '_MAX_TOOL_ERROR_CHARS' from 'tools.registry'
This job has failed 3 runs in a row - worth a review. Fix its prompt/config, or pause it with `hermes cron pause morning-scout` (resume/remove also available) to stop the noise.
```

### CODE REVIEW

**Comment by jackulau** [comment]
Note on the one red run in this PR's history, so it is not left for a reviewer to dig into.

The first push recorded the `CI` workflow as a **startup failure**: it appears under its file path (`.github/workflows/ci.yaml`) rather than its `name:`, with conclusion `failure` and **zero jobs**, so it contributed nothing to the check rollup. Nothing in it ran. I cannot re-run jobs on a fork PR, so I amended with no content change to get a fresh head sha, which re-registered the workflow normally.

Same two files, same diff, same commit message. Current state: **47 checks, 35 success, 0 failing**, including `OS-specific tests / Windows-only tests` and `Python lints / Windows footguns`.
