### PR TITLE
fix(mcp): restore HTTP transport + OAuth compatibility with mcp >= 2.0.0

### PR DESCRIPTION
**Pull request by fourdollars**
The `mcp` Python SDK's 2.0.0 release (which added support for the 2026-07-28 protocol revision) introduced several breaking changes that our native MCP HTTP/OAuth client did not account for, causing every HTTP-transport MCP server to fail once `mcp` was upgraded past 1.x:

1. `_MCP_HTTP_AVAILABLE` never becomes True on mcp >= 2.0.0, because the deprecated `streamablehttp_client` name it probes for was removed entirely in favor of `streamable_http_client`. Servers reported "requires HTTP transport but mcp.client.streamable_http is not available" even though HTTP support was present under the new name. Fix: also set `_MCP_HTTP_AVAILABLE = True` when the new-name import succeeds.

2. `streamable_http_client(...)` now yields a 2-tuple `(read_stream, write_stream)` instead of the old 3-tuple with a `get_session_id` callable, since the session-id mechanism was removed in the 2026-07-28 revision. The hardcoded 3-tuple unpack raised `ValueError: not enough values to unpack`. Fix: branch on the tuple length.

3. Our client unconditionally injects a static `mcp-protocol-version` header on every HTTP request (useful for older/deprecated-transport servers that reject session-less initialize POSTs). The new transport already negotiates and manages this header itself post-handshake. A server compliant with the 2026-07-28 revision expects MCP-Protocol-Version to be accompanied by matching Mcp-Method/Mcp-Name metadata headers; injecting only the one static header makes an otherwise fully-negotiated client look like a broken partial implementation, and some servers reject that harder than a client that sends none of the three headers. Fix: only inject the static header on the deprecated transport path (`not _MCP_NEW_HTTP`).

4. `OAuthClientProvider.__init__()` in mcp >= 2.0.0 dropped its `timeout` constructor parameter entirely. Our `HermesMCPOAuthProvider` subclass forwarded an explicit `timeout=` kwarg through `**kwargs` to `super().__init__()`, raising `unexpected keyword argument 'timeout'`. Fix: capture `timeout` as an explicit named parameter on the subclass and stop forwarding it upward.

5. mcp >= 2.0.0 vendors its own httpx fork (`httpx2`), and its `OAuthClientProvider` now subclasses `httpx2.Auth` instead of `httpx.Auth`. We build a plain `httpx.AsyncClient` and pass the OAuth provider as `auth=`; httpx rejects it with `Invalid "auth" argument` because the two Auth base classes are unrelated. Fix: prefer `import httpx2 as httpx` in the new-transport branch (falling back to `httpx` when `httpx2` isn't installed), since httpx2's public API used here mirrors httpx's closely enough that the rest of the branch is unaffected.

6. `CallToolResult.isError` was renamed to `is_error` (snake_case) in mcp >= 2.0.0. Reading `result.isError` on the new model raised `AttributeError`, silently breaking error-result handling for tool calls. Fix: read `is_error` first, falling back to `isError` for older SDKs.

7. `OAuthClientProvider` in mcp >= 2.0.0 no longer accepts `timeout` in its constructor. Hermes passed `timeout=` through to `super().__init__()`, which raised `unexpected keyword argument 'timeout'`. Fix: keep `timeout` on the Hermes subclass so the SDK never sees it, while still allowing Hermes to honor the configured timeout locally.

All fixes are additive and defensive: they probe the new API first and fall back to the old behavior, so they should remain compatible across the mcp 1.24.0+ range without pinning the package.

Verified against two real HTTP MCP servers after upgrading the local `mcp` package to 2.0.0: a Bearer-auth server and an OAuth 2.1 PKCE server both connect and discover tools cleanly via `hermes mcp test <name>`.

### CODE REVIEW

**Comment by teknium1** [comment]
Thanks for this — you independently identified and fixed six real breaks, and verified against two live HTTP servers. All six are covered on main as of #88180 (the salvage of #76736, which landed the same fixes as part of the full SDK 2.x migration):

1. `_MCP_HTTP_AVAILABLE` on the new-name import → `_MCP_HTTP_AVAILABLE = _MCP_NEW_HTTP or _MCP_LEGACY_HTTP`
2. 2-tuple transport arity → dedicated both-generations handling
3. static `mcp-protocol-version` header → now seeded from the handshake version the body actually speaks
4. `OAuthClientProvider` `timeout` kwarg → moved to the callback waiter's poll loop
5. httpx2 `Auth` base-class mismatch → `sdk_httpx()` resolver
6. `isError` → `is_error` → `mcp_field()` dual-name reader

Closing as superseded; your analysis is credited in #88180's description. Much appreciated.
