### PR TITLE
fix(holographic-memory): surface init failure instead of cryptic AttributeError

### PR DESCRIPTION
**Pull request by akaponym-byte**
Refs #32495.

## Summary

`HolographicMemoryProvider.__init__` defaults `self._store = None`. If
`MemoryStore.__init__` then raises during `initialize()` — the reporter's
case was a corrupt `memory_store.db` after a crash mid-WAL-checkpoint —
`MemoryManager.initialize_all()` catches the exception, logs a single
`WARNING`, and leaves the provider registered. The tool schemas stay in
the agent's tool surface, so the agent keeps calling `fact_store` /
`fact_feedback`.

Every call falls through to `None.<method>`. The catch-all
`except Exception` at the bottom of each handler wraps that as
`tool_error("'NoneType' object has no attribute 'list_facts'")` — no
actionable signal for the agent, no chat-level error for the user. The
reporter in #32495 spent 18 days / 300+ session initializations in this
state before noticing the symptom.

## Fix

Add an explicit `None` guard at the top of `_handle_fact_store` and
`_handle_fact_feedback` that returns a `tool_error` naming:

- the affected subsystem (\`Holographic memory\`),
- the typical cause (\`corrupt \$HERMES_HOME/memory_store.db\`),
- where to look (\`hermes errors log for the underlying exception\`),
- and the recovery step (\`remove or restore memory_store.db, then restart\`).

The guard sits **before** the existing try/except so genuine `MemoryStore`
runtime failures still take the existing `except Exception` path — there
is no behaviour change when \`_store\` is alive.

## Scope intentionally narrow

The issue lists four candidate fixes. This PR is just #1 (the minimal,
no-regression one). The others are deferred:

- **Auto-recover from corrupt DB** (#2 in the issue). Deletes user data
  if the heuristic misclassifies a legitimate file. Wants maintainer
  sign-off on the recovery policy before landing.
- **Unregister tools when init fails** (#4 in the issue). Architectural
  change to \`MemoryManager\`; applies to every provider, not just
  holographic. Belongs in its own PR.
- **\`system_prompt_block()\` honesty** (#3 in the issue). The current
  code already returns an empty string when \`_store is None\` (\`line
  184: if not self._store: return \"\"\`), so the system prompt is silent
  rather than lying. No change needed.

## Test plan

- [x] New \`tests/plugins/memory/test_holographic_provider.py\` matches
  the pattern of the other in-tree memory providers
  (\`test_openviking_provider.py\`, \`test_mem0_v2.py\`, etc.). It
  constructs a provider without calling \`initialize()\` so \`_store\`
  stays at its constructor default of \`None\`, exercises every
  \`fact_store\` action shape (\`list\`/\`add\`/\`search\`/\`probe\`)
  and \`fact_feedback\`, and asserts the error text neither leaks
  \`NoneType\` nor swallows the failure silently. Without the guard the
  test fails with the exact payload reported in #32495:
  \`{\"error\": \"'NoneType' object has no attribute 'list_facts'\"}\`.
- [x] \`pytest tests/plugins/memory/ tests/agent/test_memory_provider.py\`
  — 240 passed (no regressions).
- [x] \`ruff check plugins/memory/holographic/__init__.py
  tests/plugins/memory/test_holographic_provider.py\` — clean.

### CODE REVIEW

**Comment by teknium1** [comment]
Thanks for the focused failure-path guard. The current-main premise is verified: `HolographicMemoryProvider` exposes both schemas at `plugins/memory/holographic/__init__.py:227`, while its handlers dereference nullable state at lines 270-355 and 357-366; `MemoryManager.initialize_all()` only logs initialization errors at `agent/memory_manager.py:1128-1135`.

### Problems
- The new recovery text hard-codes `$HERMES_HOME/memory_store.db`, but `db_path` is configurable at `plugins/memory/holographic/__init__.py:162` and documented in `plugins/memory/holographic/README.md:26`. For a custom database path, this can direct recovery toward the wrong file.

### Suggested changes
- Make the recovery text distinguish the default database from a configured `db_path`, or refer to the configured holographic database generically; add a custom-path test for that wording.

Automated hermes-sweeper review.

**Comment by akaponym-byte** [comment]
Addressed in 4bd794cca.

The hard-coded `$HERMES_HOME/memory_store.db` is gone. `initialize()` now records the resolved `db_path` (after `$HERMES_HOME` expansion) **before** constructing `MemoryStore`, so the recovery message names the actual file even when init fails on a custom path. When no path has been resolved yet (init never ran / failed before resolution) it falls back to a generic "configured holographic database (see the db_path setting)" reference rather than pointing at the wrong file.

Added two tests in `tests/plugins/memory/test_holographic_provider.py`:
- `test_unavailable_message_names_configured_db_path` — drives the real failure mode (a directory as `db_path` makes `MemoryStore.__init__` raise) and asserts the configured path appears in the recovery text.
- `test_unavailable_message_is_generic_before_initialize` — asserts the generic `db_path` fallback wording before `initialize()`.
