### ISSUE TITLE
[Bug]: fix(qqbot): QQBot adapter.connect() missing is_reconnect parameter causes infinite retry loop

### ISSUE THREAD

**Issue by fishlikeX** [NousResearch/hermes-agent#52914]
## Bug Description

After updating Hermes Agent to the latest version (commit `43b8ba4181` or later), the QQBot gateway enters an infinite retry loop and fails to connect.

## Error Log

```
ERROR gateway.run: ✗ qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
WARNING gateway.run: Reconnect qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect', next retry in 60s
```

## Environment

- Hermes Agent: latest (post-`43b8ba4181`)
- Python: 3.11.9
- qq-botpy: 1.2.1
- OS: Windows 10

## Reproduction Steps

1. Update Hermes Agent to latest version (post-`43b8ba4181`)
2. Configure QQBot platform in config
3. Start or restart gateway (`hermes gateway restart`)
4. Observe QQBot failing to connect with `is_reconnect` TypeError, entering exponential backoff retry loop

### Expected Behavior

qqbot  connected

### Actual Behavior

qqbot retry

### Affected Component

Gateway (Telegram/Discord/Slack/WhatsApp)

### Debug Report

```shell
⚠️  This will upload the following to a public paste service:
  • System info (OS, Python version, Hermes version, provider, which API keys
    are configured — NOT the actual keys)
  • Recent log lines (agent.log, errors.log, gateway.log, gui.log, desktop.log
    — may contain conversation fragments and file paths)
  • Full agent.log, gateway.log, gui.log, and desktop.log (up to 512 KB each —
    likely contains conversation content, tool outputs, and file paths)

Pastes auto-delete after 6 hours.

Collecting debug report...
Uploading...

Debug report uploaded:
  Report       https://paste.rs/MAGUc
  agent.log    https://paste.rs/CiYKD
  gateway.log  https://paste.rs/UP4Pb
  gui.log      https://paste.rs/YwZ61
  desktop.log  https://paste.rs/LN4T7

⏱  Pastes will auto-delete in 6 hours.
To delete now:  hermes debug delete <url>

Share these links with the Hermes team for support.
```

### Operating System

Win10

### Python Version

3.11.9

### Hermes Version

latest (post-`43b8ba4181`)

### Additional Logs / Traceback (optional)

```shell

```

## Root Cause

Commit `43b8ba4181` (`fix(telegram): preserve Bot API update queue on watcher reconnect`) added an `is_reconnect` keyword argument to:
- `gateway/platforms/base.py` → `BasePlatformAdapter.connect(self, *, is_reconnect: bool = False)`
- `gateway/run.py` → `_connect_adapter_with_timeout()` now passes `is_reconnect=True` on reconnect

However, **QQBot adapter's `connect()` method was not updated** to accept this parameter:

**Before (broken):**
```python
# gateway/platforms/qqbot/adapter.py line 281
async def connect(self) -> bool:
```

**After (fixed):**
```python
async def connect(self, *, is_reconnect: bool = False) -> bool:
```

## Workaround

Manually patch `gateway/platforms/qqbot/adapter.py` line 281:
```python
sed -i 's/async def connect(self) -> bool:/async def connect(self, *, is_reconnect: bool = False) -> bool:/' gateway/platforms/qqbot/adapter.py
```
Then restart gateway and clear Python cache:
```bash
rm -f gateway/platforms/qqbot/__pycache__/adapter.cpython-311.pyc
hermes gateway restart
```

### Are you willing to submit a PR for this?

- [ ] I'd like to fix this myself and submit a PR

**Comment by iborazzi** [comment]
I'd like to take this one!

The fix is straightforward — `QQAdapter.connect()` needs to accept the `is_reconnect: bool = False` keyword argument added in commit `43b8ba4181`. I'll also check if any other platform adapters are missing this parameter to avoid the same issue elsewhere.

Will submit a PR shortly.

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Confirmed real regression: `gateway/platforms/qqbot/adapter.py` `connect(self)` does not accept the `is_reconnect` kwarg required by `BasePlatformAdapter.connect(*, is_reconnect=False)`. The gateway's fatal-error reconnect watcher calls `connect(is_reconnect=True)`, so QQBot raises `TypeError` and never recovers. Same contract fix that MERGED #52911 applied to the relay adapter — the qqbot adapter needs to accept (and may ignore) the flag the same way. Distinct from the reconnect-exhaustion family (#39928, #29005).

**Comment by ttxs69** [comment]
## Adding the 3 PRs that opened after alt-glitch's triage

Confirming the bug and the workaround from `hermes-agent 0.17.0` (editable install) with `QQ_APP_ID`/`QQ_CLIENT_SECRET` set — `qqbot: connected` in `gateway_state.json` after applying the 1-line signature fix and `hermes gateway restart`.

Since the AI triage on this issue, **3 more PRs** have opened with the same 1-line fix that didn't exist when alt-glitch commented on Jun 26. Updated PR landscape for the canonical issue:

- **#52922 (iborazzi)** — your "I'd like to take this one" candidate; the diff has UTF-8 encoding corruption (BOM injected, em-dashes mojibake'd, Chinese text garbled in `[语音识别失败]`) that would block merge
- **#52966 (luxuguang-leo)** — clean diff + adds regression test `test_connect_accepts_is_reconnect_param`; author reports 116 existing QQBot tests still pass
- **#53540 (AlexFucuson9)** — clean 1-line change
- **#53546 (ulnit)** — clean 1-line change
- **#53948 (fantaskiss)** — clean 1-line change

All five implement the same `*, is_reconnect: bool = False` kwarg-only addition as the already-merged RelayAdapter fix (PR #52911 / commit `cb7d1f68f`). QQ has no server-side update queue to preserve, so the flag is accepted and ignored in the body — exactly the pattern alt-glitch described.

Suggestion: pick one (PR #52966 looks strongest because of the test, otherwise any of the other clean three), close the rest as duplicates, and merge. The bug is P2 and trivial — it's just rotting while new PRs keep arriving.

cc @alt-glitch

**Comment by dupl** [comment]
抓紧时间修复啊

**Comment by dupl** [comment]
Please fix it as soon as possible.

**Comment by rebecca554owen** [comment]
I've submitted a minimal fix in #55419. The change is just the `connect()` signature alignment in `gateway/platforms/qqbot/adapter.py` to accept `is_reconnect`, matching the base class introduced in 43b8ba4181.

**Comment by alaya233** [comment]
Please fix it as soon as possible.

**Comment by johny-liu** [comment]
Confirming reproduction on a clean install:

- Hermes v0.18.0 (2026.7.1), upstream commit 88d1d620 ("Up to date")
- Gateway log: `ERROR gateway.run: ✗ qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'` followed by `WARNING gateway.run: Reconnect qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect', next retry in 60s` — exactly the infinite backoff loop described.
- QQ app id: 1903443968, configured via `QQ_APP_ID`/`QQ_CLIENT_SECRET` in ~/.hermes/.env (not via plugin — so this is the builtin qqbot adapter, not a plugin-managed install).
- Local fix: 1-line change in `gateway/platforms/qqbot/adapter.py` — `async def connect(self) -> bool:` → `async def connect(self, *, is_reconnect: bool = False) -> bool:`. Body unchanged (kwarg accepted and ignored, since QQ has no server-side update queue to preserve). This is the same shape as the already-merged RelayAdapter fix in PR #52911 / commit cb7d1f68f.
- After the local fix: `✓ qqbot connected` followed by `Ready, session_id=...`, both wecom and qqbot running stably under a single gateway.

Agree with the earlier comments — any of the clean 1-line PRs (#52966, #53540, #53546, #53948, #54029, #54037, #54165, #55419) would close this. Picking one and merging would unblock everyone still hitting this.

**Comment by alaya233** [comment]
> 已确认在全新安装环境下可复现此问题：
> 
> * Hermes v0.18.0 (2026.7.1)，上游提交[88d1d62](https://github.com/NousResearch/hermes-agent/commit/88d1d6206f399c134d1f4c0b7db27733aaa3c50c)（“已是最新版本”）
> * 网关日志：`ERROR gateway.run: ✗ qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'`随后出现的`WARNING gateway.run: Reconnect qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect', next retry in 60s`正是所描述的无限退避循环。
> * QQ 应用 ID：1903443968，通过~/.hermes/.env 中的`QQ_APP_ID`/进行配置`QQ_CLIENT_SECRET`（不是通过插件——所以这是内置的 QQbot 适配器，而不是插件管理的安装）。
> * `gateway/platforms/qqbot/adapter.py`本地修复：在— `async def connect(self) -> bool:`→中更改一行`async def connect(self, *, is_reconnect: bool = False) -> bool:`。主体保持不变（接受并忽略了 kwarg，因为 QQ 没有服务器端更新队列需要保留）。这与 PR fix(relay) 中已合并的 RelayAdapter 修复相同[：在 RelayAdapter.connect 中接受 is_reconnect kwarg  #52911](https://github.com/NousResearch/hermes-agent/pull/52911) / commit [cb7d1f6](https://github.com/NousResearch/hermes-agent/commit/cb7d1f68f8768a6d7736f77cc399d806c677f105)。
> * 本地修复后`✓ qqbot connected`，`Ready, session_id=...`wecom 和 qqbot 都在单个网关下稳定运行。
> 
> 同意之前的评论——任何一个简洁的单行 PR（[#52966](https://github.com/NousResearch/hermes-agent/pull/52966)、[#53540](https://github.com/NousResearch/hermes-agent/pull/53540)、[#53546](https://github.com/NousResearch/hermes-agent/pull/53546)、[#53948](https://github.com/NousResearch/hermes-agent/pull/53948)、[#54029](https://github.com/NousResearch/hermes-agent/pull/54029)、[#54037](https://github.com/NousResearch/hermes-agent/pull/54037)、[#54165](https://github.com/NousResearch/hermes-agent/pull/54165)、[#55419](https://github.com/NousResearch/hermes-agent/pull/55419)）都能解决这个问题。选择其中一个并合并，就能解决所有仍然遇到此问题的用户。

根本没解决，没pr合并。只能先按照主楼的方案修复了

**Comment by Jensenwgd** [comment]
Confirming reproduction on latest `main` as of 2026-07-02 (commit `30e947e0`). Hermes Agent v0.18.0 (2026.7.1), QQ WebSocket gateway.

```
ERROR gateway.run: ✗ qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
WARNING gateway.run: Reconnect qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect', next retry in 60s
```

The reconnect watcher never succeeds; the QQBot platform effectively becomes a no-op. `is_reconnect` was added to `BasePlatformAdapter.connect` by `43b8ba4` (commit message *fix(telegram): preserve Bot API update queue on watcher reconnect*); every other platform adapter I checked (`webhook`, `weixin`, `yuanbao`, `bluebubbles`, `whatsapp`, `signal`, `telegram`, `discord`, `wecom`, `msgraph_webhook`) has the keyword-only parameter — **only `QQAdapter` is missing it**.

### One-line fix (drop-in for upstream review)

```diff
--- a/gateway/platforms/qqbot/adapter.py
+++ b/gateway/platforms/qqbot/adapter.py
@@ -278,7 +278,7 @@
     # Connection lifecycle
     # ------------------------------------------------------------------

-    async def connect(self) -> bool:
-        """Authenticate, obtain gateway URL, and open the WebSocket."""
+    async def connect(self, *, is_reconnect: bool = False) -> bool:
+        """Authenticate, obtain gateway URL, and open the WebSocket.
+
+        ``is_reconnect`` is part of the base abstract signature introduced
+        when the gateway reconnect watcher learned to distinguish a cold
+        boot from a watcher-triggered reconnect (commit 43b8ba4). The QQ
+        adapter has no server-side update queue, so the flag is
+        intentionally ignored here — we accept it solely to stay
+        signature-compatible with the abstract contract.
+        """
         if not AIOHTTP_AVAILABLE:
```

Local patch applied; gateway reconnects in ~1s, QQ WebSocket Ready, end-to-end message round-trip verified.

### Suggestion for maintainers

In addition to merging one of the existing #52922 / #53948 / #55419 / #54165 PRs, it may be worth adding a CI check or a `pre-commit` hook that greps every concrete `connect(` implementation against `BasePlatformAdapter.connect`'s signature to prevent the same regression in future adapter additions.

**Comment by muzilong** [comment]
崩不住，一个小Bug这样看来，至少要一个月才能修了

**Comment by wind0ws** [comment]
just repace "async def connect(self) -> bool:"  TO  "async def connect(self, *, is_reconnect: bool = False) -> bool:", why it take too long? 
This bug has been ongoing for a week.

**Comment by fishlikeX** [comment]
> 崩不住，一个小Bug这样看来，至少要一个月才能修了

可能是因为这个问题本身是个小问题，然后最近不是在推进0.18.0吗所以合并修复比较慢，没事可以理解

**Comment by ngleoi** [comment]
碰到了这个问题，gateway 每次启动都报 `QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'`，QQ Bot 完全连不上。

看了一下代码，`gateway/run.py` 里重连逻辑会传 `is_reconnect=True` 给 `adapter.connect()`，但 `QQAdapter.connect()` 的签名里没有这个参数。其他平台的适配器（Telegram、Discord、Yuanbao 等）都按基类 `BasePlatformAdapter` 的约定加了 `is_reconnect: bool = False`，QQBot 的漏掉了。

修复就一行，在 `gateway/platforms/qqbot/adapter.py:281`：

```python
# 改之前
async def connect(self) -> bool:

# 改之后
async def connect(self, *, is_reconnect: bool = False) -> bool:
```

跑了一遍 `tests/gateway/test_qqbot.py`，165 个测试全过，没有引入新问题。

**Comment by ngleoi** [comment]
## Fix Confirmed ✅

**Root cause:** `QQAdapter.connect()` was defined without the `is_reconnect` keyword argument that `BasePlatformAdapter.connect()` declares and `gateway/run.py` passes during reconnection attempts.

**Fix (1 line):**

```python
# gateway/platforms/qqbot/adapter.py, line 281
# Before:
async def connect(self) -> bool:

# After:
async def connect(self, *, is_reconnect: bool = False) -> bool:
```

**Verification:**
- `inspect.signature(QQAdapter.connect)` now matches `BasePlatformAdapter.connect`
- Gateway restarts cleanly with QQ platform connected:
  ```
  [QQBot:1905012626] WebSocket connected to wss://api.sgroup.qq.com/websocket
  [QQBot:1905012626] Connected
  ✓ qqbot connected
  Gateway running with 2 platform(s)
  ```
- QQ bot responds to messages normally after fix + gateway restart

**Note:** Fix was applied locally but gateway process must be fully restarted (kill + relaunch, not just WS reconnect) for the new code to take effect.

**Comment by dupl** [comment]
Such a long time without any result and explaination is unacceptable!

**Comment by teknium1** [comment]
Fixed in PR #61767. QQ Bot now accepts the gateway reconnect contract, and a repository-wide test prevents the same adapter signature regression.
