### ISSUE TITLE
Matrix voice delivery broken in v0.21.0: send_voice() got unexpected kwarg 'is_voice'

### ISSUE THREAD

**Issue by denkengeistit** [NousResearch/hermes-agent#102221]
### Bug

Voice message delivery to Matrix rooms fails with a TypeError after v0.21.0. Every `[[audio_as_voice]]`-tagged MEDIA attachment dies at the send step. This regressed in the v0.21.0 (2026.8.31) release — zero voice delivery errors in our logs before Sept 2, 13:16 UTC (two hours after updating to v0.21.0), then consistent 100% failure on every subsequent attempt (5+ observed within hours).

### Environment

- Hermes Agent v0.21.0 (2026.8.31), upstream 562ee8ab
- Platform: Matrix (mautrix-python), self-hosted Synapse, E2EE enabled
- TTS providers tested: piper (local) and openai-compatible (Speaches) — failure is TTS-provider-independent

### Root cause

`gateway/platforms/base.py` line ~6983 (non-streaming media dispatch loop) passes a new `is_voice` kwarg to `send_voice()`:

```python
media_result = await self.send_voice(
    chat_id=event.source.chat_id,
    audio_path=media_path,
    metadata=_final_thread_metadata,
    is_voice=is_voice,
)
```

`should_send_media_as_audio()` (line ~209) returns True for Matrix for all audio extensions, so the call always routes to `send_voice`. But the Matrix adapter's `send_voice` signature (`plugins/platforms/matrix/adapter.py` line 2581) was not updated to accept it:

```python
async def send_voice(
    self,
    chat_id: str,
    audio_path: str,
    caption: Optional[str] = None,
    reply_to: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> SendResult:   # <-- no **kwargs, no is_voice param
```

The base-class `send_voice` (line 4777) accepts `**kwargs`, but the Matrix adapter overrides it with an exact signature and no `**kwargs`, so the kwarg propagation fails.

### Error

```
WARNING gateway.platforms.base: [Matrix] Error sending media: MatrixAdapter.send_voice() got an unexpected keyword argument 'is_voice'
```

The audio file is generated correctly (valid Ogg/Opus confirmed with `file`), written to the TTS cache, and then dropped at delivery. The user sees the text of the response but never the voice message. No fallback path exists for this failure — `should_send_media_as_audio` returned True, so document fallback is never attempted.

### Suggested fix

Add `is_voice: bool = False` (or `**kwargs`) to `MatrixAdapter.send_voice`'s signature. The adapter currently implements MSC3245 voice bubbles for Ogg/Opus input; `is_voice` could also be used to gate transcode-to-Ogg-Opus for non-Opus input (matching the Telegram adapter behavior noted in `should_send_media_as_audio`).

Alternatively, stop passing `is_voice` from the base dispatch loop and let `should_send_media_as_audio` be the single decision point, since for non-Telegram platforms it already returns True for all audio extensions.

### Notes

- Confirmed deliveries still work when the file goes through the auto-extracted local-file path (`extract_local_files` → `send_document`), which is why some audio sends appear to succeed — those are document attachments, not voice bubbles.
- Happy to test a patch.

**Comment by soroush5** [comment]
Confirmed by signature audit: the shared dispatch passes `is_voice=is_voice`, the base accepts `**kwargs`, but `MatrixAdapter.send_voice` (and same-shaped `MattermostAdapter.send_voice`) take neither — every Matrix voice send raises TypeError and is swallowed as 'Error sending media'. Working on the fix (accept the kwarg on both) plus a signature-compat test.

**Comment by impiyush** [comment]
Independently confirmed — just reproduced this via code inspection on current `main` (matrix `adapter.py` still defines `send_voice(self, chat_id, audio_path, caption=None, reply_to=None, metadata=None)`, no `is_voice`, no `**kwargs`). Adding three data points that may help triage:

**1. Adapter audit (full sweep, 14 platform adapters)**

Every actively-maintained adapter accepts `**kwargs` on `send_voice` (telegram, whatsapp, slack, discord, teams, simplex, google-chat, feishu, photon, buzz, wecom, desktop). Only three don't: **Matrix, Mattermost, and Line**. Line is missing from the issue's scope — it will have the identical failure. A signature-compat regression test across all adapters would have caught this class of bug at the dispatcher (`is_voice`) → adapter boundary.

**2. The failure is fully silent for the user**

The `TypeError` fires inside the media dispatch loop *before* the failure-notice path, so the user sees nothing at all — the text part of the same response delivers fine, only the audio vanishes. No error bubble, no log line visible from the chat surface. This makes it look like "TTS randomly doesn't arrive" rather than a signature mismatch, which is probably why it took multiple users a while to pin down.

**3. One-line fix verified locally**

Adding `**kwargs` to the Matrix adapter signature (matching the convention of the other 12 adapters) restored voice-bubble delivery end-to-end in a live deployment: STT voice in → Edge TTS out → `[[audio_as_voice]]` MEDIA attachment arrives as a proper voice message in Element.

Noting multiple PRs already open for the fixes so not creating another.

**Comment by seth586** [comment]
Fix for this (plus the same bug in Mattermost, LINE, and Weixin) is up in #113952.
