### ISSUE TITLE
DaemonThreadPoolExecutor crashes on Python 3.14: object has no attribute '_initializer' (concurrent tool batches fail)

### ISSUE THREAD

**Issue by v9yrbcgkyt-spec** [NousResearch/hermes-agent#76621]
## Summary

`tools/daemon_pool.py`'s `DaemonThreadPoolExecutor` crashes on Python 3.14 with

```
AttributeError: 'DaemonThreadPoolExecutor' object has no attribute '_initializer'
```

breaking **every concurrent tool batch** (parallel tool calls, skills-hub fan-out, async delegation all go through this pool). Hermes Agent v0.19.0 (2026.7.20, Homebrew install) on Python 3.14.6.

## Error seen in the agent loop

```
Error during OpenAI-compatible API call #22: 'DaemonThreadPoolExecutor' object has no attribute '_initializer'
```

It looks intermittent because serial execution never spawns a second worker; the crash happens only when the pool needs to grow workers (i.e. on the first parallel batch), then the whole batch fails.

## Root cause

CPython 3.14 refactored `concurrent.futures.ThreadPoolExecutor`:

- The `_initializer` / `_initargs` instance attributes were removed and replaced by a `_create_worker_context()` method.
- `concurrent.futures.thread._worker` signature changed from `(executor_reference, work_queue, initializer, initargs)` to `(executor_reference, ctx, work_queue)`.

`tools/daemon_pool.py` overrides `_adjust_thread_count` and mirrors the 3.8–3.13 CPython implementation (its own comment says "Mirrors CPython's implementation (3.8–3.13)"), reading `self._initializer` / `self._initargs` — both gone in 3.14 — so the first worker spawn raises.

## Repro

```python
"""Minimal repro — run on Python 3.14 (fails) vs Python 3.9 (works)."""
import sys
import threading
import weakref
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures.thread import _worker


class DaemonThreadPoolExecutor(ThreadPoolExecutor):
    """Minimal copy of Hermes tools/daemon_pool.py _adjust_thread_count
    (the 3.8-3.13 mirror)."""

    def _adjust_thread_count(self):
        if self._idle_semaphore.acquire(timeout=0):
            return

        def weakref_cb(_, q=self._work_queue):
            q.put(None)

        num_threads = len(self._threads)
        if num_threads < self._max_workers:
            thread_name = "%s_%d" % (self._thread_name_prefix or self, num_threads)
            t = threading.Thread(
                name=thread_name,
                target=_worker,
                args=(
                    weakref.ref(self, weakref_cb),
                    self._work_queue,
                    self._initializer,  # <-- removed in CPython 3.14
                    self._initargs,     # <-- removed in CPython 3.14
                ),
                daemon=True,
            )
            t.start()
            self._threads.add(t)


if __name__ == "__main__":
    print("Python:", sys.version.split()[0])
    pool = DaemonThreadPoolExecutor(max_workers=2)
    try:
        print("OK, results:", list(pool.map(lambda x: x * 2, range(4))))
    except AttributeError as e:
        print("AttributeError:", e)
        sys.exit(1)
    finally:
        pool.shutdown(wait=True)
```

Confirmed behavior:

- Python 3.14.6 → `AttributeError: 'DaemonThreadPoolExecutor' object has no attribute '_initializer'`, exit 1
- Python 3.9.6 → `OK, results: [0, 2, 4, 6]`, exit 0

## Suggested fix

Branch on the presence of `_create_worker_context` so the same code works on 3.14 and ≤3.13:

```python
def _adjust_thread_count(self) -> None:
    if self._idle_semaphore.acquire(timeout=0):
        return

    def weakref_cb(_, q=self._work_queue):
        q.put(None)

    num_threads = len(self._threads)
    if num_threads < self._max_workers:
        thread_name = "%s_%d" % (self._thread_name_prefix or self, num_threads)
        ctx_getter = getattr(self, "_create_worker_context", None)
        if ctx_getter is not None:
            # Python 3.14+: worker context provided by _create_worker_context()
            t = threading.Thread(
                name=thread_name,
                target=_worker,
                args=(weakref.ref(self, weakref_cb), ctx_getter(), self._work_queue),
                daemon=True,
            )
        else:
            # Python 3.8–3.13: initializer/initargs passed directly
            t = threading.Thread(
                name=thread_name,
                target=_worker,
                args=(
                    weakref.ref(self, weakref_cb),
                    self._work_queue,
                    self._initializer,
                    self._initargs,
                ),
                daemon=True,
            )
        t.start()
        self._threads.add(t)
```

The two Hermes-specific behaviors (daemon workers, no `_threads_queues` registration) are preserved in both branches.

## Environment

- Hermes Agent v0.19.0 (2026.7.20), Homebrew bottle, Python 3.14.6, OpenAI SDK 2.24.0
- Upstream `main` at time of filing still contains the 3.8–3.13-only implementation.

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #58596: the same Python 3.14 DaemonThreadPoolExecutor `_initializer`/worker-contract crash in `tools/daemon_pool.py`.

**Comment by kvnloo** [comment]
Ready to close — already labeled `duplicate`. Listed in the close table: https://github.com/NousResearch/hermes-agent/issues/109552

This account cannot close tickets here. The author or a maintainer can close this copy; keep the canonical named in triage.

**Comment by kvnloo** [comment]
Duplicate of #58596.

The reported Python 3.14 `DaemonThreadPoolExecutor` `_initializer` / `_worker` contract failure is fixed on `main` by #112209, specifically commit `c9fa191334183e19ba763116d4f66ec3a3ed323f`. That commit changes `tools/daemon_pool.py::DaemonThreadPoolExecutor._adjust_thread_count` to use `_create_worker_context()` when the running stdlib exposes the Python 3.14 worker contract, while preserving the legacy path on older Python.

Closing against the canonical tracker.
