### PR TITLE
fix(qqbot): add is_reconnect kwarg to QQAdapter.connect()

### LINKED ISSUE #52914: [Bug]: fix(qqbot): QQBot adapter.connect() missing is_reconnect parameter causes infinite retry loop
## Bug Description

After updating Hermes Agent to the latest version (commit `43b8ba4181` or later), the QQBot gateway enters an infinite retry loop and fails to connect.

## Error Log

```
ERROR gateway.run: ✗ qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
WARNING gateway.run: Reconnect qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect', next retry in 60s
```

## Environment

- Hermes Agent: latest (post-`43b8ba4181`)
- Python: 3.11.9
- qq-botpy: 1.2.1
- OS: Windows 10

## Reproduction Steps

1. Update Hermes Agent to latest version (post-`43b8ba4181`)
2. Configure QQBot platform in config
3. Start or restart gateway (`hermes gateway restart`)
4. Observe QQBot failing to connect with `is_reconnect` TypeError, entering exponential backoff retry loop

### Expected Behavior

qqbot  connected

### Actual Behavior

qqbot retry

### Affected Component

Gateway (Telegram/Discord/Slack/WhatsApp)

### Messaging Platform (if gateway-related)

_No response_

### Debug Report

```shell
⚠️  This will upload the following to a public paste service:
  • System info (OS, Python version, Hermes version, provider, which API keys
    are configured — NOT the actual keys)
  • Recent log lines (agent.log, errors.log, gateway.log, gui.log, desktop.log
    — may contain conversation fragments and file paths)
  • Full agent.log, gateway.log, gui.log, and desktop.log (up to 512 KB each —
    likely contains conversation content, tool outputs, and file paths)

Pastes auto-delete after 6 hours.

Collecting debug report...
Uploading...

Debug report uploaded:
  Report       https://paste.rs/MAGUc
  agent.log    https://paste.rs/CiYKD
  gateway.log  https://paste.rs/UP4Pb
  gui.log      https://paste.rs/YwZ61
  desktop.log  https://paste.rs/LN4T7

⏱  Pastes will auto-delete in 6 hours.
To delete now:  hermes debug delete <url>

Share these links with the Hermes team for support.
```

### Operating System

Win10

### Python Version

3.11.9

### Hermes Version

latest (post-`43b8ba4181`)

### Additional Logs / Traceback (optional)

```shell

```

## Root Cause

Commit `43b8ba4181` (`fix(telegram): preserve Bot API update queue on watcher reconnect`) added an `is_reconnect` keyword argument to:
- `gateway/platforms/base.py` → `BasePlatformAdapter.connect(self, *, is_reconnect: bool = False)`
- `gateway/run.py` → `_connect_adapter_with_timeout()` now passes `is_reconnect=True` on reconnect

However, **QQBot adapter's `connect()` method was not updated** to accept this parameter:

**Before (broken):**
```python
# gateway/platforms/qqbot/adapter.py line 281
async def connect(self) -> bool:
```

**After (fixed):**
```python
async def connect(self, *, is_reconnect: bool = False) -> bool:
```

## Workaround

Manually patch `gateway/platforms/qqbot/adapter.py` line 281:
```python
sed -i 's/async def connect(self) -> bool:/async def connect(self, *, is_reconnect: bool = False) -> bool:/' gateway/platforms/qqbot/adapter.py
```
Then restart gateway and clear Python cache:
```bash
rm -f gateway/platforms/qqbot/__pycache__/adapter.cpython-311.pyc
hermes gateway restart
```

### Are you willing to submit a PR for this?

- [ ] I'd like to fix this myself and submit a PR

### LINKED ISSUE #53443: fix(qqbot): QQAdapter.connect() missing is_reconnect kwarg causes TypeError on every gateway startup
## Bug Description

`QQAdapter.connect()` lacks the `is_reconnect` keyword argument that `BasePlatformAdapter.connect()` and the gateway runner expect. On every gateway startup (and on every reconnect watcher cycle), `gateway/run.py` calls `adapter.connect(is_reconnect=False)` / `adapter.connect(is_reconnect=True)`, which raises:

```
TypeError: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
```

This makes the qqbot platform completely unable to connect — it errors immediately on boot and the reconnect watcher never succeeds either.

## Root Cause

`BasePlatformAdapter.connect()` was updated to include `*, is_reconnect: bool = False` (so adapters with a server-side update queue can preserve it across outages, see #46621). The gateway reconnect watcher (`gateway/run.py` line 3132/3135) calls `adapter.connect(is_reconnect=...)`.

`QQAdapter` inherits `BasePlatformAdapter` but its `connect()` override kept the old bare signature:

```python
# gateway/platforms/qqbot/adapter.py:281 (current)
async def connect(self) -> bool:
```

## Related Fix

The exact same bug was fixed for `RelayAdapter` in commit `cb7d1f68f` / PR #52911 (merged 2026-06-26). That fix added `*, is_reconnect: bool = False` to `RelayAdapter.connect()`. QQAdapter was apparently missed.

## Expected Fix

One-line change — same pattern as the RelayAdapter fix:

```diff
-    async def connect(self) -> bool:
+    async def connect(self, *, is_reconnect: bool = False) -> bool:
```

QQAdapter has no server-side update queue to preserve, so it deliberately ignores the flag (same rationale as RelayAdapter in PR #52911).

## Environment

- hermes-agent 0.17.0 (editable install)
- Python 3.11
- Reproducible on every gateway startup when qqbot platform is enabled

## Steps to Reproduce

1. Enable qqbot platform in config (`QQ_APP_ID` + `QQ_CLIENT_SECRET` set)
2. Start gateway: `hermes gateway run`
3. Observe: `ERROR gateway.run: ✗ qqbot error: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'`
4. Reconnect watcher keeps retrying with same error indefinitely

### LINKED ISSUE #54679: [Bug]: fix(gateway): QQAdapter.connect() does not accept is_reconnect parameter on reconnect
### Bug Description

After updating to v0.17.0, QQ Bot fails to reconnect after disconnection.
QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
In gateway/run.py, _connect_adapter_with_timeout() passes is_reconnect=True to adapter.connect(is_reconnect=is_reconnect), but the QQ Bot adapter's connect() method signature is async def connect(self): — it does not accept this parameter.

### Steps to Reproduce

Two options:
QQ Bot adapter: add **kwargs to the connect() signature
gateway/run.py: wrap the connect() call in try/except TypeError and fall back to connect() without arguments
Workaround
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):

### Expected Behavior

Two options:
QQ Bot adapter: add **kwargs to the connect() signature
gateway/run.py: wrap the connect() call in try/except TypeError and fall back to connect() without arguments
Workaround
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):

### Actual Behavior

Two options:
QQ Bot adapter: add **kwargs to the connect() signature
gateway/run.py: wrap the connect() call in try/except TypeError and fall back to connect() without arguments
Workaround
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):

### Affected Component

Gateway (Telegram/Discord/Slack/WhatsApp)

### Messaging Platform (if gateway-related)

_No response_

### Debug Report

```shell
Edit adapter.py, change async def connect(self): to async def connect(self, **kwargs):
```

### Operating System

Windows 11

### Python Version

3.11.9

### Hermes Version

0.17.0

### Additional Logs / Traceback (optional)

```shell

```

### Root Cause Analysis (optional)

_No response_

### Proposed Fix (optional)

_No response_

### Are you willing to submit a PR for this?

- [ ] I'd like to fix this myself and submit a PR

### PR DESCRIPTION
**Pull request by Autsunset**
## Summary

Fixes the QQBot adapter to accept the `is_reconnect` keyword argument that `BasePlatformAdapter.connect()` and the gateway runner expect.

## Problem

On every gateway startup and reconnection attempt, the runner calls `adapter.connect(is_reconnect=False/True)`, which raised:

```
TypeError: QQAdapter.connect() got an unexpected keyword argument 'is_reconnect'
```

This made the qqbot platform completely unable to connect.

## Solution

Added `*, is_reconnect: bool = False` to the method signature to align with the base class.

## Related Issues

- Fixes #53443
- Fixes #52914  
- Fixes #57266
- Fixes #54679
- Related PRs: #55419, #54165, #53546

## Checklist

- [x] I've read the Contributing Guide
- [x] My commit messages follow Conventional Commits
- [x] I searched for existing PRs to make sure this isn't a duplicate
- [x] My changes are minimal and focused on the fix

### CODE REVIEW

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

Duplicate of #52966 — the earliest still-open canonical fix adding the keyword-only `is_reconnect` kwarg to `QQAdapter.connect()` for #52914. This is an identical one-line signature fix in a saturated dup cluster (the previously-cited anchor #52922 is closed/unmerged, so #52966 is canonical).

**Comment by teknium1** [comment]
Thanks for the focused QQBot reconnect fix.

This automated hermes-sweeper review found that the exact behavior is already on current `main` through merged PR #61767:

- `gateway/platforms/qqbot/adapter.py:281` defines `QQAdapter.connect(self, *, is_reconnect: bool = False)` in commit `276542c729c10ff9d093760897f4c2d1256a79ce`.
- `gateway/run.py:3500` and `gateway/run.py:3503` forward `is_reconnect` to adapters; the QQ implementation now satisfies that contract.
- Main includes QQ-specific coverage at `tests/gateway/test_qqbot.py:193` and repository-wide reconnect-signature coverage added in `8416545c423a1f0f88f1236fd999c03922318547`.

Closing as implemented on main.
