### PR TITLE
fix(delegate): add missing task_count to _build_child_agent() call sites

### PR DESCRIPTION
**Pull request by MestreY0d4-Uninter**
## Summary
Fixes a critical regression introduced in PR #11155 where the `_build_child_agent()` function signature was updated to require `task_count` as a mandatory parameter, but the call sites were not updated accordingly.

## Bug Report
- **Reported by:** @trevorgordon981
- **Issue:** `TypeError: _build_child_agent() missing 1 required positional argument: 'task_count'`
- **Impact:** All delegation calls would fail at runtime

## Changes
- `tools/delegate_tool.py:892` — Added `task_count=n_tasks` to the `_build_child_agent()` call site
- `tests/tools/test_delegate_tier_core.py:105` — Added `task_count=1` to the test call

## Validation
All tests passing (82/82):
- ✅ `test_delegate_tier_core.py` (NEW): 10/10 PASS
- ✅ `test_delegate.py` (EXISTING): 67/67 PASS  
- ✅ `test_delegate_toolset_scope.py`: 5/5 PASS

## Follows
- hermes-contrib workflow: clean branch, minimal fix, validated before push
- hermes-pr-lifecycle: validation complete, ready for review

Fixes regression from PR #11155.

### CODE REVIEW

**Comment by MestreY0d4-Uninter** [comment]
Closing as this has been absorbed into main. The `task_count=n_tasks` parameter is already present at `tools/delegate_tool.py:774` in commit fc8e4ebf. Validation: grep -n 'task_count=n_tasks' tools/delegate_tool.py returns the line with the fix already applied.
