### ISSUE TITLE
Desktop dashboard cron scheduler races the gateway; when it wins a tick it has no live adapter and delivery hangs until script_timeout (600s)

### ISSUE THREAD

**Issue by lslj090707-ops** [NousResearch/hermes-agent#52202]
## Summary

When a launchd `hermes gateway run` service and the desktop app run on the **same HERMES_HOME**, two in-process cron schedulers race. The desktop dashboard backend (`HERMES_DESKTOP=1`) starts its own scheduler in `web_server.py:_start_desktop_cron_ticker`, alongside the gateway's scheduler. They coordinate via `cron/.tick.lock` ("whichever grabs the lock first wins the tick"), which prevents double-fire — but when the **desktop process wins** a tick for a job that delivers to a live platform (e.g. Telegram), it runs with **no live adapter** (the docstring itself notes *"no live adapters; delivery falls back to the per-platform send path"*).

That cold fallback send **hangs** until `cron.script_timeout_seconds` (default 600s), the job is killed, and the user gets the generic `provider timeout. Fallback chain was exhausted or unavailable.` It is **intermittent** — a coin flip on which process wins the lock per tick — so the same job succeeds on days the gateway wins and fails on days the desktop app is open at fire time and wins.

## Evidence

- Cron output reports `Script timed out after 600s` even for a **trivial `no_agent` script** (a plain `cat` of a prebuilt file) that runs in 0.00s standalone. Network and the script are both fine.
- Job scheduled at HH:30 but the failure/timeout lands at HH:40 — exactly 600s late.
- `gui.log` shows the desktop side changed from a passive `Desktop cron ticker` to a full `Desktop cron scheduler (provider=builtin)` in a recent update, which is when the intermittent failures began.
- Gateway log shows the job only `delivered to telegram` as the *failure notice*, not the report.

## Repro

1. Install/run `hermes gateway run` as a launchd service (has live Telegram adapter).
2. Also open the desktop app (spawns `hermes dashboard` with `HERMES_DESKTOP=1`, which now starts its own scheduler) on the same HERMES_HOME.
3. Create a `no_agent` cron job that delivers to Telegram.
4. Over several days with the app open at fire time, some runs hang ~600s and fail.

## Suggested fix

The desktop ticker should **not start its own scheduler when a live gateway already owns cron** on the same HERMES_HOME (e.g. detect a live `gateway.pid` / gateway lock and skip), or it should **hand live-platform delivery off to the gateway** instead of cold-sending without an adapter.

## Version

`hermes-agent` main @ `404b06ac4`, macOS desktop app.

**Comment by GottZ** [comment]
> *This was generated by AI during triage.*

#### Summary

Nine PRs are associated with this issue complex: six address the Desktop-versus-Gateway cron race, while #67135, #67198, and #67204 add scheduler-provider tests without changing ownership or delivery behavior. The fix diffs range from obsolete direct-ticker guards and lifecycle suppression to provider-aware runtime-lock deferral; verification selects #44050 as the best existing fix.

#### Related pull requests

- #44049 `partial` — (+211/-13) — partial_fix: Adds scheduler-level runtime-lock deferral, threads it through the provider contract, and opts the Desktop ticker in, addressing the adapterless-delivery cause but substantially duplicating #44050 while also changing the Chronos interface.
- #44050 `best fix` — (+219/-14) — partial_fix, best existing fix: Carries narrow owner deferral through the active built-in provider path while preserving the Gateway default and external-provider contracts. Its updated diff addresses the keep_open review by adding provider-boundary, owner/no-owner, Gateway-default, and external-provider coverage.
- #46207 `partial` — (+83/-2) — partial_fix: Checks Gateway liveness before each Desktop tick and fails open, but patches the removed direct cron_tick() loop rather than the active provider path. Despite the keep_open review, the requested provider-aware port is already implemented in #44050.
- #47358 `partial` — (+73/-3) — partial_fix: Uses get_running_pid() to stand down the old Desktop ticker and targets macOS TCC provenance, but its production hunk and tests bypass the current resolve_cron_scheduler().start() path introduced by abbd8646eb511833500377799f5853d8d4eda5a2. Despite the automated keep_open verdict, #44050 covers the active path.
- #52259 `partial` — (+456/-16) — partial_fix: Suppresses Desktop scheduling at startup, stops an active built-in ticker when a Gateway later appears, and separately bounds standalone sends to 30 seconds. Its keep_open verdict supports salvage, but the ownership portion duplicates #44050 and the stopped ticker does not automatically resume after a later Gateway exit.
- #67135 `unrelated` — (+26/-0) — unrelated: Adds only pre-set stop_event lifecycle coverage and changes no scheduler-ownership, live-adapter, or delivery behavior; its automated keep_open verdict supports retaining it independently for #67102.
- #67198 `unrelated` — (+155/-0) — unrelated: Adds interval fidelity, adapter/loop forwarding, recovery ordering, and compatibility-shim tests without introducing a Desktop-versus-Gateway ownership guard; its automated keep_open verdict supports separate scheduler-test triage.
- #67204 `unrelated` — (+46/-0) — unrelated: Adds a real-time inter-tick pacing test and no production arbitration or delivery change. Its keep_open review supports the test but requests correction of the comment claiming a jitter margin that the assertion does not implement.
- #67418 `partial` — (+849/-16) — partial_fix: The current diff adds a provider-aware per-tick gate backed by a read-only Gateway lock-record classifier, automatic Desktop resumption, and extensive PID/profile/status hardening. Despite the keep_open review and redesign, the discussion still documents a residual handoff window; its ownership result overlaps #44050, while independently useful status hardening is salvageable.

#### Duplicates

#44049 and #44050 implement substantially the same runtime-lock-backed scheduler deferral; #46207 and #47358 are obsolete direct-ticker variants, while the ownership portions of #52259 and #67418 address the same race through broader lifecycle, timeout, or status-probe changes. #67135, #67198, and #67204 are independent test PRs, not ownership-fix duplicates.

#### Suggested consolidation

Author action: rebase #44050 onto current main, preserving its built-in-only provider integration and regression coverage; it is the best existing fix, but no merge action is recommended here. Close #44049, #46207, and #47358 as duplicates of #44050; for #52259, split out the standalone-send timeout before closing its ownership portion as duplicate, and for #67418, split independently justified status/profile hardening before closing its ownership gate as duplicate. These closure recommendations explicitly differ from the keep_open reviews on #46207, #47358, #52259, and #67418 because the first two target the obsolete direct-ticker path, while the latter two combine overlapping ownership behavior with distinct salvageable work. Keep #67135 and #67198 in their separate scheduler-test triage, and request the documented comment correction on #67204.

#### Complex graph

```mermaid
flowchart TD
    classDef open fill:#dbeafe,stroke:#1d4ed8,color:#1e3a8a
    classDef merged fill:#dcfce7,stroke:#15803d,color:#14532d
    classDef closed fill:#e5e7eb,stroke:#6b7280,color:#1f2937
    classDef unverified fill:#f3f4f6,stroke:#9ca3af,color:#374151
    classDef best stroke-width:3px,stroke:#b45309
    classDef target stroke-width:3px,stroke:#4338ca
    I43965(["issue #43965 (open)"])
    I52202(["issue #52202 (open)"])
    I66629(["issue #66629 (open)"])
    subgraph Dup44049 ["PRs duplicating each other"]
        P44049["PR #44049 (open)"]
        P44050["PR #44050 (open)"]
        P46207["PR #46207 (open)"]
        P47358["PR #47358 (open)"]
        P52259["PR #52259 (open)"]
        P67418["PR #67418 (open)"]
    end
    P44049 -.->|partial| I52202
    P44050 -->|best fix| I52202
    P46207 -.->|partial| I52202
    P47358 -.->|partial| I52202
    P52259 -.->|partial| I52202
    P67418 -.->|partial| I52202
    P44049 -.->|partial| I43965
    P44050 -->|best fix| I43965
    P46207 -.->|partial| I43965
    P47358 -.->|partial| I43965
    P52259 -.->|partial| I43965
    P67418 -.->|partial| I43965
    P44049 -.->|partial| I66629
    P44050 -->|best fix| I66629
    P46207 -.->|partial| I66629
    P47358 -.->|partial| I66629
    P52259 -.->|partial| I66629
    P67418 -.->|partial| I66629
    class I43965 open
    class I52202 open
    class I66629 open
    class I52202 target
    class P44049 open
    class P44050 open
    class P46207 open
    class P47358 open
    class P52259 open
    class P67418 open
    class P44050 best
    class P44050 best
    class P44050 best
    click I43965 "https://github.com/NousResearch/hermes-agent/issues/43965"
    click I52202 "https://github.com/NousResearch/hermes-agent/issues/52202"
    click I66629 "https://github.com/NousResearch/hermes-agent/issues/66629"
    click P44049 "https://github.com/NousResearch/hermes-agent/pull/44049"
    click P44050 "https://github.com/NousResearch/hermes-agent/pull/44050"
    click P46207 "https://github.com/NousResearch/hermes-agent/pull/46207"
    click P47358 "https://github.com/NousResearch/hermes-agent/pull/47358"
    click P52259 "https://github.com/NousResearch/hermes-agent/pull/52259"
    click P67418 "https://github.com/NousResearch/hermes-agent/pull/67418"
```
*Graph: solid arrow = fixes / best fix, dashed arrow = partial or unverified (see edge label); boxed group = PRs duplicating each other; amber border = best fix; indigo border = target; gray node = closed (state tag in the node label).*

_Cross-PR triage: Reviewed 9 pull requests and 3 issues in this complex. Each diff was read against this issue; Assessment working set: 114 kB of PR diffs, 42 kB of issue/PR text, 15 kB of discussion (22 comments), 25 verify verdicts. verdicts reflect diff content, not PR titles. Part of an automated triage batch._
