### ISSUE TITLE
mcp extra pins mcp==2.0.0, breaks third-party MCP servers (akshare_mcp, eltdx, fetch)

### ISSUE THREAD

**Issue by jamesxia1988** [NousResearch/hermes-agent#89153]
## Description

The `[mcp]` optional extra in `pyproject.toml` pins `mcp==2.0.0` (added for CVE-2026-48710). This extra is included in `[all]`, so every `hermes update` (which runs `uv sync --extra all --locked`) force-upgrades the `mcp` package to 2.0.0.

However, mcp 2.0.0 has breaking API changes — specifically, `mcp.server.fastmcp` module was removed/renamed. This causes the following third-party MCP servers to crash on startup:

- **akshare_mcp** — `ImportError: cannot import name 'request_ctx' from 'mcp.server.lowlevel.server'` (via fastmcp)
- **eltdx** — `ModuleNotFoundError: No module named 'mcp.server.fastmcp'`
- **mcp-server-fetch** — connection closed immediately

All three work perfectly with `mcp==1.29.0`.

## Root Cause Chain

```
pyproject.toml [all] includes → hermes-agent[mcp]
pyproject.toml [mcp] extra → mcp==2.0.0, httpx2==2.7.0, starlette==1.3.1
uv.lock records → mcp==2.0.0
hermes update runs → uv sync --extra all --locked → installs mcp==2.0.0
mcp 2.0.0 removes → mcp.server.fastmcp module
→ akshare_mcp, eltdx, fetch all crash
```

## Environment

- Hermes Agent: v0.20.4
- Python: 3.11
- macOS ARM (Apple Silicon)
- Affected packages: akshare_mcp 0.1.3, eltdx 1.2.0, mcp-server-fetch 2026.7.10

## Workaround

After each `hermes update`:

```bash
~/.hermes/hermes-agent/venv/bin/pip install "mcp==1.29.0"
```

I patched my `~/.zshrc` `hermes-update` function to auto-detect and fix this, but this doesn't cover the Desktop app's built-in updater.

## Suggested Fix

Options:
1. **Move `mcp` out of `[all]`** — make it opt-in only (users who need Hermes's own MCP OAuth client can install `.[mcp]` separately)
2. **Pin `mcp<2.0` in `[all]`** instead of `mcp==2.0.0` — use the CVE fix only when explicitly opted in
3. **Lazy-install the `mcp` extra** like other opt-in backends (anthropic, messaging, etc.) — per the 2026-05-12 policy comment in pyproject.toml

The `mcp` extra was added for Hermes's own MCP client (OAuth), but it conflicts with the many third-party MCP servers that still depend on the mcp 1.x API. Since Hermes's own MCP OAuth code already handles mcp < 2.0 gracefully (try/except fallback in `mcp_oauth.py:682`), there's no functional reason to force 2.0 for all users.

**Comment by Roovelrz** [comment]
hi @alt-glitch :)

I’m working on this now. I’ll build on the root-cause analysis in the issue, especially the dependency chain from `[all]` to the `[mcp]` extra and the forced `mcp==2.0.0` install during `hermes update`.

I’ll first verify the current MCP OAuth fallback behavior and the security constraint that introduced the 2.0.0 pin, then keep the fix as narrow as possible so normal updates do not unnecessarily break third-party MCP servers. I’ll also add regression coverage for the dependency/update behavior where appropriate.

I’ll avoid simply downgrading the dependency globally and make sure the fix preserves the intended MCP OAuth and security behavior.
