### PR TITLE
fix(gateway): @ context reference expansion never ran (AttributeError on nonexistent self._model)

### LINKED ISSUE #62695: Gateway @ context-reference expansion never runs: AttributeError on nonexistent self._model, silently swallowed
## Summary

The gateway's "@" context-reference expansion (@file:, @folder:, @diff, ...) never runs. Every inbound message containing "@" hits an AttributeError that is silently swallowed, so references pass through to the model unexpanded.

## Root cause

`GatewayRunner._prepare_inbound_message_text` (gateway/run.py, ~10608-10648 on current main) reads `self._model` and `self._base_url`:

```python
_msg_ctx_len = await get_model_context_length_async(
    self._model,
    base_url=self._base_url or _msg_runtime.get("base_url") or "",
    ...)
```

Neither attribute is ever assigned on GatewayRunner (`grep -n "self\._model\s*=" gateway/run.py` returns nothing). The block was introduced in da44c196b as a copy of the HermesCLI implementation, where `self.model` / `self.base_url` are real attributes. In the gateway class the first read raises AttributeError, which the surrounding `except Exception as exc: logger.debug(...)` hides at debug level.

## Repro

Call `_prepare_inbound_message_text` with a message containing `@file:notes.txt`: the debug log shows `@ context reference expansion failed: 'GatewayRunner' object has no attribute '_model'` and the returned text is unchanged.

## Fix

PR incoming: resolve model/provider/base_url via `self._resolve_session_agent_runtime(...)` (the same session-aware resolution the hygiene compression block uses later in the file), and raise the swallow log to warning so future breakage of this feature is visible.

### PR DESCRIPTION
**Pull request by TheTom**
Closes #62695

## Problem

GatewayRunner._prepare_inbound_message_text's "@" context-reference block reads `self._model` / `self._base_url`, which are never assigned on GatewayRunner (copy-pasted in da44c196b from HermesCLI, which does carry `self.model`/`self.base_url`). Every message containing "@" raised AttributeError inside the try block, silently swallowed by the surrounding `except Exception` at debug level, so `preprocess_context_references_async` never ran in the gateway and @file:/@folder:/@diff references passed through unexpanded.

## Fix

- Resolve model/provider/base_url via `self._resolve_session_agent_runtime(source=, session_key=, user_config=)`, the same session-aware resolution the hygiene compression block already uses later in this file, so per-session /model overrides and channel overrides are honored. Also passes `provider=` through to `get_model_context_length_async` (previously omitted).
- Raise the swallow log from debug to warning (traceback stays at debug via exc_info) so a future regression here is visible instead of silent. Behavior stays fail-open.

## Tests

`tests/gateway/test_context_ref_expansion_runtime.py`:
- `test_at_reference_reaches_preprocessor_with_real_context_length`: asserts the except branch is not taken, `preprocess_context_references_async` is invoked with a real int context_length, and its expanded output is adopted.
- `test_at_reference_resolves_model_via_session_runtime`: asserts the model/base_url/provider handed to `get_model_context_length_async` come from session runtime resolution.

Both verified to fail on unfixed main (first with the swallowed AttributeError, second with no call ever reaching `get_model_context_length_async`). Existing `_prepare_inbound_message_text` and context-reference suites: 177 tests pass. ruff clean.

### CODE REVIEW

**Comment by teknium1** [comment]
Thanks for the focused gateway regression fix. The premise is confirmed on current main: `gateway/run.py:10606-10607` dereferences `self._model` and `self._base_url`, while `GatewayRunner` does not define either attribute. That exception is caught at `gateway/run.py:10627-10628`, preventing `preprocess_context_references_async` from running.

The proposed resolver matches the existing session-aware mechanism: `_resolve_session_agent_runtime()` documents `/model` and channel-override precedence at `gateway/run.py:3745-3749`, and the hygiene path already uses it before context-length lookup at `gateway/run.py:11051-11058`. The new tests cover both reaching the preprocessor and propagating model, base URL, and provider.

The target hunk is unchanged between the PR base and current main, so salvage should be a clean cherry-pick.

Automated hermes-sweeper review.
