### PR TITLE
fix(desktop): arm the backend READY scanner at spawn instead of after the claim (#96315)

### LINKED ISSUE #96315: Desktop app: backend readiness race causes reproducible 90s boot timeout
## Summary

The desktop Electron app's backend-boot handshake has a race condition: the backend process logs its `HERMES_BACKEND_READY port=N` line and is confirmed listening on that port, but the "wait for port announcement" promise for the *current* spawn attempt still times out at 90s, and boot is marked failed even though the backend is actually up.

Reproduced 3 times across relaunches on 2026-08-27 (and previously on 2026-08-24), version 0.20.5.

## Log evidence

```
[hermes]   Hermes backend listening on 127.0.0.1:50468
... (renderer loads, ~45s later)
[hermes] Ignoring stale Hermes backend exit (SIGTERM)
[hermes] [boot] Desktop boot failed: Timed out waiting for Hermes backend port announcement (90000ms)
[hermes] Error: Timed out waiting for Hermes backend port announcement (90000ms)
    at Timeout.<anonymous> (.../dist/electron-main.mjs:1981:14)
    at listOnTimeout (node:internal/timers:605:17)
    at process.processTimers (node:internal/timers:541:7)
```

After this, the renderer loops indefinitely:
```
[profiles] refreshProfiles failed after 3 attempt(s): Error: Error invoking remote method 'hermes:api': Error: Timed out waiting for Hermes backend port announcement (90000ms)
```

The dashboard never recovers on its own — it needs a full app relaunch, which frequently reproduces the same race.

## Root cause (from reading the packaged/minified `electron-main.mjs`)

The port-wait logic resolves via a stdout regex match against a `_READY_RE` pattern:

```js
let nl;
while ((nl = buf.indexOf("\n")) !== -1) {
  const line = buf.slice(0, nl);
  buf = buf.slice(nl + 1);
  const m = line.match(_READY_RE);
  if (m) {
    cleanup();
    resolve(parseInt(m[1], 10));
    return;
  }
}
...
const timer = setTimeout(() => {
  cleanup();
  reject(new Error(`Timed out waiting for Hermes backend port announcement (${timeoutMs}ms)`));
}, timeoutMs);
child.stdout.on("data", onData);
child.on("exit", onExit);
child.on("error", onError2);
```

Separately, backend-exit handling treats a SIGTERM against the (still-current-looking) child as stale/superseded and drops it silently:

```js
hermesProcess.once("exit", (code, signal) => {
  releaseBackendChild(hermesProcess);
  if (!backendConnectionState.clearForCurrentProcess(processOwner)) {
    rememberLog(`Ignoring stale Hermes backend exit (${signal || code})`);
    if (!backendReady) {
      rejectBackendStart?.(new Error("Hermes backend start was superseded by a newer connection attempt."));
    }
    return;
  }
  ...
```

The `HERMES_BACKEND_READY` line does reach the aggregate log, but the specific `onData` listener bound to that spawn attempt's promise apparently doesn't see/parse it in time (or the promise it should resolve has already been superseded/orphaned by a prior attempt's bookkeeping), so the 90s timer wins the race against a backend that's actually alive and listening.

## Repro steps

1. Launch Hermes desktop.
2. Occasionally (not always) the backend spawn takes long enough, or a stale prior backend process/promise lingers, that the readiness promise for the current attempt never resolves even though `HERMES_BACKEND_READY port=N` appears in the log shortly after spawn.
3. Wait 90s → boot fails, dashboard renderer loops `refreshProfiles failed` forever.
4. Relaunching the app sometimes clears it, sometimes reproduces it again immediately.

## Environment

- Hermes 0.20.5, macOS (arm64), local build at `apps/desktop/release/mac-arm64/Hermes.app`.
- Backend gateway daemon (separate process, launchd-supervised) is unaffected — this is specifically the desktop app's own local backend spawn for the GUI.

## Suggested direction

The readiness-wait promise/listener setup looks like it can get orphaned across spawn attempts (see the "stale exit" / "superseded" handling nearby). Worth auditing whether `_READY_RE` matching and promise resolution are correctly scoped per-attempt, and whether the listener is ever detached from a previous attempt's process object before a new one is created.

Happy to provide a full local diagnostic bundle (`hermes debug share --local` output) privately if useful — not attaching it here since it contains local paths/user identifiers.

### PR DESCRIPTION
**Pull request by JoaoMarcos44**
## What Problem This Solves

The desktop's port-announcement wait could never settle even though the backend was healthy, listening, and had printed its sentinel — the boot then failed at the 90s deadline and the renderer looped `refreshProfiles failed` forever (#96315).

The cause is listener ordering in the spawn path, not the sentinel itself:

1. `spawn()` → `outputTail.attach(child)` puts the child's stdout **and** stderr into flowing mode. From this instant the tail is the only listener.
2. `await claimBackendChild(...)` — on Windows the start-marker probe alone budgets **30s** of PowerShell (`backend-claim.ts`, `timeout: 30_000`). Then `await advanceBootProgress('backend.port', …)`.
3. Only *after* those awaits did `waitForDashboardPortAnnouncement` attach **its own** `data` listener.

A Node stream in flowing mode delivers each chunk exactly once, to the listeners that exist when it is emitted. A `HERMES_BACKEND_READY port=N` line printed during step 2 therefore reached the tail and nothing else — and it is **not replayable**. The waiter sat on a promise that could no longer be settled and burned the full deadline, which is precisely the reported log shape: the READY/listening lines are present in `desktop.log`, and the wait times out anyway.

```mermaid
%%{init: {'theme': 'dark', 'themeVariables': { 'primaryColor': '#8b0000', 'mainBkg': '#0a0204', 'primaryTextColor': '#ffccd5', 'primaryBorderColor': '#ff0038', 'lineColor': '#ff0038'}}}%%
graph TD
    A[🩸 spawn hermes serve] --> B[🔥 outputTail.attach — stdout + stderr flowing]
    B --> C{⚔️ Before: scanner armed later}
    C -->|await claimBackendChild — up to 30s| D[💀 READY chunk delivered to tail ONLY]
    D --> E[☠️ waiter attaches too late — chunk unreplayable]
    E --> F[🕯️ 90s deadline wins against a live backend]
    B --> G{🗡️ After: scanner armed same tick}
    G --> H[🔥 armPortAnnouncement observes every raw chunk]
    H --> I[⚡ sentinel latched whenever it arrives]
    I --> J[🏆 waiter settles instantly — stdout or stderr]
```

## What Changed

**`backend-claim.ts`** — `BackendOutputTail` gains `observe(listener)`: every raw chunk from both streams is forwarded to registered observers, and returns an unsubscribe function. Observers receive the chunk **before** the ring buffer trims it, so a burst larger than the 8 KiB tail cannot evict a line that was never scanned. A throwing observer cannot break buffering for the others.

**`backend-ready.ts`**
- `createReadyLineScanner()` — one line-buffered sentinel parser, latching the first match, now shared by both paths so a chunk-split line behaves identically in each.
- `armPortAnnouncement(tail)` — builds the scanner on the tail's feed and exposes `port()` / `whenAnnounced(cb)` / `dispose()`. It owns no timers and never rejects; the deadline, exit and error semantics stay exactly where they were.
- `waitForDashboardPort` / `waitForDashboardReadyFile` / `waitForDashboardPortAnnouncement` accept the armed announcement and settle from it — synchronously when the sentinel already flew past. Without one, the legacy stdout listener is used unchanged.

**`main.ts`** — both local-backend spawn sites (`primary` and the profile pool) call `armPortAnnouncement(tail)` in the **same tick** as `tail.attach(child)`, before their first `await`, and pass it into the wait.

Because the tail attaches to stdout **and** stderr, reading through it also covers the sentinel-on-stderr family (the import-time `sys.stdout = sys.stderr` in `tui_gateway/server.py`, #96282 / #96324) with the same code path instead of a second channel. That redirect's own fix (`_write_machine_sentinel_line`, merged in #96311) is already on `main`; this PR is the consumer-side half — it is the reason the race survives even with the sentinel correctly on fd 1.

## Why This Shape, and How It Differs From #96347

#96347 targets the same issue with four parallel channels (spawn-time tail scan, live stdout **and** stderr `data` listeners, a `HERMES_DESKTOP_READY_FILE` armed for every spawn with 50 ms `fs` polling, plus last-chance scans of the partial-line buffer and `stream.read()` at exit). This PR removes the race at its source instead:

- **One channel, not four.** The tail is already the sole listener attached at spawn; the sentinel is read from it. Nothing else needs a fallback because no byte is ever lost in the first place.
- **Immune to ring-buffer eviction.** A tail-*text* scan reads a truncated 8 KiB ring; a chatty backend can evict the sentinel before it is scanned. Observing raw chunks cannot. Covered by a regression test with a 64-byte tail.
- **No new I/O surface.** No ready file per boot in `userData`, no 50 ms polling interval, no unlink path, and no dependency on the Python `_write_dashboard_ready_file()` channel for correctness.
- **Deliberately no exit-time resolve.** A backend that exited is gone; handing its port to `waitForHermes()` converts a clear "exited before ready" error (which already carries the output tail from #93608) into a confusing connection failure downstream. Exit stays a rejection here.

Out of scope, intentionally: scoping the import-time `sys.stdout` redirect in `tui_gateway/server.py` (issue #96324's part 1), and the fact that `backend.readyFile` is still never set by any runtime resolver — that channel is left exactly as it was.

## Evidence

**Sabotage run** — announcement wiring disabled (`const announcement = null`), tests untouched:

```
× resolves a sentinel that was emitted BEFORE the waiter was created
× resolves a sentinel that lands on stderr (import-time stdout redirect)
× parses a tail-fed sentinel split across chunks and across streams
× a burst larger than the tail ring cannot evict an unscanned sentinel
× the armed announcement settles the ready-file wait when no file appears
× a timed-out armed waiter tears down and does not double-settle
Tests  6 failed | 23 passed (29)
```

**With the fix**: `backend-ready.test.ts` + `backend-claim.test.ts` → **46/46 pass**.

**Full electron vitest project**: 34 failures both with and without the change — the failing-file set is byte-identical to the fix-stashed baseline (git/ssh/`electron`-module/python-path environment failures on this Windows box, since `apps/desktop/node_modules` is not installed here). The one file that differed, `git-review-ops.test.ts`, passes on its own twice with the fix applied and is load-flaky (real `git`, 8.5s under full-suite load).

**Typecheck** (`tsc -p tsconfig.electron.json --noEmit`): 38 errors before, 38 after, identical apart from shifted line numbers — all pre-existing `Cannot find module 'electron'` noise from the uninstalled desktop deps. **Zero** in the touched files.

## Test Plan

- [x] 12 new tests (8 in `backend-ready.test.ts`, 4 in `backend-claim.test.ts`)
- [x] Sabotage run proves 6 of them fail pre-fix
- [x] Control test asserts the *old* shape still loses the sentinel, documenting the bug
- [x] `backend-ready` + `backend-claim` suites: 46/46
- [x] Full electron project: failure set identical to the fix-stashed baseline
- [x] Electron typecheck: no new diagnostics

Closes #96315

### CODE REVIEW

**Review by Halldrix — COMMENTED** [review]
For the record on this issue: three open PRs address this exact race — #60986,
#96347 and #96468. I read all three against current main and ran a full
Windows verification of the #96468 approach on a real Windows 11 host
(win32 x64, Node 26, Electron 40, PR head `0f70b16`):

- **E2E boot of the actual desktop app from the PR's own bundle + a venv
  built from the clone** (isolated `HERMES_HOME`): `HERMES_BACKEND_READY
  port=61616` announced, waiter resolved, `Hermes backend is ready.
  Finalizing desktop startup` in **~22s** from spawn. No timeout, no
  `refreshProfiles failed` loop.
- **`backend-ready.test.ts` + `backend-claim.test.ts` (vitest, electron
  project): 46/46 pass.**
- **Typecheck (`tsc -p tsconfig.electron.json --noEmit`): clean.**
- **Live pipe smoke against real `child_process` pipes:** sentinel emitted
  during a simulated spawn/claim await resolves instantly for a waiter created
  afterwards (the #96315 core case; the unarmed control times out on the same
  timing); CRLF line endings (raw pipe even shows double-CR) parse fine; a
  12KB burst after the sentinel evicts the 8KiB ring buffer yet the raw-chunk
  observer still yields the port.

So the armed-observer design is verified end-to-end on Windows where the
"waiter attaches after the claim" shape provably fails — the same
listener-ordering failure this issue reports on macOS.

**How the three PRs compare:**

- **#60986** (21 lines, `main.ts` only) moves the watcher creation before an
  `await advanceBootProgress` — but the dominant gap, `await
  claimBackendChild` (up to ~30s on Windows), runs before that in both spawn
  paths, and it never touches `backend-ready.ts` or replays the tail. It
  narrows the window but leaves the root cause (and the macOS case) open.
- **#96347** (multi-channel state machine: spawn-time tail pre-scan, live
  stdout+stderr listeners, atomic ready-file poll, exit-time scans). Robust
  defense-in-depth, but its core pre-scan reads `outputTail.text()` — the 8KiB
  ring, which a chatty backend can evict — and its live listeners attach after
  the claim awaits, the same post-flowing-mode pattern this issue says never
  fires on macOS.
- **#96468** arms a line-buffered scanner on the **raw chunk feed** of the
  spawn-time tail, in the same tick as `attach()` — no spectator window exists
  at all, ring eviction cannot lose the line, stderr is covered for free, and
  it is the only one of the three with a control test proving the old shape
  still loses the sentinel. This is the one I verified above.

**One gap worth closing if it lands as base:** #96468 is a single
observation channel with no independent fallback — a missed chunk on an
untested corner means a hard 90s timeout with zero recovery. Concretely: fold
#96347's unconditional ready-file poll (50ms unref'd interval over the atomic
JSON) into #96468 as an orthogonal safety net (armed observer = fast path,
ready file = fallback), and deliberately cherry-pick #96347's exit-time scans
("announced-then-exited", partial line at teardown) if that case matters on
Windows. #60986 can be closed as superseded.

Summary: **arm-at-spawn designs correctly; #96468 is upstream of #96347's
approach and is now verified end-to-end on Windows (Linux + macOS-report
mechanics already stood).** Adding the ready-file fallback closes the
single-channel corner.

**Comment by JoaoMarcos44** [comment]
Closing this as superseded — every layer it covered is now handled on `main` or by a PR that owns that layer.

**1. Arming the scanner before the claim** — landed in **#100442** (merged 2026-09-01, `da96a9c204`). Both `spawnPoolBackend` and `startHermes` now create `waitForDashboardPortAnnouncement` *before* any `await`, which was this PR's central change.

**2. Recovering a sentinel already consumed by the tail** — also #100442, via the `bufferedOutput()` seed. My follow-up **#103841** fixes the remaining hole in that seed: the tail merges stdout and stderr into one non-line-accurate buffer, so an unterminated stderr chunk splices onto the sentinel and the `^`-anchored regex silently misses it (#103792).

**3. Reading the sentinel off stderr as well as stdout** — **#97086** owns this layer, so it should not come from here.

**4. `observe()` catching chunks already evicted from the 8192-char ring buffer** — this was the one mechanism unique to this PR, and it is now moot. It mattered only because the wait used to attach seconds later (after `claimBackendChild`); with #100442's ordering the pre-attach window is microseconds, so evicting the sentinel would require 8KB of output inside that sliver.

The branch is also ~3 weeks stale and CONFLICTING against `main`. Rebasing it would mean re-litigating #97086's layer, which isn't mine to take. Closing rather than leaving a conflicting PR on a seam three other PRs are working.
