### PR TITLE
fix(gateway/line): correct message_type mapping and source factory method

### LINKED ISSUE #23728: [Bug]: LINE adapter crashes with AttributeError: 'LineAdapter' object has no attribute 'create_source'
## Summary

The LINE Messaging API adapter (introduced in #23197, merged 2026-05-10) crashes on every incoming webhook event with:

```
AttributeError: 'LineAdapter' object has no attribute 'create_source'
```

As a result, no inbound LINE message is ever dispatched to the agent — webhooks return 200 but the user receives no reply.

## Reproduction

1. Configure a LINE Messaging API channel and set the webhook URL to a running Hermes gateway (`nousresearch/hermes-agent:latest`).
2. Set `LINE_CHANNEL_SECRET`, `LINE_CHANNEL_ACCESS_TOKEN`, `LINE_PUBLIC_URL`, `LINE_ALLOWED_USERS` in `.env`.
3. Send any text message to the bot from LINE.

## Observed

```
ERROR hermes_plugins.line_platform.adapter: LINE: dispatch_event failed
Traceback (most recent call last):
  File "/opt/hermes/plugins/platforms/line/adapter.py", line 877, in _handle_webhook
    await self._dispatch_event(event)
  File "/opt/hermes/plugins/platforms/line/adapter.py", line 910, in _dispatch_event
    await self._handle_message_event(event)
  File "/opt/hermes/plugins/platforms/line/adapter.py", line 962, in _handle_message_event
    source_obj = self.create_source(
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'LineAdapter' object has no attribute 'create_source'
```

## Root cause

`plugins/platforms/line/adapter.py:962` calls `self.create_source(...)`, but the base adapter exposes this factory as `build_source(...)` — see `plugins/platforms/irc/adapter.py:495` and `plugins/platforms/teams/adapter.py` for the established pattern. No `create_source` method exists anywhere in `plugins/platforms/`.

## Fix

One-line: rename the call to `self.build_source(...)`. Verified locally — once patched, LINE messages are dispatched and the agent replies as expected. PR incoming.

## Environment

- Image: `nousresearch/hermes-agent:latest` (pulled 2026-05-11)
- Platform: macOS host (arm64) via Docker, cloudflared quick tunnel

### PR DESCRIPTION
**Pull request by irandoku**
## Summary

Fixes two `AttributeError` crashes in the LINE adapter that prevent inbound messages from ever reaching the agent.

### Bug 1: Missing `build_source` method (fixes #23728)

`self.create_source()` is not a method on `BasePlatformAdapter`. The correct factory method is `self.build_source()`, used by all other platform adapters (IRC, Teams, etc.).

Before this fix, every inbound LINE message crashed with:
```
AttributeError: 'LineAdapter' object has no attribute 'create_source'
```

### Bug 2: Non-existent `MessageType.IMAGE` member

`gateway/platforms/base.py` defines `MessageType` with `PHOTO` (not `IMAGE`) as the member for image/photo messages. The fallback expression:

```python
MessageType.TEXT if msg_type == "text" else MessageType.IMAGE
```

throws `AttributeError: IMAGE` on every non-text inbound message. It also incorrectly classifies audio, video, file, sticker, and location messages as images.

**Fix:** Replace with an explicit mapping using the correct enum members:
- `image` → `MessageType.PHOTO`
- `audio` → `MessageType.AUDIO`
- `video` → `MessageType.VIDEO`
- `file` → `MessageType.DOCUMENT`
- `sticker` → `MessageType.STICKER`
- `location` → `MessageType.LOCATION`

## Testing

- Verified locally: text, image, sticker, and location messages now dispatch correctly through LINE webhooks.
- `python -m py_compile plugins/platforms/line/adapter.py` passes.

## Related

- Fixes #23728

### CODE REVIEW

**Comment by alt-glitch** [comment]
Duplicate of #23305 — 5th PR for the LINE adapter create_source→build_source fix (#23728). This PR additionally fixes MessageType.IMAGE→PHOTO mapping, but the primary fix duplicates #23305, #23569, #23730, #23782.
