### ISSUE TITLE
Update aborted by a non-Hermes python -m http.server process inside the install dir; dialog gives misleading 'Close other Hermes windows' advice

### ISSUE THREAD

**Issue by bgexpert** [NousResearch/hermes-agent#77422]
## Title
Update aborted by a non-Hermes `python -m http.server` process inside the install dir; dialog gives misleading "Close other Hermes windows" advice

### Summary
On Windows, the in-app / desktop "Update" aborts with:
```
Update aborted: another Hermes process is using this installation.

Close other Hermes windows and terminals, then retry. If the problem
persists, run `hermes update` in a terminal for detailed diagnostics.
```
In a real case the **only** blocker was a **stray `python -m http.server 8077`**
process that a user had started by hand to preview a local website, whose
working directory / process path lives under the Hermes install dir
(`%LOCALAPPDATA%\hermes\hermes-agent`). It is **not** a Hermes process, but the
blocker probe flags any `python.exe` under the install dir and aborts the update.

The advice in the dialog ("Close other Hermes windows and terminals") is then
**wrong and unactionable**: there are no Hermes windows/terminals to close, so
retry can never succeed through the UI.

This is distinct from the already-filed gateway-self-lock issues (#77277, #75334,
#70337): those are about Hermes-owned gateway/backend processes. Here the blocker
is a **user-launched, non-Hermes** process, and the failure mode is the
**misleading instruction**, not just a lock.

### Environment
- Windows 10
- Hermes Desktop (Electron), install at `C:\Users\<user>\AppData\Local\hermes\hermes-agent` (git checkout, main)
- Hermes Agent v0.19.1

### Steps to Reproduce
1. From a terminal, `cd` into any dir and run `python -m http.server 8077` (or start a preview server that ends up with a process path under the Hermes install dir), leaving it running in the background.
2. Open Hermes Desktop and click the in-app **Update** button.
3. Observe: `Update aborted: another Hermes process is using this installation` — even with no Hermes windows or terminals open.
4. Click **Retry** — fails identically. The `http.server` process is never mentioned.

### Expected Behavior
- The blocker probe should distinguish **Hermes-owned** processes (gateway, serve, backend) from **arbitrary third-party `python.exe`** living under the install dir.
- If a non-Hermes process is the blocker, the message should name it explicitly, e.g.:
  > Update aborted: port 8077 is held by `python -m http.server` (PID 21544), which is not a Hermes process. Close or stop that process, then retry.
- The generic "Close other Hermes windows and terminals" text should only appear when the blocker is actually a Hermes-owned window/terminal.

### Impact
Users who run local dev servers / preview servers (common with `python -m http.server`) inside or near the Hermes install dir hit a dead-end loop through the Desktop UI and can only recover by running `hermes update` in a terminal (which kills the session as a side effect) or by manually hunting the PID. The misleading instruction makes the cause non-obvious.

### Suggested Fix
In the venv-blocker scan (`apps/desktop/electron/venv-blocker-scan.ts` or equivalent):
- Classify each candidate process as `hermes-owned` vs `foreign` (e.g. command line contains `hermes_cli.main` / known service args vs anything else).
- For `foreign` blockers, report the exact command line + PID + port so the user can stop the right process.
- Only show the "Close other Hermes windows/terminals" guidance when the blocker set is non-empty AND consists solely of Hermes-owned UI/terminal processes.

**Comment by ApacheWang** [comment]
I’m investigating this on Windows and plan to submit a focused fix with regression coverage. I’ll first verify the current blocker-classification behavior, then improve the diagnostic so foreign processes are identified without weakening the updater’s fail-closed safety.

**Comment by blackzhanzhan** [comment]
Additional reproduction from another Windows installation; this appears to be the same failure mode, with an extra consequence.

When clicking the Desktop “Update now” button, the dialog reports:

```
Update aborted: another Hermes process is using this installation.
These processes must be stopped before updating.
```

The listed processes included:

- a Hermes backend running from `...\\hermes-agent\\venv\\Scripts\\python.exe`
- a user-owned Python watcher, `fenbi_session_refresh.py`, also running from that same managed venv
- the PowerShell launcher for the user script

The user-owned Python process is not a Hermes window or terminal, but the updater still treats it as a hard blocker because it uses the Hermes installation's venv. Closing Hermes Desktop alone therefore cannot make the update eligible, and clicking Retry repeats the same abort. The UI does not clearly distinguish Hermes-owned processes from external processes or provide a supported handoff/stop action.

After the processes were stopped and `hermes update` was retried manually, the in-place dependency update failed while replacing PyYAML:

```
failed to uninstall PyYAML-6.0.2.dist-info: RECORD file not found
failed to remove/replace yaml\\_yaml.cp311-win_amd64.pyd: Windows access denied (os error 5)
```

The managed venv was then left partially updated and the Desktop backend failed to start with:

```
AttributeError: module 'yaml' has no attribute 'SafeDumper'
```

Manual recovery required force-reinstalling `pyyaml==6.0.3` and restarting Hermes.

Expected behavior:

1. The preflight should classify blockers as Hermes-owned versus external and show the exact command/process that must be stopped.
2. The updater should either coordinate a safe stop/handoff or use a staged candidate venv and atomically switch to it.
3. A failed dependency update must not leave the active venv in a partially installed state; it should roll back or keep the old environment intact.

This also seems related to the Windows in-place update/locked-file failure described in #68760.
