### ISSUE TITLE
fix(vision): _resolve_single_provider kwargs regression — fallback_chain silently fails on Gemini quota errors

### ISSUE THREAD

**Issue by saved-j** [NousResearch/hermes-agent#35876]
## Problem

When Gemini returns HTTP 429 (quota/resource exhausted), the vision fallback chain (`_try_configured_fallback_chain`) attempts to create clients for fallback providers (xiaomi-tp, ollama) via `_resolve_single_provider`. However, this function does not correctly forward `explicit_base_url`/`explicit_api_key` kwargs to `resolve_provider_client` after certain updates.

**Root cause:** `_resolve_single_provider` calls `resolve_provider_client(provider=..., model=..., explicit_base_url=base_url, explicit_api_key=api_key)`. The `explicit_base_url`/`explicit_api_key` parameters are ~14 lines after `def` — any refactoring that shifts the function body can silently break the fallback chain.

## Impact

- Users on Gemini free tier get quota exhausted → 429
- Fallback chain silently returns None for all providers
- User sees raw Gemini error, no fallback to MiMo/Ollama
- Verify check (grep -A3) was insufficient; explicit_base_url is on line ~14

## Expected

`_resolve_single_provider` should robustly forward all kwargs to `resolve_provider_client`. Options: make `resolve_provider_client` accept `base_url`/`api_key` as positional params; add a unit test; document the contract.

## Workaround

Re-apply kwargs fix after every `hermes update`.

**Comment by alt-glitch** [comment]
Duplicate of #27555 — same bug: `_resolve_single_provider()` passes `base_url`/`api_key` as kwargs but `resolve_provider_client()` expects `explicit_base_url`/`explicit_api_key`. TypeError silently swallowed, fallback chain never fires. Existing fix PRs: #33813, #27850, #29091.

**Comment by saved-j** [comment]
**Symptom:** After upstream updates the provider resolver receives a regression `TypeError: resolve_provider_client() got an unexpected keyword argument 'base_url'`, breaking fallback chain creation.

**Fix (applied in our local elara-patches):** In `agent/auxiliary_client.py` change `base_url=base_url` → `explicit_base_url=base_url` and `api_key=api_key` → `explicit_api_key=api_key` in the local call path. This keeps custom provider resolution working after upstream kwargs changes.

**Comment by alt-glitch** [comment]
> *This was generated by AI during triage.*

The kwarg-name regression described here appears to be resolved on `main`: `agent/auxiliary_client.py::_resolve_single_provider` already forwards `explicit_base_url=` / `explicit_api_key=` to `resolve_provider_client()` (the corrected names), so the `TypeError: ... unexpected keyword argument 'base_url'` should no longer fire. Root issue #27555 is closed; OPEN fix family #33813 carries the same rename. If you can still reproduce on a recent `main` build, please reopen with the exact commit SHA and traceback.

**Comment by saved-j** [comment]
Consolidated into #51513. Fallback chain fully working on v0.18.0 — tested with 4 broken entries, all traversed, response from last working one. All Gemini failure modes (geo-block, 429, 503, credential exhaustion, stale auth, model-not-found, 500) now correctly trigger chain iteration. See #51513 for verification log and patches.

**Comment by konsisumer** [comment]
These issues look like facets of **one underlying problem**: #35876, #49586, #51513.

They were grouped by a semantic pass as different symptoms of one underlying problem in `comp/agent`. A single coordinated fix may resolve them together — flagging for visibility; no action has been taken on the individual issues.

_Automated root-cause grouping. Reply to correct if these are unrelated._

**Comment by teknium1** [comment]
Thanks for the report. This is resolved on current `main` by the fallback-policy implementation, so this duplicate can be closed.

Automated hermes-sweeper review verified:
- `agent/auxiliary_client.py:4117-4122` now calls `resolve_provider_client()` with `explicit_base_url=base_url` and `explicit_api_key=api_key`.
- `agent/auxiliary_client.py:4392-4399` declares those exact resolver parameters.
- Merge commit `4858942c552733f72de5b2d0dfdfcc7a3a1dc248` (PR #47235) made the kwarg rename and routes configured fallback entries through the corrected resolver.
- The fix is contained by release tag `v2026.7.7`.

The later discussion's consolidation in #51513 may cover broader fallback reliability work, but the specific kwargs regression reported here is already fixed.
