### ISSUE TITLE
Memory leak: relay_runtime.pop() TypeError crashes Gateway and fills SWAP to 100%

### ISSUE THREAD

**Issue by truegroundx** [NousResearch/hermes-agent#78993]
## Bug Description

After upgrading Hermes to v0.20.0 ("The Herald Release"), the Gateway process experienced a memory leak caused by an unhandled TypeError in `relay_runtime.py`. This caused the container's memory and SWAP usage to steadily climb to nearly 100%, blocking the event loop and eventually requiring a container restart to recover.

## Steps to Reproduce

1. Run Hermes v0.20.0 in a Docker container
2. Use the agent to perform tool calls (terminal, etc.)
3. Observe repeated `relay finalization failed` errors in `errors.log`
4. Memory and SWAP usage steadily increase without bound
5. Event loop becomes stalled (8.1s → 40.9s)
6. Container becomes unresponsive; manual restart required

## Error Log

```
TypeError: pop() got an unexpected keyword argument 'metadata'
  File "/opt/hermes/agent/relay_runtime.py", line 217, in run_in_session
    return context.run(invoke)
  File "/opt/hermes/agent/relay_runtime.py", line 213, in invoke
    return callback(*args, **kwargs)
```

Repeated ~15 times, followed by:
```
agent.relay_llm: Hermes Relay logical LLM finalization failed
agent.relay_runtime: Hermes Relay logical LLM finalization failed
agent.relay_runtime: turn finalization failed
hermes_cli.web_server: event loop stalled 8.1s (GIL pressure suspected)
hermes_cli.web_server: event loop stalled 40.9s (GIL pressure suspected)
```

## Root Cause Analysis

In `relay_runtime.py:217`, the `pop()` method is called with a `metadata=...` keyword argument that the underlying dictionary/API does not support. This raises `TypeError`, which is not caught properly. Each failed invocation:
- Leaves old Python object stacks uncleaned
- Causes the Gateway to retry the tool call in a loop
- Accumulates unreleased objects in memory

Eventually this fills the container's physical memory and spills into SWAP until the event loop stalls and the container becomes unresponsive.

## Environment

- **Hermes version:** v0.20.0 ("The Herald Release")
- **Container:** Docker (hermes-gateway)
- **Runtime:** Python 3.13
- **System:** Debian (1Panel container on Proxmox VE)
- **Memory:** 7.5 GiB container limit, SWAP 7.5 GiB
- **Date:** 2026-08-04

## Workaround

Restart the container via 1Panel to release all leaked memory. Monitor `errors.log` for `relay finalization failed` — if it appears repeatedly, restart proactively before SWAP fills.

## Related

The `pop()` call at line 217 of `relay_runtime.py` should be fixed to not pass `metadata` as a keyword argument, or the TypeError should be caught and handled gracefully.

**Comment by ramen-man318** [comment]
**Reproduced on ARM64 / systemd (non-Docker)**

I am also seeing this on Raspberry Pi 5 (ARM64, 8GB RAM, Ubuntu 24.04) running Hermes v0.20.0 as a systemd service (not Docker). The gateway was killed twice today by the OOM killer (hermes process, anon-rss 5.7GB and 6.0GB).

`errors.log` shows the same relay finalization failure on 2026-08-04 and 2026-08-05:

```
Hermes Relay turn finalization failed
  File "relay_runtime.py", line 644, in end_turn
  File "relay_runtime.py", line 217, in run_in_session
  File "relay_runtime.py", line 213, in invoke
  File "nemo_relay/scope.py", line 144, in pop
RuntimeError: invalid argument: scope handle is not at the top of the stack
```

Note: in my environment the error is a `RuntimeError`, not the `TypeError` described in the report — same code path (`nemo_relay/scope.py:144`), different exception.

Observation only (not proven causation): both OOM kills happened while running external commands via the terminal tool (GitHub CLI). Happy to gather more logs if useful.

**Comment by jplavoiemtl** [comment]
**Third confirmation — ARM64 / systemd, 3.6 GB RAM. Adds a data-loss consequence not yet reported.**

Same code path and same `RuntimeError` variant as @ramen-man318. I'm adding
process-level measurements and one consequence that I think raises the severity:
**this leak corrupted my `state.db`.**

### Measured leak rate

Gateway PID 55935, **15 minutes** after a clean start:

RSS      1,886,332 kB   (1.9 GB)
VmSwap   4,510 MB
VSZ     13,501,912 kB   (13.5 GB)
                        → ~6.4 GB committed in 15 min

`systemctl --user stop hermes-gateway` released all 6.4 GB instantly.

### OOM kill and an oversized single allocation

14:23:29 oom-kill: task=hermes,pid=53033
         Killed process 53033 (hermes) total-vm:9407320kB anon-rss:2521136kB
14:40:30 __vm_enough_memory: pid: 55658, comm: hermes,
         bytes: 6509113344 not enough memory for the allocation   (×4)

That second one is worth a look on its own: a **single 6.5 GB allocation request**.
With `overcommit_memory=0` the kernel refuses anything larger than RAM+swap, so
this fails outright rather than leaking gradually. Two restarts in 20 minutes.

### The part I think matters most: SQLite corruption

An earlier OOM kill during the same failure mode left `~/.hermes/state.db`
(2.09 GB) structurally corrupt — not just the FTS index:

Tree 369716 page 371736: btreeInitPage() returns error code 11
Tree   9    page 213146: btreeInitPage() returns error code 11
Tree   5    page  16456 cell 0: overflow list length is 3 but should be 6

Consequences:
- Context compression could not run (it writes to `state.db`), so the agent blocked
  ~11 min until the 600 s ceiling fired: `Context compression made no progress for
  605.4s ... continuing without compression`. It then ran indefinitely in that
  degraded state — responsive, but with compression permanently dead.
- **`hermes doctor --fix` and `hermes sessions repair` both failed to recover it.**
  They dropped every FTS table, failed the REINDEX pass, then reported
  `state.db schema repair could not recover ... manual restore from backup may be
  required` — pointing at a backup named `state.db.malformed-backup-*`, i.e. the
  already-corrupt pre-repair copy. Following that advice restores the corruption.
- Recovery required building the `sqlite3` CLI from the amalgamation and running
  `.recover` into a fresh database. No data lost, but nothing in the product could
  do it.

One possibly relevant detail: `hermes_state.py::_enforce_macos_synchronous_full`
sets `PRAGMA synchronous=FULL` **only on Darwin**, and its own docstring names this
exact signature — *"can leave the main DB with half-written btree pages →
`btreeInitPage error 11`"*. I hit that signature on Linux/ext4. I'm not claiming the
macOS rationale transfers, but the failure mode did.

Also flagging a misleading log line, since it cost me time: `state.db: WAL
journal_mode unsupported on this filesystem (disk I/O error)`. The filesystem is
ext4 on a local SSD with 878 GB free — the real cause was memory pressure, not the
filesystem. The message sends you down the wrong path.

### Environment

| | |
|---|---|
| Hermes | v0.20.0 (2026.8.3), upstream `1be70d63`, git install |
| Host | Arduino Uno Q — aarch64, Debian 13 (trixie), kernel 6.16.7 |
| RAM / CPU | **3.6 GB** / 4 cores (lowest-memory report so far — surfaces fast) |
| Runtime | Python 3.11.15 (venv), SQLite 3.53.1 |
| Deployment | `systemd --user` service, **not Docker** |
| Provider | openai-codex, gpt-5.6-luna |
| Swap | zram 1.8 GB only, at the time of the OOM kills |

### Note on zram

My swap was **zram only** (compressed RAM, no disk backing), which adds no real
capacity — the OOM killer fires while `free -h` still shows swap available. Adding a
6 GB disk swapfile at a lower priority converted the crash into a slowdown: the
gateway now reaches the same ~6.4 GB and survives. It is a mitigation, not a fix,
but it may be a useful workaround for others on small ARM hosts.

Happy to provide full `errors.log`, `dmesg`, or run any instrumented build.

**Comment by jplavoiemtl** [comment]
**Follow-up (same reporter): a candidate reproduction, and evidence that the
logged `scope pop` error under-reports the leak.**

### Candidate repro — leak scales with *tool output size*

The clearest single event I've captured. One terminal tool call took the gateway
from ~261 MB to 2,044 MB RSS + 2,241 MB swap **between two consecutive
measurements**:

2026-08-06 22:06:32 Tool terminal returned error (180.59s):
{"output": "== state.db.healthy-preopt ==\nok\n
           == state.db.corrupt-20260805 ==\n*** in database main ***\n
           Tree 348817 page 502573: btreeInit...

That was `PRAGMA integrity_check` against two ~2 GB SQLite files, one of them
corrupt — so it emitted thousands of error lines over 180 s. **~4 GB retained
from a single turn.**

If tool output is held per-turn and the turn's scope is never released, this
should reproduce on any host: run one tool call that emits a very large stdout
(e.g. `seq 1 5000000`, or `find / -type f`) and watch RSS before/after. That
would be a much faster repro than waiting hours for gradual growth.

### The leak rate is strongly workload-dependent

| Condition | Rate |
|---|---|
| Active use, large tool outputs | **~430 MB/h** (8.6 GB over 19.7 h) |
| Light use, no large outputs | **~10 MB/h** (315 MB over 14.9 h, 0 swap) |

Same host, same version, same config — only the workload differs. Worth
controlling for when attempting a repro: an idle gateway will look nearly
healthy.

### `scope handle is not at the top of the stack` does NOT fire on every leak

This may matter for root-causing. On my host all seven occurrences are on a
single day:

2026-08-05  01:44 · 04:00 · 04:00 · 15:47 · 16:15 · 16:25 · 16:39

**None after 16:39 on Aug 5.** Yet the gateway was OOM-killed again at
`2026-08-06 02:03:36`, and after restarting at 02:30 it grew to 8.6 GB
(2,146 MB RSS + 6,421 MB swap) by 22:11 — **with zero occurrences of that
error in the entire window.**

So the leak continues while the check is silent. Either the scope stack stays
misaligned after the first failure without re-triggering the guard, or there is
a second retention path. Counting these log lines is therefore **not** a
reliable measure of whether a fix worked.

### Updated OOM data

2026-08-05 14:59:34  Killed process 55935  total-vm 13,501,912 kB  anon-rss 2,719,528 kB
2026-08-06 02:03:36  Killed process 79396  total-vm 15,574,260 kB  anon-rss 2,747,740 kB

Four OOM kills total. Peak `total-vm` is now **15.5 GB** on a 3.6 GB host. Worst
event-loop stall observed: **434.9 s**.

### Mitigations that measurably helped (not fixes)

- A **disk** swapfile. My host's swap was zram only — compressed RAM, no extra
  capacity — so the OOM killer fired while `free -h` still showed swap free.
- `session_reset` (`mode: both`, `idle_minutes: 360`). It defaults to `none`;
  the changelog notes it was `both` until July 2026. Long-lived sessions
  re-inflate memory on reload — after one restart the gateway returned to
  6.4 GB in 15 min purely from replaying a ~120k-token session.
- Avoiding large tool outputs entirely.

Happy to run an instrumented build or `tracemalloc` snapshots if that would help.

**Comment by jplavoiemtl** [comment]
**Regression boundary identified: clean under 0.19.1, failing within 4 hours of
upgrading to 0.20.0.**

I went back through a month of rotated logs on the same host. The failure
classes in this issue do not exist before the 0.20.0 upgrade.

### The boundary

From `~/.hermes/logs/hermes-update.log`, timestamped **2026-08-03 18:28 UTC**:

- hermes-agent==0.19.1 (from file:///home/arduino/.hermes/hermes-agent)
- hermes-agent==0.20.0 (from file:///home/arduino/.hermes/hermes-agent)

Installed commit: `aad8f7412`.

**First `scope handle is not at the top of the stack` in the entire log history:
`2026-08-03 22:21:18`** — 3 h 53 min after the upgrade.

### Event history, by day

| Date | Version | Events |
|---|---|---|
| Jul 6 – Jul 31 | 0.19.1 | **12 × STALL only** |
| **Aug 3 18:28** | **↑ upgrade to 0.20.0** | |
| Aug 3 | 0.20.0 | 1 × SCOPE_POP, 1 × FINALIZE |
| Aug 4 | 0.20.0 | 1 × SCOPE_POP, 2 × UNCLEAN_EXIT |
| Aug 5 | 0.20.0 | 8 × SCOPE_POP, 6 × FINALIZE, **2 × OOM_KILL**, 2 × ALLOC_DENIED, 2 × UNCLEAN_EXIT, 10 × STALL |
| Aug 6 | 0.20.0 | **2 × OOM_KILL**, 2 × UNCLEAN_EXIT, 3 × STALL |

Across 26 days on 0.19.1: **zero** `SCOPE_POP`, **zero** `finalization failed`,
**zero** unclean exits, **zero** OOM kills, **zero** denied allocations.

To be precise about what is *not* new: `event loop stalled` existed under 0.19.1
(12 occurrences in July, all short). What changed is both its severity — worst
stall under 0.19.1 vs **434.9 s** on Aug 5 — and the appearance of five failure
classes that had never occurred.

The day-over-day escalation is also consistent with a leak that compounds as
state accumulates, rather than a fixed cost per turn.

### Reproducing this check

For the other reporters — this is worth confirming independently, and it only
needs your rotated logs:

```bash
# when did you upgrade?
grep -E 'hermes-agent==0\.(19|20)' ~/.hermes/logs/hermes-update.log

# first occurrence of the signature, across rotations
grep -h -B8 'scope handle is not at the top' ~/.hermes/logs/errors.log* \
  | grep -oE '^2026-[0-9-]+ [0-9:]+' | sort | head -1

If your first occurrence also lands after your 0.20.0 upgrade, that closes the
question of whether this is a regression.

I now keep a deduplicated, cumulative incident history on this host (dmesg is
lost on reboot and errors.log rotates, so the evidence disappears otherwise).
Happy to share the full 54-event timeline, or the collection script, if useful.
