### PR TITLE
fix(execute-code): correct helper import contract

### PR DESCRIPTION
**Pull request by yuzilongleif-collab**
## Summary

- stop advertising `json_parse`, `shell_quote`, and `retry` as preloaded globals
- point helper `NameError` recovery hints to the working `hermes_tools` import
- distinguish a true helper import failure as runtime/schema skew
- add execution, schema, hint, and cross-transport generated-module regression coverage

## Root cause

The generated helpers are functions in the sibling `hermes_tools.py` module. The execute_code schema and recovery hint instead told models to call them directly without importing them, which deterministically raises `NameError`. Explicit imports from `hermes_tools` already work on both generated transports, so correcting the contract is smaller and safer than injecting names into Python `builtins`.

## Reproduction

```python
print(shell_quote("two words"))
```

Before: `NameError: name 'shell_quote' is not defined`, followed by a misleading hint to call it directly without importing it.

Working contract:

```python
from hermes_tools import shell_quote
print(shell_quote("two words"))
```

## Tests

```text
scripts/run_tests.sh tests/tools/test_code_execution.py tests/tools/test_code_execution_modes.py tests/tools/test_sandbox_failure_hints.py -v
74 passed, 0 failed
```

The committed transport smoke test generates both UDS and file-based `hermes_tools.py` modules, starts a fresh child interpreter for each, and imports and executes `json_parse`, `shell_quote`, and `retry`. A script beginning with a `from __future__` import is also covered.

### CODE REVIEW

**Comment by yuzilongleif-collab** [comment]
CI note: the failing `tests/gateway/test_multiplex_busy_input_mode.py::test_profile_route_and_nonmultiplexed_resolution_preserve_boundaries` case is reproducible unchanged on the current `origin/main` (`c0106e50e`), where it returns `interrupt` and logs that profile `research` is not served. This PR does not touch Gateway/profile-routing code.

That baseline failure is already tracked in #83743 and fixed separately by #83745. I rebased this PR onto the current `origin/main`; its three affected test files still pass 73/73 locally.

**Comment by yuzilongleif-collab** [comment]
Independent adversarial review found no material correctness/security/compatibility issue. I addressed its two low-severity observations in `44702b50a`:

- corrected the stale internal comment that described the required helper import as misuse
- added a committed smoke test that generates both UDS and file-transport `hermes_tools.py`, launches a fresh child interpreter for each, and imports/executes all three convenience helpers

Updated scoped result: 74 passed. The rerun's ruff/ty, Windows/macOS, e2e, OSV, supply-chain, and 11 unaffected Python slices passed; slice 5 remains the independently reproduced `origin/main` failure tracked in #83743 and fixed by #83745.

**Comment by Enough1122** [comment]
> AI code review — automated review for reference, author can ignore or act on any point.

**fix(execute-code): correct helper import contract**

Aligning the schema with reality — helpers are exports of the generated `hermes_tools.py`, not preloaded globals — is the right fix, and the smoke test that spawns a real subprocess per transport (`test_convenience_helpers_import_and_execute_for_each_transport`) is the strongest kind of guard here. A few observations:

1. **Hint text is vague on the common cause**: for `ImportError: cannot import name 'json_parse'`, the new hint says "expected to be exported by hermes_tools, but this sandbox did not expose it… retry in a fresh session." The most frequent real cause is a stale generated module or a wrong import path (e.g. importing from a different `hermes_tools` on `sys.path`), not a runtime/schema sync issue — an actionable hint ("verify the generated hermes_tools.py is fresh; check the import line") would help more than "retry in a fresh session".
2. **Contract drift elsewhere**: the schema and hints are now consistent, but anything else that still advertises the old "built-in helpers (no import)" contract (e.g. skills, website docs, or the execute_code description in other toolsets) will now mislead users — a quick grep for "no import" / "BUILT-IN helper" in docs/skills would catch stragglers.
3. **`python -c` path resolution**: the smoke test relies on `sys.path[0] == ''` (cwd) for `from hermes_tools import ...` to resolve, which faithfully mirrors the sandbox's tmpdir staging — worth a brief comment in the test so a future refactor doesn't "fix" the cwd and silently break the assertion.
4. Minor: `test_schema_requires_import_for_convenience_helpers` asserts on the schema description text — that's a legitimate behavior contract for the schema deliverable, but it's text-snapshot-ish; the subprocess smoke test is the durable guarantee.

**Comment by yuzilongleif-collab** [comment]
Follow-up is now at head `0d766525ec`.

Changes: actionable helper-import skew guidance; a comment documenting why the subprocess smoke test must keep cwd-first import resolution; repository-wide grep found no old helper contract outside files already changed by this PR.

Local verification: 60 passed + 2 subtests, Ruff clean, `git diff --check` clean.

**Comment by yuzilongleif-collab** [comment]
Superseded by #105005, which adapted this helper-import contract fix and is now merged into main. Closing this older PR to avoid duplicate tracking. Thank you for carrying the fix forward.
